import type { BentoItem, BentoWidgetTemplate } from "./types";

/** Widget templates available in the Bento workspace add/remove menu. */
export const BENTO_WIDGET_CATALOG: BentoWidgetTemplate[] = [
  {
    templateId: "allocation",
    label: "Allocation",
    colSpan: 6,
    rowSpan: 4,
    content: {
      type: "stat",
      props: {
        label: "Joint allocation",
        value: "$31,234",
        tone: "accent",
        visualization: { type: "ring", percent: 68 },
        caption: "Retirement 42%",
      },
    },
  },
  {
    templateId: "debt-payoff",
    label: "Debt payoff",
    colSpan: 12,
    rowSpan: 8,
    content: {
      type: "metricChart",
      props: {
        label: "Debt payoff",
        value: "$18,420",
        change: { amount: "-$2,140", percent: "-10.4%", caption: "This year", direction: "down" },
        chartValues: [92, 88, 84, 80, 76, 72, 68, 64, 58, 52, 46, 40],
      },
    },
  },
  {
    templateId: "cash-flow",
    label: "Cash flow",
    colSpan: 6,
    rowSpan: 4,
    content: {
      type: "kpi",
      icon: "folder",
      label: "Cash flow",
      value: "$1,234,567",
      meta: "Available balance",
    },
  },
  {
    templateId: "stocks",
    label: "Stocks",
    colSpan: 8,
    rowSpan: 8,
    content: {
      type: "stockList",
      items: [
        { name: "Apple Inc.", avatarName: "Apple", value: "$12,840", change: "+2.4%", direction: "up" },
        { name: "Microsoft", avatarName: "Microsoft", value: "$9,210", change: "+1.1%", direction: "up" },
        { name: "Tesla", avatarName: "Tesla", value: "$4,680", change: "-0.8%", direction: "down" },
      ],
    },
  },
  {
    templateId: "music",
    label: "Music player",
    colSpan: 10,
    rowSpan: 4,
    content: {
      type: "musicPlayer",
      props: {
        title: "Les Muses: Taylor",
        artist: "Taylor Swift",
        sourceLabel: "Spotify",
        imageTone: "neutral",
        progress: 42,
        elapsed: "1:24",
        duration: "3:18",
        playing: true,
      },
    },
  },
  {
    templateId: "calendar",
    label: "Calendar",
    colSpan: 8,
    rowSpan: 8,
    content: {
      type: "calendarSchedule",
      props: {
        monthLabel: "April 2023",
        days: [
          { value: "", muted: true },
          { value: "", muted: true },
          { value: "", muted: true },
          { value: "", muted: true },
          { value: "", muted: true },
          { value: 1 },
          { value: 2 },
          { value: 3 },
          { value: 4 },
          { value: 5 },
          { value: 6 },
          { value: 7 },
          { value: 8 },
          { value: 9 },
          { value: 10 },
          { value: 11 },
          { value: 12 },
          { value: 13 },
          { value: 14 },
          { value: 15 },
          { value: 16 },
          { value: 17 },
          { value: 18 },
          { value: 19, selected: true },
          { value: 20 },
          { value: 21 },
          { value: 22 },
          { value: 23 },
          { value: 24 },
          { value: 25 },
          { value: 26 },
          { value: 27 },
          { value: 28 },
          { value: 29 },
          { value: 30 },
        ],
        events: [
          { title: "Yoga Class", timeRange: "8:00–9:00 AM", tone: "accent" },
          { title: "Gym", timeRange: "6:00–7:00 PM", tone: "success" },
        ],
      },
    },
  },
  {
    templateId: "insight",
    label: "Insight",
    colSpan: 6,
    rowSpan: 4,
    content: {
      type: "insight",
      props: {
        title: "Revise meeting order",
        description: "Start later, rest longer, finish earlier.",
      },
    },
  },
  {
    templateId: "link-bank",
    label: "Link bank",
    colSpan: 8,
    rowSpan: 4,
    content: {
      type: "cta",
      icon: "external-link",
      title: "Link your bank",
      description: "Connect accounts to track cash flow automatically.",
      buttonLabel: "Connect your bank",
    },
  },
  {
    templateId: "glass-clock",
    label: "Analog clock",
    colSpan: 4,
    rowSpan: 4,
    content: { type: "glassWidget", props: { variant: "analogClock", hours: 10, minutes: 25 } },
  },
  {
    templateId: "design-weather",
    label: "Weather",
    colSpan: 10,
    rowSpan: 4,
    content: {
      type: "designCard",
      props: {
        variant: "weather",
        city: "New York",
        temperature: "66°",
        aqi: "38 AQI",
        wind: "7 Mph",
      },
    },
  },
];

/** Default starter layout for the Bento workspace. */
export const BENTO_SAMPLE_ITEMS: BentoItem[] = [
  {
    id: "allocation-1",
    templateId: "allocation",
    label: "Allocation",
    col: 1,
    row: 1,
    colSpan: 6,
    rowSpan: 4,
    content: BENTO_WIDGET_CATALOG[0].content,
  },
  {
    id: "cash-flow-1",
    templateId: "cash-flow",
    label: "Cash flow",
    col: 7,
    row: 1,
    colSpan: 6,
    rowSpan: 4,
    content: BENTO_WIDGET_CATALOG[2].content,
  },
  {
    id: "debt-payoff-1",
    templateId: "debt-payoff",
    label: "Debt payoff",
    col: 13,
    row: 1,
    colSpan: 12,
    rowSpan: 8,
    content: BENTO_WIDGET_CATALOG[1].content,
  },
  {
    id: "insight-1",
    templateId: "insight",
    label: "Insight",
    col: 1,
    row: 5,
    colSpan: 6,
    rowSpan: 4,
    content: BENTO_WIDGET_CATALOG[6].content,
  },
  {
    id: "glass-clock-1",
    templateId: "glass-clock",
    label: "Analog clock",
    col: 7,
    row: 5,
    colSpan: 4,
    rowSpan: 4,
    content: BENTO_WIDGET_CATALOG[8].content,
  },
  {
    id: "stocks-1",
    templateId: "stocks",
    label: "Stocks",
    col: 1,
    row: 9,
    colSpan: 8,
    rowSpan: 8,
    content: BENTO_WIDGET_CATALOG[3].content,
  },
  {
    id: "music-1",
    templateId: "music",
    label: "Music player",
    col: 9,
    row: 9,
    colSpan: 10,
    rowSpan: 4,
    content: BENTO_WIDGET_CATALOG[4].content,
  },
  {
    id: "design-weather-1",
    templateId: "design-weather",
    label: "Weather",
    col: 9,
    row: 13,
    colSpan: 10,
    rowSpan: 4,
    content: BENTO_WIDGET_CATALOG[9].content,
  },
];
