/** Tailwind class map — converted from MusicWorkspace.module.css */
const styles: Record<string, string> = {
  addBtn: "inline-flex items-center justify-center w-[40px] h-[40px] border border-solid border-[var(--music-control-border)] rounded-lf-pill bg-transparent text-[var(--music-text)] cursor-pointer hover:border-[var(--music-text)] hover:[transform:scale(1.04)]",
  art: "[flex-shrink:0] rounded-lf-sm bg-[var(--art-gradient,_linear-gradient(135deg,_#444,_#222))] overflow-hidden",
  artAmber: "[--art-gradient:linear-gradient(135deg,_#fbbf24,_#b45309)]",
  artBlue: "[--art-gradient:linear-gradient(135deg,_#60a5fa,_#1d4ed8)]",
  artCyan: "[--art-gradient:linear-gradient(135deg,_#22d3ee,_#0e7490)]",
  artFull: "w-full h-full",
  artGreen: "[--art-gradient:linear-gradient(135deg,_#4ade80,_#15803d)]",
  artIndigo: "[--art-gradient:linear-gradient(135deg,_#818cf8,_#4338ca)]",
  artLg: "w-[200px] h-[200px] rounded-lf-md",
  artLime: "[--art-gradient:linear-gradient(135deg,_#a3e635,_#4d7c0f)]",
  artMd: "w-[56px] h-[56px]",
  artOrange: "[--art-gradient:linear-gradient(135deg,_#fb923c,_#c2410c)]",
  artPink: "[--art-gradient:linear-gradient(135deg,_#f472b6,_#be185d)]",
  artPurple: "[--art-gradient:linear-gradient(135deg,_#c084fc,_#7e22ce)]",
  artRose: "[--art-gradient:linear-gradient(135deg,_#fb7185,_#be123c)]",
  artSm: "w-[40px] h-[40px]",
  artTeal: "[--art-gradient:linear-gradient(135deg,_#2dd4bf,_#0f766e)]",
  artViolet: "[--art-gradient:linear-gradient(135deg,_#a78bfa,_#6d28d9)]",
  body: "flex-1 flex min-h-0",
  contentFilters: "flex flex-wrap gap-lf-2 mb-lf-5",
  controlBtn: "flex items-center justify-center w-[32px] h-[32px] border-none rounded-lf-pill bg-transparent text-[var(--music-text-subtle)] cursor-pointer hover:text-[var(--music-text)]",
  controlBtnActive: "text-[var(--music-accent)]",
  controlRow: "flex items-center justify-center gap-lf-3",
  featuredActions: "flex items-center gap-lf-3",
  featuredCard: "flex items-stretch gap-lf-5 p-lf-5 rounded-lf-lg bg-[linear-gradient(_135deg,_var(--music-featured-gradient-start),_var(--music-featured-gradient-end)_)]",
  featuredDescription: "m-[0_0_var(--lf-space-4)] text-[var(--music-text-subtle)] text-lf-sm leading-[var(--lf-line-height-normal)]",
  featuredLabel: "m-[0_0_var(--lf-space-2)] text-lf-xs font-semibold [letter-spacing:0.04em] uppercase text-[var(--music-text-subtle)]",
  featuredMeta: "flex-1 flex flex-col justify-center min-w-0",
  featuredTitle: "m-[0_0_var(--lf-space-2)] text-lf-2xl font-bold leading-[var(--lf-line-height-tight)]",
  filterChip: "p-[6px_12px] border-none rounded-lf-pill bg-[var(--music-bg-highlight)] text-[var(--music-text)] text-lf-xs font-semibold cursor-pointer transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:bg-[var(--music-bg-press)]",
  filterChipActive: "bg-[var(--music-text)] text-[var(--music-on-primary)]",
  iconBtn: "flex items-center justify-center w-[32px] h-[32px] border-none rounded-lf-pill bg-transparent text-[var(--music-text-subtle)] cursor-pointer hover:text-[var(--music-text)] hover:bg-[var(--music-hover-bg)]",
  installBtn: "p-[var(--lf-space-2)_var(--lf-space-4)] border-none rounded-lf-pill bg-[var(--music-text)] text-[var(--music-on-primary)] text-lf-sm font-semibold cursor-pointer whitespace-nowrap hover:[transform:scale(1.04)]",
  libraryFilters: "flex flex-wrap gap-lf-2 p-[0_var(--lf-space-4)_var(--lf-space-3)]",
  libraryHeader: "flex items-center justify-between p-[var(--lf-space-3)_var(--lf-space-4)]",
  libraryHeaderActions: "flex items-center gap-lf-1",
  libraryItem: "flex items-center gap-lf-3 w-full p-lf-2 border-none rounded-lf-md bg-transparent text-[inherit] text-left cursor-pointer hover:bg-[var(--music-hover-bg)]",
  libraryItemActive: "bg-[var(--music-active-bg)]",
  libraryItemMeta: "min-w-0 flex-1",
  libraryItemSubtitle: "block mt-[2px] text-lf-sm leading-[var(--lf-line-height-tight)] text-[var(--music-text-subtle)] whitespace-nowrap overflow-hidden text-ellipsis",
  libraryItemTitle: "block text-lf-md font-semibold leading-[var(--lf-line-height-tight)] whitespace-nowrap overflow-hidden text-ellipsis",
  libraryList: "flex-1 min-h-0 overflow-auto p-[0_var(--lf-space-2)_var(--lf-space-3)]",
  libraryPane: "[flex-shrink:0] w-[320px] flex flex-col min-h-0 bg-[var(--music-bg)] border-r border-[var(--music-border)]",
  librarySort: "flex items-center gap-[4px] border-none bg-transparent text-[inherit] text-lf-xs font-semibold cursor-pointer",
  libraryTitle: "m-0 text-lf-lg font-semibold leading-[var(--lf-line-height-tight)]",
  libraryToolbar: "flex items-center justify-between p-[0_var(--lf-space-4)_var(--lf-space-2)] text-[var(--music-text-subtle)]",
  mainPane: "flex-1 min-w-0 flex flex-col min-h-0 bg-[linear-gradient(180deg,_var(--music-main-gradient-top)_0%,_var(--music-bg)_280px)]",
  mainScroll: "flex-1 min-h-0 overflow-auto p-[var(--lf-space-4)_var(--lf-space-5)_var(--lf-space-6)]",
  mixArtists: "m-0 text-lf-sm text-[var(--music-text-subtle)] leading-[var(--lf-line-height-tight)]",
  mixArtWrap: "relative aspect-[1] rounded-lf-sm overflow-hidden",
  mixCard: "relative flex flex-col gap-lf-3 p-lf-4 border-none rounded-lf-md bg-[var(--music-bg-highlight)] text-[inherit] text-left cursor-pointer overflow-hidden transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:bg-[var(--music-bg-press)] hover:opacity-100 hover:[transform:translateY(0)]",
  mixNumber: "text-lf-xs font-semibold [letter-spacing:0.04em] uppercase text-[var(--music-text-subtle)]",
  mixPlay: "absolute right-[8px] bottom-[8px] flex items-center justify-center w-[40px] h-[40px] border-none rounded-lf-pill bg-[var(--music-accent)] text-[#000] opacity-0 [transform:translateY(8px)] transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] cursor-pointer shadow-[0_8px_16px_var(--music-shadow)]",
  mixRow: "grid grid-cols-[repeat(4,_minmax(140px,_1fr))] gap-lf-4",
  mixTitle: "m-0 text-lf-md font-semibold leading-[var(--lf-line-height-tight)]",
  navBtn: "flex items-center justify-center w-[40px] h-[40px] border-none rounded-lf-pill bg-[var(--music-nav-btn-bg)] text-[var(--music-text)] cursor-pointer transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:bg-[var(--music-nav-btn-hover-bg)] hover:[transform:scale(1.04)]",
  navCluster: "flex items-center gap-lf-2 flex-1 min-w-0",
  nowPlayingArt: "relative aspect-[1] rounded-lf-md overflow-hidden mb-lf-4",
  nowPlayingArtists: "m-0 text-[var(--music-text-subtle)] text-lf-sm leading-[var(--lf-line-height-tight)]",
  nowPlayingHeader: "p-lf-4 text-lf-sm font-semibold text-[var(--music-text-subtle)] whitespace-nowrap overflow-hidden text-ellipsis",
  nowPlayingPane: "[flex-shrink:0] w-[340px] flex flex-col min-h-0 bg-[var(--music-bg)] border-l border-[var(--music-border)]",
  nowPlayingScroll: "flex-1 min-h-0 overflow-auto p-[0_var(--lf-space-4)_var(--lf-space-4)]",
  nowPlayingTitle: "m-[0_0_4px] text-lf-lg font-semibold leading-[var(--lf-line-height-tight)]",
  nowPlayingTrack: "flex items-start justify-between gap-lf-3 mb-lf-5",
  playBtn: "inline-flex items-center justify-center w-[48px] h-[48px] border-none rounded-lf-pill bg-[var(--music-accent)] text-[#000] cursor-pointer shadow-[0_8px_24px_var(--music-shadow)] transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:[transform:scale(1.06)] hover:bg-[var(--music-accent-hover)]",
  playerBar: "[flex-shrink:0] grid grid-cols-[1fr_2fr_1fr] items-center gap-lf-4 p-[var(--lf-space-2)_var(--lf-space-4)] bg-[var(--music-bg-elevated)] border-t border-[var(--music-border)]",
  playerControls: "flex flex-col items-center gap-lf-2",
  playerExtras: "flex items-center justify-end gap-lf-2",
  playerTrack: "flex items-center gap-lf-3 min-w-0",
  playerTrackArtists: "block text-lf-sm leading-[var(--lf-line-height-tight)] text-[var(--music-text-subtle)] whitespace-nowrap overflow-hidden text-ellipsis",
  playerTrackMeta: "min-w-0",
  playerTrackTitle: "block text-lf-md font-semibold leading-[var(--lf-line-height-tight)] whitespace-nowrap overflow-hidden text-ellipsis",
  playPauseBtn: "flex items-center justify-center w-[36px] h-[36px] border-none rounded-lf-pill bg-[var(--music-text)] text-[var(--music-on-primary)] cursor-pointer hover:[transform:scale(1.06)]",
  premiumBtn: "p-[var(--lf-space-2)_var(--lf-space-4)] border-none rounded-lf-pill bg-transparent text-[var(--music-text)] text-lf-sm font-semibold cursor-pointer whitespace-nowrap hover:[transform:scale(1.04)]",
  profileBtn: "w-[28px] h-[28px] border-none rounded-lf-pill bg-[#5038a0] text-[var(--music-text)] text-lf-xs font-semibold cursor-pointer",
  progressFill: "block h-full rounded-[inherit] bg-[var(--music-text)]",
  progressRow: "flex items-center gap-lf-2 w-full max-w-[560px]",
  progressTrack: "flex-1 h-[4px] rounded-lf-pill bg-[var(--music-track-bg)] overflow-hidden",
  quickCard: "flex items-center gap-lf-3 min-h-[56px] pr-lf-4 border-none rounded-lf-md bg-[var(--music-card-bg)] text-[inherit] text-left cursor-pointer overflow-hidden transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:bg-[var(--music-card-hover-bg)]",
  quickCardTitle: "text-lf-md font-semibold leading-[var(--lf-line-height-tight)]",
  quickGrid: "grid grid-cols-[repeat(2,_minmax(0,_1fr))] gap-lf-3 mb-lf-6",
  relatedArtists: "block mt-[2px] text-lf-sm leading-[var(--lf-line-height-tight)] text-[var(--music-text-subtle)] whitespace-nowrap overflow-hidden text-ellipsis",
  relatedItem: "flex items-center gap-lf-3 w-full p-lf-2 border-none rounded-lf-md bg-transparent text-[inherit] text-left cursor-pointer hover:bg-[var(--music-hover-bg)]",
  relatedList: "flex flex-col gap-lf-2",
  relatedMeta: "min-w-0",
  relatedSectionTitle: "m-[0_0_var(--lf-space-3)] text-lf-md font-semibold leading-[var(--lf-line-height-tight)]",
  relatedTitle: "block text-lf-md font-semibold leading-[var(--lf-line-height-tight)] whitespace-nowrap overflow-hidden text-ellipsis",
  scrollable: "[scrollbar-width:thin] [scrollbar-color:var(--music-scrollbar-thumb)_transparent]",
  searchBar: "flex-1 max-w-[480px] flex items-center gap-lf-2 p-[0_var(--lf-space-4)] h-[44px] rounded-lf-pill bg-[var(--music-search-bg)] text-[var(--music-text-subtle)] text-lf-sm bg-[var(--music-search-bg-focus)] text-[var(--music-text)]",
  searchInput: "flex-1 border-none bg-transparent text-[inherit] [font:inherit] outline-none",
  section: "mb-lf-6",
  sectionHeader: "flex items-baseline justify-between mb-lf-4",
  sectionTitle: "m-0 text-lf-lg font-semibold leading-[var(--lf-line-height-tight)]",
  timeLabel: "min-w-[36px] text-lf-xs leading-[var(--lf-line-height-tight)] text-[var(--music-text-subtle)] [font-variant-numeric:tabular-nums]",
  topActions: "flex items-center gap-lf-2 [flex-shrink:0]",
  topBar: "[flex-shrink:0] flex items-center gap-lf-3 p-[var(--lf-space-2)_var(--lf-space-4)] bg-[var(--music-top-bar-bg)] border-b border-[var(--music-border)]",
  videoSwitch: "absolute left-[50%] bottom-[16px] [transform:translateX(-50%)] p-[8px_16px] border-none rounded-lf-pill bg-[var(--music-overlay-bg)] text-[#ffffff] text-lf-xs font-semibold cursor-pointer",
  videoTag: "inline-flex mt-[2px] p-[1px_6px] rounded-lf-pill bg-[var(--music-tag-bg)] text-lf-xs font-semibold text-[var(--music-text-subtle)]",
  volumeFill: "block h-full w-[68%] rounded-[inherit] bg-[var(--music-text)]",
  volumeRow: "flex items-center gap-lf-2 min-w-[120px]",
  volumeTrack: "flex-1 h-[4px] rounded-lf-pill bg-[var(--music-track-bg)] overflow-hidden",
  workspace: "[--music-accent:#1db954] [--music-accent-hover:#1ed760] [--music-accent-muted:rgba(29,_185,_84,_0.14)] [--music-bg:#121212] [--music-bg-elevated:#181818] [--music-bg-highlight:#282828] [--music-bg-press:#333333] [--music-text:#ffffff] [--music-text-subtle:#b3b3b3] [--music-text-muted:#a7a7a7] [--music-on-primary:#000000] [--music-border:var(--lf-divider)] [--music-top-bar-bg:rgba(0,_0,_0,_0.35)] [--music-nav-btn-bg:rgba(0,_0,_0,_0.55)] [--music-nav-btn-hover-bg:rgba(0,_0,_0,_0.72)] [--music-search-bg:rgba(255,_255,_255,_0.1)] [--music-search-bg-focus:rgba(255,_255,_255,_0.16)] [--music-hover-bg:rgba(255,_255,_255,_0.08)] [--music-active-bg:rgba(255,_255,_255,_0.12)] [--music-card-bg:rgba(255,_255,_255,_0.08)] [--music-card-hover-bg:rgba(255,_255,_255,_0.14)] [--music-main-gradient-top:#1f1f1f] [--music-featured-gradient-start:rgba(255,_255,_255,_0.12)] [--music-featured-gradient-end:rgba(255,_255,_255,_0.04)] [--music-control-border:rgba(255,_255,_255,_0.35)] [--music-overlay-bg:rgba(0,_0,_0,_0.72)] [--music-track-bg:rgba(255,_255,_255,_0.25)] [--music-tag-bg:rgba(255,_255,_255,_0.12)] [--music-shadow:rgba(0,_0,_0,_0.35)] [--music-scrollbar-thumb:rgba(255,_255,_255,_0.24)] [--music-scrollbar-thumb-hover:rgba(255,_255,_255,_0.38)] h-full flex flex-col min-h-0 bg-[var(--music-bg)] text-[var(--music-text)] font-sans text-lf-base leading-[var(--lf-line-height-normal)]",
};
export default styles;
