import type { BankDashboardData, CryptoWalletData } from "longformer-ui";

export const bankDashboardData: BankDashboardData = {
  accountName: "Jane's Account",
  userName: "Jane Doe",
  totalBalance: "$587,105.65",
  balanceTrendUp: "$7.5K",
  balanceTrendDown: "-$11K",
  balanceChart: [520, 545, 538, 560, 552, 575, 568, 587],
  balanceChartLabels: ["Nov 9", "Nov 15", "Nov 21", "Nov 27"],
  navItems: [
    { id: "home", label: "Home", icon: "home", active: true },
    { id: "tasks", label: "Tasks", icon: "check" },
    { id: "transactions", label: "Transactions", icon: "list" },
    { id: "payments", label: "Payments", icon: "wallet", hasChildren: true },
    { id: "cards", label: "Cards", icon: "square" },
    { id: "accounts", label: "Accounts", icon: "grid", hasChildren: true },
  ],
  quickActions: [
    { id: "send", label: "Send", primary: true },
    { id: "transfer", label: "Transfer" },
    { id: "deposit", label: "Deposit" },
    { id: "request", label: "Request" },
    { id: "upload", label: "Upload Bill" },
  ],
  accounts: [
    { id: "checking", name: "Checking", suffix: "..1234", balance: "$34,550.22", icon: "🏦", iconBg: "#e8edf5" },
    { id: "savings", name: "Savings", suffix: "..8347", balance: "$210,890.42", icon: "💰", iconBg: "#e8f5ec" },
    { id: "invest", name: "Invest", balance: "$281,271.43", icon: "📈", iconBg: "#f0ebff" },
    { id: "vacation", name: "Vacation Travel", balance: "$7,489.32", icon: "✈️", iconBg: "#fff4e5" },
    { id: "subs", name: "Subscriptions & Memberships", balance: "$562.87", icon: "🔁", iconBg: "#fce8ef" },
    { id: "emergency", name: "Emergency Fund", balance: "$52,341.39", icon: "🛡️", iconBg: "#e8f0ff" },
  ],
  moneyInTotal: "$7,526.82",
  moneyOutTotal: "-$10,958.21",
  moneyInItems: [
    { id: "in-1", label: "Sequoia", amount: "$3,526.82" },
    { id: "in-2", label: "Savings ..8347", amount: "$4,000.00" },
  ],
  moneyOutItems: [
    { id: "out-1", label: "Chase", amount: "-$2,958.21" },
    { id: "out-2", label: "Fidelity", amount: "-$8,000.00" },
  ],
  periodLabel: "Nov 2025",
};

export const cryptoWalletData: CryptoWalletData = {
  totalBalance: "$11,542.21",
  assets: [
    {
      id: "btc",
      name: "Bitcoin",
      symbol: "BTC",
      price: "$45,294.10",
      balance: "0.072 BTC",
      balanceUsd: "$2714",
      icon: "₿",
      iconBg: "#f7931a",
      changePercent: "0.10%",
      changeUsd: "$43.10",
      chart: [43800, 43950, 43700, 44100, 43900, 44200, 44035, 44150, 44000, 44080, 44035, 44120],
      activities: [
        { id: "a1", type: "sent", date: "Jan 4, 2024", amount: "0.017 BTC", amountUsd: "$725.00" },
        { id: "a2", type: "received", date: "Jan 2, 2024", amount: "0.025 BTC", amountUsd: "$1,100.00" },
        { id: "a3", type: "sent", date: "Dec 28, 2023", amount: "0.008 BTC", amountUsd: "$352.00" },
      ],
    },
    {
      id: "eth",
      name: "Ethereum",
      symbol: "ETH",
      price: "$2,456.80",
      balance: "1.24 ETH",
      balanceUsd: "$3046",
      icon: "Ξ",
      iconBg: "#627eea",
    },
    {
      id: "usdc",
      name: "USD Coin",
      symbol: "USDC",
      price: "$1.00",
      balance: "1,250 USDC",
      balanceUsd: "$1250",
      icon: "$",
      iconBg: "#2775ca",
    },
    {
      id: "usdt",
      name: "Tether",
      symbol: "USDT",
      price: "$1.00",
      balance: "890 USDT",
      balanceUsd: "$890",
      icon: "₮",
      iconBg: "#26a17b",
    },
    {
      id: "bnb",
      name: "Binance Coin",
      symbol: "BNB",
      price: "$312.45",
      balance: "2.1 BNB",
      balanceUsd: "$656",
      icon: "B",
      iconBg: "#f3ba2f",
    },
    {
      id: "sol",
      name: "Solana",
      symbol: "SOL",
      price: "$98.72",
      balance: "8.5 SOL",
      balanceUsd: "$839",
      icon: "S",
      iconBg: "#9945ff",
    },
    {
      id: "matic",
      name: "Polygon",
      symbol: "MATIC",
      price: "$0.89",
      balance: "420 MATIC",
      balanceUsd: "$374",
      icon: "M",
      iconBg: "#8247e5",
    },
    {
      id: "busd",
      name: "Binance USD",
      symbol: "BUSD",
      price: "$1.00",
      balance: "773 BUSD",
      balanceUsd: "$773",
      icon: "B",
      iconBg: "#f0b90b",
    },
  ],
};
