import type { PhoneContact } from "longformer-ui";

export const phoneContacts: PhoneContact[] = [
  {
    id: "p1",
    name: "Riley Chen",
    phone: "+1 (415) 555-0142",
    phoneLabel: "Mobile",
    email: "riley@meridian.dev",
    company: "Meridian Labs",
    title: "Engineering",
    favorite: true,
  },
  {
    id: "p2",
    name: "Jordan Hayes",
    phone: "+1 (628) 555-0198",
    phoneLabel: "Work",
    email: "jordan@meridian.dev",
    company: "Meridian Labs",
    title: "Design",
  },
  {
    id: "p3",
    name: "Sam Patel",
    phone: "+1 (510) 555-0177",
    phoneLabel: "Mobile",
    email: "sam@meridian.dev",
    company: "Meridian Labs",
    title: "Platform",
    favorite: true,
  },
  {
    id: "p4",
    name: "Alex Morgan",
    phone: "+1 (206) 555-0103",
    phoneLabel: "Mobile",
    email: "alex@meridian.dev",
    company: "Meridian Labs",
    title: "Founder",
  },
  {
    id: "p5",
    name: "Acme Support",
    phone: "+1 (800) 555-0199",
    phoneLabel: "Main line",
    company: "Acme Corp",
  },
  {
    id: "p6",
    name: "Front Desk",
    phone: "+1 (415) 555-0100",
    phoneLabel: "Office",
    company: "WeWork Mission",
  },
];
