import type { NotificationItem } from "longformer-ui";

export const initialNotifications: NotificationItem[] = [
  {
    id: "n1",
    type: "mention",
    actor: { name: "Riley Chen" },
    message: "Riley Chen mentioned you in \u201cPicnic Planning Notes\u201d",
    detail: "@Alex can you confirm the catering headcount before we finalize?",
    timestamp: "2m",
    group: "Today",
  },
  {
    id: "n2",
    type: "system",
    message: "Agent finished the task \u201cDraft volunteer shift schedule\u201d",
    detail: "1 document updated · ready for review",
    timestamp: "18m",
    group: "Today",
  },
  {
    id: "n3",
    type: "comment",
    actor: { name: "Jordan Hayes" },
    message: "Jordan Hayes commented on the event poster draft",
    detail: "Love the map callout — just one wording tweak on the welcome banner.",
    timestamp: "1h",
    group: "Today",
  },
  {
    id: "n4",
    type: "assignment",
    actor: { name: "Sam Patel" },
    message: "Sam Patel assigned you \u201cConfirm pavilion rental\u201d",
    timestamp: "3h",
    read: true,
    group: "Today",
  },
  {
    id: "n5",
    type: "reaction",
    actor: { name: "Riley Chen" },
    message: "Riley Chen reacted \u2b50 to your message",
    timestamp: "Yesterday",
    read: true,
    group: "Yesterday",
  },
  {
    id: "n6",
    type: "invite",
    actor: { name: "Jordan Hayes" },
    message: "Jordan Hayes invited you to the \u201cCommunity Events\u201d teamspace",
    timestamp: "Yesterday",
    read: true,
    group: "Yesterday",
  },
  {
    id: "n7",
    type: "system",
    message: "Weekly digest is ready \u2014 4 tasks completed, 1 waiting on a reply",
    timestamp: "2d",
    read: true,
    group: "Earlier",
  },
];
