import type { NotificationItem } from "longformer-ui";

export const initialNotifications: NotificationItem[] = [
  {
    id: "n1",
    type: "mention",
    actor: { name: "Dana Cho" },
    message: "Dana Cho mentioned you in \u201cAddressing User Feedback\u201d",
    detail: "@Paul can you take a look at the validation gap before we ship?",
    timestamp: "2m",
    group: "Today",
  },
  {
    id: "n2",
    type: "system",
    message: "Agent finished the task \u201cWire the WebSocket gateway validation\u201d",
    detail: "3 files changed · tests passing",
    timestamp: "18m",
    group: "Today",
  },
  {
    id: "n3",
    type: "comment",
    actor: { name: "Marcus Webb" },
    message: "Marcus Webb commented on your pull request",
    detail: "Nice catch on the payload size cap — LGTM once CI is green.",
    timestamp: "1h",
    group: "Today",
  },
  {
    id: "n4",
    type: "assignment",
    actor: { name: "Priya Nair" },
    message: "Priya Nair assigned you \u201cSet up CI watchdog automation\u201d",
    timestamp: "3h",
    read: true,
    group: "Today",
  },
  {
    id: "n5",
    type: "reaction",
    actor: { name: "Dana Cho" },
    message: "Dana Cho reacted \u2b50 to your message",
    timestamp: "Yesterday",
    read: true,
    group: "Yesterday",
  },
  {
    id: "n6",
    type: "invite",
    actor: { name: "Marcus Webb" },
    message: "Marcus Webb invited you to the \u201cLongformer\u201d teamspace",
    timestamp: "Yesterday",
    read: true,
    group: "Yesterday",
  },
  {
    id: "n7",
    type: "system",
    message: "Weekly digest is ready \u2014 3 tasks completed, 1 blocked",
    timestamp: "2d",
    read: true,
    group: "Earlier",
  },
];
