import type { OrchestratorWorkspaceData } from "longformer-ui";

export const orchestratorWorkspaceData: OrchestratorWorkspaceData = {
  productName: "Orchestrator",
  userName: "Alex Morgan",
  userEmail: "alex@example.com",
  navItems: [
    { id: "dashboard", label: "Dashboard", icon: "grid", view: "dashboard" },
    { id: "agents", label: "Agents", icon: "users", view: "agents" },
    { id: "jobs", label: "Jobs", icon: "package", view: "jobs" },
    { id: "playground", label: "Playground", icon: "play", view: "playground" },
    { id: "playground-history", label: "Playground History", icon: "clock", view: "playground-history" },
    { id: "traces", label: "Traces", icon: "layers", view: "traces" },
    { id: "logs", label: "Logs", icon: "file", view: "logs" },
    { id: "settings", label: "Settings", icon: "settings", view: "settings" },
  ],
  metrics: [
    { id: "status", label: "System Status", value: "Healthy", icon: "check", tone: "success" },
    { id: "active-agents", label: "Active Agents", value: "2", icon: "users", tone: "accent" },
    { id: "total-jobs", label: "Total Jobs", value: "17", icon: "package", tone: "accent" },
    { id: "avg-runtime", label: "Average Runtime", value: "27ms", icon: "clock", tone: "accent" },
    { id: "tool-calls", label: "Tool Calls", value: "8", icon: "zap", tone: "accent" },
    { id: "cache-hits", label: "Cache Hits", value: "2", icon: "folder", tone: "accent" },
    { id: "total-tokens", label: "Total Tokens", value: "13,873", icon: "sparkles", tone: "accent" },
    { id: "completed-jobs", label: "Completed Jobs", value: "1", icon: "check", tone: "accent" },
  ],
  agents: [
    {
      id: "agent-researcher",
      name: "researcher",
      description: "Web Research Specialist",
      toolsCount: 4,
      traceCount: 12,
      lastExecuted: "11/05/2025, 02:31:12",
      lastExecutedAt: Date.parse("2025-11-05T02:31:12"),
    },
    {
      id: "agent-coordinator",
      name: "coordinator",
      description: "Multi-Agent Workflow Coordinator",
      toolsCount: 6,
      traceCount: 28,
      lastExecuted: "11/05/2025, 02:28:44",
      lastExecutedAt: Date.parse("2025-11-05T02:28:44"),
    },
    {
      id: "agent-analyzer",
      name: "analyzer",
      description: "Data Pattern Analyzer",
      toolsCount: 3,
      traceCount: 9,
      lastExecuted: "11/04/2025, 18:12:03",
      lastExecutedAt: Date.parse("2025-11-04T18:12:03"),
    },
    {
      id: "agent-writer",
      name: "writer",
      description: "Long-form Content Synthesizer",
      toolsCount: 2,
      traceCount: 15,
      lastExecuted: "11/04/2025, 14:05:19",
      lastExecutedAt: Date.parse("2025-11-04T14:05:19"),
    },
    {
      id: "agent-coder",
      name: "coder",
      description: "Code Generation & Review Agent",
      toolsCount: 5,
      traceCount: 21,
      lastExecuted: "11/03/2025, 09:47:55",
      lastExecutedAt: Date.parse("2025-11-03T09:47:55"),
    },
    {
      id: "agent-summarizer",
      name: "summarizer",
      description: "Document Summarization Agent",
      toolsCount: 2,
      traceCount: 7,
      lastExecuted: "11/02/2025, 22:18:30",
      lastExecutedAt: Date.parse("2025-11-02T22:18:30"),
    },
    {
      id: "agent-retriever",
      name: "retriever",
      description: "Vector Search & Retrieval Agent",
      toolsCount: 3,
      traceCount: 18,
      lastExecuted: "11/02/2025, 16:02:11",
      lastExecutedAt: Date.parse("2025-11-02T16:02:11"),
    },
    {
      id: "agent-validator",
      name: "validator",
      description: "Output Quality & Safety Checker",
      toolsCount: 1,
      traceCount: 5,
      lastExecuted: "11/01/2025, 11:33:08",
      lastExecutedAt: Date.parse("2025-11-01T11:33:08"),
    },
    {
      id: "agent-planner",
      name: "planner",
      description: "Task Decomposition Planner",
      toolsCount: 4,
      traceCount: 11,
      lastExecuted: "10/31/2025, 20:44:52",
      lastExecutedAt: Date.parse("2025-10-31T20:44:52"),
    },
    {
      id: "agent-monitor",
      name: "monitor",
      description: "Runtime Health & Metrics Observer",
      toolsCount: 2,
      traceCount: 6,
      lastExecuted: "10/30/2025, 08:15:27",
      lastExecutedAt: Date.parse("2025-10-30T08:15:27"),
    },
  ],
};
