import type { PassportWorkspaceData } from "longformer-ui";

export const passportWorkspaceData: PassportWorkspaceData = {
  workspaceName: "Passport",
  userName: "Paul Bloch",
  tagline: "Encrypted vault for credentials your agents can use when granted.",
  navItems: [
    { id: "dashboard", label: "Overview", icon: "home", view: "dashboard" },
    { id: "vault", label: "Vault", icon: "lock", view: "vault", badge: "18" },
    { id: "env-sets", label: "Env Sets", icon: "code", view: "env-sets", badge: "4" },
    { id: "grants", label: "Agent Grants", icon: "sparkles", view: "grants" },
    { id: "audit", label: "Audit Log", icon: "clock", view: "audit" },
  ],
  overviewMetrics: [
    { id: "total-secrets", label: "Total secrets", value: "18", change: "+2 this week", icon: "lock", tone: "accent" },
    { id: "active-grants", label: "Active grants", value: "24", change: "6 agents", icon: "sparkles", tone: "success" },
    { id: "env-sets", label: "Env sets", value: "4", icon: "code", tone: "neutral" },
    { id: "last-access", label: "Last agent read", value: "2m ago", icon: "clock", tone: "warning" },
  ],
  secrets: [
    {
      id: "sec-openai",
      name: "OpenAI API Key",
      kind: "api-key",
      maskedValue: "sk-••••••••••••••••",
      service: "OpenAI",
      tags: ["llm", "production"],
      grantedAgentIds: ["agent-chat", "agent-orchestrator", "agent-coding"],
      lastUsed: "2m ago",
      updatedAt: "Jul 1",
    },
    {
      id: "sec-anthropic",
      name: "Anthropic API Key",
      kind: "api-key",
      maskedValue: "sk-ant-••••••••••••",
      service: "Anthropic",
      tags: ["llm"],
      grantedAgentIds: ["agent-chat", "agent-coding"],
      lastUsed: "1h ago",
      updatedAt: "Jun 28",
    },
    {
      id: "sec-github-pat",
      name: "GitHub Personal Access Token",
      kind: "secret-key",
      maskedValue: "ghp_••••••••••••••••",
      service: "GitHub",
      tags: ["git", "ci"],
      grantedAgentIds: ["agent-coding"],
      lastUsed: "Yesterday",
      updatedAt: "Jun 20",
    },
    {
      id: "sec-vercel",
      name: "Vercel Deploy Token",
      kind: "api-key",
      maskedValue: "vercel_••••••••••••",
      service: "Vercel",
      tags: ["deploy", "server"],
      grantedAgentIds: ["agent-coding", "agent-orchestrator"],
      lastUsed: "3d ago",
      updatedAt: "Jun 15",
    },
    {
      id: "sec-db-prod",
      name: "Production Database URL",
      kind: "env-variable",
      maskedValue: "postgres://••••••••••••",
      service: "Neon",
      tags: ["database", "production"],
      grantedAgentIds: ["agent-orchestrator"],
      updatedAt: "Jun 10",
      note: "Read-only connection for analytics agent",
    },
    {
      id: "sec-1password",
      name: "1Password Service Account",
      kind: "secret-key",
      maskedValue: "ops_••••••••••••••••",
      service: "1Password",
      tags: ["vault", "sync"],
      grantedAgentIds: [],
      updatedAt: "Jun 5",
    },
    {
      id: "sec-aws",
      name: "AWS Access Key",
      kind: "api-key",
      maskedValue: "AKIA••••••••••••",
      service: "AWS",
      tags: ["cloud", "s3"],
      grantedAgentIds: ["agent-orchestrator"],
      lastUsed: "Jun 30",
      updatedAt: "Jun 1",
    },
    {
      id: "sec-slack-bot",
      name: "Slack Bot Token",
      kind: "api-key",
      maskedValue: "xoxb-••••••••••••",
      service: "Slack",
      tags: ["comms", "bot"],
      grantedAgentIds: ["agent-chat"],
      lastUsed: "4h ago",
      updatedAt: "May 28",
    },
    {
      id: "sec-linear",
      name: "Linear API Key",
      kind: "api-key",
      maskedValue: "lin_api_••••••••••••",
      service: "Linear",
      tags: ["tickets", "workflow"],
      grantedAgentIds: ["agent-orchestrator"],
      updatedAt: "May 20",
    },
    {
      id: "sec-gmail",
      name: "Gmail App Password",
      kind: "password",
      maskedValue: "•••• •••• •••• ••••",
      service: "Google",
      username: "paul@longformer.dev",
      tags: ["email"],
      grantedAgentIds: [],
      updatedAt: "May 15",
    },
    {
      id: "sec-posthog",
      name: "PostHog Project Key",
      kind: "api-key",
      maskedValue: "phc_••••••••••••••••",
      service: "PostHog",
      tags: ["analytics"],
      grantedAgentIds: ["agent-chat"],
      updatedAt: "May 10",
    },
    {
      id: "sec-stripe",
      name: "Stripe Secret Key",
      kind: "secret-key",
      maskedValue: "sk_live_••••••••••••",
      service: "Stripe",
      tags: ["payments", "production"],
      grantedAgentIds: [],
      updatedAt: "May 1",
      note: "Restricted — manual grant only",
    },
    {
      id: "sec-redis-local",
      name: "Local Redis URL",
      kind: "env-variable",
      maskedValue: "redis://••••••••••••",
      tags: ["local", "cache"],
      grantedAgentIds: ["agent-coding", "agent-chat"],
      lastUsed: "Today",
      updatedAt: "Apr 28",
    },
    {
      id: "sec-docker-hub",
      name: "Docker Hub Password",
      kind: "password",
      maskedValue: "••••••••••••",
      service: "Docker Hub",
      username: "paulbloch",
      tags: ["deploy", "registry"],
      grantedAgentIds: ["agent-coding"],
      updatedAt: "Apr 20",
    },
    {
      id: "sec-figma",
      name: "Figma Personal Access Token",
      kind: "api-key",
      maskedValue: "figd_••••••••••••••••",
      service: "Figma",
      tags: ["design"],
      grantedAgentIds: ["agent-coding", "agent-chat"],
      lastUsed: "Jun 29",
      updatedAt: "Apr 15",
    },
    {
      id: "sec-jwt-signing",
      name: "JWT Signing Secret",
      kind: "secret-key",
      maskedValue: "••••••••••••••••••••",
      tags: ["auth", "backend"],
      grantedAgentIds: ["agent-orchestrator"],
      updatedAt: "Apr 1",
    },
    {
      id: "sec-sentry-dsn",
      name: "Sentry DSN",
      kind: "env-variable",
      maskedValue: "https://••••••••@sentry.io/••••",
      service: "Sentry",
      tags: ["monitoring"],
      grantedAgentIds: ["agent-coding"],
      updatedAt: "Mar 20",
    },
    {
      id: "sec-npm-token",
      name: "npm Access Token",
      kind: "api-key",
      maskedValue: "npm_••••••••••••••••",
      service: "npm",
      tags: ["publish", "registry"],
      grantedAgentIds: ["agent-coding"],
      updatedAt: "Mar 10",
    },
  ],
  envSets: [
    {
      id: "env-local",
      name: "Local Development",
      description: "Variables for running the full stack on localhost — agent server, automation, and Vite dev server.",
      environment: "local",
      variableCount: 12,
      secretIds: ["sec-redis-local"],
      grantedAgentIds: ["agent-coding", "agent-chat"],
      updatedAt: "Jul 1",
    },
    {
      id: "env-staging",
      name: "Staging",
      description: "Preview deployment credentials for PR branches and integration testing.",
      environment: "staging",
      variableCount: 18,
      secretIds: ["sec-vercel", "sec-posthog"],
      grantedAgentIds: ["agent-orchestrator", "agent-coding"],
      updatedAt: "Jun 25",
    },
    {
      id: "env-production",
      name: "Production",
      description: "Live environment variables — restricted grants, audit every read.",
      environment: "production",
      variableCount: 24,
      secretIds: ["sec-db-prod", "sec-stripe", "sec-aws"],
      grantedAgentIds: ["agent-orchestrator"],
      updatedAt: "Jun 10",
    },
    {
      id: "env-ci",
      name: "CI / GitHub Actions",
      description: "Secrets injected into CI workflows for build, test, and deploy pipelines.",
      environment: "development",
      variableCount: 9,
      secretIds: ["sec-github-pat", "sec-npm-token"],
      grantedAgentIds: ["agent-coding"],
      updatedAt: "Jun 5",
    },
  ],
  agents: [
    {
      id: "agent-chat",
      name: "Chat Agent",
      description: "Primary conversational agent — reads LLM keys and comms tokens when granted.",
      icon: "chat",
      grantedSecretCount: 7,
      lastAccess: "2m ago",
      status: "active",
    },
    {
      id: "agent-coding",
      name: "Coding Agent",
      description: "OpenHands agent for repo work — git, deploy, and MCP integrations.",
      icon: "terminal",
      grantedSecretCount: 11,
      lastAccess: "15m ago",
      status: "active",
    },
    {
      id: "agent-orchestrator",
      name: "Orchestrator",
      description: "Fleet coordinator — schedules jobs and delegates to sub-agents with scoped grants.",
      icon: "sparkles",
      grantedSecretCount: 6,
      lastAccess: "1h ago",
      status: "active",
    },
    {
      id: "agent-transcribe",
      name: "Transcribe Agent",
      description: "Audio transcription pipeline — no vault access by default.",
      icon: "mic",
      grantedSecretCount: 0,
      status: "paused",
    },
  ],
  grants: [
    { id: "g1", agentId: "agent-chat", secretId: "sec-openai", grantedAt: "Jun 1", grantedBy: "Paul Bloch", lastAccessed: "2m ago" },
    { id: "g2", agentId: "agent-chat", secretId: "sec-anthropic", grantedAt: "Jun 1", grantedBy: "Paul Bloch", lastAccessed: "1h ago" },
    { id: "g3", agentId: "agent-chat", secretId: "sec-slack-bot", grantedAt: "May 28", grantedBy: "Paul Bloch", lastAccessed: "4h ago" },
    { id: "g4", agentId: "agent-chat", secretId: "sec-posthog", grantedAt: "May 10", grantedBy: "Paul Bloch" },
    { id: "g5", agentId: "agent-chat", secretId: "sec-redis-local", grantedAt: "Apr 28", grantedBy: "Paul Bloch", lastAccessed: "Today" },
    { id: "g6", agentId: "agent-chat", secretId: "sec-figma", grantedAt: "Apr 15", grantedBy: "Paul Bloch", lastAccessed: "Jun 29" },
    { id: "g7", agentId: "agent-coding", secretId: "sec-openai", grantedAt: "Jun 1", grantedBy: "Paul Bloch" },
    { id: "g8", agentId: "agent-coding", secretId: "sec-anthropic", grantedAt: "Jun 1", grantedBy: "Paul Bloch" },
    { id: "g9", agentId: "agent-coding", secretId: "sec-github-pat", grantedAt: "Jun 20", grantedBy: "Paul Bloch", lastAccessed: "Yesterday" },
    { id: "g10", agentId: "agent-coding", secretId: "sec-vercel", grantedAt: "Jun 15", grantedBy: "Paul Bloch" },
    { id: "g11", agentId: "agent-coding", secretId: "sec-docker-hub", grantedAt: "Apr 20", grantedBy: "Paul Bloch" },
    { id: "g12", agentId: "agent-coding", secretId: "sec-redis-local", grantedAt: "Apr 28", grantedBy: "Paul Bloch" },
    { id: "g13", agentId: "agent-coding", secretId: "sec-sentry-dsn", grantedAt: "Mar 20", grantedBy: "Paul Bloch" },
    { id: "g14", agentId: "agent-coding", secretId: "sec-npm-token", grantedAt: "Mar 10", grantedBy: "Paul Bloch" },
    { id: "g15", agentId: "agent-coding", secretId: "sec-figma", grantedAt: "Apr 15", grantedBy: "Paul Bloch" },
    { id: "g16", agentId: "agent-orchestrator", secretId: "sec-openai", grantedAt: "Jun 1", grantedBy: "Paul Bloch" },
    { id: "g17", agentId: "agent-orchestrator", secretId: "sec-vercel", grantedAt: "Jun 15", grantedBy: "Paul Bloch" },
    { id: "g18", agentId: "agent-orchestrator", secretId: "sec-db-prod", grantedAt: "Jun 10", grantedBy: "Paul Bloch" },
    { id: "g19", agentId: "agent-orchestrator", secretId: "sec-aws", grantedAt: "Jun 1", grantedBy: "Paul Bloch", lastAccessed: "Jun 30" },
    { id: "g20", agentId: "agent-orchestrator", secretId: "sec-linear", grantedAt: "May 20", grantedBy: "Paul Bloch" },
    { id: "g21", agentId: "agent-orchestrator", secretId: "sec-jwt-signing", grantedAt: "Apr 1", grantedBy: "Paul Bloch" },
  ],
  auditLog: [
    { id: "a1", agentName: "Chat Agent", secretName: "OpenAI API Key", action: "read", timestamp: "2m ago", context: "Conversation start" },
    { id: "a2", agentName: "Coding Agent", secretName: "GitHub PAT", action: "read", timestamp: "15m ago", context: "git push" },
    { id: "a3", agentName: "Paul Bloch", secretName: "Stripe Secret Key", action: "grant", timestamp: "1h ago", context: "Revoked from Orchestrator" },
    { id: "a4", agentName: "Orchestrator", secretName: "AWS Access Key", action: "read", timestamp: "3h ago", context: "S3 upload job" },
    { id: "a5", agentName: "Paul Bloch", secretName: "Figma PAT", action: "grant", timestamp: "Yesterday", context: "Granted to Coding Agent" },
    { id: "a6", agentName: "Chat Agent", secretName: "Slack Bot Token", action: "read", timestamp: "Yesterday", context: "Channel post" },
    { id: "a7", agentName: "Paul Bloch", secretName: "npm Access Token", action: "create", timestamp: "Mar 10", context: "Added to vault" },
    { id: "a8", agentName: "Coding Agent", secretName: "Local Redis URL", action: "read", timestamp: "Today", context: "Dev stack bootstrap" },
    { id: "a9", agentName: "Paul Bloch", secretName: "1Password Service Account", action: "update", timestamp: "Jun 5", context: "Rotated token" },
    { id: "a10", agentName: "Orchestrator", secretName: "Production Database URL", action: "read", timestamp: "Jun 28", context: "Analytics query" },
  ],
};
