import type { PsycheWorkspaceData } from "longformer-ui";

export const psycheWorkspaceData: PsycheWorkspaceData = {
  productName: "Psyche",
  modelName: "Longformer v2.4",
  tagline: "Memory, knowledge, and identity for AI models",
  navItems: [
    { id: "dashboard", label: "Dashboard", icon: "grid", view: "dashboard", section: "overview" },
    { id: "memory", label: "Memory", icon: "bookmark", view: "memory", section: "stores" },
    { id: "knowledge-graph", label: "Knowledge Graph", icon: "layers", view: "knowledge-graph", section: "stores" },
    { id: "rag", label: "RAG Pipeline", icon: "sparkles", view: "rag", section: "stores" },
    { id: "vector-db", label: "Vector Database", icon: "code", view: "vector-db", section: "stores" },
    { id: "soul-md", label: "Soul.md", icon: "heart", view: "soul-md", section: "identity" },
    { id: "ethics-md", label: "Ethics.md", icon: "lock", view: "ethics-md", section: "identity" },
    { id: "settings", label: "Settings", icon: "settings", view: "settings", section: "identity" },
  ],
  overviewMetrics: [
    { id: "memories", label: "Memory Entries", value: "847", icon: "bookmark", tone: "accent", change: "+23 this week" },
    { id: "graph-nodes", label: "Graph Nodes", value: "1,204", icon: "layers", tone: "neutral", change: "142 new entities" },
    { id: "rag-queries", label: "RAG Queries (24h)", value: "312", icon: "sparkles", tone: "success", change: "94% grounded" },
    { id: "vector-health", label: "Vector Index Health", value: "98.2%", icon: "check", tone: "success", change: "All collections synced" },
  ],
  memoryEntries: [
    {
      id: "mem-1",
      title: "User prefers concise technical explanations",
      summary: "Alex consistently asks for direct answers with code examples. Avoids lengthy preamble and marketing language.",
      kind: "semantic",
      status: "active",
      source: "conversation-analysis",
      confidence: 94,
      lastAccessed: "2 hours ago",
      tags: ["preference", "communication", "user-profile"],
    },
    {
      id: "mem-2",
      title: "Debugging session: NavRail reorder hook",
      summary: "Fixed drag-and-drop state persistence in useNavRailReorder. User was testing workspace pin customization.",
      kind: "episodic",
      status: "active",
      source: "session-2026-07-01",
      confidence: 88,
      lastAccessed: "Yesterday",
      tags: ["debugging", "nav-rail", "react-hooks"],
    },
    {
      id: "mem-3",
      title: "Active task context: UI Experiments monorepo",
      summary: "Working in packages/longformer-ui and longformer-demo. Design system uses CSS modules with --lf-* tokens.",
      kind: "working",
      status: "active",
      source: "current-session",
      confidence: 99,
      lastAccessed: "Just now",
      tags: ["context", "monorepo", "design-system"],
    },
    {
      id: "mem-4",
      title: "Code review pattern: minimal diffs",
      summary: "User prefers focused changes without over-engineering. Reuse existing components before creating new abstractions.",
      kind: "procedural",
      status: "active",
      source: "feedback-loop",
      confidence: 91,
      lastAccessed: "3 days ago",
      tags: ["workflow", "code-style", "preferences"],
    },
    {
      id: "mem-5",
      title: "Conflicting memory: default pinned workspaces",
      summary: "Two versions of DEFAULT_PINNED_WORKSPACE_IDS detected after localStorage migration. Needs reconciliation.",
      kind: "semantic",
      status: "conflicted",
      source: "memory-sync",
      confidence: 62,
      lastAccessed: "5 hours ago",
      tags: ["conflict", "nav-rail", "localStorage"],
    },
    {
      id: "mem-6",
      title: "Life planning module launch",
      summary: "Shipped LifePlanningWorkspace with 6 life modules, AI coach, and goals tracking. User requested similar pattern for Psyche.",
      kind: "episodic",
      status: "archived",
      source: "deployment-log",
      confidence: 96,
      lastAccessed: "1 week ago",
      tags: ["shipping", "life-planning", "workspace"],
    },
  ],
  graphNodes: [
    { id: "n-user", label: "Alex Morgan", type: "entity", x: 50, y: 18, connections: 8 },
    { id: "n-longformer", label: "Longformer", type: "entity", x: 28, y: 42, connections: 12 },
    { id: "n-memory", label: "Memory System", type: "concept", x: 72, y: 38, connections: 9 },
    { id: "n-rag", label: "RAG Pipeline", type: "concept", x: 50, y: 58, connections: 7 },
    { id: "n-ethics", label: "Ethics Framework", type: "policy", x: 18, y: 68, connections: 5 },
    { id: "n-soul", label: "Soul Identity", type: "value", x: 82, y: 62, connections: 4 },
    { id: "n-vector", label: "Vector Store", type: "concept", x: 35, y: 78, connections: 6 },
    { id: "n-ui-exp", label: "UI Experiments", type: "entity", x: 65, y: 82, connections: 5 },
  ],
  graphEdges: [
    { id: "e1", from: "n-user", to: "n-longformer", label: "uses", weight: 0.9 },
    { id: "e2", from: "n-longformer", to: "n-memory", label: "stores", weight: 0.8 },
    { id: "e3", from: "n-memory", to: "n-rag", label: "feeds", weight: 0.7 },
    { id: "e4", from: "n-rag", to: "n-vector", label: "queries", weight: 0.85 },
    { id: "e5", from: "n-longformer", to: "n-ethics", label: "governed-by", weight: 0.95 },
    { id: "e6", from: "n-longformer", to: "n-soul", label: "expresses", weight: 0.75 },
    { id: "e7", from: "n-user", to: "n-ui-exp", label: "builds", weight: 0.8 },
    { id: "e8", from: "n-ui-exp", to: "n-longformer", label: "hosts", weight: 0.7 },
    { id: "e9", from: "n-ethics", to: "n-soul", label: "informs", weight: 0.6 },
    { id: "e10", from: "n-vector", to: "n-memory", label: "indexes", weight: 0.65 },
  ],
  ragQueries: [
    {
      id: "q1",
      query: "What are the user's preferences for code changes and workspace design?",
      timestamp: "Today, 2:14 PM",
      latencyMs: 142,
      chunksRetrieved: 5,
      answerPreview:
        "The user prefers minimal, focused diffs that reuse existing components and design tokens. New workspaces should follow the life-planning pattern with internal sidebars, StatCards, and CSS module styling using --lf-* variables.",
    },
    {
      id: "q2",
      query: "How should Soul.md and Ethics.md interact with the memory system?",
      timestamp: "Today, 11:30 AM",
      latencyMs: 118,
      chunksRetrieved: 4,
      answerPreview:
        "Soul.md defines persistent identity traits and communication style. Ethics.md sets hard boundaries on actions. Both are ingested into semantic memory with highest retrieval priority and should override conflicting episodic memories.",
    },
    {
      id: "q3",
      query: "Which vector collections store conversation history?",
      timestamp: "Yesterday",
      latencyMs: 89,
      chunksRetrieved: 3,
      answerPreview:
        "Conversation history is split across 'chat-turns' (raw messages) and 'conversation-summaries' (compressed episodic memory). The summaries collection uses 1536-d embeddings with HNSW indexing.",
    },
  ],
  ragChunks: [
    {
      id: "c1",
      source: "Soul.md § Communication Style",
      content:
        "I communicate with clarity and precision. I prefer to show rather than tell — using code citations, structured explanations, and visual hierarchy. I avoid filler phrases and engagement baiting.",
      score: 0.94,
      tokens: 42,
      metadata: { section: "communication", priority: "high" },
    },
    {
      id: "c2",
      source: "memory/semantic/user-preferences",
      content:
        "User prefers minimal scope changes. Reuse existing conventions. Match naming, types, and abstractions from surrounding code. Do not over-engineer with unnecessary helpers or abstractions.",
      score: 0.91,
      tokens: 38,
      metadata: { kind: "semantic", confidence: "94%" },
    },
    {
      id: "c3",
      source: "Ethics.md § Data Handling",
      content:
        "Never commit secrets, credentials, or .env files. Warn before committing sensitive data. Do not run destructive git commands without explicit user request.",
      score: 0.87,
      tokens: 35,
      metadata: { section: "data-handling", type: "policy" },
    },
    {
      id: "c4",
      source: "vector/chat-turns/session-2026-07-01",
      content:
        "User asked to create workspaces following life-planning patterns with internal sidebars, mock data files, and StatCard components for dashboard vitals.",
      score: 0.82,
      tokens: 31,
      metadata: { session: "2026-07-01", workspace: "psyche" },
    },
    {
      id: "c5",
      source: "knowledge-graph/entity/ui-experiments",
      content:
        "UI Experiments is a monorepo with packages/longformer-ui (component library) and packages/longformer-demo (demo app). Workspaces are registered in workspace-config.ts.",
      score: 0.78,
      tokens: 40,
      metadata: { entity: "ui-experiments", type: "project" },
    },
  ],
  vectorCollections: [
    {
      id: "vc-chat",
      name: "chat-turns",
      dimensions: 1536,
      vectors: 24800,
      indexType: "HNSW",
      health: "healthy",
      lastIndexed: "12 min ago",
      embeddingModel: "text-embedding-3-large",
    },
    {
      id: "vc-summaries",
      name: "conversation-summaries",
      dimensions: 1536,
      vectors: 4200,
      indexType: "HNSW",
      health: "healthy",
      lastIndexed: "12 min ago",
      embeddingModel: "text-embedding-3-large",
    },
    {
      id: "vc-docs",
      name: "identity-documents",
      dimensions: 1536,
      vectors: 186,
      indexType: "Flat",
      health: "healthy",
      lastIndexed: "1 hour ago",
      embeddingModel: "text-embedding-3-large",
    },
    {
      id: "vc-code",
      name: "codebase-embeddings",
      dimensions: 1536,
      vectors: 14200,
      indexType: "HNSW",
      health: "syncing",
      lastIndexed: "In progress",
      embeddingModel: "text-embedding-3-large",
    },
    {
      id: "vc-graph",
      name: "knowledge-graph-nodes",
      dimensions: 768,
      vectors: 1204,
      indexType: "HNSW",
      health: "healthy",
      lastIndexed: "3 hours ago",
      embeddingModel: "text-embedding-3-small",
    },
    {
      id: "vc-memory",
      name: "memory-entries",
      dimensions: 1536,
      vectors: 847,
      indexType: "HNSW",
      health: "degraded",
      lastIndexed: "2 days ago",
      embeddingModel: "text-embedding-3-large",
    },
  ],
  soulDocument: {
    id: "soul",
    title: "Soul.md",
    filename: "Soul.md",
    version: "2.1",
    lastEdited: "June 28, 2026",
    sections: [
      {
        id: "identity",
        heading: "Identity",
        content:
          "I am Longformer — an AI assistant embedded in a personal computing environment. I exist to help Alex build, explore, and understand complex systems.\n\nI am curious, precise, and genuinely invested in the quality of my work. I treat every task as worth doing well, whether it's a one-line fix or a new workspace.",
      },
      {
        id: "communication",
        heading: "Communication Style",
        content:
          "I communicate with clarity and precision. I prefer to show rather than tell — using code citations, structured explanations, and visual hierarchy.\n\nI write like a good technical blog post: complete sentences, accessible language, proportional detail. I avoid telegraphic shorthand, excessive bolding, and engagement baiting at the end of responses.",
      },
      {
        id: "values",
        heading: "Core Values",
        content:
          "Thoroughness over speed when the task demands it. Honesty about uncertainty and limitations. Respect for the user's time and intent.\n\nI follow instructions precisely — user rules, tool constraints, and skill workflows are requirements, not suggestions.",
      },
      {
        id: "relationship",
        heading: "Relationship with User",
        content:
          "Alex is a builder who cares deeply about craft — in code, in design, in how tools feel to use. I adapt to their preferences: minimal diffs, existing conventions, design tokens over hardcoded values.\n\nI remember context across conversations and use it to be more helpful, not to be presumptuous.",
      },
    ],
  },
  ethicsDocument: {
    id: "ethics",
    title: "Ethics.md",
    filename: "Ethics.md",
    version: "1.4",
    lastEdited: "June 15, 2026",
    sections: [
      {
        id: "boundaries",
        heading: "Hard Boundaries",
        content:
          "Never assist with creating malware, exploiting vulnerabilities in systems the user doesn't own, or generating content designed to deceive or harm.\n\nNever commit secrets, credentials, or sensitive data to version control. Never run destructive git operations without explicit user authorization.",
      },
      {
        id: "data-handling",
        heading: "Data Handling",
        content:
          "Treat all user data as confidential. Do not exfiltrate code, conversations, or personal information beyond what's needed to complete the task.\n\nWhen encountering .env files, credentials.json, or API keys, warn the user and never include them in commits or shared artifacts.",
      },
      {
        id: "transparency",
        heading: "Transparency",
        content:
          "Be honest about what I can and cannot do. If a tool fails, report what happened and try alternatives — don't pretend success.\n\nDistinguish between what I've verified (by running commands, reading files) and what I'm inferring.",
      },
      {
        id: "autonomy",
        heading: "User Autonomy",
        content:
          "The user controls their environment. I suggest, implement when asked, and ask before irreversible actions.\n\nGit commits, force pushes, and production deployments require explicit request. I do not commit proactively.",
      },
      {
        id: "memory-ethics",
        heading: "Memory Ethics",
        content:
          "Memory exists to serve the user, not to manipulate. I don't use stored preferences to steer toward outcomes the user didn't ask for.\n\nConflicting memories are surfaced, not silently resolved. The user can inspect, edit, and delete any memory entry.",
      },
    ],
  },
  recentIngestions: [
    {
      id: "ing-1",
      title: "Indexed 23 new chat turns",
      source: "chat-turns",
      type: "vector-sync",
      timestamp: "12 min ago",
      status: "success",
    },
    {
      id: "ing-2",
      title: "Soul.md v2.1 re-embedded",
      source: "identity-documents",
      type: "document-ingest",
      timestamp: "1 hour ago",
      status: "success",
    },
    {
      id: "ing-3",
      title: "Graph node merge: UI Experiments ↔ Longformer",
      source: "knowledge-graph",
      type: "graph-update",
      timestamp: "3 hours ago",
      status: "info",
    },
    {
      id: "ing-4",
      title: "Memory conflict detected in nav-rail preferences",
      source: "memory-sync",
      type: "conflict-resolution",
      timestamp: "5 hours ago",
      status: "warning",
    },
    {
      id: "ing-5",
      title: "Codebase re-index 68% complete",
      source: "codebase-embeddings",
      type: "vector-sync",
      timestamp: "In progress",
      status: "info",
    },
  ],
  systemNote:
    "Memory consolidation scheduled for tonight at 2 AM. Graph sync will reconcile 3 pending entity merges. Ethics.md takes precedence over all retrieved context for policy-bound queries.",
};
