import type { ServerWorkspaceData } from "longformer-ui";

export const serverWorkspaceData: ServerWorkspaceData = {
  teamName: "Paul's projects",
  planLabel: "Hobby",
  userName: "paulbloch",
  navItems: [
    { id: "dashboard", label: "Projects", icon: "grid", view: "dashboard" },
    { id: "deployments", label: "Deployments", icon: "layers", view: "deployments", badge: "12" },
    { id: "storage", label: "Storage", icon: "folder", view: "storage" },
    { id: "servers", label: "Servers", icon: "terminal", view: "servers" },
    { id: "sources", label: "Sources", icon: "code", view: "sources" },
    { id: "domains", label: "Domains", icon: "globe", view: "domains" },
  ],
  usageExceeded: true,
  usageMetrics: [
    { id: "img", label: "Image Optimization", used: 10, limit: 5, unit: "K", exceeded: true },
    { id: "cpu", label: "Fluid Active CPU", used: 4, limit: 4, unit: "h", exceeded: true },
    { id: "edge", label: "Edge Requests", used: 8.2, limit: 10, unit: "K" },
    { id: "transfer", label: "Fast Origin Transfer", used: 1.1, limit: 10, unit: "GB" },
  ],
  recentPreviews: [
    {
      id: "prev-1",
      branch: "color-update",
      commitMessage: "Update brand palette and hero gradient",
      author: "Paul Bloch",
      timeAgo: "2h ago",
    },
    {
      id: "prev-2",
      branch: "feat/api-v2",
      commitMessage: "Add rate limiting middleware",
      author: "Paul Bloch",
      timeAgo: "5h ago",
    },
    {
      id: "prev-3",
      branch: "fix/docker-health",
      commitMessage: "Fix healthcheck interval for worker",
      author: "Paul Bloch",
      timeAgo: "1d ago",
    },
  ],
  projects: [
    {
      id: "proj-1",
      name: "andrew-cohen-site",
      url: "andrew-cohen-site.vercel.app",
      kind: "frontend",
      status: "ready",
      repo: "FraterCCCLXIII/andrew-cohen-site",
      commitMessage: "Update hero section copy",
      deployedAt: "Jun 20",
      branch: "main",
      icon: "A",
      iconBg: "var(--lf-accent-muted)",
    },
    {
      id: "proj-2",
      name: "castbook-api",
      url: "api.castbook.dev",
      kind: "backend",
      status: "ready",
      repo: "paulbloch/castbook-api",
      commitMessage: "Migrate auth to JWT refresh tokens",
      deployedAt: "Jun 18",
      branch: "production",
      icon: "⚡",
      iconBg: "var(--lf-warning-muted)",
    },
    {
      id: "proj-3",
      name: "dharma-atlas",
      url: "dharma-atlas.io",
      kind: "fullstack",
      status: "building",
      repo: "paulbloch/dharma-atlas",
      commitMessage: "Add map tile caching layer",
      deployedAt: "Building…",
      branch: "main",
      icon: "🗺",
      iconBg: "var(--lf-success-muted)",
    },
    {
      id: "proj-4",
      name: "lasting-book",
      url: "lasting-book.app",
      kind: "docker",
      status: "ready",
      repo: "paulbloch/lasting-book",
      commitMessage: "Bump postgres to 16.2",
      deployedAt: "Jun 15",
      branch: "main",
      icon: "📖",
      iconBg: "var(--lf-surface-sunken)",
    },
    {
      id: "proj-5",
      name: "mobile-acupuncture",
      url: "mobile-acupuncture.com",
      kind: "static",
      status: "ready",
      repo: "paulbloch/mobile-acupuncture",
      commitMessage: "Update booking widget embed",
      deployedAt: "Jun 12",
      branch: "main",
      icon: "🌿",
      iconBg: "var(--lf-success-muted)",
    },
    {
      id: "proj-6",
      name: "analytics-worker",
      url: "worker.internal",
      kind: "worker",
      status: "stopped",
      repo: "paulbloch/analytics-worker",
      commitMessage: "Scale down for maintenance window",
      deployedAt: "Jun 10",
      branch: "main",
      icon: "📊",
      iconBg: "var(--lf-surface-sunken)",
    },
  ],
  deployments: [
    {
      id: "dep-1",
      projectName: "castbook-api",
      status: "ready",
      branch: "production",
      commit: "a3f8c21",
      commitMessage: "Migrate auth to JWT refresh tokens",
      author: "Paul Bloch",
      duration: "1m 42s",
      timeAgo: "18m ago",
      environment: "production",
    },
    {
      id: "dep-2",
      projectName: "dharma-atlas",
      status: "building",
      branch: "main",
      commit: "7b2e901",
      commitMessage: "Add map tile caching layer",
      author: "Paul Bloch",
      duration: "—",
      timeAgo: "3m ago",
      environment: "preview",
    },
    {
      id: "dep-3",
      projectName: "andrew-cohen-site",
      status: "ready",
      branch: "color-update",
      commit: "c91d4ff",
      commitMessage: "Update brand palette and hero gradient",
      author: "Paul Bloch",
      duration: "48s",
      timeAgo: "2h ago",
      environment: "preview",
    },
    {
      id: "dep-4",
      projectName: "lasting-book",
      status: "ready",
      branch: "main",
      commit: "e04a118",
      commitMessage: "Bump postgres to 16.2",
      author: "Paul Bloch",
      duration: "2m 15s",
      timeAgo: "Jun 15",
      environment: "production",
    },
    {
      id: "dep-5",
      projectName: "analytics-worker",
      status: "error",
      branch: "main",
      commit: "f8820aa",
      commitMessage: "Increase batch size for nightly rollup",
      author: "Paul Bloch",
      duration: "failed",
      timeAgo: "Jun 11",
      environment: "production",
    },
  ],
  servers: [
    {
      id: "srv-1",
      name: "localhost",
      description: "This is the server where Coolify is running. Don't delete this!",
      status: "online",
      ip: "127.0.0.1",
      cpu: 24,
      memory: 58,
      disk: 42,
      apps: 6,
    },
    {
      id: "srv-2",
      name: "production-us-east",
      description: "Primary production VPS — Hetzner CPX31",
      status: "online",
      ip: "65.108.42.17",
      region: "Ashburn, VA",
      cpu: 67,
      memory: 72,
      disk: 81,
      apps: 4,
    },
    {
      id: "srv-3",
      name: "staging-eu",
      description: "Staging environment for preview deployments",
      status: "maintenance",
      ip: "116.203.88.4",
      region: "Frankfurt, DE",
      cpu: 12,
      memory: 34,
      disk: 28,
      apps: 2,
    },
  ],
  volumes: [
    {
      id: "vol-1",
      name: "castbook-uploads",
      mountPath: "/var/lib/castbook/uploads",
      projectName: "castbook-api",
      usedGb: 42.3,
      totalGb: 100,
      type: "persistent",
    },
    {
      id: "vol-2",
      name: "lasting-book-db",
      mountPath: "/data/postgres",
      projectName: "lasting-book",
      usedGb: 8.7,
      totalGb: 20,
      type: "persistent",
    },
    {
      id: "vol-3",
      name: "dharma-cache",
      mountPath: "/cache/tiles",
      projectName: "dharma-atlas",
      usedGb: 15.2,
      totalGb: 50,
      type: "persistent",
    },
    {
      id: "vol-4",
      name: "worker-tmp",
      mountPath: "/tmp/processing",
      projectName: "analytics-worker",
      usedGb: 1.8,
      totalGb: 5,
      type: "tmpfs",
    },
  ],
  buckets: [
    {
      id: "bucket-1",
      name: "castbook-assets",
      provider: "s3",
      endpoint: "s3.us-east-1.amazonaws.com",
      usedGb: 128.4,
      totalGb: 500,
      objects: 24831,
      status: "connected",
    },
    {
      id: "bucket-2",
      name: "dharma-media",
      provider: "r2",
      endpoint: "r2.cloudflarestorage.com",
      usedGb: 56.2,
      totalGb: 200,
      objects: 9104,
      status: "connected",
    },
    {
      id: "bucket-3",
      name: "backups-minio",
      provider: "minio",
      endpoint: "minio.internal:9000",
      usedGb: 312.0,
      totalGb: 1000,
      objects: 4820,
      status: "syncing",
    },
  ],
  databases: [
    {
      id: "db-1",
      name: "castbook-postgres",
      engine: "postgres",
      projectName: "castbook-api",
      usedGb: 4.2,
      totalGb: 20,
      connections: 24,
    },
    {
      id: "db-2",
      name: "lasting-book-db",
      engine: "postgres",
      projectName: "lasting-book",
      usedGb: 8.7,
      totalGb: 20,
      connections: 8,
    },
    {
      id: "db-3",
      name: "session-cache",
      engine: "redis",
      projectName: "castbook-api",
      usedGb: 0.3,
      totalGb: 2,
      connections: 156,
    },
    {
      id: "db-4",
      name: "analytics-events",
      engine: "mongodb",
      projectName: "analytics-worker",
      usedGb: 22.1,
      totalGb: 50,
      connections: 12,
    },
  ],
};
