import type { SheetsWorkspaceData } from "longformer-ui";

export const sheetsWorkspaceData: SheetsWorkspaceData = {
  workbooks: [
    {
      id: "wb-q2-budget",
      title: "Q2 Budget Tracker",
      starred: true,
      meta: "Edited 2h ago",
      sheets: [
        {
          id: "sheet-summary",
          name: "Summary",
          cells: {
            A1: { value: "Category", format: { bold: true, fill: "muted" } },
            B1: { value: "Budget", format: { bold: true, fill: "muted", align: "right" } },
            C1: { value: "Actual", format: { bold: true, fill: "muted", align: "right" } },
            D1: { value: "Variance", format: { bold: true, fill: "muted", align: "right" } },
            A2: { value: "Payroll" },
            B2: { value: 42000, format: { numberFormat: "currency" } },
            C2: { value: 41500, format: { numberFormat: "currency" } },
            D2: { value: 500, format: { numberFormat: "currency" } },
            A3: { value: "Cloud & Infra" },
            B3: { value: 8600, format: { numberFormat: "currency" } },
            C3: { value: 9120, format: { numberFormat: "currency" } },
            D3: { value: -520, format: { numberFormat: "currency" } },
            A4: { value: "Marketing" },
            B4: { value: 12000, format: { numberFormat: "currency" } },
            C4: { value: 10840, format: { numberFormat: "currency" } },
            D4: { value: 1160, format: { numberFormat: "currency" } },
            A5: { value: "Travel" },
            B5: { value: 4500, format: { numberFormat: "currency" } },
            C5: { value: 6200, format: { numberFormat: "currency" } },
            D5: { value: -1700, format: { numberFormat: "currency" } },
            A6: { value: "Software" },
            B6: { value: 3200, format: { numberFormat: "currency" } },
            C6: { value: 2980, format: { numberFormat: "currency" } },
            D6: { value: 220, format: { numberFormat: "currency" } },
            A8: { value: "Total", format: { bold: true, fill: "accent" } },
            B8: { value: 70300, format: { bold: true, numberFormat: "currency", fill: "accent" } },
            C8: { value: 70640, format: { bold: true, numberFormat: "currency", fill: "accent" } },
            D8: { value: -340, format: { bold: true, numberFormat: "currency", fill: "accent" } },
            A10: { value: "Notes", format: { bold: true } },
            A11: {
              value: "Marketing underspend offset cloud overage. Travel spike from SF offsite.",
            },
            A13: { value: "Runway (months)", format: { bold: true } },
            B13: { value: 14.2 },
            C13: { value: "Target", format: { italic: true } },
            D13: { value: 12 },
          },
        },
        {
          id: "sheet-expenses",
          name: "Expenses",
          cells: {
            A1: { value: "Date", format: { bold: true, fill: "muted" } },
            B1: { value: "Vendor", format: { bold: true, fill: "muted" } },
            C1: { value: "Category", format: { bold: true, fill: "muted" } },
            D1: { value: "Amount", format: { bold: true, fill: "muted", align: "right" } },
            A2: { value: "2026-04-02" },
            B2: { value: "AWS" },
            C2: { value: "Cloud & Infra" },
            D2: { value: 2840, format: { numberFormat: "currency" } },
            A3: { value: "2026-04-05" },
            B3: { value: "Linear" },
            C3: { value: "Software" },
            D3: { value: 480, format: { numberFormat: "currency" } },
            A4: { value: "2026-04-08" },
            B4: { value: "Google Ads" },
            C4: { value: "Marketing" },
            D4: { value: 2200, format: { numberFormat: "currency" } },
            A5: { value: "2026-04-12" },
            B5: { value: "Delta" },
            C5: { value: "Travel" },
            D5: { value: 640, format: { numberFormat: "currency" } },
            A6: { value: "2026-04-18" },
            B6: { value: "Figma" },
            C6: { value: "Software" },
            D6: { value: 180, format: { numberFormat: "currency" } },
          },
        },
        {
          id: "sheet-forecast",
          name: "Forecast",
          cells: {
            A1: { value: "Month", format: { bold: true, fill: "muted" } },
            B1: { value: "Revenue", format: { bold: true, fill: "muted", align: "right" } },
            C1: { value: "Burn", format: { bold: true, fill: "muted", align: "right" } },
            D1: { value: "Net", format: { bold: true, fill: "muted", align: "right" } },
            A2: { value: "Apr" },
            B2: { value: 92000, format: { numberFormat: "currency" } },
            C2: { value: 71000, format: { numberFormat: "currency" } },
            D2: { formula: "=B2-C2", value: 21000, format: { numberFormat: "currency" } },
            A3: { value: "May" },
            B3: { value: 98000, format: { numberFormat: "currency" } },
            C3: { value: 72500, format: { numberFormat: "currency" } },
            D3: { formula: "=B3-C3", value: 25500, format: { numberFormat: "currency" } },
            A4: { value: "Jun" },
            B4: { value: 104000, format: { numberFormat: "currency" } },
            C4: { value: 74000, format: { numberFormat: "currency" } },
            D4: { formula: "=B4-C4", value: 30000, format: { numberFormat: "currency" } },
            A6: { value: "Growth", format: { bold: true } },
            B6: { value: 0.13, format: { numberFormat: "percent" } },
          },
        },
      ],
    },
    {
      id: "wb-roadmap",
      title: "Product Roadmap",
      shared: true,
      owner: "Alex Kim",
      meta: "Edited yesterday",
      sheets: [
        {
          id: "sheet-roadmap-q2",
          name: "Q2",
          cells: {
            A1: { value: "Initiative", format: { bold: true, fill: "muted" } },
            B1: { value: "Owner", format: { bold: true, fill: "muted" } },
            C1: { value: "Status", format: { bold: true, fill: "muted" } },
            D1: { value: "Target", format: { bold: true, fill: "muted" } },
            A2: { value: "Sheets workspace" },
            B2: { value: "Paul" },
            C2: { value: "In progress" },
            D2: { value: "Apr 18" },
            A3: { value: "Hover nav rail" },
            B3: { value: "Jordan" },
            C3: { value: "Shipped" },
            D3: { value: "Apr 10" },
            A4: { value: "Agent orchestrator" },
            B4: { value: "Alex" },
            C4: { value: "Planning" },
            D4: { value: "May 2" },
          },
        },
      ],
    },
    {
      id: "wb-okrs",
      title: "Team OKRs",
      meta: "Edited 3d ago",
      sheets: [
        {
          id: "sheet-okrs",
          name: "OKRs",
          cells: {
            A1: { value: "Objective", format: { bold: true, fill: "muted" } },
            B1: { value: "Key result", format: { bold: true, fill: "muted" } },
            C1: { value: "Progress", format: { bold: true, fill: "muted", align: "right" } },
            A2: { value: "Ship AI OS shell" },
            B2: { value: "Launch 12 workspaces" },
            C2: { value: 0.75, format: { numberFormat: "percent" } },
            A3: { value: "Grow design system" },
            B3: { value: "Cover 40 primitives" },
            C3: { value: 0.62, format: { numberFormat: "percent" } },
          },
        },
      ],
    },
    {
      id: "wb-invoices",
      title: "Invoice Tracker",
      starred: true,
      meta: "Edited last week",
      sheets: [
        {
          id: "sheet-invoices",
          name: "Invoices",
          cells: {
            A1: { value: "Client", format: { bold: true, fill: "muted" } },
            B1: { value: "Amount", format: { bold: true, fill: "muted", align: "right" } },
            C1: { value: "Status", format: { bold: true, fill: "muted" } },
            A2: { value: "Northwind Labs" },
            B2: { value: 12400, format: { numberFormat: "currency" } },
            C2: { value: "Paid" },
            A3: { value: "Helix Research" },
            B3: { value: 8600, format: { numberFormat: "currency" } },
            C3: { value: "Sent" },
          },
        },
      ],
    },
  ],
  collaborators: [
    { name: "Paul Bloch" },
    { name: "Alex Kim" },
    { name: "Jordan Lee" },
  ],
};
