import type { TranscribeWorkspaceData } from "longformer-ui";

export const transcribeWorkspaceData: TranscribeWorkspaceData = {
  productName: "Transcribe",
  userName: "Alex Morgan",
  userEmail: "alex@meridian.dev",
  navItems: [
    { id: "library", label: "Library", icon: "notebook", view: "library" },
    { id: "in-progress", label: "In Progress", icon: "loader", view: "in-progress", badge: "3" },
    { id: "sources", label: "Sources", icon: "layers", view: "sources" },
    { id: "uploads", label: "Uploads", icon: "attach", view: "uploads" },
    { id: "settings", label: "Settings", icon: "settings", view: "settings" },
  ],
  connectedSources: [
    { id: "zoom", label: "Zoom", icon: "video", provider: "Zoom", status: "connected", lastSync: "2 min ago" },
    { id: "meet", label: "Google Meet", icon: "users", provider: "Google", status: "connected", lastSync: "15 min ago" },
    { id: "podcasts", label: "Podcast Feeds", icon: "play", provider: "RSS", status: "syncing", lastSync: "Syncing…" },
    { id: "drive", label: "Google Drive", icon: "folder", provider: "Google", status: "connected", lastSync: "1 hr ago" },
    { id: "dropbox", label: "Dropbox", icon: "folder", provider: "Dropbox", status: "disconnected" },
  ],
  pinnedTranscripts: [
    { id: "pin-1", label: "Q2 Planning — All Hands", meta: "42:18" },
    { id: "pin-2", label: "Investor Call — Series B", meta: "1:05:22" },
    { id: "pin-3", label: "Design Review — Mobile", meta: "28:44" },
  ],
  processingCount: 3,
  metrics: [
    { id: "total", label: "Total Transcripts", value: 148, trend: 18, status: "ready" },
    { id: "ready", label: "Ready", value: 132, trend: 12, status: "ready" },
    { id: "processing", label: "Processing", value: 3, trend: -25, status: "processing" },
    { id: "queued", label: "Queued", value: 5, trend: 40, status: "queued" },
    { id: "sources", label: "Connected Sources", value: 4, trend: 0, status: "connected" },
  ],
  transcripts: [
    {
      id: "tr-001",
      title: "Q2 Planning — All Hands",
      sourceType: "meeting",
      sourceLabel: "Zoom",
      status: "ready",
      durationMs: 2538000,
      wordCount: 8420,
      speakerCount: 12,
      createdAt: "Jul 2, 2026",
      createdAtMs: Date.parse("2026-07-02T10:00:00"),
      excerpt: "…focus on shipping the mobile redesign by end of quarter…",
      language: "English",
      pinned: true,
    },
    {
      id: "tr-002",
      title: "Investor Call — Series B",
      sourceType: "call",
      sourceLabel: "Phone",
      status: "ready",
      durationMs: 3922000,
      wordCount: 11840,
      speakerCount: 4,
      createdAt: "Jul 1, 2026",
      createdAtMs: Date.parse("2026-07-01T14:30:00"),
      excerpt: "…runway extends through Q1 2027 with current burn rate…",
      language: "English",
      pinned: true,
    },
    {
      id: "tr-003",
      title: "Design Review — Mobile App",
      sourceType: "meeting",
      sourceLabel: "Google Meet",
      status: "ready",
      durationMs: 1724000,
      wordCount: 5620,
      speakerCount: 6,
      createdAt: "Jul 1, 2026",
      createdAtMs: Date.parse("2026-07-01T09:15:00"),
      excerpt: "…navigation pattern should follow the bottom tab bar approach…",
      language: "English",
      pinned: true,
    },
    {
      id: "tr-004",
      title: "Lenny's Podcast — Ep. 412",
      sourceType: "podcast",
      sourceLabel: "RSS Feed",
      status: "processing",
      durationMs: 5400000,
      createdAt: "Jul 1, 2026",
      createdAtMs: Date.parse("2026-07-01T06:00:00"),
      excerpt: "Processing speaker diarization…",
      language: "English",
    },
    {
      id: "tr-005",
      title: "Customer Interview — Acme Corp",
      sourceType: "call",
      sourceLabel: "Zoom Phone",
      status: "ready",
      durationMs: 1845000,
      wordCount: 4890,
      speakerCount: 2,
      createdAt: "Jun 30, 2026",
      createdAtMs: Date.parse("2026-06-30T16:45:00"),
      excerpt: "…the onboarding flow lost us at the permissions step…",
      language: "English",
    },
    {
      id: "tr-006",
      title: "Board Meeting — June 2026",
      sourceType: "meeting",
      sourceLabel: "Zoom",
      status: "ready",
      durationMs: 7200000,
      wordCount: 15200,
      speakerCount: 8,
      createdAt: "Jun 30, 2026",
      createdAtMs: Date.parse("2026-06-30T13:00:00"),
      excerpt: "…approved the revised headcount plan for engineering…",
      language: "English",
    },
    {
      id: "tr-007",
      title: "Product Demo Recording",
      sourceType: "recording",
      sourceLabel: "Screen Capture",
      status: "queued",
      durationMs: 900000,
      createdAt: "Jun 30, 2026",
      createdAtMs: Date.parse("2026-06-30T11:20:00"),
      language: "English",
    },
    {
      id: "tr-008",
      title: "Team Standup — Engineering",
      sourceType: "meeting",
      sourceLabel: "Google Meet",
      status: "ready",
      durationMs: 900000,
      wordCount: 2340,
      speakerCount: 9,
      createdAt: "Jun 29, 2026",
      createdAtMs: Date.parse("2026-06-29T09:00:00"),
      excerpt: "…blocked on the API migration, need DevOps support…",
      language: "English",
    },
    {
      id: "tr-009",
      title: "Conference Talk — React Summit",
      sourceType: "upload",
      sourceLabel: "Manual Upload",
      status: "ready",
      durationMs: 2700000,
      wordCount: 7200,
      speakerCount: 1,
      createdAt: "Jun 28, 2026",
      createdAtMs: Date.parse("2026-06-28T15:30:00"),
      excerpt: "…server components changed how we think about data fetching…",
      language: "English",
    },
    {
      id: "tr-010",
      title: "How I Built This — Interview",
      sourceType: "podcast",
      sourceLabel: "Spotify",
      status: "processing",
      durationMs: 3600000,
      createdAt: "Jun 28, 2026",
      createdAtMs: Date.parse("2026-06-28T08:00:00"),
      excerpt: "Transcribing audio track 2 of 2…",
      language: "English",
    },
    {
      id: "tr-011",
      title: "Sales Call — Enterprise Lead",
      sourceType: "call",
      sourceLabel: "Phone",
      status: "failed",
      durationMs: 1200000,
      createdAt: "Jun 27, 2026",
      createdAtMs: Date.parse("2026-06-27T14:00:00"),
      excerpt: "Audio quality too low for transcription",
      language: "English",
    },
    {
      id: "tr-012",
      title: "Weekly Sync — Product Team",
      sourceType: "meeting",
      sourceLabel: "Zoom",
      status: "ready",
      durationMs: 2700000,
      wordCount: 6100,
      speakerCount: 5,
      createdAt: "Jun 27, 2026",
      createdAtMs: Date.parse("2026-06-27T10:00:00"),
      excerpt: "…design tokens are ready for the component library update…",
      language: "English",
    },
  ],
};
