import type { WalletExpense } from "longformer-ui";

export const walletExpenses: WalletExpense[] = [
  {
    id: "exp-uber",
    merchant: "Uber Inc.",
    category: "Taxi",
    amount: 35,
    color: "#c8dcc4",
    avatarLabel: "U",
    dateLabel: "Today · 9:14 AM",
    note: "Airport transfer to SFO Terminal 2.",
  },
  {
    id: "exp-netflix",
    merchant: "Netflix",
    category: "Movie",
    amount: 15,
    color: "#d8c4a8",
    avatarLabel: "N",
    dateLabel: "Yesterday",
    note: "Standard plan — monthly renewal.",
  },
  {
    id: "exp-dribbble",
    merchant: "Dribbble Inc.",
    category: "Design",
    amount: 35,
    color: "#efe6a8",
    avatarLabel: "D",
    dateLabel: "Jun 28",
    note: "Pro subscription for design asset access.",
  },
  {
    id: "exp-mcdonalds",
    merchant: "McDonald's",
    category: "Food",
    amount: 109,
    color: "#ef5350",
    avatarLabel: "M",
    dateLabel: "Jun 27 · Lunch",
    note: "Team lunch — 4 people.",
  },
  {
    id: "exp-playstation",
    merchant: "Play Station",
    category: "Games",
    amount: 281.5,
    color: "#e4e4e4",
    avatarLabel: "P",
    dateLabel: "Jun 24",
    note: "DualSense Edge controller and game bundle.",
  },
  {
    id: "exp-amazon",
    merchant: "Amazon",
    category: "Shopping",
    amount: 64.99,
    color: "#ffb74d",
    avatarLabel: "A",
    dateLabel: "Jun 22",
    note: "USB-C hub and cable kit.",
  },
];
