/** Tailwind class map — converted from ComposerWorkspace.module.css */
const styles: Record<string, string> = {
  actionActive: "text-[var(--composer-accent)]",
  art: "[flex-shrink:0] rounded-lf-sm bg-[var(--art-gradient,_linear-gradient(135deg,_#444,_#222))] overflow-hidden",
  artAmber: "[--art-gradient:linear-gradient(135deg,_#fbbf24,_#b45309)]",
  artBlue: "[--art-gradient:linear-gradient(135deg,_#60a5fa,_#1d4ed8)]",
  artCyan: "[--art-gradient:linear-gradient(135deg,_#22d3ee,_#0e7490)]",
  artFull: "w-full h-full",
  artGreen: "[--art-gradient:linear-gradient(135deg,_#4ade80,_#15803d)]",
  artIndigo: "[--art-gradient:linear-gradient(135deg,_#818cf8,_#4338ca)]",
  artLime: "[--art-gradient:linear-gradient(135deg,_#a3e635,_#4d7c0f)]",
  artMd: "w-[72px] h-[72px] rounded-lf-md",
  artOrange: "[--art-gradient:linear-gradient(135deg,_#fb923c,_#c2410c)]",
  artPink: "[--art-gradient:linear-gradient(135deg,_#f472b6,_#be185d)]",
  artPurple: "[--art-gradient:linear-gradient(135deg,_#c084fc,_#7e22ce)]",
  artRose: "[--art-gradient:linear-gradient(135deg,_#fb7185,_#be123c)]",
  artSm: "w-[40px] h-[40px]",
  artTeal: "[--art-gradient:linear-gradient(135deg,_#2dd4bf,_#0f766e)]",
  artViolet: "[--art-gradient:linear-gradient(135deg,_#a78bfa,_#6d28d9)]",
  body: "flex-1 flex min-h-0 [--lf-divider:var(--composer-border)]",
  breadcrumbMuted: "text-[var(--composer-text-muted)]",
  breadcrumbs: "flex items-center gap-lf-2 mb-lf-3 text-lf-sm font-semibold",
  controlRow: "flex items-center justify-center gap-lf-2",
  creationHeader: "flex items-center justify-between gap-lf-3",
  creationPane: "h-full min-h-0",
  creationPanel: "flex flex-col gap-lf-4 h-full min-h-0 p-lf-4 bg-[var(--composer-bg-elevated)]",
  creationResizable: "[flex-shrink:0]",
  filterBtn: "[flex-shrink:0]",
  inputTypeBtn: "gap-lf-2",
  inputTypes: "flex flex-wrap gap-lf-2",
  instrumentalToggle: "p-[6px_12px] border border-solid border-[var(--composer-border)] rounded-lf-pill bg-transparent text-[var(--composer-text-subtle)] text-lf-xs font-semibold cursor-pointer",
  instrumentalToggleActive: "bg-[var(--composer-text)] text-[var(--composer-bg)] border-transparent",
  libraryHeader: "[flex-shrink:0] p-[var(--lf-space-4)_var(--lf-space-5)_var(--lf-space-3)] border-b border-[var(--composer-border)]",
  libraryPanel: "flex-1 min-w-0 flex flex-col min-h-0 bg-[var(--composer-bg)] text-[var(--composer-text)] [--lf-surface-1:var(--composer-bg)] [--lf-surface-2:var(--composer-hover-bg)] [--lf-surface-3:var(--composer-bg-highlight)] [--lf-text-primary:var(--composer-text)] [--lf-text-secondary:var(--composer-text-subtle)] [--lf-text-tertiary:var(--composer-text-muted)] [scrollbar-color:var(--composer-scrollbar-thumb)_transparent]",
  libraryToolbar: "flex items-center gap-lf-2 flex-wrap",
  lyricsBtn: "gap-lf-2",
  mainArea: "flex-1 flex min-w-0 min-h-0",
  modelTrigger: "inline-flex items-center gap-[4px] p-[6px_10px] border border-solid border-[var(--composer-border)] rounded-lf-pill bg-[var(--composer-card-bg)] text-[var(--composer-text)] text-lf-xs font-semibold cursor-pointer",
  modeTabs: "flex-1 min-w-0",
  moreBtn: "inline-flex items-center justify-center w-[32px] h-[32px] border-none rounded-lf-md bg-transparent text-[var(--composer-text-subtle)] cursor-pointer hover:bg-[var(--composer-hover-bg)] hover:text-[var(--composer-text)]",
  navSearchField: "text-[var(--composer-text)]",
  navSearchInput: "bg-[var(--composer-bg-highlight)] border-[var(--composer-border)]",
  navSidebar: "h-full bg-[var(--composer-bg)] text-[var(--composer-text)] [--lf-surface-1:var(--composer-bg)] [--lf-surface-2:var(--composer-hover-bg)] [--lf-surface-3:var(--composer-bg-highlight)] [--lf-surface-sunken:var(--composer-bg-highlight)] [--lf-divider:var(--composer-border)] [--lf-border-subtle:var(--composer-border)] [--lf-border-strong:var(--composer-scrollbar-thumb)] [--lf-text-primary:var(--composer-text)] [--lf-text-secondary:var(--composer-text-subtle)] [--lf-text-tertiary:var(--composer-text-muted)] [scrollbar-color:var(--composer-scrollbar-thumb)_transparent]",
  newBadge: "p-[1px_6px] rounded-lf-pill bg-[var(--composer-accent)] text-[var(--composer-on-primary)] text-[10px] font-bold uppercase",
  pagination: "flex items-center gap-[2px] ml-auto",
  playerBar: "[flex-shrink:0] grid grid-cols-[1fr_2fr_1fr] items-center gap-lf-4 p-[var(--lf-space-2)_var(--lf-space-4)] bg-[var(--composer-bg-elevated)] border-t border-[var(--composer-border)]",
  playerControls: "flex flex-col items-center gap-lf-2",
  playerExtras: "flex items-center justify-end gap-lf-1",
  playerTrack: "flex items-center gap-lf-3 min-w-0",
  playerTrackCreator: "block text-lf-xs text-[var(--composer-text-subtle)] whitespace-nowrap overflow-hidden text-ellipsis",
  playerTrackMeta: "min-w-0 flex-1",
  playerTrackTitle: "block text-lf-sm font-semibold whitespace-nowrap overflow-hidden text-ellipsis",
  playPauseBtn: "flex items-center justify-center w-[40px] h-[40px] border-none rounded-lf-pill bg-[var(--composer-text)] text-[var(--composer-bg)] cursor-pointer hover:[transform:scale(1.05)]",
  progressFill: "block h-full rounded-[inherit] bg-[var(--composer-text)]",
  progressRow: "flex items-center gap-lf-2 w-full max-w-[520px]",
  progressTrack: "flex-1 h-[4px] rounded-lf-pill bg-[var(--composer-track-bg)] overflow-hidden",
  promptActions: "flex items-center gap-lf-2",
  promptComposer: "flex-1 min-h-0 min-w-0 flex flex-col",
  promptComposerSurface: "flex-1 flex flex-col min-h-[140px] bg-[var(--composer-bg-highlight)] border-[var(--composer-border)] [--lf-surface-2:var(--composer-bg-highlight)] [--lf-surface-3:var(--composer-hover-bg)] [--lf-border-default:var(--composer-border)] [--lf-border-strong:var(--composer-scrollbar-thumb)] [--lf-text-primary:var(--composer-text)] [--lf-text-secondary:var(--composer-text-subtle)] [--lf-text-tertiary:var(--composer-text-muted)] flex-1 min-h-0 flex flex-col flex-1 min-h-[120px] text-[var(--composer-text)]",
  promptHeader: "flex items-center justify-between",
  promptLabel: "text-lf-sm font-semibold text-[var(--composer-text-subtle)]",
  promptSection: "flex flex-col gap-lf-2 flex-1 min-h-[160px]",
  searchInput: "text-[var(--composer-text)]",
  searchWrapper: "flex-1 min-w-[180px] max-w-[280px] bg-[var(--composer-bg-highlight)] border-[var(--composer-border)]",
  sortBtn: "[flex-shrink:0] inline-flex items-center gap-[4px] p-[6px_10px] border-none rounded-lf-md bg-transparent text-[var(--composer-text-subtle)] text-lf-sm font-semibold cursor-pointer hover:bg-[var(--composer-hover-bg)] hover:text-[var(--composer-text)]",
  suggestions: "flex flex-wrap gap-lf-2",
  suggestionScroll: "[flex-shrink:0]",
  timeLabel: "min-w-[36px] text-lf-xs text-[var(--composer-text-subtle)] [font-variant-numeric:tabular-nums]",
  trackActions: "col-[2] row-[1] [justify-self:end] flex items-center gap-[2px] opacity-0 pointer-events-none transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)]",
  trackDescription: "text-[var(--composer-text-subtle)] text-lf-sm leading-[var(--lf-line-height-tight)] whitespace-nowrap overflow-hidden text-ellipsis",
  trackDuration: "col-[2] row-[1] [justify-self:end] min-w-[36px] text-lf-xs font-medium [font-variant-numeric:tabular-nums] text-[var(--composer-text-muted)] text-right transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)]",
  trackList: "flex-1 min-h-0",
  trackListInner: "flex flex-col gap-lf-1 p-[var(--lf-space-2)_var(--lf-space-4)_var(--lf-space-4)]",
  trackMain: "flex items-center gap-lf-3 min-w-0 border-none bg-transparent text-[inherit] text-left cursor-pointer p-0",
  trackMeta: "flex flex-col gap-[4px] min-w-0 flex-1",
  trackRow: "grid grid-cols-[minmax(0,_1fr)_112px] items-center gap-lf-3 min-h-[72px] p-[var(--lf-space-2)_var(--lf-space-3)] rounded-lf-md transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:bg-[var(--composer-hover-bg)] bg-[var(--composer-hover-bg)] hover:opacity-0 opacity-0 hover:opacity-100 hover:pointer-events-auto opacity-100 pointer-events-auto",
  trackRowActive: "bg-[var(--composer-active-bg)]",
  trackRowActive_trackActions: "opacity-100 pointer-events-auto",
  trackRowActive_trackDuration: "opacity-0",
  trackTitle: "min-w-0 text-lf-md font-semibold leading-[var(--lf-line-height-tight)] whitespace-nowrap overflow-hidden text-ellipsis",
  trackTitleRow: "flex items-center gap-lf-2 min-w-0",
  trackVersion: "[flex-shrink:0] p-[2px_6px] rounded-lf-sm bg-[var(--composer-card-bg)] text-[var(--composer-text-muted)] text-[10px] font-bold uppercase [letter-spacing:0.03em]",
  viewBtn: "[flex-shrink:0] hover:bg-[var(--composer-hover-bg)] hover:text-[var(--composer-text)] inline-flex items-center justify-center w-[32px] h-[32px] border-none rounded-lf-md bg-transparent text-[var(--composer-text-subtle)] cursor-pointer",
  volumeFill: "block h-full w-[68%] rounded-[inherit] bg-[var(--composer-text)]",
  volumeRow: "flex items-center gap-lf-2 min-w-[100px] text-[var(--composer-text-subtle)]",
  volumeTrack: "flex-1 h-[4px] rounded-lf-pill bg-[var(--composer-track-bg)] overflow-hidden",
  workspace: "[--composer-accent:#f43f5e] [--composer-accent-hover:#fb7185] [--composer-accent-muted:rgba(244,_63,_94,_0.14)] [--composer-bg:#0a0a0a] [--composer-bg-elevated:#121212] [--composer-bg-highlight:#1a1a1a] [--composer-bg-press:#242424] [--composer-text:#ffffff] [--composer-text-subtle:#a3a3a3] [--composer-text-muted:#737373] [--composer-on-primary:#ffffff] [--composer-border:rgba(255,_255,_255,_0.08)] [--composer-hover-bg:rgba(255,_255,_255,_0.06)] [--composer-active-bg:rgba(255,_255,_255,_0.1)] [--composer-card-bg:rgba(255,_255,_255,_0.04)] [--composer-track-bg:rgba(255,_255,_255,_0.18)] [--composer-scrollbar-thumb:rgba(255,_255,_255,_0.2)] h-full min-h-0 flex flex-col bg-[var(--composer-bg)] text-[var(--composer-text)] font-sans",
};
export default styles;
