/** Tailwind class map — converted from TicketsListView.module.css */
const styles: Record<string, string> = {
  actionBtn: "inline-flex items-center justify-center w-[28px] h-[28px] border-none rounded-lf-md bg-transparent text-lf-text-tertiary cursor-pointer hover:bg-lf-surface-sunken hover:text-lf-text-primary",
  actionsCol: "w-[48px] text-right",
  addTicketBtn: "bg-lf-success text-[white] hover:enabled:bg-[color-mix(in_srgb,_var(--lf-success)_85%,_black)]",
  automationActions: "flex items-center gap-lf-2 [flex-shrink:0]",
  automationBanner: "flex items-center justify-between gap-lf-4 p-[var(--lf-space-3)_var(--lf-space-4)] mb-lf-4 rounded-lf-lg bg-lf-success text-[white] flex-col items-start",
  automationBtn: "p-[var(--lf-space-1)_var(--lf-space-3)] border border-solid border-[rgba(255,_255,_255,_0.35)] rounded-lf-md bg-transparent text-lf-sm font-medium text-[white] cursor-pointer",
  automationBtnPrimary: "bg-[white] border-[white] text-lf-success",
  automationText: "m-0 text-lf-sm font-medium",
  checkboxCol: "w-[40px]",
  clientCell: "flex items-center gap-lf-2 min-w-[140px]",
  clientName: "overflow-hidden text-ellipsis whitespace-nowrap text-lf-text-primary",
  email: "text-lf-text-secondary",
  empty: "p-lf-8 text-center text-lf-text-tertiary",
  filterBtn: "inline-flex items-center gap-lf-1 p-[var(--lf-space-2)_var(--lf-space-3)] border border-solid border-lf-border-subtle rounded-lf-lg bg-lf-surface-1 text-lf-sm text-lf-text-secondary cursor-pointer hover:bg-lf-surface-sunken hover:text-lf-text-primary",
  filters: "flex flex-wrap items-center gap-lf-2 mb-lf-4",
  header: "flex items-center justify-between gap-lf-4 mb-lf-5 flex-col items-start",
  headerActions: "flex items-center gap-lf-2",
  intent: "text-lf-text-secondary",
  metricCard: "min-h-[88px]",
  metricLabel: "block mb-lf-2 text-lf-sm text-lf-text-secondary",
  metricRow: "flex items-baseline gap-lf-2",
  metrics: "grid grid-cols-[repeat(5,_minmax(0,_1fr))] gap-lf-3 mb-lf-4 grid-cols-[repeat(3,_minmax(0,_1fr))] grid-cols-[repeat(2,_minmax(0,_1fr))] grid-cols-[1fr]",
  metricTrend: "inline-flex items-center gap-[2px] text-lf-xs font-semibold",
  metricValue: "text-lf-xl font-bold [letter-spacing:-0.02em] text-lf-text-primary",
  priorityBadge: "inline-flex items-center gap-lf-1 w-fit p-[2px_8px] rounded-lf-sm text-lf-xs font-semibold",
  priorityLow: "bg-lf-success-muted text-lf-success",
  priorityMedium: "bg-lf-warning-muted text-lf-warning",
  priorityUrgent: "bg-lf-danger-muted text-lf-danger",
  subject: "max-w-[220px] overflow-hidden text-ellipsis whitespace-nowrap text-lf-text-primary",
  table: "w-full [border-collapse:collapse] text-lf-sm",
  "table tbody tr": "last:[border-bottom:none] hover:bg-lf-surface-sunken",
  "table td": "p-[var(--lf-space-3)_var(--lf-space-4)] text-left border-b border-lf-divider [vertical-align:middle]",
  "table th": "p-[var(--lf-space-3)_var(--lf-space-4)] text-left border-b border-lf-divider [vertical-align:middle] text-lf-xs font-semibold text-lf-text-tertiary uppercase [letter-spacing:0.04em] bg-lf-surface-sunken",
  tableCard: "overflow-hidden",
  tableWrap: "[overflow-x:auto]",
  ticketId: "font-semibold text-lf-text-primary",
  ticketIdCell: "flex flex-col gap-lf-1",
  ticketIdCol: "min-w-[160px]",
  ticketView: "p-lf-6 max-w-[1400px]",
  title: "m-0 text-lf-2xl font-bold [letter-spacing:-0.03em] text-lf-text-primary",
  trendDown: "text-lf-danger",
  trendUp: "text-lf-success",
  typeCell: "inline-flex items-center gap-lf-1 text-lf-text-secondary",
};
export default styles;
