/** Tailwind class map — converted from DesignCard.module.css */
const styles: Record<string, string> = {
  actionButtons: "flex items-center gap-lf-2",
  actionCircle: "inline-flex items-center justify-center w-[36px] h-[36px] border-none rounded-full bg-[rgba(255,_255,_255,_0.12)] text-[rgba(255,_255,_255,_0.92)] cursor-pointer",
  actionPill: "inline-flex items-center gap-[6px] p-[6px_10px] border-none rounded-lf-pill bg-[rgba(255,_255,_255,_0.12)] text-[rgba(255,_255,_255,_0.92)] text-[11px] font-semibold cursor-pointer",
  actionPillIdentity: "flex items-center gap-lf-2 min-w-0",
  actionPillRow: "flex items-center justify-between gap-lf-3",
  actionPills: "inline-flex gap-lf-2",
  actionPillTitle: "text-lf-xs font-semibold",
  activityBar: "flex-1 min-w-[6px] rounded-[4px_4px_0_0] bg-[rgba(255,_255,_255,_0.14)]",
  activityBarActive: "bg-[#84cc16]",
  activityBars: "flex items-end gap-[4px] h-[88px]",
  activityLabels: "flex gap-[4px] text-[9px] text-[rgba(255,_255,_255,_0.38)] overflow-hidden",
  "activityLabels span": "flex-1 min-w-[6px] text-center",
  activityRingGrid: "flex items-center justify-between gap-lf-1 flex-wrap justify-center",
  airpodsGauges: "flex justify-between gap-lf-4",
  airpodsHead: "flex items-center gap-lf-2 text-lf-sm font-semibold",
  alertBell: "relative inline-flex items-center justify-center w-[32px] h-[32px] rounded-full bg-[rgba(239,_68,_68,_0.18)] text-[#ef4444]",
  alertBellMark: "absolute right-[-2px] bottom-[-2px] w-[14px] h-[14px] rounded-full text-[8px] font-[800] inline-flex items-center justify-center [border:2px_solid_#000]",
  alertLeft: "flex items-center gap-lf-2 min-w-0",
  alertPillRow: "flex items-center justify-between gap-lf-3",
  alertText: "text-lf-xs font-semibold",
  bar: "w-full max-w-[14px] rounded-[6px_6px_2px_2px] mt-auto",
  barChart: "flex items-end justify-center gap-[6px] min-h-[72px]",
  barColumn: "flex flex-col items-center gap-[6px] flex-1 h-[72px]",
  barLabel: "text-[10px] text-[rgba(255,_255,_255,_0.45)]",
  billingAmount: "mt-lf-1 text-lf-2xl font-[800]",
  billingBar: "w-full max-w-[16px] mt-auto rounded-[6px_6px_2px_2px] bg-[#2563eb]",
  "billingBar-danger": "bg-[#dc2626]",
  "billingBar-neutral": "bg-[#9ca3af]",
  billingBarCol: "flex flex-col items-center gap-[4px] flex-1 h-full",
  billingBarLabel: "text-[9px] text-[rgba(0,_0,_0,_0.45)]",
  billingBars: "flex items-end gap-[6px] h-[72px]",
  billingCountdown: "mt-[4px] text-lf-sm font-bold text-[#dc2626]",
  billingGrid: "grid grid-cols-[1fr_auto] gap-lf-3 [align-items:start]",
  billingKicker: "text-[10px] [letter-spacing:0.08em] font-bold text-[rgba(0,_0,_0,_0.45)]",
  brandMark: "inline-flex items-center justify-center [flex-shrink:0] rounded-full text-[11px] font-[800] text-[#fff]",
  buyCircle: "w-auto min-w-[36px] p-[0_14px] gap-[6px] bg-[#84cc16] text-[#111] text-[11px] font-[800]",
  circleButton: "inline-flex items-center justify-center w-[36px] h-[36px] border border-solid border-[rgba(255,_255,_255,_0.16)] rounded-lf-pill bg-[rgba(255,_255,_255,_0.08)] text-[rgba(255,_255,_255,_0.92)] cursor-pointer",
  circleButtonPrimary: "bg-[rgba(255,_255,_255,_0.92)] text-[#000] border-transparent",
  coverArt: "w-[48px] h-[48px] rounded-[10px] bg-[rgba(255,_255,_255,_0.12)] inline-flex items-center justify-center",
  deliveryEta: "mt-[4px] text-lf-xs text-[rgba(255,_255,_255,_0.55)]",
  deliveryGrid: "grid grid-cols-[1fr_auto] gap-lf-3 items-center",
  deliveryStatus: "mt-[4px] text-lf-md font-bold",
  deltaPill: "p-[4px_8px] rounded-lf-pill bg-[rgba(74,_222,_128,_0.2)] text-[#4ade80] text-[11px] font-bold",
  discountPill: "p-[2px_8px] rounded-lf-pill bg-[rgba(74,_222,_128,_0.2)] text-[#4ade80] text-[11px]",
  dotChart: "w-full h-[40px]",
  dotLabels: "flex justify-between text-[10px] text-[rgba(255,_255,_255,_0.45)]",
  dotLine: "[stroke:rgba(255,_255,_255,_0.55)] [stroke-width:2] [stroke-dasharray:2_6] [vector-effect:non-scaling-stroke]",
  driver: "inline-flex items-center gap-lf-2 text-lf-xs",
  dualCyan: "bg-[linear-gradient(90deg,_#06b6d4,_#22d3ee)]",
  dualPurple: "bg-[linear-gradient(90deg,_#8b5cf6,_#c084fc)]",
  dualTrack: "flex h-[6px] rounded-lf-pill overflow-hidden bg-[rgba(255,_255,_255,_0.1)]",
  espressoBars: "",
  espressoBars_bar: "bg-[linear-gradient(180deg,_#fb923c,_#ea580c)]",
  eta: "text-[#67e8f9] [font-variant-numeric:tabular-nums]",
  financeHead: "flex items-center justify-between gap-lf-2",
  financeIdentity: "flex items-center gap-lf-2 min-w-0",
  financeTitle: "text-lf-xs font-semibold whitespace-nowrap overflow-hidden text-ellipsis",
  financeUpdated: "text-[10px] text-[rgba(255,_255,_255,_0.45)] whitespace-nowrap",
  flightMeta: "grid grid-cols-[1fr_auto_1fr] gap-lf-2 text-lf-xs text-[rgba(255,_255,_255,_0.55)]",
  "flightMeta span": "last:text-right",
  glucoseBars: "",
  glucoseBars_bar: "bg-[linear-gradient(180deg,_#f472b6,_#8b5cf6)]",
  heartBars: "",
  heartBars_bar: "bg-[linear-gradient(180deg,_#fb7185,_#ec4899)]",
  heroMetric: "text-lf-2xl font-[800] [font-variant-numeric:tabular-nums]",
  issArc: "w-full h-[64px]",
  issCountdown: "text-[#67e8f9] [font-variant-numeric:tabular-nums]",
  issIcon: "absolute left-[8px] top-[8px] text-[#67e8f9]",
  issVisual: "relative min-h-[64px]",
  kicker: "text-[10px] [letter-spacing:0.08em] uppercase text-[rgba(255,_255,_255,_0.45)]",
  laundryFill: "block h-full rounded-[inherit] bg-[rgba(255,_255,_255,_0.88)] bg-[#2563eb]",
  laundryHead: "flex items-center gap-lf-2",
  laundryMeta: "flex justify-between text-[10px] font-bold [letter-spacing:0.04em] text-[rgba(0,_0,_0,_0.45)]",
  laundryPhase: "flex justify-between text-lf-xs font-semibold text-[rgba(0,_0,_0,_0.55)]",
  laundryProgram: "text-lf-md font-bold",
  laundryTimer: "text-lf-sm text-[rgba(0,_0,_0,_0.55)] [font-variant-numeric:tabular-nums]",
  laundryTrack: "h-[4px] rounded-lf-pill bg-[rgba(255,_255,_255,_0.16)] overflow-hidden bg-[rgba(0,_0,_0,_0.08)]",
  leaguePill: "self-center p-[4px_10px] rounded-lf-pill bg-[#fff] text-[#111] text-[10px]",
  limeFill: "block h-full rounded-[inherit] bg-[#a3e635]",
  limeTrack: "h-[4px] rounded-lf-pill bg-[rgba(255,_255,_255,_0.12)] overflow-hidden",
  mediaDuration: "text-[10px] opacity-[0.72] [font-variant-numeric:tabular-nums]",
  mediaFill: "block h-full rounded-[inherit] bg-[rgba(255,_255,_255,_0.88)]",
  mediaProgressRow: "grid grid-cols-[auto_1fr_auto] items-center gap-lf-2",
  mediaTrack: "h-[4px] rounded-lf-pill bg-[rgba(255,_255,_255,_0.16)] overflow-hidden",
  metricHead: "flex items-center justify-between gap-lf-2 text-lf-sm font-semibold",
  metricUnit: "text-lf-sm font-medium opacity-[0.72]",
  metricValue: "text-lf-lg font-bold",
  milestone: "absolute top-[50%] [transform:translate(-50%,_-50%)] inline-flex items-center justify-center w-[22px] h-[22px] rounded-lf-pill bg-[rgba(255,_255,_255,_0.12)] text-[rgba(255,_255,_255,_0.88)]",
  miniMap: "w-[72px] h-[72px] [flex-shrink:0]",
  networkStat: "inline-flex items-center gap-[4px]",
  networkStats: "flex flex-wrap gap-lf-3 text-lf-sm font-bold [font-variant-numeric:tabular-nums]",
  orderFooter: "flex items-center justify-between gap-lf-3",
  podcastArt: "w-[48px] h-[48px] rounded-[10px] bg-[rgba(255,_255,_255,_0.12)] inline-flex items-center justify-center",
  podcastGrid: "grid grid-cols-[1fr_auto] gap-lf-3 [align-items:start]",
  podcastShow: "mt-[4px] text-lf-sm opacity-[0.72]",
  podcastTitle: "text-lf-md font-bold",
  progressFillCyan: "block h-full rounded-[inherit] bg-[linear-gradient(90deg,_#06b6d4,_#22d3ee)]",
  progressFillPurple: "block h-full rounded-[inherit] bg-[linear-gradient(90deg,_#8b5cf6,_#c084fc)]",
  progressMarkerCyan: "absolute top-[50%] [transform:translate(-50%,_-50%)] inline-flex items-center justify-center w-[22px] h-[22px] rounded-lf-pill bg-[#000] text-[#22d3ee] shadow-[0_0_0_2px_rgba(34,_211,_238,_0.35)]",
  progressTrackCyan: "relative h-[6px] rounded-lf-pill bg-[rgba(255,_255,_255,_0.12)]",
  progressTrackPurple: "relative h-[6px] rounded-lf-pill bg-[rgba(255,_255,_255,_0.12)]",
  raceSector: "text-lf-sm font-bold text-[rgba(255,_255,_255,_0.72)]",
  raceTrack: "w-full h-[88px]",
  ringDot: "absolute bottom-[14px] w-[6px] h-[6px] rounded-lf-pill bg-[#fff]",
  ringFill: "[fill:none] [stroke:#fff] [stroke-width:3] [stroke-linecap:round]",
  ringGauge: "relative flex flex-col items-center gap-[4px]",
  ringGaugeActive: "",
  ringGaugeActive_ringFill: "[stroke:#fff]",
  ringGaugeLight: "",
  ringGaugeLight_ringFill: "[stroke:#2563eb]",
  ringGaugeLight_ringTrack: "[stroke:rgba(0,_0,_0,_0.1)]",
  ringLabel: "absolute inset-0 flex items-center justify-center text-[10px] font-bold",
  ringRow: "flex items-center justify-between gap-lf-1",
  ringTrack: "[fill:none] [stroke:rgba(255,_255,_255,_0.15)] [stroke-width:3]",
  routeDash: "opacity-[0.45]",
  routeHead: "flex items-center justify-between gap-lf-2 text-lf-sm font-semibold",
  semiFill: "[fill:none] [stroke:#fff] [stroke-width:4] [stroke-linecap:round]",
  semiGauge: "relative flex-1 text-center",
  semiLabel: "absolute left-[50%] bottom-[2px] [transform:translateX(-50%)] text-[10px] opacity-[0.55]",
  semiTrack: "[fill:none] [stroke:rgba(255,_255,_255,_0.15)] [stroke-width:4]",
  semiValue: "block mt-[2px] text-lf-sm font-bold",
  sleepChartWrap: "relative grid grid-cols-[repeat(3,_1fr)] gap-lf-2 pt-lf-1",
  sleepDay: "flex flex-col gap-[6px]",
  sleepDayLabel: "text-[10px] text-[rgba(255,_255,_255,_0.45)] text-center",
  sleepGoal: "absolute top-0 bottom-[18px] w-[2px] bg-[#ef4444] [transform:translateX(-50%)]",
  sleepHead: "flex items-center gap-lf-2",
  sleepSegment: "bg-[linear-gradient(180deg,_#4ade80,_#16a34a)] bg-[linear-gradient(180deg,_#22d3ee,_#0891b2)] bg-[linear-gradient(180deg,_#a78bfa,_#7c3aed)]",
  sleepStack: "flex h-[36px] rounded-[8px] overflow-hidden bg-[rgba(255,_255,_255,_0.08)]",
  speedPill: "p-[2px_8px] rounded-lf-pill bg-[rgba(255,_255,_255,_0.16)] text-[10px] font-bold",
  splitHead: "flex items-center justify-between gap-lf-2 text-lf-sm font-semibold",
  sportsBottom: "grid grid-cols-[1fr_auto_1fr] items-stretch min-h-[36px] text-[#fff] text-[11px] font-bold",
  "sportsBottom span": "first:flex first:items-center first:justify-center first:p-lf-2 last:flex last:items-center last:justify-center last:p-lf-2",
  sportsCard: "flex flex-col w-full min-h-0 rounded-[28px] overflow-hidden bg-[#fff] text-[#111] shadow-[0_8px_24px_rgba(0,_0,_0,_0.12)]",
  sportsScoreLine: "text-lf-xl font-[800] [font-variant-numeric:tabular-nums]",
  sportsTop: "grid grid-cols-[1fr_auto_1fr] items-center gap-lf-2 p-[var(--lf-space-4)_var(--lf-space-5)]",
  statusBar: "flex items-center justify-between gap-lf-2 text-[10px] font-semibold text-[rgba(0,_0,_0,_0.55)]",
  statusBarLeft: "inline-flex items-center gap-[6px]",
  statusBarRight: "inline-flex items-center gap-[6px]",
  statusCenter: "text-[rgba(255,_255,_255,_0.92)] font-semibold",
  statusInnerChange: "inline-flex items-center gap-[4px] text-lf-xs font-bold text-[#84cc16]",
  statusInnerLabel: "text-lf-xs font-semibold",
  statusInnerLeft: "inline-flex items-center gap-lf-2 min-w-0",
  statusInnerPill: "flex items-center justify-between gap-lf-3 p-[10px_14px] rounded-[999px] bg-[#000] text-[#fff]",
  statusInnerValue: "text-lf-sm font-[800] text-[#84cc16] [font-variant-numeric:tabular-nums]",
  statusPillOuter: "gap-lf-2",
  stockArea: "[fill:rgba(132,_204,_22,_0.12)]",
  stockBaseline: "[stroke:rgba(255,_255,_255,_0.18)] [stroke-width:1] [stroke-dasharray:4_4]",
  stockChangeBlock: "flex flex-col items-end gap-[2px] text-[11px] font-bold",
  stockChangeDown: "text-[#ef4444]",
  stockChangeUp: "text-[#84cc16]",
  stockLine: "[fill:none] [stroke:#84cc16] [stroke-width:2.5] [vector-effect:non-scaling-stroke]",
  stockLineChart: "relative h-[72px]",
  stockLineSvg: "w-full h-full",
  stockPrice: "text-[2rem] font-[800] [letter-spacing:-0.04em] leading-none [font-variant-numeric:tabular-nums]",
  stockQuoteBody: "flex items-end justify-between gap-lf-3",
  stopButton: "self-center inline-flex items-center gap-lf-2 p-[8px_16px] border-none rounded-lf-pill bg-[#ea580c] text-[#fff] text-lf-xs font-bold cursor-pointer",
  subwayDot: "relative z-[1] w-[10px] h-[10px] rounded-lf-pill bg-[#fff] [border:2px_solid_#f97316]",
  subwayDotActive: "w-[14px] h-[14px] bg-[#f97316]",
  subwayHeadline: "text-lf-md font-[800] leading-[1.2]",
  subwayMeta: "text-lf-xs text-[rgba(0,_0,_0,_0.45)] text-center",
  subwayTrack: "relative flex items-center justify-between gap-[10px] p-[var(--lf-space-2)_0] before:before:[content:\"\"] before:before:absolute before:before:left-[var(--lf-space-5)] before:before:right-[var(--lf-space-5)] before:before:h-[3px] before:before:bg-[#f97316] before:before:rounded-lf-pill before:before:z-[0]",
  tagPill: "p-[4px_10px] rounded-lf-pill bg-[rgba(255,_255,_255,_0.12)] text-[10px] font-bold [letter-spacing:0.04em]",
  tagPillSuccess: "bg-[rgba(74,_222,_128,_0.2)] text-[#4ade80]",
  tagRow: "flex gap-lf-2",
  teamMark: "text-[10px] font-[800] [letter-spacing:0.06em] text-[rgba(0,_0,_0,_0.45)]",
  timerAccent: "text-[#67e8f9] [font-variant-numeric:tabular-nums]",
  transitDot: "w-[10px] h-[10px] rounded-lf-pill bg-[rgba(255,_255,_255,_0.24)]",
  transitDotActive: "bg-[#22c55e] shadow-[0_0_0_4px_rgba(34,_197,_94,_0.2)]",
  transitLabel: "text-[10px] text-[rgba(255,_255,_255,_0.45)] whitespace-nowrap",
  transitLabelActive: "text-[rgba(255,_255,_255,_0.92)] font-semibold",
  transitLine: "flex items-center gap-0 [overflow-x:auto]",
  transitSegment: "absolute top-[4px] left-[calc(50%_+_8px)] w-[calc(100%_-_16px)] h-[3px] bg-[#22c55e] rounded-lf-pill",
  transitStop: "relative flex flex-col items-center gap-[8px] min-w-[72px] flex-1",
  trendDown: "text-[#f472b6]",
  trendUp: "text-[#4ade80]",
  weatherBars: "",
  weatherBars_bar: "bg-[rgba(255,_255,_255,_0.55)]",
  weatherCity: "text-lf-sm opacity-[0.85]",
  weatherGauge: "flex flex-col items-center gap-[4px] text-[10px] font-bold",
  weatherHead: "flex items-start justify-between",
  weatherStats: "grid grid-cols-[auto_1fr_auto] items-end gap-lf-2",
  weatherTemp: "text-[var(--lf-font-size-3xl)] font-[800] leading-none",
  wishlistGrid: "grid grid-cols-[1fr_auto] gap-lf-3 [align-items:start]",
  wishlistPriceRow: "flex items-center gap-lf-2 mt-[4px] font-bold",
  wishlistTitle: "text-lf-md font-bold",
  workoutBars: "",
  workoutBars_bar: "bg-[linear-gradient(180deg,_#fde047,_#eab308)]",
  workoutControls: "flex items-center justify-center gap-lf-3",
  workoutDistance: "text-lf-sm text-[rgba(255,_255,_255,_0.55)]",
  workoutElapsed: "text-lf-xl font-[800] [font-variant-numeric:tabular-nums]",
  workoutHead: "flex items-center justify-between gap-lf-2 text-lf-sm font-semibold",
};
export default styles;
