/** Tailwind class map — converted from SlackWorkspace.module.css */
const styles: Record<string, string> = {
  channelHeader: "[flex-shrink:0] flex items-center gap-lf-3 h-[52px] p-[0_var(--lf-space-5)] border-b border-lf-divider bg-lf-surface-1",
  channelHeaderActions: "flex items-center gap-lf-1 [flex-shrink:0]",
  channelHeaderIdentity: "flex-1 min-w-0",
  channelHeaderTitle: "flex items-center gap-lf-1 text-lf-md font-bold text-lf-text-primary",
  channelHeaderTopic: "mt-[2px] overflow-hidden text-ellipsis whitespace-nowrap text-lf-xs text-lf-text-tertiary",
  channelIcon: "overflow-hidden",
  channelIcon_header: "w-[28px] h-[28px] rounded-[7px]",
  channelIcon_header_channelIconGlyph: "text-[15px]",
  channelIcon_sidebar: "w-[24px] h-[24px] rounded-[6px]",
  channelIconGlyph: "flex items-center justify-center w-full h-full text-[13px] leading-none",
  channelIconImage: "w-full h-full object-cover",
  composer: "border border-solid border-lf-border-default rounded-lf-lg bg-[var(--groups-compose-bg)] overflow-hidden",
  composerActions: "flex items-center gap-[2px]",
  composerDock: "[flex-shrink:0] p-[var(--lf-space-3)_var(--lf-space-5)_var(--lf-space-4)] bg-lf-surface-1",
  composerFooter: "flex items-center justify-between p-[var(--lf-space-2)_var(--lf-space-3)]",
  composerInput: "w-full min-h-[44px] max-h-[160px] p-[var(--lf-space-3)_var(--lf-space-4)] border-none bg-transparent text-lf-text-primary [font:inherit] text-lf-sm leading-normal [resize:none] outline-none",
  dayDivider: "flex items-center gap-lf-3 m-[var(--lf-space-4)_0] text-lf-text-tertiary text-lf-xs font-semibold before:before:[content:\"\"] before:before:flex-1 before:before:h-[1px] before:before:bg-lf-divider before:after:[content:\"\"] before:after:flex-1 before:after:h-[1px] before:after:bg-lf-divider",
  dmAvatar: "inline-flex [flex-shrink:0]",
  emptyPane: "flex-1 flex items-center justify-center bg-lf-surface-1",
  link: "text-[var(--groups-link)] no-underline hover:[text-decoration:underline]",
  main: "flex-1 min-w-0 flex flex-col min-h-0 hidden hidden",
  mention: "text-[var(--groups-mention)] bg-lf-accent-muted rounded-[3px] p-[0_2px]",
  message: "flex gap-lf-3 p-[var(--lf-space-2)_var(--lf-space-3)] rounded-lf-md hover:bg-lf-surface-2",
  messageBody: "flex-1 min-w-0 text-lf-sm leading-normal text-lf-text-primary whitespace-pre-wrap [word-break:break-word]",
  messageHead: "flex items-baseline gap-lf-2 mb-[2px]",
  messageSender: "text-lf-sm font-bold text-lf-text-primary",
  messageSenderButton: "border-none bg-transparent p-0 [font:inherit] text-[inherit] cursor-pointer hover:[text-decoration:underline]",
  messageTimestamp: "text-lf-xs text-lf-text-tertiary",
  profileActions: "flex gap-lf-2 p-[0_var(--lf-space-4)_var(--lf-space-4)]",
  profileAvatarWrap: "relative inline-flex mb-lf-3",
  profileDeactivated: "absolute [inset:auto_0_0] p-[4px] bg-[rgba(0,_0,_0,_0.72)] text-lf-text-on-accent text-[10px] font-semibold",
  profileField: "flex items-center gap-lf-3 text-lf-sm text-lf-text-primary",
  profileHeader: "[flex-shrink:0] flex items-center justify-between h-[52px] p-[0_var(--lf-space-4)] border-b border-lf-divider font-semibold text-lf-text-primary",
  profileHero: "relative p-[var(--lf-space-5)_var(--lf-space-4)_var(--lf-space-4)] text-center",
  profileLink: "block mt-lf-3 border-none bg-transparent text-[var(--groups-link)] text-lf-sm cursor-pointer hover:[text-decoration:underline]",
  profileName: "text-lf-lg font-bold text-lf-text-primary",
  profilePane: "h-full flex flex-col min-h-0 bg-lf-surface-1",
  profilePrimaryAction: "flex-1 p-[8px_var(--lf-space-3)] border border-solid border-lf-border-default rounded-lf-md bg-transparent text-lf-text-primary text-lf-sm font-semibold cursor-pointer hover:bg-lf-surface-2",
  profileResizable: "hidden",
  profileScroll: "flex-1",
  profileSection: "p-lf-4 border-t border-lf-divider",
  profileSectionTitle: "mb-lf-3 text-lf-xs font-bold [letter-spacing:0.04em] uppercase text-lf-text-tertiary",
  profileTitle: "mt-[4px] text-lf-sm text-lf-text-secondary",
  rail: "[flex-shrink:0] w-[68px] flex flex-col items-center gap-lf-2 p-[var(--lf-space-3)_var(--lf-space-2)] bg-[var(--groups-rail-bg)] border-r border-lf-divider hidden hidden",
  railAdd: "w-[40px] h-[40px] [border:1px_dashed_var(--lf-border-default)] rounded-lf-lg bg-transparent text-lf-text-secondary cursor-pointer hover:bg-lf-surface-2 hover:border-lf-border-strong hover:text-lf-text-primary",
  railBadge: "absolute top-[3px] right-[3px] min-w-[14px] h-[14px] p-[0_3px] rounded-[999px] bg-lf-danger text-lf-text-on-accent text-[8px] font-bold leading-[14px] text-center pointer-events-none shadow-[0_0_0_2px_var(--ws-accent,_var(--lf-surface-3))]",
  railFooter: "flex flex-col items-center gap-lf-2",
  railWorkspace: "relative [flex-shrink:0] flex items-center justify-center w-[40px] h-[40px] border-none rounded-lf-lg bg-[var(--ws-accent,_var(--lf-surface-3))] text-lf-text-on-accent text-lf-sm font-bold cursor-pointer transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:[transform:scale(1.06)] hover:[filter:brightness(1.12)]",
  railWorkspaceActive: "shadow-[inset_0_0_0_2px_rgb(255_255_255_/_0.45)]",
  railWorkspaces: "flex-1 min-h-0 flex flex-col items-center gap-lf-2 w-full [padding-block:var(--lf-space-2)] overflow-x-hidden overflow-y-auto",
  sidebarHeader: "flex items-center gap-lf-2",
  sidebarHeaderActions: "flex items-center gap-[2px] [flex-shrink:0]",
  sidebarNav: "h-full",
  sidebarPane: "h-full min-w-0 overflow-hidden bg-[var(--groups-sidebar-bg)]",
  sidebarResizable: "[flex-shrink:0] w-full w-full",
  sidebarTitle: "flex-1 min-w-0 flex items-center gap-lf-1 border-none bg-transparent text-lf-text-primary text-lf-md font-bold text-left cursor-pointer p-0",
  sidebarTitleText: "overflow-hidden text-ellipsis whitespace-nowrap",
  threadInner: "p-[var(--lf-space-5)_var(--lf-space-6)] flex flex-col gap-lf-1",
  threadScroll: "flex-1 bg-lf-surface-1",
  unreadListItem: "text-lf-text-primary font-semibold",
  unreadMentions: "flex items-center justify-between gap-lf-2 w-full m-[0_0_var(--lf-space-2)] p-[var(--lf-space-2)_var(--lf-space-3)] border border-solid border-lf-accent-border rounded-lf-md bg-lf-accent-muted text-lf-accent text-lf-sm font-semibold text-left cursor-pointer transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:bg-lf-surface-2 hover:border-lf-border-strong",
  workspace: "[--groups-rail-bg:var(--lf-surface-sunken)] [--groups-sidebar-bg:var(--lf-surface-1)] [--groups-sidebar-footer-bg:var(--lf-surface-2)] [--groups-mention:var(--lf-accent)] [--groups-link:var(--lf-accent)] [--groups-compose-bg:var(--lf-surface-2)] h-full flex min-h-0 bg-lf-surface-canvas",
};
export default styles;
