/** Tailwind class map — converted from DesignShell.module.css */
const styles: Record<string, string> = {
  appBadge: "flex items-center justify-center w-[28px] h-[28px] rounded-lf-sm bg-[linear-gradient(135deg,_var(--lf-app-hue-violet-from),_var(--lf-app-hue-violet-to))] text-lf-text-on-accent text-lf-xs font-bold",
  body: "flex-1 min-h-0 flex",
  canvas: "flex-1 min-w-0 min-h-0 relative overflow-hidden",
  canvasArea: "flex-1 min-w-0 min-h-0 flex flex-col bg-lf-surface-sunken",
  canvasCentered: "flex items-center justify-center overflow-auto p-lf-8",
  canvasRow: "flex-1 min-h-0 flex",
  fillSwatch: "w-[28px] h-[28px] mt-auto rounded-lf-sm [border:2px_solid_var(--lf-border-default)] cursor-pointer",
  listItem: "flex items-center gap-lf-2 w-full p-[var(--lf-space-1)_var(--lf-space-3)] border-none rounded-lf-sm bg-transparent text-lf-text-primary text-lf-xs text-left cursor-pointer hover:bg-[var(--lf-desktop-chrome-hover)]",
  listItemActive: "bg-lf-accent-muted text-lf-accent",
  panelHeader: "[flex-shrink:0] p-lf-3 border-b border-lf-border-default",
  panelMeta: "m-[var(--lf-space-1)_0_0] text-lf-xs text-lf-text-secondary",
  panelTabBar: "[flex-shrink:0] p-[0_var(--lf-space-3)] border-b border-lf-border-default",
  panelTabBarFlush: "pl-0 pr-0",
  panelTitle: "m-0 text-lf-sm font-semibold text-lf-text-primary",
  propertyGroup: "p-[0_var(--lf-space-3)_var(--lf-space-4)]",
  propertyLabel: "m-[0_0_var(--lf-space-2)] text-lf-xs font-semibold text-lf-text-secondary",
  rail: "[flex-shrink:0] w-[48px] flex flex-col items-center gap-lf-1 p-[var(--lf-space-2)_0] border-r border-lf-border-default bg-lf-surface-1",
  railButton: "flex flex-col items-center gap-[2px] w-[40px] p-[6px_0] border-none rounded-lf-sm bg-transparent text-lf-text-secondary text-[9px] cursor-pointer hover:bg-[var(--lf-desktop-chrome-hover)] hover:text-lf-text-primary",
  railButtonActive: "bg-[var(--lf-desktop-chrome-hover)] text-lf-text-primary",
  rulerCorner: "[flex-shrink:0] w-[22px] bg-lf-surface-2 border-r border-lf-border-default border-b border-lf-border-default",
  rulerHorizontal: "flex-1 relative overflow-hidden bg-lf-surface-2 border-b border-lf-border-default",
  rulerRow: "[flex-shrink:0] flex h-[22px]",
  rulerTick: "absolute text-[8px] text-lf-text-tertiary leading-none",
  rulerTickH: "top-[8px] [transform:translateX(-50%)]",
  rulerTickV: "left-[2px] [transform:translateY(-50%)_rotate(-90deg)] [transform-origin:left_center]",
  rulerVertical: "[flex-shrink:0] w-[22px] relative overflow-hidden bg-lf-surface-2 border-r border-lf-border-default",
  section: "flex-1 min-h-0 flex flex-col border-b border-lf-border-default last:[border-bottom:none]",
  sectionBody: "flex-1 min-h-0",
  sectionHeader: "[flex-shrink:0] flex items-center justify-between gap-lf-2 p-[var(--lf-space-2)_var(--lf-space-3)]",
  sectionTitle: "m-0 text-lf-xs font-semibold text-lf-text-tertiary uppercase [letter-spacing:0.04em]",
  sidePanel: "[flex-shrink:0] w-[240px] flex flex-col min-h-0 bg-lf-surface-2 border-lf-border-default hidden",
  sidePanelLeft: "border-right border-lf-border-default",
  sidePanelRight: "border-left border-lf-border-default",
  statusBar: "[flex-shrink:0] flex items-center justify-between min-h-[28px] p-[0_var(--lf-space-3)] border-t border-lf-border-default bg-lf-surface-1 text-lf-xs text-lf-text-secondary",
  toolDock: "absolute left-[50%] bottom-[var(--lf-space-4)] [transform:translateX(-50%)] flex items-center gap-lf-1 p-lf-1 rounded-lf-lg bg-lf-surface-overlay border border-solid border-lf-border-default shadow-lf-lg z-[2]",
  toolDockActive: "bg-lf-accent-muted text-lf-accent",
  toolDockDivider: "w-[1px] h-[24px] m-[0_var(--lf-space-1)] bg-lf-border-default",
  toolDockGroup: "flex items-center gap-[2px]",
  toolRail: "[flex-shrink:0] w-[44px] flex flex-col items-center gap-[2px] p-[var(--lf-space-2)_0] border-r border-lf-border-default bg-lf-surface-1",
  topBar: "[flex-shrink:0] flex items-center gap-lf-2 min-h-[40px] p-[0_var(--lf-space-3)] border-b border-lf-border-default bg-lf-surface-1",
  topBarDivider: "w-[1px] h-[20px] bg-lf-border-default [flex-shrink:0]",
  topBarGroup: "flex items-center gap-lf-1 [flex-shrink:0]",
  topBarSpacer: "flex-1 min-w-0",
  topBarTabs: "flex-1 min-w-0 [overflow-x:auto]",
  workspace: "flex flex-col h-full min-h-0 bg-lf-surface-canvas text-lf-text-primary",
};
export default styles;
