/** Tailwind class map — converted from GlassWidget.module.css */
const styles: Record<string, string> = {
  activityDistance: "text-[2rem] font-[800] [letter-spacing:-0.04em] leading-none",
  activityGoalLabel: "text-[11px] opacity-[0.45] text-center",
  activityHero: "flex items-center justify-between gap-lf-3",
  activityStats: "grid grid-cols-[repeat(3,_1fr)] gap-lf-2 mt-auto",
  albumArt: "w-[52px] h-[52px] rounded-[12px] bg-[linear-gradient(145deg,_#fda4af,_#fb7185)] [flex-shrink:0]",
  calendarDay: "aspect-[1] flex items-center justify-center text-[11px] font-semibold rounded-full",
  calendarDayHigh: "bg-[#84cc16] text-[#111]",
  calendarDayLow: "shadow-[inset_0_0_0_2px_rgba(255,_255,_255,_0.18)]",
  calendarDayMilestone: "bg-[#f97316] text-[#111]",
  calendarDayNone: "opacity-[0.35]",
  calendarGrid: "grid grid-cols-[repeat(7,_1fr)] gap-[6px]",
  calendarHead: "flex items-baseline justify-between",
  calendarMonth: "text-lf-md font-[800]",
  calendarWeekdays: "grid grid-cols-[repeat(7,_1fr)] gap-[4px] text-[10px] opacity-[0.45] text-center",
  cameraHead: "flex items-center gap-lf-2",
  cameraStatus: "text-lf-xs font-bold text-[#ef4444]",
  carArt: "h-[48px] rounded-[12px] bg-[linear-gradient(180deg,_rgba(0,_0,_0,_0.04),_rgba(0,_0,_0,_0.02))] relative overflow-hidden",
  carBody: "absolute left-[50%] bottom-[10px] [transform:translateX(-50%)] w-[72px] h-[28px] rounded-[14px_14px_8px_8px] bg-[#f5f5f5] shadow-[inset_0_-4px_0_rgba(0,_0,_0,_0.08)] before:before:[content:\"\"] before:before:absolute before:before:bottom-[-6px] before:before:w-[14px] before:before:h-[14px] before:before:rounded-full before:before:bg-[#222] before:after:[content:\"\"] before:after:absolute before:after:bottom-[-6px] before:after:w-[14px] before:after:h-[14px] before:after:rounded-full before:after:bg-[#222] before:before:left-[10px] before:after:right-[10px]",
  chargeBar: "h-[14px] rounded-lf-pill bg-[rgba(255,_255,_255,_0.08)] overflow-hidden",
  chargeFill: "block h-full rounded-[inherit] bg-[linear-gradient(90deg,_#84cc16,_#a3e635)]",
  chargeHead: "flex items-center gap-lf-2 text-lf-sm font-bold",
  clockFace: "relative w-full max-w-[120px] m-[0_auto] aspect-[1]",
  clockHand: "[stroke:currentColor] [stroke-linecap:round]",
  clockNumeral: "text-[10px] [fill:currentColor] opacity-[0.45]",
  clockSecond: "[stroke:#ef4444]",
  clockSvg: "w-full h-full",
  controlBtn: "inline-flex items-center justify-center w-[28px] h-[28px] border-none rounded-full bg-transparent text-[inherit] opacity-[0.7] cursor-pointer",
  dark: "",
  dark_carArt: "bg-[linear-gradient(180deg,_rgba(255,_255,_255,_0.08),_rgba(255,_255,_255,_0.03))]",
  dark_musicProgress: "bg-[rgba(255,_255,_255,_0.12)]",
  dark_musicProgressFill: "bg-[#fff]",
  dark_playBtn: "bg-[rgba(255,_255,_255,_0.12)]",
  dark_rideEta: "bg-[rgba(255,_255,_255,_0.1)]",
  dayFill: "block h-full rounded-[inherit] bg-[linear-gradient(90deg,_#2563eb,_#60a5fa)]",
  dayTrack: "h-[6px] rounded-lf-pill bg-[rgba(255,_255,_255,_0.1)] overflow-hidden",
  energyBar: "flex-1 rounded-[6px_6px_0_0] bg-[rgba(249,_115,_22,_0.35)]",
  energyChart: "flex items-end gap-[6px] h-[56px]",
  energyHead: "flex items-baseline gap-lf-2",
  energyLabel: "text-[11px] opacity-[0.45]",
  energyPercent: "text-lf-xl font-[800]",
  flightCity: "font-bold",
  flightCode: "opacity-[0.45]",
  flightFill: "block h-full rounded-[inherit] bg-[linear-gradient(90deg,_#fff,_rgba(255,_255,_255,_0.5))]",
  flightHeadline: "text-lf-sm font-bold",
  flightPlane: "absolute top-[50%] [transform:translate(-50%,_-50%)] inline-flex items-center justify-center w-[22px] h-[22px] rounded-full bg-[#111] text-[#fff]",
  flightRoute: "grid grid-cols-[1fr_auto_1fr] items-center gap-lf-2 text-lf-xs",
  flightTrack: "relative h-[6px] rounded-lf-pill bg-[rgba(255,_255,_255,_0.12)]",
  gateCountdown: "mt-auto text-lf-lg font-[800] [font-variant-numeric:tabular-nums]",
  gateStatus: "mt-[4px] text-lf-xs opacity-[0.55]",
  gateValue: "text-[2rem] font-[800] [letter-spacing:-0.04em] leading-none",
  habitLabel: "text-lf-sm font-bold",
  habitMeta: "min-w-0",
  habitRemaining: "mt-[4px] text-[11px] font-bold text-[#f97316]",
  habitRow: "flex items-center justify-between gap-lf-3",
  headRow: "flex items-center justify-between gap-lf-2",
  iconBadge: "inline-flex items-center justify-center w-[36px] h-[36px] rounded-full bg-[rgba(37,_99,_235,_0.14)] text-[#2563eb]",
  iconBadgeGreen: "bg-[rgba(163,_230,_53,_0.16)] text-[#84cc16]",
  iconBadgeRed: "bg-[rgba(239,_68,_68,_0.16)] text-[#ef4444]",
  light: "",
  light_dayTrack: "bg-[rgba(0,_0,_0,_0.08)]",
  light_iconBadge: "bg-[rgba(37,_99,_235,_0.12)]",
  light_ringTrack: "[stroke:rgba(0,_0,_0,_0.08)]",
  light_toggle: "bg-[rgba(0,_0,_0,_0.08)]",
  musicArtist: "text-lf-xs opacity-[0.55]",
  musicControls: "flex items-center justify-center gap-lf-3",
  musicMeta: "min-w-0",
  musicProgress: "h-[4px] rounded-lf-pill bg-[rgba(0,_0,_0,_0.08)] overflow-hidden",
  musicProgressFill: "block h-full rounded-[inherit] bg-[#111]",
  musicRow: "flex items-center gap-lf-3",
  musicSource: "inline-flex items-center gap-[4px] mt-[4px] text-[10px] opacity-[0.45]",
  musicTitle: "text-lf-sm font-bold whitespace-nowrap overflow-hidden text-ellipsis",
  navEta: "text-lf-xs opacity-[0.55]",
  navTop: "flex items-start justify-between gap-lf-3",
  navTurn: "text-[2rem] font-[800] leading-none [letter-spacing:-0.04em]",
  network: "text-lf-xs opacity-[0.55] mt-[2px]",
  offsetPill: "self-start p-[4px_10px] rounded-lf-pill text-[11px] font-bold",
  offsetSuccess: "bg-[rgba(132,_204,_22,_0.18)] text-[#84cc16]",
  offsetWarning: "bg-[rgba(249,_115,_22,_0.18)] text-[#f97316]",
  playBtn: "w-[36px] h-[36px] bg-[rgba(0,_0,_0,_0.08)] opacity-100",
  recordButton: "inline-flex items-center justify-center w-[36px] h-[36px] border-none rounded-full bg-[#ef4444] text-[#fff] cursor-pointer shadow-[0_0_0_6px_rgba(239,_68,_68,_0.22)]",
  recordFooter: "flex items-center justify-between gap-lf-2",
  recordTime: "text-lf-md font-bold [font-variant-numeric:tabular-nums]",
  rideBrand: "text-lf-md font-[800]",
  rideEta: "p-[4px_10px] rounded-lf-pill bg-[rgba(0,_0,_0,_0.06)] text-[11px] font-bold",
  rideHead: "flex items-center justify-between",
  ringCenter: "absolute inset-0 flex items-center justify-center",
  ringFill: "[fill:none] [stroke:#84cc16] [stroke-width:4] [stroke-linecap:round]",
  ringFillOrange: "[stroke:#f97316]",
  ringGauge: "relative inline-flex items-center justify-center [flex-shrink:0]",
  ringTrack: "[fill:none] [stroke:rgba(255,_255,_255,_0.12)] [stroke-width:4]",
  scooterDate: "text-lf-xs opacity-[0.55]",
  scooterHead: "flex items-center justify-between",
  scooterLabel: "text-[10px] opacity-[0.45]",
  scooterStat: "flex flex-col gap-[2px]",
  scooterStats: "grid grid-cols-[repeat(3,_1fr)] gap-lf-2 mt-auto",
  scooterValue: "text-lf-sm font-[800]",
  stretch: "flex-1 flex flex-col",
  subtitle: "text-lf-xs opacity-[0.55]",
  timezoneLocation: "text-lf-xs opacity-[0.55]",
  timezoneTime: "text-lf-xl font-[800] [font-variant-numeric:tabular-nums]",
  timezoneTop: "flex flex-col gap-[2px]",
  title: "text-lf-sm font-bold",
  toggle: "relative w-[44px] h-[26px] border-none rounded-lf-pill bg-[rgba(255,_255,_255,_0.12)] cursor-pointer",
  toggleKnob: "absolute top-[3px] left-[3px] w-[20px] h-[20px] rounded-full bg-[#fff] transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)]",
  toggleOn: "bg-[#84cc16]",
  toggleOn_toggleKnob: "[transform:translateX(18px)]",
  vehicleMeta: "text-lf-xs opacity-[0.55]",
  waveBar: "flex-1 min-w-[2px] rounded-[2px] bg-[rgba(255,_255,_255,_0.35)]",
  waveform: "flex items-center gap-[3px] h-[36px]",
};
export default styles;
