export interface EmojiEntry {
  emoji: string;
  keywords: string[];
}

export interface EmojiCategory {
  id: string;
  label: string;
  emojis: EmojiEntry[];
}

/** Curated emoji set grouped for the composer picker search and scroll UI. */
export const emojiCategories: EmojiCategory[] = [
  {
    id: "smileys",
    label: "Smileys",
    emojis: [
      { emoji: "😀", keywords: ["grin", "happy", "smile"] },
      { emoji: "😃", keywords: ["smile", "happy", "joy"] },
      { emoji: "😄", keywords: ["smile", "laugh", "happy"] },
      { emoji: "😁", keywords: ["beam", "grin", "happy"] },
      { emoji: "😆", keywords: ["laugh", "lol", "happy"] },
      { emoji: "😅", keywords: ["sweat", "nervous", "laugh"] },
      { emoji: "🤣", keywords: ["rofl", "laugh", "lol"] },
      { emoji: "😂", keywords: ["joy", "tears", "laugh", "lol"] },
      { emoji: "🙂", keywords: ["slight", "smile"] },
      { emoji: "😉", keywords: ["wink", "flirt"] },
      { emoji: "😊", keywords: ["blush", "smile", "happy"] },
      { emoji: "😇", keywords: ["innocent", "angel", "halo"] },
      { emoji: "🥰", keywords: ["love", "hearts", "smile"] },
      { emoji: "😍", keywords: ["heart", "eyes", "love"] },
      { emoji: "🤩", keywords: ["star", "eyes", "excited"] },
      { emoji: "😘", keywords: ["kiss", "love"] },
      { emoji: "😗", keywords: ["kiss", "whistle"] },
      { emoji: "😋", keywords: ["yum", "delicious", "tongue"] },
      { emoji: "😛", keywords: ["tongue", "playful"] },
      { emoji: "😜", keywords: ["wink", "tongue", "crazy"] },
      { emoji: "🤪", keywords: ["zany", "crazy", "goofy"] },
      { emoji: "😝", keywords: ["tongue", "squint"] },
      { emoji: "🤑", keywords: ["money", "rich"] },
      { emoji: "🤗", keywords: ["hug", "warm"] },
      { emoji: "🤭", keywords: ["giggle", "oops"] },
      { emoji: "🤫", keywords: ["shh", "quiet", "secret"] },
      { emoji: "🤔", keywords: ["think", "hmm", "consider"] },
      { emoji: "🤐", keywords: ["zip", "quiet", "secret"] },
      { emoji: "😐", keywords: ["neutral", "meh"] },
      { emoji: "😑", keywords: ["expressionless", "blank"] },
      { emoji: "😶", keywords: ["silent", "speechless"] },
      { emoji: "😏", keywords: ["smirk", "sly"] },
      { emoji: "😒", keywords: ["unamused", "meh"] },
      { emoji: "🙄", keywords: ["roll", "eyes", "whatever"] },
      { emoji: "😬", keywords: ["grimace", "awkward"] },
      { emoji: "😌", keywords: ["relieved", "calm"] },
      { emoji: "😔", keywords: ["pensive", "sad"] },
      { emoji: "😪", keywords: ["sleepy", "tired"] },
      { emoji: "🤤", keywords: ["drool", "hungry"] },
      { emoji: "😴", keywords: ["sleep", "zzz", "tired"] },
      { emoji: "😷", keywords: ["mask", "sick"] },
      { emoji: "🤒", keywords: ["sick", "thermometer"] },
      { emoji: "🤕", keywords: ["hurt", "bandage"] },
      { emoji: "🤢", keywords: ["nausea", "sick"] },
      { emoji: "🤮", keywords: ["vomit", "sick"] },
      { emoji: "🥵", keywords: ["hot", "sweat"] },
      { emoji: "🥶", keywords: ["cold", "freeze"] },
      { emoji: "🥴", keywords: ["woozy", "dizzy"] },
      { emoji: "😵", keywords: ["dizzy", "dead"] },
      { emoji: "🤯", keywords: ["mind", "blown", "wow"] },
      { emoji: "🤠", keywords: ["cowboy", "hat"] },
      { emoji: "🥳", keywords: ["party", "celebrate"] },
      { emoji: "😎", keywords: ["cool", "sunglasses"] },
      { emoji: "🤓", keywords: ["nerd", "glasses"] },
      { emoji: "🧐", keywords: ["monocle", "inspect"] },
    ],
  },
  {
    id: "gestures",
    label: "Gestures",
    emojis: [
      { emoji: "👍", keywords: ["thumbs", "up", "yes", "ok", "good"] },
      { emoji: "👎", keywords: ["thumbs", "down", "no", "bad"] },
      { emoji: "👌", keywords: ["ok", "perfect"] },
      { emoji: "✌️", keywords: ["peace", "victory"] },
      { emoji: "🤞", keywords: ["cross", "fingers", "luck"] },
      { emoji: "🤟", keywords: ["love", "you", "rock"] },
      { emoji: "🤘", keywords: ["rock", "horns"] },
      { emoji: "🤙", keywords: ["call", "shaka"] },
      { emoji: "👋", keywords: ["wave", "hello", "hi", "bye"] },
      { emoji: "🤚", keywords: ["raised", "hand"] },
      { emoji: "🖐️", keywords: ["hand", "five"] },
      { emoji: "✋", keywords: ["stop", "high", "five"] },
      { emoji: "🖖", keywords: ["vulcan", "spock"] },
      { emoji: "👏", keywords: ["clap", "applause"] },
      { emoji: "🙌", keywords: ["raise", "celebrate", "hooray"] },
      { emoji: "👐", keywords: ["open", "hands"] },
      { emoji: "🤲", keywords: ["palms", "up", "pray"] },
      { emoji: "🤝", keywords: ["handshake", "deal"] },
      { emoji: "🙏", keywords: ["pray", "thanks", "please"] },
      { emoji: "💪", keywords: ["muscle", "strong", "flex"] },
      { emoji: "🦾", keywords: ["prosthetic", "arm", "strong"] },
      { emoji: "👊", keywords: ["fist", "bump", "punch"] },
      { emoji: "✊", keywords: ["fist", "power"] },
      { emoji: "🤛", keywords: ["left", "fist", "bump"] },
      { emoji: "🤜", keywords: ["right", "fist", "bump"] },
      { emoji: "👈", keywords: ["point", "left"] },
      { emoji: "👉", keywords: ["point", "right"] },
      { emoji: "👆", keywords: ["point", "up"] },
      { emoji: "👇", keywords: ["point", "down"] },
      { emoji: "☝️", keywords: ["index", "up", "one"] },
      { emoji: "✍️", keywords: ["write", "pen"] },
      { emoji: "🤳", keywords: ["selfie", "phone"] },
      { emoji: "💅", keywords: ["nail", "polish", "sassy"] },
    ],
  },
  {
    id: "hearts",
    label: "Hearts",
    emojis: [
      { emoji: "❤️", keywords: ["heart", "love", "red"] },
      { emoji: "🧡", keywords: ["heart", "orange", "love"] },
      { emoji: "💛", keywords: ["heart", "yellow", "love"] },
      { emoji: "💚", keywords: ["heart", "green", "love"] },
      { emoji: "💙", keywords: ["heart", "blue", "love"] },
      { emoji: "💜", keywords: ["heart", "purple", "love"] },
      { emoji: "🖤", keywords: ["heart", "black", "love"] },
      { emoji: "🤍", keywords: ["heart", "white", "love"] },
      { emoji: "🤎", keywords: ["heart", "brown", "love"] },
      { emoji: "💔", keywords: ["broken", "heart", "sad"] },
      { emoji: "❣️", keywords: ["heart", "exclamation"] },
      { emoji: "💕", keywords: ["hearts", "love"] },
      { emoji: "💞", keywords: ["revolving", "hearts"] },
      { emoji: "💓", keywords: ["beating", "heart"] },
      { emoji: "💗", keywords: ["growing", "heart"] },
      { emoji: "💖", keywords: ["sparkling", "heart"] },
      { emoji: "💘", keywords: ["cupid", "arrow", "heart"] },
      { emoji: "💝", keywords: ["gift", "heart", "ribbon"] },
      { emoji: "💟", keywords: ["heart", "decoration"] },
      { emoji: "♥️", keywords: ["suit", "heart", "card"] },
    ],
  },
  {
    id: "nature",
    label: "Nature",
    emojis: [
      { emoji: "🐶", keywords: ["dog", "puppy", "pet"] },
      { emoji: "🐱", keywords: ["cat", "kitten", "pet"] },
      { emoji: "🐭", keywords: ["mouse", "rat"] },
      { emoji: "🐹", keywords: ["hamster", "pet"] },
      { emoji: "🐰", keywords: ["rabbit", "bunny"] },
      { emoji: "🦊", keywords: ["fox"] },
      { emoji: "🐻", keywords: ["bear"] },
      { emoji: "🐼", keywords: ["panda"] },
      { emoji: "🐨", keywords: ["koala"] },
      { emoji: "🐯", keywords: ["tiger"] },
      { emoji: "🦁", keywords: ["lion"] },
      { emoji: "🐮", keywords: ["cow"] },
      { emoji: "🐷", keywords: ["pig"] },
      { emoji: "🐸", keywords: ["frog"] },
      { emoji: "🐵", keywords: ["monkey"] },
      { emoji: "🦄", keywords: ["unicorn", "magic"] },
      { emoji: "🐝", keywords: ["bee", "honey"] },
      { emoji: "🦋", keywords: ["butterfly"] },
      { emoji: "🌸", keywords: ["flower", "blossom", "spring"] },
      { emoji: "🌺", keywords: ["flower", "hibiscus"] },
      { emoji: "🌻", keywords: ["sunflower"] },
      { emoji: "🌹", keywords: ["rose", "flower", "love"] },
      { emoji: "🌷", keywords: ["tulip", "flower"] },
      { emoji: "🌱", keywords: ["seedling", "plant", "grow"] },
      { emoji: "🌲", keywords: ["tree", "evergreen"] },
      { emoji: "🌳", keywords: ["tree", "deciduous"] },
      { emoji: "🍀", keywords: ["clover", "luck", "four", "leaf"] },
      { emoji: "🍁", keywords: ["maple", "leaf", "fall"] },
      { emoji: "🌍", keywords: ["earth", "globe", "world"] },
      { emoji: "🌙", keywords: ["moon", "night"] },
      { emoji: "⭐", keywords: ["star"] },
      { emoji: "🌈", keywords: ["rainbow"] },
      { emoji: "☀️", keywords: ["sun", "sunny"] },
      { emoji: "⛅", keywords: ["cloud", "sun", "partly"] },
      { emoji: "🌧️", keywords: ["rain", "cloud"] },
      { emoji: "❄️", keywords: ["snow", "cold", "winter"] },
      { emoji: "🔥", keywords: ["fire", "hot", "lit"] },
      { emoji: "💧", keywords: ["droplet", "water"] },
    ],
  },
  {
    id: "food",
    label: "Food",
    emojis: [
      { emoji: "🍎", keywords: ["apple", "fruit", "red"] },
      { emoji: "🍊", keywords: ["orange", "fruit"] },
      { emoji: "🍋", keywords: ["lemon", "fruit", "citrus"] },
      { emoji: "🍌", keywords: ["banana", "fruit"] },
      { emoji: "🍉", keywords: ["watermelon", "fruit"] },
      { emoji: "🍇", keywords: ["grapes", "fruit"] },
      { emoji: "🍓", keywords: ["strawberry", "fruit", "berry"] },
      { emoji: "🫐", keywords: ["blueberry", "berry"] },
      { emoji: "🍒", keywords: ["cherry", "fruit"] },
      { emoji: "🥑", keywords: ["avocado"] },
      { emoji: "🥦", keywords: ["broccoli", "vegetable"] },
      { emoji: "🥕", keywords: ["carrot", "vegetable"] },
      { emoji: "🌽", keywords: ["corn", "vegetable"] },
      { emoji: "🍞", keywords: ["bread", "toast"] },
      { emoji: "🥐", keywords: ["croissant", "pastry"] },
      { emoji: "🥨", keywords: ["pretzel", "snack"] },
      { emoji: "🧀", keywords: ["cheese"] },
      { emoji: "🍳", keywords: ["egg", "breakfast", "cook"] },
      { emoji: "🥞", keywords: ["pancakes", "breakfast"] },
      { emoji: "🍕", keywords: ["pizza", "food"] },
      { emoji: "🍔", keywords: ["burger", "hamburger", "food"] },
      { emoji: "🌮", keywords: ["taco", "mexican"] },
      { emoji: "🌯", keywords: ["burrito", "wrap"] },
      { emoji: "🥗", keywords: ["salad", "healthy"] },
      { emoji: "🍜", keywords: ["noodles", "ramen", "bowl"] },
      { emoji: "🍣", keywords: ["sushi", "japanese"] },
      { emoji: "🍩", keywords: ["donut", "doughnut", "dessert"] },
      { emoji: "🍪", keywords: ["cookie", "dessert"] },
      { emoji: "🎂", keywords: ["cake", "birthday", "dessert"] },
      { emoji: "🍰", keywords: ["cake", "slice", "dessert"] },
      { emoji: "🍫", keywords: ["chocolate", "candy"] },
      { emoji: "🍬", keywords: ["candy", "sweet"] },
      { emoji: "🍭", keywords: ["lollipop", "candy"] },
      { emoji: "☕", keywords: ["coffee", "cafe", "drink"] },
      { emoji: "🍵", keywords: ["tea", "drink"] },
      { emoji: "🧃", keywords: ["juice", "box", "drink"] },
      { emoji: "🍺", keywords: ["beer", "drink", "cheers"] },
      { emoji: "🍷", keywords: ["wine", "drink"] },
      { emoji: "🥂", keywords: ["cheers", "champagne", "toast"] },
    ],
  },
  {
    id: "objects",
    label: "Objects",
    emojis: [
      { emoji: "⌚", keywords: ["watch", "time"] },
      { emoji: "📱", keywords: ["phone", "mobile"] },
      { emoji: "💻", keywords: ["laptop", "computer"] },
      { emoji: "⌨️", keywords: ["keyboard", "type"] },
      { emoji: "🖥️", keywords: ["desktop", "monitor"] },
      { emoji: "🖨️", keywords: ["printer"] },
      { emoji: "🖱️", keywords: ["mouse", "click"] },
      { emoji: "💾", keywords: ["floppy", "save", "disk"] },
      { emoji: "💿", keywords: ["cd", "disc"] },
      { emoji: "📷", keywords: ["camera", "photo"] },
      { emoji: "🎥", keywords: ["movie", "camera", "film"] },
      { emoji: "🎧", keywords: ["headphones", "music"] },
      { emoji: "🎤", keywords: ["microphone", "sing"] },
      { emoji: "🎵", keywords: ["music", "note"] },
      { emoji: "🎶", keywords: ["music", "notes"] },
      { emoji: "🔔", keywords: ["bell", "notification"] },
      { emoji: "🔕", keywords: ["mute", "silent", "bell"] },
      { emoji: "📣", keywords: ["megaphone", "announce"] },
      { emoji: "💡", keywords: ["light", "bulb", "idea"] },
      { emoji: "🔦", keywords: ["flashlight"] },
      { emoji: "📚", keywords: ["books", "read", "study"] },
      { emoji: "📖", keywords: ["book", "read"] },
      { emoji: "✏️", keywords: ["pencil", "write", "edit"] },
      { emoji: "📝", keywords: ["memo", "note", "write"] },
      { emoji: "📎", keywords: ["paperclip", "attach"] },
      { emoji: "📌", keywords: ["pin", "pushpin"] },
      { emoji: "📁", keywords: ["folder", "file"] },
      { emoji: "📂", keywords: ["folder", "open"] },
      { emoji: "🗂️", keywords: ["index", "divider", "organize"] },
      { emoji: "🗃️", keywords: ["card", "file", "box"] },
      { emoji: "🗄️", keywords: ["cabinet", "file"] },
      { emoji: "🔒", keywords: ["lock", "secure"] },
      { emoji: "🔓", keywords: ["unlock", "open"] },
      { emoji: "🔑", keywords: ["key", "password"] },
      { emoji: "🛠️", keywords: ["tools", "fix", "build"] },
      { emoji: "⚙️", keywords: ["gear", "settings"] },
      { emoji: "🔧", keywords: ["wrench", "fix"] },
      { emoji: "🔨", keywords: ["hammer", "build"] },
      { emoji: "⚡", keywords: ["lightning", "zap", "fast"] },
      { emoji: "🧲", keywords: ["magnet", "attract"] },
      { emoji: "🧪", keywords: ["test", "tube", "science"] },
      { emoji: "🔬", keywords: ["microscope", "science"] },
      { emoji: "🎁", keywords: ["gift", "present"] },
      { emoji: "🎈", keywords: ["balloon", "party"] },
      { emoji: "🎉", keywords: ["party", "tada", "celebrate"] },
      { emoji: "🏆", keywords: ["trophy", "win", "award"] },
      { emoji: "🥇", keywords: ["gold", "medal", "first"] },
      { emoji: "⚽", keywords: ["soccer", "football", "ball"] },
      { emoji: "🏀", keywords: ["basketball", "ball"] },
      { emoji: "🎮", keywords: ["game", "controller", "play"] },
      { emoji: "🎲", keywords: ["dice", "game", "random"] },
    ],
  },
  {
    id: "symbols",
    label: "Symbols",
    emojis: [
      { emoji: "✅", keywords: ["check", "done", "yes", "complete"] },
      { emoji: "❌", keywords: ["x", "no", "wrong", "cross"] },
      { emoji: "❓", keywords: ["question", "help"] },
      { emoji: "❗", keywords: ["exclamation", "important"] },
      { emoji: "‼️", keywords: ["double", "exclamation"] },
      { emoji: "⁉️", keywords: ["interrobang", "question"] },
      { emoji: "💯", keywords: ["hundred", "perfect", "score"] },
      { emoji: "🔴", keywords: ["red", "circle", "dot"] },
      { emoji: "🟠", keywords: ["orange", "circle"] },
      { emoji: "🟡", keywords: ["yellow", "circle"] },
      { emoji: "🟢", keywords: ["green", "circle"] },
      { emoji: "🔵", keywords: ["blue", "circle"] },
      { emoji: "🟣", keywords: ["purple", "circle"] },
      { emoji: "⚫", keywords: ["black", "circle"] },
      { emoji: "⚪", keywords: ["white", "circle"] },
      { emoji: "🔶", keywords: ["orange", "diamond"] },
      { emoji: "🔷", keywords: ["blue", "diamond"] },
      { emoji: "🔺", keywords: ["red", "triangle", "up"] },
      { emoji: "🔻", keywords: ["red", "triangle", "down"] },
      { emoji: "💬", keywords: ["speech", "bubble", "chat", "comment"] },
      { emoji: "🗨️", keywords: ["speech", "left", "bubble"] },
      { emoji: "🗯️", keywords: ["anger", "bubble", "mad"] },
      { emoji: "💭", keywords: ["thought", "bubble", "think"] },
      { emoji: "🔀", keywords: ["shuffle", "random"] },
      { emoji: "🔁", keywords: ["repeat", "loop"] },
      { emoji: "⏩", keywords: ["fast", "forward"] },
      { emoji: "⏪", keywords: ["rewind", "back"] },
      { emoji: "▶️", keywords: ["play", "start"] },
      { emoji: "⏸️", keywords: ["pause", "stop"] },
      { emoji: "⏹️", keywords: ["stop", "square"] },
      { emoji: "➕", keywords: ["plus", "add"] },
      { emoji: "➖", keywords: ["minus", "subtract"] },
      { emoji: "✖️", keywords: ["multiply", "x"] },
      { emoji: "➗", keywords: ["divide"] },
      { emoji: "♾️", keywords: ["infinity", "forever"] },
      { emoji: "©️", keywords: ["copyright"] },
      { emoji: "™️", keywords: ["trademark"] },
      { emoji: "🔤", keywords: ["abc", "letters", "alphabet"] },
      { emoji: "🔡", keywords: ["lowercase", "letters"] },
      { emoji: "🔢", keywords: ["numbers", "123"] },
      { emoji: "#️⃣", keywords: ["hash", "number", "pound"] },
      { emoji: "*️⃣", keywords: ["asterisk", "star"] },
      { emoji: "0️⃣", keywords: ["zero", "number"] },
      { emoji: "1️⃣", keywords: ["one", "number"] },
      { emoji: "2️⃣", keywords: ["two", "number"] },
      { emoji: "3️⃣", keywords: ["three", "number"] },
      { emoji: "4️⃣", keywords: ["four", "number"] },
      { emoji: "5️⃣", keywords: ["five", "number"] },
    ],
  },
];

export function filterEmojiCategories(query: string): EmojiCategory[] {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return emojiCategories;

  return emojiCategories
    .map((category) => ({
      ...category,
      emojis: category.emojis.filter(
        (entry) =>
          entry.keywords.some((keyword) => keyword.includes(normalized)) ||
          category.label.toLowerCase().includes(normalized),
      ),
    }))
    .filter((category) => category.emojis.length > 0);
}
