/** Tailwind class map — converted from AgentBlocks.module.css */
const styles: Record<string, string> = {
  action: "[composes:agentBlock] border border-solid border-lf-border-subtle rounded-lf-lg bg-lf-surface-1 overflow-hidden",
  actionBody: "p-lf-3 border-t border-lf-divider bg-lf-surface-sunken",
  actionChevron: "inline-flex [flex-shrink:0] text-lf-text-tertiary transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)]",
  actionChevronClosed: "[transform:rotate(-90deg)]",
  actionChevronOpen: "[transform:rotate(0deg)]",
  actionCommand: "[flex-shrink:0] p-[1px_var(--lf-space-1)] rounded-lf-sm bg-lf-surface-2 text-lf-text-tertiary font-mono text-lf-xs",
  actionHeader: "flex items-center gap-lf-2 w-full p-[var(--lf-space-2)_var(--lf-space-3)] bg-lf-surface-sunken border-none text-lf-text-secondary font-sans text-lf-sm text-left cursor-pointer hover:text-lf-text-primary",
  actionHeaderStatic: "cursor-default hover:text-lf-text-secondary",
  actionIcon: "inline-flex [flex-shrink:0] text-lf-text-tertiary",
  actionOutput: "m-0 text-lf-text-secondary font-mono text-lf-sm leading-[var(--lf-line-height-relaxed)] whitespace-pre-wrap [word-break:break-word]",
  actionTitle: "flex-1 min-w-0",
  agentBlock: "mb-lf-3",
  fileBadge: "inline-flex items-center justify-center [flex-shrink:0] w-[18px] h-[18px] rounded-[var(--lf-radius-xs)] font-mono text-[9px] font-bold [letter-spacing:-0.02em] leading-none",
  fileBadgeCss: "bg-[rgba(86,_156,_214,_0.14)] text-[#569cd6]",
  fileBadgeOther: "bg-lf-surface-3 text-lf-text-tertiary",
  fileBadgeTs: "bg-lf-info-muted text-lf-info",
  fileBadgeTsx: "bg-lf-info-muted text-lf-info",
  fileChip: "[composes:agentBlock] inline-flex items-center gap-lf-2 max-w-full p-[var(--lf-space-1)_var(--lf-space-2)] border border-solid border-lf-border-subtle rounded-lf-md bg-lf-surface-2 text-lf-text-primary font-sans text-lf-sm text-left cursor-default",
  fileChipInteractive: "cursor-pointer hover:bg-lf-surface-3 hover:border-lf-border-default",
  fileCreation: "[composes:agentBlock]",
  fileCreationBody: "mt-lf-2",
  fileCreationChevron: "inline-flex [flex-shrink:0] text-lf-text-tertiary transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)]",
  fileCreationChevronClosed: "[transform:rotate(0deg)]",
  fileCreationChevronOpen: "[transform:rotate(90deg)]",
  fileCreationContent: "flex flex-wrap items-center gap-lf-2 min-w-0 p-[var(--lf-space-1)_0_var(--lf-space-2)] border-none bg-[none] text-[inherit] [font:inherit] text-left",
  fileCreationDone: "flex items-center gap-lf-2 mt-lf-1 pl-[calc(18px_+_var(--lf-space-2))] text-lf-text-tertiary text-lf-sm",
  fileCreationDoneIcon: "inline-flex items-center justify-center w-[16px] h-[16px] rounded-full bg-lf-success-muted text-lf-success",
  fileCreationFilename: "[flex-shrink:0] p-[2px_var(--lf-space-2)] rounded-[var(--lf-radius-pill,_999px)] bg-lf-surface-2 text-lf-text-tertiary font-mono text-lf-xs leading-[1.3]",
  fileCreationHeader: "inline-flex items-center gap-lf-1 p-0 border-none bg-[none] text-lf-text-secondary font-sans text-lf-sm font-medium cursor-pointer hover:text-lf-text-primary",
  fileCreationIcon: "inline-flex items-center justify-center w-[18px] h-[18px] [flex-shrink:0] mt-[1px] text-lf-text-tertiary",
  fileCreationLabel: "min-w-0 text-lf-text-secondary text-lf-sm leading-[var(--lf-line-height-normal)]",
  fileCreationList: "flex flex-col gap-0 m-0 p-0 list-none",
  fileCreationRail: "relative flex flex-col items-center [flex-shrink:0] w-[18px]",
  fileCreationRow: "flex items-stretch gap-lf-2 min-w-0",
  fileCreationRowInteractive: "cursor-pointer rounded-lf-sm hover:text-lf-text-primary",
  fileCreationRowWithConnector: "",
  fileCreationRowWithConnector_fileCreationRail: "before:after:[content:\"\"] before:after:absolute before:after:top-[20px] before:after:bottom-[-6px] before:after:left-[50%] before:after:w-[1px] before:after:[transform:translateX(-50%)] before:after:bg-lf-border-subtle",
  fileCreationTitle: "min-w-0",
  fileName: "min-w-0 overflow-hidden text-ellipsis whitespace-nowrap font-mono text-lf-sm",
  status: "[composes:agentBlock] mt-[calc(-1_*_var(--lf-space-1))] mb-lf-3 text-lf-sm text-lf-text-tertiary",
  thought: "[composes:agentBlock]",
  thoughtChevron: "flex transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)]",
  thoughtChevronClosed: "[transform:rotate(-90deg)]",
  thoughtChevronOpen: "[transform:rotate(0deg)]",
  thoughtContent: "mt-lf-2 text-lf-text-tertiary text-lf-md leading-[var(--lf-line-height-normal)]",
  "thoughtContent p": "m-0",
  thoughtTrigger: "inline-flex items-center gap-lf-1 bg-[none] border-none p-0 text-lf-text-tertiary text-lf-sm font-medium cursor-pointer hover:text-lf-text-secondary",
  todoCard: "[composes:agentBlock] border border-solid border-lf-border-subtle rounded-lf-lg bg-lf-surface-1 overflow-hidden",
  todoCount: "text-lf-text-tertiary font-normal",
  todoHeader: "flex items-center gap-lf-2 p-[var(--lf-space-2)_var(--lf-space-3)] border-b border-lf-divider bg-lf-surface-sunken text-lf-sm font-medium text-lf-text-secondary",
  todoHeaderIcon: "inline-flex text-lf-text-tertiary",
  todoIndicator: "inline-flex items-center justify-center w-[16px] h-[16px] [flex-shrink:0] mt-[2px] text-lf-text-tertiary",
  todoIndicatorActive: "text-lf-text-secondary",
  todoIndicatorCompleted: "w-[14px] h-[14px] m-[3px_1px_0] rounded-full bg-lf-success-muted text-lf-success",
  todoIndicatorPending: "w-[14px] h-[14px] m-[3px_1px_0] [border:1.5px_dashed_var(--lf-border-strong)] rounded-full",
  todoLabel: "min-w-0",
  todoList: "flex flex-col gap-lf-3 m-0 p-lf-3 list-none",
  todoRow: "flex items-start gap-lf-2 min-w-0 text-lf-md text-lf-text-primary leading-[var(--lf-line-height-normal)]",
  todoRowCompleted: "text-lf-text-tertiary [text-decoration:line-through]",
  todoRowPending: "text-lf-text-secondary",
};
export default styles;
