/** Tailwind class map — converted from AdaptiveBottomNav.module.css */
const styles: Record<string, string> = {
  fade: "absolute top-0 bottom-0 w-[18px] pointer-events-none z-[1]",
  fadeLeft: "left-0 bg-[linear-gradient(to_right,_var(--lf-surface-2),_transparent)]",
  fadeRight: "right-0 bg-[linear-gradient(to_left,_var(--lf-surface-2),_transparent)]",
  modal: "min-h-[52px]",
  modal_tabButton: "min-w-[84px] [padding-inline:var(--lf-space-3)]",
  modal_tabLabel: "max-w-[84px]",
  overflowCount: "absolute top-[-5px] right-[-9px] min-w-[14px] h-[14px] p-[0_3px] rounded-[999px] bg-lf-accent text-lf-text-on-accent text-[8px] font-bold leading-[14px] text-center shadow-[0_0_0_1px_var(--lf-surface-2)]",
  overflowDock: "relative flex items-stretch [flex-shrink:0] border-l border-lf-border-subtle bg-[color-mix(in_srgb,_var(--lf-surface-2)_92%,_var(--lf-surface-1))]",
  overflowDockFade: "absolute top-0 bottom-0 left-[-16px] w-[16px] bg-[linear-gradient(to_right,_transparent,_var(--lf-surface-2))] pointer-events-none",
  overflowIconWrap: "relative",
  overflowTab: "w-[72px]",
  phone: "min-h-[56px]",
  phone_scroller: "w-full",
  phone_tabButtonActive_tabIcon: "rounded-lf-md",
  phone_tabIcon: "w-[32px] h-[32px] rounded-lf-md",
  phone_track: "w-[max-content]",
  root: "relative flex items-stretch min-w-0 border-t border-lf-border-subtle bg-[color-mix(in_srgb,_var(--lf-surface-2)_92%,_var(--lf-surface-1))] [flex-shrink:0]",
  rootWithDock: "",
  rootWithDock_scroller: "[mask-image:linear-gradient(to_right,_#000_calc(100%_-_18px),_transparent_100%)]",
  scrollButton: "absolute top-[50%] z-[2] inline-flex items-center justify-center w-[22px] h-[22px] border border-solid border-lf-border-subtle rounded-[999px] bg-lf-surface-1 text-lf-text-secondary cursor-pointer [transform:translateY(-50%)] transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:bg-lf-surface-3 hover:text-lf-text-primary",
  scrollButtonLeft: "left-[4px]",
  scrollButtonRight: "right-[4px]",
  scroller: "flex-1 min-w-0 [overflow-x:auto] overflow-y-hidden",
  tabButton: "inline-flex flex-col items-center justify-center gap-[3px] min-w-[72px] p-[4px_8px_2px] border-none rounded-lf-md bg-transparent text-lf-text-tertiary [font:inherit] text-[10px] leading-[1.2] cursor-pointer [flex-shrink:0] transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:text-lf-text-secondary hover:bg-[color-mix(in_srgb,_var(--lf-text-primary)_7%,_transparent)] active:[transform:translateY(1px)] active:bg-[color-mix(in_srgb,_var(--lf-text-primary)_11%,_transparent)] active:[transform:scale(0.96)] hover:bg-transparent",
  tabButtonActive: "text-lf-accent",
  tabButtonActive_overflowCount: "bg-lf-accent-active",
  tabButtonActive_tabIcon: "bg-lf-accent-muted shadow-[inset_0_0_0_1px_color-mix(in_srgb,_var(--lf-accent)_28%,_transparent),_0_1px_2px_color-mix(in_srgb,_var(--lf-accent)_18%,_transparent)]",
  tabButtonActive_tabLabel: "text-lf-accent font-semibold",
  tabIcon: "relative inline-flex items-center justify-center w-[34px] h-[30px] rounded-lf-pill transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)]",
  tabLabel: "max-w-[72px] overflow-hidden text-ellipsis whitespace-nowrap transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)]",
  track: "flex items-stretch w-[max-content] min-w-[100%] p-[2px_0]",
};
export default styles;
