/** Tailwind class map — converted from AdaptiveAppLayout.module.css */
const styles: Record<string, string> = {
  bottomNavWrap: "[flex-shrink:0]",
  detailHeader: "flex items-center gap-lf-2 p-[var(--lf-space-3)_var(--lf-space-4)] border-b border-lf-border-subtle [flex-shrink:0]",
  detailHeaderStatic: "flex items-center gap-lf-2 p-[var(--lf-space-3)_var(--lf-space-4)] border-b border-lf-border-subtle [flex-shrink:0]",
  detailPane: "flex flex-col flex-1 min-w-0 min-h-0 bg-lf-surface-1",
  detailScroll: "h-full min-h-0",
  detailTitle: "m-0 text-[var(--lf-text-md)] font-semibold text-lf-text-primary",
  expanded: "flex-row",
  expandedModal: "rounded-none",
  listPane: "h-full min-h-0",
  listResizable: "[flex-shrink:0] min-h-0",
  listRow: "rounded-none",
  listRowActive: "bg-lf-accent-muted",
  listScroll: "h-full min-h-0",
  root: "flex h-full min-h-0 bg-lf-surface-1",
  sidebarHeader: "flex items-center gap-lf-2 p-[var(--lf-space-3)_var(--lf-space-3)_var(--lf-space-2)]",
  sidebarIcon: "inline-flex items-center justify-center w-[28px] h-[28px] rounded-lf-sm bg-[color-mix(in_srgb,_var(--lf-accent)_12%,_var(--lf-surface-2))] text-lf-accent",
  sidebarTitle: "text-[var(--lf-text-sm)] font-semibold text-lf-text-primary",
  split: "flex-row",
  splitList: "w-[280px] [flex-shrink:0] min-w-0 min-h-0 border-r border-lf-border-subtle",
  splitRail: "flex flex-col items-center gap-lf-1 w-[56px] p-[var(--lf-space-2)_var(--lf-space-1)] border-r border-lf-border-subtle bg-lf-surface-2 [flex-shrink:0]",
  splitRailItem: "inline-flex items-center justify-center w-[40px] h-[40px] border-none rounded-lf-sm bg-transparent text-lf-text-tertiary cursor-pointer hover:bg-lf-surface-3 hover:text-lf-text-secondary",
  splitRailItemActive: "bg-lf-accent-muted text-lf-accent",
  splitRailTitle: "inline-flex items-center justify-center w-[36px] h-[36px] mb-lf-1 rounded-lf-sm bg-[color-mix(in_srgb,_var(--lf-accent)_12%,_var(--lf-surface-1))] text-lf-accent",
  stacked: "flex-col",
  stackedBack: "[flex-shrink:0]",
  stackedHeader: "grid items-center gap-lf-2 min-h-[44px] p-[var(--lf-space-2)_var(--lf-space-3)] border-b border-lf-border-subtle [flex-shrink:0] bg-lf-surface-1 grid-cols-[1fr_auto] grid-cols-[auto_1fr]",
  stackedHeaderTitle: "m-0 min-w-0 text-[var(--lf-text-sm)] font-semibold text-lf-text-primary whitespace-nowrap overflow-hidden text-ellipsis",
  stackedListWrap: "h-full min-h-0",
  stackedMain: "flex-1 min-h-0",
  stackedSection: "text-[var(--lf-text-xs)] text-lf-text-tertiary whitespace-nowrap",
  stackedTitle: "text-[var(--lf-text-sm)] font-semibold text-lf-text-primary min-w-0 whitespace-nowrap overflow-hidden text-ellipsis",
};
export default styles;
