/** Tailwind class map — converted from AppPortFrame.module.css */
const styles: Record<string, string> = {
  modalBody: "flex-1 min-h-0 overflow-hidden",
  modalCloseButton: "inline-flex items-center justify-center w-[24px] h-[24px] border-none rounded-lf-sm bg-transparent text-lf-text-tertiary cursor-pointer hover:bg-lf-surface-3 hover:text-lf-text-secondary",
  modalDimensions: "text-[10px] font-medium text-lf-text-tertiary",
  modalResetButton: "border border-solid border-lf-border-subtle rounded-lf-sm p-[2px_var(--lf-space-2)] bg-lf-surface-1 text-lf-text-tertiary [font:inherit] text-[10px] cursor-pointer hover:text-lf-text-secondary hover:bg-lf-surface-3",
  modalScrim: "flex items-center justify-center w-full h-full p-lf-4 rounded-lf-lg bg-[color-mix(in_srgb,_var(--lf-overlay)_55%,_transparent)]",
  modalTitle: "inline-flex items-center justify-center gap-lf-2 text-[var(--lf-text-xs)] font-semibold text-lf-text-secondary",
  modalTitleActions: "[justify-self:end] inline-flex items-center gap-lf-1",
  modalTitleBar: "grid grid-cols-[1fr_auto_1fr] items-center gap-lf-2 min-h-[36px] p-[0_var(--lf-space-3)] border-b border-lf-border-subtle bg-lf-surface-2 [flex-shrink:0]",
  modalTrafficClose: "w-[10px] h-[10px] rounded-[999px] bg-[#ff5f57]",
  modalTrafficLights: "flex items-center gap-[6px]",
  modalTrafficMaximize: "w-[10px] h-[10px] rounded-[999px] bg-[#28c840]",
  modalTrafficMinimize: "w-[10px] h-[10px] rounded-[999px] bg-[#febc2e]",
  modalWindow: "relative flex flex-col max-w-[calc(100%_-_var(--lf-space-8))] max-h-[calc(100%_-_var(--lf-space-8))] overflow-hidden rounded-lf-lg border border-solid border-lf-border-default shadow-lf-overlay bg-lf-surface-1",
  resizeE: "top-[8px] bottom-[8px] w-[6px] [cursor:ew-resize] right-0",
  resizeHandle: "absolute z-[2] [touch-action:none]",
  resizeN: "left-[8px] right-[8px] h-[6px] [cursor:ns-resize] top-0",
  resizeNE: "w-[10px] h-[10px] top-0 right-0 [cursor:nesw-resize]",
  resizeNW: "w-[10px] h-[10px] top-0 left-0 [cursor:nwse-resize]",
  resizeS: "left-[8px] right-[8px] h-[6px] [cursor:ns-resize] bottom-0",
  resizeSE: "w-[10px] h-[10px] bottom-0 right-0 [cursor:nwse-resize]",
  resizeSW: "w-[10px] h-[10px] bottom-0 left-0 [cursor:nesw-resize]",
  resizeW: "top-[8px] bottom-[8px] w-[6px] [cursor:ew-resize] left-0",
  screen: "flex flex-col w-full h-full max-w-full max-h-[100%] overflow-hidden rounded-lf-lg border border-solid border-lf-border-default shadow-lf-md bg-lf-surface-1 bg-lf-surface-sunken rounded-[18px]",
  screenFixed: "flex-none",
  screenWatch: "rounded-[28px]",
  stage: "flex-1 min-h-0 flex items-center justify-center p-lf-4 bg-lf-surface-canvas",
};
export default styles;
