/** Tailwind class map — converted from WatchAppChrome.module.css */
const styles: Record<string, string> = {
  appMark: "inline-flex items-center justify-center w-[22px] h-[22px] border-none rounded-[999px] [flex-shrink:0] bg-[color-mix(in_srgb,_var(--lf-accent)_14%,_var(--lf-surface-2))] text-lf-accent",
  backButton: "inline-flex items-center justify-center w-[22px] h-[22px] border-none rounded-[999px] [flex-shrink:0] bg-[color-mix(in_srgb,_var(--lf-text-primary)_10%,_transparent)] text-lf-text-primary cursor-pointer hover:bg-[color-mix(in_srgb,_var(--lf-text-primary)_16%,_transparent)]",
  body: "flex-1 min-h-0 relative before:after:[content:\"\"] before:after:sticky before:after:bottom-0 before:after:block before:after:h-[12px] before:after:mt-[-12px] before:after:pointer-events-none before:after:bg-[linear-gradient(to_bottom,_transparent,_var(--lf-surface-sunken))]",
  detailBody: "p-[0_8px_8px] text-[10px] leading-[1.4] text-lf-text-secondary",
  emptyState: "m-0 p-[8px] text-[10px] text-lf-text-tertiary text-center",
  footer: "flex flex-col items-center gap-[4px] p-[4px_8px_8px] [flex-shrink:0]",
  footerDot: "w-[6px] h-[6px] p-0 border-none rounded-[999px] bg-[color-mix(in_srgb,_var(--lf-text-primary)_22%,_transparent)] cursor-pointer",
  footerDotActive: "bg-lf-accent",
  footerDots: "flex justify-center gap-[5px]",
  footerHomeButton: "w-full border-none rounded-[999px] p-[4px_8px] bg-[color-mix(in_srgb,_var(--lf-text-primary)_7%,_transparent)] text-lf-text-secondary [font:inherit] text-[9px] font-semibold cursor-pointer hover:bg-[color-mix(in_srgb,_var(--lf-text-primary)_11%,_transparent)] hover:text-lf-text-primary",
  footerNav: "grid grid-cols-[24px_1fr_24px] items-center gap-[4px] w-full",
  footerNavButton: "inline-flex items-center justify-center w-[24px] h-[24px] border-none rounded-[999px] bg-[color-mix(in_srgb,_var(--lf-text-primary)_8%,_transparent)] text-lf-text-secondary cursor-pointer hover:bg-[color-mix(in_srgb,_var(--lf-text-primary)_12%,_transparent)] hover:text-lf-text-primary",
  footerNavLabel: "text-[9px] font-semibold text-center text-lf-text-tertiary whitespace-nowrap overflow-hidden text-ellipsis",
  header: "flex items-center gap-[6px] p-[8px_8px_6px] [flex-shrink:0]",
  headerMeta: "text-[9px] text-lf-text-tertiary",
  headerText: "flex flex-col gap-[1px] min-w-0",
  headerTitle: "text-[12px] font-bold leading-[1.2] whitespace-nowrap overflow-hidden text-ellipsis",
  itemCopy: "flex flex-col gap-[1px] min-w-0 flex-1",
  itemList: "flex flex-col gap-[4px] p-[0_6px_6px]",
  itemMeta: "text-[8px] text-lf-text-tertiary [flex-shrink:0]",
  itemRow: "flex items-center gap-[6px] w-full p-[6px_8px] border-none rounded-[10px] bg-[color-mix(in_srgb,_var(--lf-text-primary)_6%,_transparent)] text-lf-text-primary text-left cursor-pointer hover:bg-[color-mix(in_srgb,_var(--lf-text-primary)_10%,_transparent)]",
  itemRowActive: "bg-lf-accent-muted shadow-[inset_0_0_0_1px_color-mix(in_srgb,_var(--lf-accent)_24%,_transparent)]",
  itemSubtitle: "text-[9px] text-lf-text-tertiary whitespace-nowrap overflow-hidden text-ellipsis",
  itemTitle: "text-[11px] font-semibold leading-[1.2] whitespace-nowrap overflow-hidden text-ellipsis",
  root: "flex flex-col h-full min-h-0 bg-lf-surface-sunken text-lf-text-primary",
  sectionCopy: "flex flex-col gap-[1px] min-w-0 flex-1",
  sectionCount: "text-[9px] text-lf-text-tertiary whitespace-nowrap overflow-hidden text-ellipsis",
  sectionIcon: "inline-flex items-center justify-center w-[22px] h-[22px] rounded-[6px] bg-[color-mix(in_srgb,_var(--lf-text-primary)_8%,_transparent)] [flex-shrink:0]",
  sectionLabel: "text-[11px] font-semibold leading-[1.2] whitespace-nowrap overflow-hidden text-ellipsis",
  sectionList: "flex flex-col gap-[4px] p-[0_6px_6px]",
  sectionRow: "flex items-center gap-[6px] w-full p-[6px_8px] border-none rounded-[10px] bg-[color-mix(in_srgb,_var(--lf-text-primary)_6%,_transparent)] text-lf-text-primary text-left cursor-pointer hover:bg-[color-mix(in_srgb,_var(--lf-text-primary)_10%,_transparent)]",
};
export default styles;
