/** Tailwind class map — converted from VisionWorkspace.module.css */
const styles: Record<string, string> = {
  brandCluster: "flex items-center gap-lf-5 min-w-0",
  browse: "flex-1 min-h-0 overflow-auto relative",
  continueProgressFill: "block h-full bg-[var(--vision-accent)]",
  continueProgressTrack: "w-[220px] h-[4px] bg-[rgba(255,_255,_255,_0.25)]",
  continueTile: "relative [flex-shrink:0] flex flex-col gap-lf-2 p-0 border-none bg-transparent text-[inherit] cursor-pointer text-left hover:[transform:scale(1.04)] hover:shadow-[0_8px_24px_rgba(0,_0,_0,_0.45)]",
  continueTile_posterMd: "transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] rounded-[var(--lf-radius-sm)_var(--lf-radius-sm)_0_0]",
  controlBtn: "flex items-center justify-center w-[32px] h-[32px] border-none rounded-lf-pill bg-transparent text-[var(--vision-text-subtle)] cursor-pointer hover:text-[var(--vision-text)]",
  controlRow: "flex items-center gap-lf-3",
  exploreLink: "inline-flex items-center gap-[2px] border-none bg-transparent text-[var(--vision-text-muted)] text-lf-sm font-semibold cursor-pointer hover:text-[var(--vision-text)]",
  hero: "relative min-h-[68vh] flex items-end overflow-hidden min-h-[52vh]",
  hero_posterHero: "absolute inset-0 w-full h-full rounded-none",
  heroActions: "flex flex-wrap gap-lf-3",
  heroBadge: "m-[0_0_var(--lf-space-2)] text-[11px] font-[800] [letter-spacing:0.12em] text-[var(--vision-text-subtle)]",
  heroContent: "relative z-[1] max-w-[560px] p-[0_var(--lf-space-5)_var(--lf-space-8)]",
  heroDescription: "m-[0_0_var(--lf-space-4)] text-lf-md leading-normal text-[var(--vision-text-subtle)] [display:-webkit-box] line-clamp-[3] [-webkit-box-orient:vertical] overflow-hidden",
  heroRank: "flex items-center gap-lf-2 m-[0_0_var(--lf-space-3)] text-lf-sm font-bold",
  heroScrim: "absolute inset-0 bg-[linear-gradient(77deg,_rgba(0,_0,_0,_0.88)_0%,_rgba(0,_0,_0,_0.45)_45%,_rgba(0,_0,_0,_0.12)_100%),_linear-gradient(0deg,_var(--vision-bg)_0%,_transparent_55%),_linear-gradient(180deg,_rgba(0,_0,_0,_0.55)_0%,_transparent_28%)] pointer-events-none",
  heroTitle: "m-[0_0_var(--lf-space-3)] text-[clamp(2.5rem,_5vw,_4rem)] font-[900] leading-[0.95] [letter-spacing:-0.03em] uppercase",
  iconBtn: "flex items-center justify-center w-[32px] h-[32px] border-none rounded-lf-sm bg-transparent text-[var(--vision-text)] cursor-pointer hover:bg-[rgba(255,_255,_255,_0.08)]",
  infoBtn: "inline-flex items-center gap-lf-2 p-[0_var(--lf-space-5)] h-[44px] border-none rounded-lf-sm text-lf-md font-bold cursor-pointer bg-[rgba(109,_109,_110,_0.7)] text-[#fff] hover:bg-[rgba(109,_109,_110,_0.55)]",
  infoIcon: "inline-flex items-center justify-center w-[22px] h-[22px] [border:2px_solid_currentColor] rounded-lf-pill text-[13px] font-[800] [font-style:italic]",
  logo: "[flex-shrink:0] flex items-center justify-center w-[34px] h-[34px] rounded-lf-sm bg-[var(--vision-accent)] text-[#fff] text-[22px] font-[900] [letter-spacing:-0.04em]",
  mediaTile: "relative [flex-shrink:0] flex flex-col gap-lf-2 p-0 border-none bg-transparent text-[inherit] cursor-pointer text-left hover:[transform:scale(1.04)] hover:shadow-[0_8px_24px_rgba(0,_0,_0,_0.45)]",
  mediaTile_posterMd: "transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)]",
  navLink: "border-none bg-transparent text-[var(--vision-text-subtle)] text-lf-sm font-medium cursor-pointer whitespace-nowrap transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:text-[var(--vision-text)]",
  navLinkActive: "text-[var(--vision-text)]",
  playBtn: "inline-flex items-center gap-lf-2 p-[0_var(--lf-space-5)] h-[44px] border-none rounded-lf-sm text-lf-md font-bold cursor-pointer bg-[#fff] text-[#000] hover:bg-[rgba(255,_255,_255,_0.82)]",
  playerBar: "[flex-shrink:0] grid grid-cols-[minmax(180px,_1fr)_minmax(240px,_2fr)_minmax(120px,_1fr)] items-center gap-lf-4 p-[var(--lf-space-2)_var(--lf-space-4)] border-t border-lf-divider bg-[rgba(0,_0,_0,_0.92)] grid-cols-[1fr] gap-lf-2",
  playerControls: "flex flex-col items-center gap-lf-1 [order:-1]",
  playerExtras: "flex items-center justify-end gap-lf-2 hidden",
  playerKindTag: "text-[10px] font-bold [letter-spacing:0.06em] uppercase text-[var(--vision-accent)]",
  playerTrack: "flex items-center gap-lf-3 min-w-0",
  playerTrackMeta: "flex flex-col gap-[2px] min-w-0",
  playerTrackSubtitle: "text-[12px] text-[var(--vision-text-muted)] whitespace-nowrap overflow-hidden text-ellipsis",
  playerTrackTitle: "text-lf-sm font-semibold whitespace-nowrap overflow-hidden text-ellipsis",
  playPauseBtn: "flex items-center justify-center w-[36px] h-[36px] border-none rounded-lf-pill bg-[#fff] text-[#000] cursor-pointer",
  poster: "block [flex-shrink:0] rounded-lf-sm [background-size:cover] [background-position:center]",
  posterAmber: "bg-[linear-gradient(135deg,_#b45309,_#fbbf24_55%,_#fde68a)]",
  posterBlue: "bg-[linear-gradient(135deg,_#1d4ed8,_#60a5fa_55%,_#bfdbfe)]",
  posterCyan: "bg-[linear-gradient(135deg,_#0e7490,_#22d3ee_55%,_#a5f3fc)]",
  posterGreen: "bg-[linear-gradient(135deg,_#15803d,_#4ade80_55%,_#bbf7d0)]",
  posterHero: "rounded-none",
  posterIndigo: "bg-[linear-gradient(135deg,_#4338ca,_#818cf8_55%,_#c7d2fe)]",
  posterLg: "w-[280px] h-[158px]",
  posterLime: "bg-[linear-gradient(135deg,_#4d7c0f,_#a3e635_55%,_#d9f99d)]",
  posterMd: "w-[220px] h-[124px]",
  posterOrange: "bg-[linear-gradient(135deg,_#c2410c,_#fb923c_55%,_#fdba74)]",
  posterPink: "bg-[linear-gradient(135deg,_#be185d,_#f472b6_55%,_#fbcfe8)]",
  posterPurple: "bg-[linear-gradient(135deg,_#7e22ce,_#c084fc_55%,_#e9d5ff)]",
  posterRose: "bg-[linear-gradient(135deg,_#be123c,_#fb7185_55%,_#fda4af)]",
  posterSm: "w-[48px] h-[48px]",
  posterTeal: "bg-[linear-gradient(135deg,_#0f766e,_#2dd4bf_55%,_#99f6e4)]",
  posterViolet: "bg-[linear-gradient(135deg,_#6d28d9,_#a78bfa_55%,_#ddd6fe)]",
  primaryNav: "flex items-center gap-lf-4 min-w-0 overflow-hidden hidden",
  profileBtn: "flex items-center gap-lf-1 p-[2px_2px_2px_10px] border-none rounded-lf-sm bg-[rgba(229,_9,_20,_0.85)] text-[#fff] text-[11px] font-bold cursor-pointer",
  progressFill: "block h-full rounded-[inherit] bg-[var(--vision-accent)]",
  progressRow: "flex items-center gap-lf-2 w-full max-w-[420px]",
  progressTrack: "flex-1 h-[4px] rounded-lf-pill bg-[rgba(255,_255,_255,_0.2)]",
  rowArrow: "absolute top-0 bottom-0 z-[3] flex items-center justify-center w-[48px] border-none bg-[rgba(20,_20,_20,_0.65)] text-[#fff] cursor-pointer opacity-0 transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:bg-[rgba(20,_20,_20,_0.9)]",
  rowArrowLeft: "left-0",
  rowArrowRight: "right-0",
  rowHeader: "flex items-center justify-between gap-lf-3 p-[0_var(--lf-space-5)_var(--lf-space-2)]",
  rows: "relative z-[2] mt-[calc(-1_*_var(--lf-space-8))] p-[0_0_var(--lf-space-6)]",
  rowScrollWrap: "relative hover:opacity-100",
  rowSection: "mb-lf-5",
  rowTitle: "m-0 text-lf-lg font-bold",
  rowTrack: "flex gap-lf-2 p-[0_var(--lf-space-5)] [overflow-x:auto] [scroll-behavior:smooth] scrollbar-none",
  searchInput: "w-[0] border-none bg-transparent text-[inherit] [font:inherit] outline-none transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] w-[180px]",
  searchToggle: "flex items-center gap-lf-2 p-[0_var(--lf-space-2)] text-[var(--vision-text)] cursor-text w-[180px]",
  tileBadge: "absolute top-[88px] left-[8px] p-[2px_6px] rounded-[2px] bg-[var(--vision-accent)] text-[#fff] text-[10px] font-[800] [letter-spacing:0.04em]",
  tileDuration: "text-[12px] text-[var(--vision-text-muted)]",
  tileMeta: "flex flex-col gap-[2px] max-w-[220px]",
  tileRating: "absolute top-[8px] left-[8px] p-[2px_8px] rounded-lf-pill bg-[rgba(0,_0,_0,_0.72)] text-[#5eead4] text-[11px] font-bold",
  tileTitle: "text-lf-sm font-semibold whitespace-nowrap overflow-hidden text-ellipsis",
  timeLabel: "text-[11px] text-[var(--vision-text-muted)] [font-variant-numeric:tabular-nums]",
  top10Badge: "inline-flex items-center justify-center p-[2px_6px] rounded-[2px] bg-[var(--vision-accent)] text-[#fff] text-[10px] font-[900] [letter-spacing:0.06em]",
  top10Rank: "[flex-shrink:0] w-[72px] text-[7rem] font-[900] leading-[0.82] [letter-spacing:-0.06em] text-transparent [-webkit-text-stroke:3px_rgba(255,_255,_255,_0.55)] [text-shadow:0_0_24px_rgba(0,_0,_0,_0.35)] [transform:translateY(10px)]",
  top10Tile: "relative [flex-shrink:0] flex flex-col gap-lf-2 p-0 border-none bg-transparent text-[inherit] cursor-pointer text-left hover:[transform:scale(1.04)] hover:shadow-[0_8px_24px_rgba(0,_0,_0,_0.45)] flex-row items-end w-[280px]",
  top10Tile_posterMd: "transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] w-[180px] ml-[-12px]",
  top10Tile_tileMeta: "absolute left-[84px] bottom-[-2px] max-w-[180px]",
  topActions: "flex items-center gap-lf-3 [flex-shrink:0]",
  topBar: "absolute top-0 left-0 right-0 z-[20] w-full min-w-0 bg-[linear-gradient(180deg,_rgba(0,_0,_0,_0.72)_0%,_rgba(0,_0,_0,_0.35)_70%,_transparent_100%)]",
  topBarInner: "flex items-center justify-between gap-lf-4 w-full min-w-0 box-border p-[var(--lf-space-3)_var(--lf-space-5)]",
  workspace: "[--vision-accent:#e50914] [--vision-accent-hover:#f40612] [--vision-bg:#141414] [--vision-bg-elevated:#181818] [--vision-bg-highlight:#2f2f2f] [--vision-text:#ffffff] [--vision-text-subtle:#d2d2d2] [--vision-text-muted:#808080] relative h-full flex flex-col min-h-0 overflow-hidden bg-[var(--vision-bg)] text-[var(--vision-text)]",
};
export default styles;
