/** Tailwind class map — converted from GeneratorWorkspace.module.css */
const styles: Record<string, string> = {
  catalogDetailPreview: "max-w-[720px] m-[0_auto]",
  catalogFamily: "text-lf-xs text-lf-text-tertiary",
  catalogHeader: "flex flex-col gap-lf-2 p-lf-4 border-b border-lf-divider",
  catalogItem: "flex flex-col gap-lf-2 w-full p-lf-2 border border-solid border-lf-border-subtle rounded-lf-lg bg-lf-surface-2 text-left cursor-pointer transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:border-lf-accent-border hover:bg-lf-surface-3 border-lf-accent bg-lf-accent-muted min-w-[180px]",
  catalogItemBody: "flex flex-col gap-lf-1",
  catalogItemLabel: "text-lf-sm font-medium leading-[1.3]",
  catalogItemMeta: "flex items-center gap-lf-2 flex-wrap",
  catalogList: "flex flex-col gap-lf-2 flex-row [overflow-x:auto] pb-lf-1",
  catalogPreviewScale: "absolute top-[8px] left-[8px] w-[280px] [transform:scale(0.38)] [transform-origin:top_left] pointer-events-none",
  catalogPreviewViewport: "relative h-[72px] overflow-hidden rounded-lf-md bg-lf-surface-1 border border-solid border-lf-border-subtle",
  catalogScroll: "flex-1 min-h-0 max-h-[140px]",
  catalogSearch: "mt-lf-1",
  catalogSections: "flex flex-col gap-lf-4 p-lf-3",
  catalogSectionTitle: "p-[0_var(--lf-space-1)] text-[11px] font-semibold [letter-spacing:0.04em] uppercase text-lf-text-tertiary",
  catalogSidebar: "flex flex-col h-full min-h-0 bg-lf-surface-1 border-r border-lf-divider max-h-[220px] [border-right:none] border-b border-lf-divider",
  catalogSubtitle: "text-lf-xs text-lf-text-tertiary",
  catalogTitle: "text-lf-md font-semibold",
  composedBody: "flex flex-col gap-lf-4 p-[0_var(--lf-space-5)_var(--lf-space-5)]",
  composedCard: "overflow-hidden shadow-lf-sm",
  composedDescription: "text-lf-sm text-lf-text-secondary leading-normal",
  composedEyebrow: "text-lf-xs font-semibold [letter-spacing:0.04em] uppercase text-lf-accent",
  composedFooter: "flex gap-lf-2 p-[var(--lf-space-4)_var(--lf-space-5)] border-t border-lf-divider bg-[color-mix(in_srgb,_var(--lf-surface-2)_60%,_transparent)]",
  composedHeader: "flex flex-col gap-lf-1 p-lf-5",
  composedPriceMeta: "text-lf-sm font-medium text-lf-text-tertiary",
  composedTitle: "text-lf-md font-semibold leading-[1.3]",
  exampleButton: "p-[var(--lf-space-2)_var(--lf-space-3)] border border-solid border-lf-border-default rounded-lf-lg bg-lf-surface-1 text-lf-text-primary text-lf-sm text-left cursor-pointer transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:enabled:border-lf-accent-border hover:enabled:bg-lf-surface-2 disabled:opacity-[0.6] disabled:cursor-not-allowed",
  exampleList: "flex flex-col gap-lf-2",
  examples: "flex flex-col gap-[10px]",
  examplesLabel: "text-lf-xs font-medium text-lf-text-tertiary",
  featureItem: "flex items-center gap-lf-2 text-lf-sm text-lf-text-secondary",
  featureList: "m-0 p-0 list-none flex flex-col gap-lf-2",
  formField: "flex flex-col gap-lf-2",
  formTextarea: "min-h-[96px] p-lf-3 border border-solid border-lf-border-default rounded-lf-lg bg-lf-surface-1",
  mainGrid: "flex-1 min-w-0 min-h-0 grid grid-cols-[minmax(340px,_420px)_1fr] grid-cols-[1fr] grid-rows-[auto_1fr]",
  previewCanvas: "flex justify-center p-[var(--lf-space-2)_0]",
  previewCard: "w-full",
  previewColumn: "flex flex-col gap-lf-2 w-full",
  previewContent: "p-[var(--lf-space-4)_var(--lf-space-8)]",
  previewEmpty: "flex flex-col items-center justify-center gap-lf-3 min-h-[280px] text-lf-text-tertiary text-center",
  "previewEmpty p": "m-0 max-w-[320px] text-lf-sm leading-normal",
  previewFrame: "w-full max-w-[36rem]",
  previewMuted: "text-lf-sm text-lf-text-tertiary",
  previewPanel: "flex flex-col min-w-0 min-h-0 bg-[color-mix(in_srgb,_var(--lf-surface-2)_45%,_transparent)]",
  previewRow: "flex flex-wrap items-center gap-lf-2",
  previewScroll: "flex-1 min-h-0",
  previewTitle: "text-lf-sm font-medium whitespace-nowrap overflow-hidden text-ellipsis",
  previewTitleRow: "flex items-center gap-lf-2 min-w-0",
  previewToolbar: "flex items-center justify-between gap-lf-3 p-[var(--lf-space-2)_var(--lf-space-4)] border-b border-lf-divider bg-lf-surface-1",
  productArt: "h-[160px] rounded-lf-lg bg-[linear-gradient(135deg,_var(--lf-accent-muted),_var(--lf-surface-3))]",
  productBody: "flex flex-col gap-lf-3",
  productCard: "grid gap-lf-4",
  productPrice: "text-lf-xl font-bold",
  productPriceRow: "flex items-baseline gap-lf-2",
  profileRow: "flex items-center gap-lf-3",
  promptComposer: "flex flex-col gap-lf-3",
  promptDescription: "m-0 text-lf-sm leading-normal text-lf-text-secondary",
  promptField: "relative",
  promptHint: "m-0 text-lf-xs text-lf-text-tertiary",
  promptIntro: "flex flex-col gap-lf-2",
  promptPanel: "flex flex-col gap-lf-6 p-[var(--lf-space-4)_var(--lf-space-6)] border-r border-lf-divider border-b border-lf-divider min-h-0 overflow-auto [border-bottom:none]",
  promptSubmit: "absolute right-[10px] bottom-[10px]",
  promptTextarea: "w-full min-h-[128px] p-[var(--lf-space-3)_44px_var(--lf-space-3)_var(--lf-space-3)] border border-solid border-lf-border-default rounded-lf-lg bg-lf-surface-1 focus-visible:[outline:2px_solid_var(--lf-focus-ring)] focus-visible:[outline-offset:1px]",
  promptTitle: "m-0 text-lf-lg font-semibold [letter-spacing:-0.02em]",
  schemaBlock: "m-0 p-[var(--lf-space-4)_var(--lf-space-6)] font-mono text-[12px] leading-[1.6] text-lf-text-secondary whitespace-pre-wrap [word-break:break-word]",
  workspace: "flex h-full min-h-0 bg-lf-surface-canvas text-lf-text-primary flex-col",
};
export default styles;
