/** Tailwind class map — converted from CreatorWidget.module.css */
const styles: Record<string, string> = {
  actionColumn: "flex flex-col gap-[8px] items-center",
  actionColumnBtn: "inline-flex items-center justify-center w-[28px] h-[28px] border-none rounded-lf-pill bg-[rgba(255,_255,_255,_0.14)] text-[inherit] cursor-pointer",
  audioInfo: "text-[11px] opacity-[0.72] leading-[1.4]",
  audioMeta: "grid grid-cols-[1fr_auto] gap-lf-3 [align-items:end]",
  authorMeta: "min-w-0",
  authorName: "inline-flex items-center gap-[4px] text-lf-sm font-bold leading-[var(--lf-line-height-tight)]",
  authorRow: "flex items-center gap-lf-2 min-w-0",
  authorSub: "text-[11px] opacity-[0.72] mt-[2px] leading-[1.3] overflow-hidden text-ellipsis whitespace-nowrap",
  avatar: "inline-flex items-center justify-center w-[28px] h-[28px] rounded-lf-pill bg-[rgba(255,_255,_255,_0.18)] [border:1.5px_solid_rgba(255,_255,_255,_0.35)] text-[10px] font-bold [flex-shrink:0]",
  avatarStack: "inline-flex items-center",
  bio: "text-lf-sm opacity-[0.82] leading-[1.35]",
  body: "flex-1 flex flex-col justify-end gap-lf-2 min-h-0",
  chapterRow: "inline-flex items-center gap-[6px] text-lf-sm font-semibold mb-[4px]",
  footer: "flex items-center justify-between gap-lf-2 mt-auto",
  footer_glassBtn: "flex-1 min-w-0",
  footerActions: "flex items-center gap-lf-2 w-full",
  footerActions_glassBtn: "flex-1 min-w-0",
  glassBtn: "inline-flex items-center justify-center gap-[6px] h-[28px] p-[0_var(--lf-space-3)] border-none rounded-lf-pill bg-[rgba(255,_255,_255,_0.18)] [backdrop-filter:blur(8px)] text-[inherit] text-lf-sm font-semibold leading-none whitespace-nowrap cursor-pointer [flex-shrink:0]",
  glassBtnDark: "bg-[rgba(0,_0,_0,_0.82)] text-[#fff]",
  glassBtnPrimary: "bg-[rgba(255,_255,_255,_0.28)]",
  glassBtnSolid: "bg-[#111] text-[#fff]",
  iconBtn: "inline-flex items-center justify-center w-[36px] h-[36px] border-none rounded-[10px] bg-[#3b82f6] text-[#fff] cursor-pointer [flex-shrink:0]",
  light: "",
  light_avatar: "bg-[rgba(0,_0,_0,_0.06)] border-[rgba(0,_0,_0,_0.08)]",
  light_glassBtn: "bg-[rgba(255,_255,_255,_0.55)]",
  light_glassBtnDark: "bg-[#111] text-[#fff]",
  light_glassBtnSolid: "bg-[#111] text-[#fff]",
  light_pillMuted: "bg-[rgba(0,_0,_0,_0.06)]",
  lightText: "opacity-[0.72] text-[11px]",
  mainColumn: "flex flex-col gap-lf-3 min-h-0 flex-1",
  metric: "text-right [flex-shrink:0]",
  metricLabel: "text-[11px] opacity-[0.72] mt-[2px]",
  metricValue: "text-[28px] font-[800] leading-none [font-variant-numeric:tabular-nums]",
  pdfBtn: "inline-flex items-center gap-[6px] h-[28px] p-[0_var(--lf-space-3)] border-none rounded-lf-pill bg-[#ef4444] text-[#fff] text-lf-sm font-bold leading-none whitespace-nowrap cursor-pointer [flex-shrink:0]",
  pill: "inline-flex items-center h-[20px] p-[0_8px] rounded-lf-pill text-[10px] font-bold [letter-spacing:0.02em]",
  pillAdFree: "bg-[#ef4444] text-[#fff]",
  pillAvail: "bg-[#22c55e] text-[#052e16]",
  pillDonate: "bg-[rgba(139,_92,_246,_0.85)] text-[#fff]",
  pillLive: "bg-[#ef4444] text-[#fff]",
  pillMuted: "bg-[rgba(255,_255,_255,_0.14)] text-[inherit]",
  pillPrice: "bg-[rgba(255,_255,_255,_0.16)] text-[inherit]",
  pillRow: "flex flex-wrap items-center gap-[6px]",
  playBtn: "inline-flex items-center justify-center w-[52px] h-[52px] border-none rounded-lf-pill bg-[#ef4444] text-[#fff] cursor-pointer [flex-shrink:0] shadow-[0_8px_24px_rgba(239,_68,_68,_0.35)]",
  priceTag: "text-lf-lg font-[800]",
  quoteMark: "text-[42px] leading-[0.8] font-[800] opacity-[0.85]",
  quoteText: "text-lf-md font-bold leading-[1.35] max-w-[92%]",
  rating: "inline-flex items-center gap-[3px] font-bold",
  spacer: "flex-1",
  stackAvatar: "inline-flex items-center justify-center w-[22px] h-[22px] ml-[-6px] rounded-lf-pill [border:1.5px_solid_rgba(255,_255,_255,_0.35)] bg-[rgba(255,_255,_255,_0.2)] text-[8px] font-bold first:ml-0",
  statItem: "inline-flex items-center gap-[4px] opacity-[0.88]",
  statsRow: "flex items-center flex-wrap gap-lf-2 text-[11px]",
  title: "text-lf-lg font-[800] leading-[var(--lf-line-height-tight)]",
  topRow: "flex items-start justify-between gap-lf-3",
  verified: "inline-flex items-center justify-center w-[14px] h-[14px] rounded-lf-pill bg-[#3b82f6] text-[#fff] [flex-shrink:0]",
  waveBar: "w-[4px] rounded-lf-pill bg-[linear-gradient(180deg,_#a855f7,_#6366f1)] min-h-[8px]",
  waveform: "flex items-end justify-center gap-[3px] h-[72px] m-[var(--lf-space-2)_0]",
  withSideActions: "grid grid-cols-[1fr_auto] gap-lf-2 [align-items:start]",
};
export default styles;
