/** Tailwind class map — converted from FinanceWidget.module.css */
const styles: Record<string, string> = {
  balance: "gap-lf-3",
  balanceAmount: "text-[clamp(1.75rem,_4vw,_2.25rem)] font-[800] [letter-spacing:-0.03em] leading-none",
  balanceBody: "grid grid-cols-[minmax(0,_0.9fr)_minmax(0,_1.1fr)] gap-lf-3 flex-1 min-h-0 items-center grid-cols-[1fr]",
  balanceChange: "text-lf-sm font-bold",
  balanceHeader: "flex items-center justify-between gap-lf-2",
  balanceHighlight: "mt-lf-2 text-[clamp(2rem,_5vw,_2.75rem)] font-[800] leading-none [letter-spacing:-0.04em]",
  balanceHighlightUnit: "text-[0.45em] [vertical-align:super]",
  balanceIcon: "flex items-center justify-center w-[32px] h-[32px] rounded-[999px] bg-[#121212] text-[#fff]",
  balanceLabel: "text-[11px] font-medium opacity-[0.65]",
  balanceStatPct: "ml-auto opacity-[0.65]",
  balanceStatRow: "flex items-center gap-[6px] text-[10px] font-semibold",
  balanceStats: "flex flex-col gap-[6px]",
  balanceTitle: "text-lf-md font-[800]",
  balanceToggle: "flex p-[3px] rounded-lf-pill bg-[rgba(0,_0,_0,_0.08)] text-[8px] font-[800] [letter-spacing:0.04em]",
  "balanceToggle span": "p-[4px_8px] rounded-lf-pill opacity-[0.55]",
  balanceToggleActive: "bg-[#121212] text-[#fff] opacity-100",
  balanceTop: "flex items-center justify-between",
  currentBalance: "justify-between gap-lf-2",
  donutCenter: "absolute text-[28px] font-[800] [letter-spacing:-0.02em]",
  donutWrap: "relative flex items-center justify-center",
  expenses: "gap-lf-2",
  expensesChart: "flex-1 flex items-center justify-center",
  expensesPeriod: "text-[11px] text-[rgba(255,_255,_255,_0.45)]",
  legend: "flex flex-col gap-[6px]",
  legendDot: "w-[8px] h-[8px] rounded-[999px] [flex-shrink:0]",
  legendLeft: "flex items-center gap-lf-2",
  legendRow: "flex items-center justify-between text-[11px] text-[rgba(255,_255,_255,_0.75)]",
  lineChartWrap: "relative min-w-0",
  lineGrid: "[stroke:rgba(0,_0,_0,_0.08)] [stroke-width:1]",
  lineLabels: "flex justify-between mt-[4px] text-[8px] font-bold [letter-spacing:0.04em] opacity-[0.45]",
  lineSeries: "[stroke-linecap:round] [stroke-linejoin:round]",
  lineTooltip: "absolute top-0 right-0 p-[4px_8px] rounded-[6px] bg-[#fff] shadow-[0_4px_12px_rgba(0,_0,_0,_0.12)] text-[9px] font-[800] [letter-spacing:0.04em] text-[#121212]",
  lineTooltipStem: "[stroke:rgba(0,_0,_0,_0.25)] [stroke-width:1]",
  performance: "gap-lf-2",
  performanceBarCol: "flex-1 flex flex-col items-center gap-[6px] h-full",
  performanceBarFill: "w-full rounded-[8px_8px_4px_4px] bg-[var(--finance-lavender,_#b8a9e8)]",
  performanceBarLabel: "text-[10px] font-bold text-[rgba(255,_255,_255,_0.9)]",
  performanceBarTrack: "flex-1 w-full flex items-end rounded-[8px_8px_4px_4px] bg-[rgba(255,_255,_255,_0.04)]",
  performanceChart: "flex-1 flex items-end gap-lf-2 min-h-[80px] pt-lf-2",
  performanceFooter: "flex items-center gap-lf-2 text-[10px] font-bold [letter-spacing:0.06em] text-[rgba(255,_255,_255,_0.55)]",
  performanceHeadline: "text-[clamp(1.5rem,_3vw,_2rem)] font-[800] [letter-spacing:-0.02em] leading-[1.1]",
  performancePeriod: "text-[11px] text-[rgba(255,_255,_255,_0.45)]",
  progress: "justify-between gap-lf-3",
  progressPill: "self-start p-[6px_12px] rounded-lf-pill bg-[var(--finance-teal,_#5ec4b6)] text-[#fff] text-[11px] font-bold",
  progressTitle: "text-[11px] font-semibold opacity-[0.55]",
  progressValue: "flex items-center gap-lf-2 text-[clamp(1.5rem,_3vw,_2rem)] font-[800] [letter-spacing:-0.02em]",
  subscription: "justify-between gap-lf-3",
  subscriptionBlock: "flex flex-col gap-[2px]",
  subscriptionCount: "text-lf-lg font-bold",
  subscriptionKicker: "text-[9px] font-bold [letter-spacing:0.08em] opacity-[0.75]",
  subscriptionNext: "text-lf-sm font-semibold",
  subscriptionTotal: "text-[clamp(1.5rem,_3vw,_2rem)] font-[800] [letter-spacing:-0.02em]",
  tag: "inline-flex self-start p-[4px_10px] rounded-lf-pill bg-[var(--finance-lime,_#d4f547)] text-[#121212] text-[9px] font-[800] [letter-spacing:0.08em]",
  tagOrange: "bg-[var(--finance-orange,_#f5a623)]",
};
export default styles;
