import type { GeneratedBlock } from "longformer-ui-tailwind";

const weightTrackerValues = [
  90.2, 90.5, 91.0, 90.8, 91.2, 91.5, 91.0, 90.6, 90.1, 89.6, 89.2, 89.5, 89.8, 90.0,
  90.8, 91.2, 91.8, 92.2, 92.8, 92.4, 92.0, 91.4, 91.0, 90.4, 90.0, 89.7, 90.1, 90.6,
  91.2, 92.0, 92.6, 93.2, 92.5, 91.8,
];

/** Example card collections — grids and carousels mixing banking, finance, and fitness widgets. */
export const cardCollectionExamples: GeneratedBlock[] = [
  {
    id: "cc-intro-heading",
    type: "text",
    tone: "heading",
    text: "Card collections",
  },
  {
    id: "cc-intro-body",
    type: "text",
    tone: "muted",
    text: "Dashboard widgets can be arranged in responsive grids, snap carousels, featured layouts, and bento grids.",
  },
  {
    id: "cc-banking-grid",
    type: "cardCollection",
    title: "Responsive grid",
    subtitle: "Auto-fill layout — cards wrap as the viewport narrows.",
    layout: "grid",
    itemHeight: 260,
    items: [
      {
        id: "bg1",
        kind: "banking",
        variant: "monthlyRevenue",
        amount: "$12,890.67",
        period: "14 Jan - 13 Feb, 2025",
        thisMonth: [42, 55, 48, 68],
        previousMonth: [38, 44, 52, 58],
      },
      {
        id: "bg2",
        kind: "banking",
        variant: "transactions",
        groups: [
          {
            label: "TODAY",
            items: [{ id: "t1", title: "Movie Tickets", date: "24 Apr", amount: "$12.5", icon: "🎬" }],
          },
        ],
      },
      {
        id: "bg3",
        kind: "banking",
        variant: "exchange",
        amount: "$285.72",
        available: "$18,375.94",
        rate: "1 USD = 0.88 EUR",
        total: "$294.29",
      },
      {
        id: "bg4",
        kind: "banking",
        variant: "familySaving",
        amount: "$64,705.882",
        subtitle: "You're halfway to your target",
        values: [4, 6, 5, 8, 7, 9, 6, 8, 7, 5, 6, 9],
        highlightIndex: 6,
        tooltip: { label: "Highest", value: "$1,258.73" },
      },
    ],
  },
  {
    id: "cc-finance-dense",
    type: "cardCollection",
    title: "Dense grid",
    subtitle: "Tighter columns for compact finance readouts.",
    layout: "denseGrid",
    itemHeight: 220,
    items: [
      {
        id: "fd1",
        kind: "finance",
        variant: "expenses",
        total: "32K",
        period: "In the past 7 days",
        segments: [
          { label: "Relax", percent: 54, color: "teal" },
          { label: "Food", percent: 27, color: "lavender" },
          { label: "Transport", percent: 12, color: "lime" },
          { label: "Pets", percent: 7, color: "orange" },
        ],
      },
      {
        id: "fd2",
        kind: "finance",
        variant: "currentBalance",
        amount: "$ 1248",
        change: "+3,51 %",
      },
      {
        id: "fd3",
        kind: "finance",
        variant: "progress",
        value: "72,5%",
        pill: "+0,10 (+0,13%)",
      },
      {
        id: "fd4",
        kind: "finance",
        variant: "subscription",
        count: "4 subs",
        total: "$25.99",
        nextPayment: "Spotify — $9.99",
      },
      {
        id: "fd5",
        kind: "finance",
        variant: "performance",
        headline: "+280%",
        period: "In the past 30 days",
        bars: [
          { label: "12%", value: 12 },
          { label: "78%", value: 78 },
          { label: "62%", value: 62 },
          { label: "95%", value: 95 },
        ],
      },
    ],
  },
  {
    id: "cc-fitness-carousel",
    type: "cardCollection",
    title: "Scroll carousel",
    subtitle: "Horizontal row with edge fades — free scrolling.",
    layout: "carousel",
    itemHeight: 240,
    items: [
      { id: "fc1", kind: "fitness", variant: "hiking", distance: "100", unit: "m" },
      { id: "fc2", kind: "fitness", variant: "running", date: "10.03", distance: "10.00", unit: "KM" },
      { id: "fc3", kind: "fitness", variant: "gymStreak", completed: 3, total: 7, dots: [true, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false] },
      { id: "fc4", kind: "fitness", variant: "stepsStreak", steps: "5,548", streak: "1 DAY" },
      { id: "fc5", kind: "fitness", variant: "workoutPhoto", totalTime: "6H 20" },
    ],
  },
  {
    id: "cc-mixed-snap",
    type: "cardCollection",
    title: "Snap carousel",
    subtitle: "Scroll-snap slides — one card settles at a time.",
    layout: "snapCarousel",
    itemHeight: 280,
    items: [
      {
        id: "sc1",
        kind: "banking",
        variant: "exchange",
        amount: "$285.72",
        available: "$18,375.94",
        rate: "1 USD = 0.88 EUR",
        tax: "$5.71",
        fee: "$2.86",
        total: "$294.29",
      },
      {
        id: "sc2",
        kind: "banking",
        variant: "creditCard",
        number: "4567 - 1234 - 5678 - 9012",
        brand: "VISA",
        name: "Samantha William",
        expiry: "May 2028",
        transactionLimit: "$500",
        dailyLimit: "$1,000",
      },
      {
        id: "sc3",
        kind: "fitness",
        variant: "heartRate",
        average: 124,
        rangeMin: 56,
        rangeMax: 172,
        chartValues: [42, 68, 55, 92, 78, 110, 88, 124, 98, 72, 58, 84],
      },
      {
        id: "sc4",
        kind: "finance",
        variant: "balance",
        highlightValue: "5",
        highlightUnit: "%",
        series: [
          { id: "a", color: "lavender", label: "12450", percent: "40%", values: [42, 48, 52, 58, 55, 62, 68] },
          { id: "b", color: "teal", label: "11252", percent: "11%", values: [38, 44, 46, 50, 48, 54, 60] },
        ],
        tooltip: { label: "PROF./H", value: "12 450" },
      },
    ],
  },
  {
    id: "cc-featured",
    type: "cardCollection",
    title: "Featured layout",
    subtitle: "First card spans a 2×2 hero slot; others fill the grid.",
    layout: "featured",
    itemHeight: 220,
    items: [
      {
        id: "ft1",
        kind: "banking",
        variant: "familySaving",
        amount: "$64,705.882",
        subtitle: "You're halfway to your target",
        values: [4, 6, 5, 8, 7, 9, 6, 8, 7, 5, 6, 9],
        highlightIndex: 6,
        tooltip: { label: "Highest", value: "$1,258.73" },
      },
      { id: "ft2", kind: "finance", variant: "currentBalance", amount: "$ 1248", change: "+3,51 %" },
      { id: "ft3", kind: "fitness", variant: "stepsStreak", steps: "5,548", streak: "1 DAY" },
      { id: "ft4", kind: "finance", variant: "currentBalance", amount: "$ 1248", change: "+3,51 %" },
      { id: "ft5", kind: "finance", variant: "progress", value: "72,5%", pill: "+0,10 (+0,13%)" },
    ],
  },
  {
    id: "cc-bento",
    type: "cardCollection",
    title: "Bento grid",
    subtitle: "Mixed spans — wide and tall slots in a 4-column mosaic.",
    layout: "bento",
    itemHeight: 200,
    items: [
      {
        id: "bn1",
        kind: "banking",
        variant: "monthlyRevenue",
        span: "hero",
        amount: "$12,890.67",
        period: "14 Jan - 13 Feb, 2025",
        thisMonth: [42, 55, 48, 68],
        previousMonth: [38, 44, 52, 58],
      },
      {
        id: "bn2",
        kind: "fitness",
        variant: "weightTracker",
        span: "wide",
        change: "-0.5",
        baseline: 89,
        threshold: 92,
        max: 94,
        values: weightTrackerValues,
      },
      { id: "bn3", kind: "finance", variant: "subscription", count: "4 subs", total: "$25.99", nextPayment: "Spotify — $9.99" },
      { id: "bn4", kind: "fitness", variant: "hiking", distance: "100", unit: "m" },
      {
        id: "bn5",
        kind: "finance",
        variant: "performance",
        span: "wide",
        headline: "+280%",
        period: "In the past 30 days",
        bars: [
          { label: "12%", value: 12 },
          { label: "78%", value: 78 },
          { label: "95%", value: 95 },
        ],
      },
    ],
  },
  {
    id: "cc-strip",
    type: "cardCollection",
    title: "Compact strip",
    subtitle: "Short-height carousel for quick-scan KPI tiles.",
    layout: "strip",
    itemHeight: 168,
    items: [
      { id: "st1", kind: "finance", variant: "currentBalance", amount: "$ 1248", change: "+3,51 %" },
      { id: "st2", kind: "fitness", variant: "gymStreak", completed: 3, total: 7, dots: [true, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false] },
      { id: "st3", kind: "finance", variant: "progress", value: "72,5%", pill: "+0,10 (+0,13%)" },
      { id: "st4", kind: "finance", variant: "progress", value: "72,5%", pill: "+0,10 (+0,13%)" },
      { id: "st5", kind: "fitness", variant: "running", date: "10.03", distance: "10.00", unit: "KM" },
      { id: "st6", kind: "finance", variant: "currentBalance", amount: "$ 1248", change: "+3,51 %" },
    ],
  },
  {
    id: "cc-wide",
    type: "cardCollection",
    title: "Wide grid",
    subtitle: "Roomier columns for charts and detailed cards.",
    layout: "wideGrid",
    itemHeight: 280,
    items: [
      {
        id: "wg1",
        kind: "fitness",
        variant: "heartRate",
        average: 124,
        rangeMin: 56,
        rangeMax: 172,
        chartValues: [42, 68, 55, 92, 78, 110, 88, 124, 98, 72, 58, 84, 96, 118, 102, 76],
      },
      {
        id: "wg2",
        kind: "fitness",
        variant: "progressTracker",
        rows: ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"],
        columns: ["GYM", "HIKING", "YOGA", "RUNNING", "SLEEP"],
        cells: [
          true, true, false, true, false,
          true, false, true, false, true,
          false, true, true, true, false,
          true, true, false, false, true,
          false, false, true, true, true,
          true, false, false, true, false,
          false, true, true, false, true,
        ],
      },
      {
        id: "wg3",
        kind: "finance",
        variant: "balance",
        highlightValue: "5",
        highlightUnit: "%",
        series: [
          { id: "a", color: "lavender", label: "12450", percent: "40%", values: [42, 48, 52, 58, 55, 62, 68] },
          { id: "b", color: "teal", label: "11252", percent: "11%", values: [38, 44, 46, 50, 48, 54, 60] },
        ],
        tooltip: { label: "PROF./H", value: "12 450" },
      },
    ],
  },
];
