import type { ExtensionsWorkspaceData } from "longformer-ui-tailwind";

export const extensionsWorkspaceData: ExtensionsWorkspaceData = {
  workspaceName: "Extensions",
  userName: "Alex Morgan",
  navItems: [
    { id: "agent-skills", label: "Agent Skills", icon: "sparkles", view: "agent-skills", badge: "6" },
    { id: "plugins", label: "Plugins", icon: "package", view: "plugins", badge: "12" },
    { id: "prompts", label: "Prompts", icon: "chat", view: "prompts" },
    { id: "app-templates", label: "App Templates", icon: "app-window", view: "app-templates" },
  ],
  agentSkills: [
    {
      id: "skill-code-review",
      name: "Code Review",
      description: "Structured PR review with security, performance, and style checks before merge.",
      author: "Longformer",
      enabled: true,
      tags: ["engineering", "quality"],
      triggerCount: 142,
      updatedAt: "Jun 28",
    },
    {
      id: "skill-figma",
      name: "Figma Design-to-Code",
      description: "Fetch design context from Figma and translate nodes into production-ready components.",
      author: "Longformer",
      enabled: true,
      tags: ["design", "frontend"],
      triggerCount: 89,
      updatedAt: "Jun 25",
    },
    {
      id: "skill-commit",
      name: "Commit Messages",
      description: "Generate concise commit messages from staged diffs following repository conventions.",
      author: "Community",
      enabled: true,
      tags: ["git", "workflow"],
      triggerCount: 256,
      updatedAt: "Jun 20",
    },
    {
      id: "skill-pr",
      name: "Pull Request Author",
      description: "Draft PR summaries with test plans and risk notes from branch diffs.",
      author: "Community",
      enabled: false,
      tags: ["git", "collaboration"],
      triggerCount: 34,
      updatedAt: "Jun 15",
    },
    {
      id: "skill-deploy",
      name: "Deploy Checklist",
      description: "Pre-flight checks for staging and production deployments across Vercel and Docker.",
      author: "Alex Morgan",
      enabled: true,
      tags: ["devops", "server"],
      triggerCount: 18,
      updatedAt: "Jun 10",
    },
    {
      id: "skill-docs",
      name: "Literate Documentation",
      description: "Write PBRT-style literate code with concise explainer docs woven into every module.",
      author: "Alex Morgan",
      enabled: false,
      tags: ["docs", "quality"],
      triggerCount: 7,
      updatedAt: "May 30",
    },
  ],
  plugins: [
    {
      id: "plugin-figma",
      name: "Figma",
      description: "Read designs, screenshots, and variables from Figma files via MCP.",
      author: "Figma",
      version: "1.4.2",
      installed: true,
      icon: "layers",
      category: "Design",
      rating: 4.8,
    },
    {
      id: "plugin-github",
      name: "GitHub",
      description: "Issues, pull requests, checks, and repository operations from the workspace.",
      author: "GitHub",
      version: "2.1.0",
      installed: true,
      icon: "code",
      category: "Development",
      rating: 4.9,
    },
    {
      id: "plugin-linear",
      name: "Linear",
      description: "Sync issues, cycles, and project updates with your Linear workspace.",
      author: "Linear",
      version: "0.9.3",
      installed: true,
      icon: "target",
      category: "Project Management",
      rating: 4.7,
    },
    {
      id: "plugin-slack",
      name: "Slack",
      description: "Send messages, read channels, and trigger workflows from Slack.",
      author: "Slack",
      version: "1.2.1",
      installed: false,
      icon: "hash",
      category: "Communication",
      rating: 4.5,
    },
    {
      id: "plugin-datadog",
      name: "Datadog",
      description: "Query metrics, logs, and monitors for production observability.",
      author: "Datadog",
      version: "0.6.0",
      installed: false,
      icon: "monitor",
      category: "Observability",
      rating: 4.4,
    },
    {
      id: "plugin-notion",
      name: "Notion",
      description: "Read and write pages, databases, and blocks in your Notion workspace.",
      author: "Notion",
      version: "1.0.8",
      installed: true,
      icon: "notebook",
      category: "Knowledge",
      rating: 4.6,
    },
    {
      id: "plugin-browser",
      name: "Browser Automation",
      description: "Navigate, snapshot, and interact with web pages for testing and scraping.",
      author: "Longformer",
      version: "0.3.5",
      installed: true,
      icon: "globe",
      category: "Automation",
      rating: 4.3,
    },
    {
      id: "plugin-postgres",
      name: "PostgreSQL",
      description: "Run read-only SQL queries against connected database instances.",
      author: "Community",
      version: "0.2.0",
      installed: false,
      icon: "terminal",
      category: "Data",
      rating: 4.2,
    },
  ],
  prompts: [
    {
      id: "prompt-refactor",
      title: "Safe Refactor",
      body: "Refactor this code to improve readability and maintainability. Preserve behavior, minimize scope, and match existing conventions.",
      category: "Engineering",
      usageCount: 87,
      starred: true,
      updatedAt: "Jul 1",
    },
    {
      id: "prompt-debug",
      title: "Debug Assistant",
      body: "Investigate this bug systematically. Gather evidence, form hypotheses, and propose the smallest fix that addresses the root cause.",
      category: "Engineering",
      usageCount: 64,
      starred: true,
      updatedAt: "Jun 29",
    },
    {
      id: "prompt-copy",
      title: "UX Copy Polish",
      body: "Rewrite this UI copy to be clear, concise, and accessible. Use plain language and active voice.",
      category: "Design",
      usageCount: 31,
      updatedAt: "Jun 27",
    },
    {
      id: "prompt-meeting",
      title: "Meeting Summary",
      body: "Summarize this transcript into decisions, action items with owners, and open questions.",
      category: "Productivity",
      usageCount: 52,
      starred: true,
      updatedAt: "Jun 25",
    },
    {
      id: "prompt-spec",
      title: "Feature Spec",
      body: "Draft a feature spec with problem statement, user stories, acceptance criteria, and out-of-scope items.",
      category: "Product",
      usageCount: 19,
      updatedAt: "Jun 22",
    },
    {
      id: "prompt-test",
      title: "Test Plan",
      body: "Create a test plan with happy path, edge cases, and regression checks for this change.",
      category: "Quality",
      usageCount: 41,
      updatedAt: "Jun 18",
    },
  ],
  appTemplates: [
    {
      id: "template-chat",
      name: "Chat Workspace",
      description: "Multi-model chat with context panel, file attachments, and usage tracking.",
      author: "Longformer",
      icon: "chat",
      stack: ["React", "TypeScript", "CSS Modules"],
      installs: 2840,
      featured: true,
    },
    {
      id: "template-dashboard",
      name: "Analytics Dashboard",
      description: "KPI cards, charts, and filterable data tables with dark mode support.",
      author: "Longformer",
      icon: "grid",
      stack: ["React", "Recharts", "TypeScript"],
      installs: 1920,
      featured: true,
    },
    {
      id: "template-kanban",
      name: "Kanban Board",
      description: "Drag-and-drop task board with columns, labels, and sprint views.",
      author: "Community",
      icon: "layers",
      stack: ["React", "dnd-kit"],
      installs: 1560,
    },
    {
      id: "template-docs",
      name: "Documentation Site",
      description: "Sidebar navigation, full-text search, and MDX content pages.",
      author: "Community",
      icon: "bookmark",
      stack: ["Next.js", "MDX"],
      installs: 980,
    },
    {
      id: "template-form",
      name: "Form Builder",
      description: "Dynamic form fields with validation, conditional logic, and submission handling.",
      author: "Community",
      icon: "edit",
      stack: ["React", "Zod"],
      installs: 720,
    },
    {
      id: "template-server",
      name: "Deploy Console",
      description: "Project list, deployment history, and server monitoring inspired by Vercel.",
      author: "Longformer",
      icon: "terminal",
      stack: ["React", "TypeScript"],
      installs: 640,
      featured: true,
    },
  ],
};
