import type { GeneratedSurfaceSchema } from "longformer-ui-tailwind";
import { cardCollectionExamples } from "./card-collections";

export const generatedSchema: GeneratedSurfaceSchema = {
  id: "surface-1",
  blocks: [
    ...cardCollectionExamples,
    { id: "g1", type: "text", tone: "heading", text: "Here's what I found and set up" },
    {
      id: "g2",
      type: "text",
      tone: "muted",
      text: "Generated from a single agent turn — every block below is plain data, rendered by the kit.",
    },
    {
      id: "g3",
      type: "cardGrid",
      title: "Suggested next steps",
      cards: [
        { id: "c1", title: "Add rate limiting", description: "Gateway accepts unbounded message sizes.", icon: "terminal", badge: "Risk" },
        { id: "c2", title: "Split App.tsx", description: "One file mixes input, rendering, and HUD logic.", icon: "code" },
        { id: "c3", title: "Add assertNever", description: "Dispatch switch falls through silently.", icon: "check", badge: "Quick win" },
      ],
    },
    {
      id: "g3b",
      type: "mediaCards",
      title: "Stay ideas for the offsite",
      cards: [
        {
          id: "m1",
          tone: "accent",
          title: "Santorini Villa",
          description: "Private infinity pool with a sunset view over the Aegean.",
          badges: [
            { icon: "star", label: "4.8" },
            { label: "3 night stay" },
          ],
          actionLabel: "Reserve now",
        },
        {
          id: "m2",
          tone: "success",
          title: "Kanazawa Grand Inn",
          description: "28% below usual rate, 5 minutes from the station.",
          badges: [
            { icon: "star", label: "4.6" },
            { label: "$48/night" },
          ],
          actionLabel: "Book now",
        },
        {
          id: "m3",
          tone: "warning",
          title: "Karra Loft",
          description: "3 bed, 2 bath tokenized listing with a 26.3% projected IRR.",
          badges: [{ label: "Active" }],
          actionLabel: "View listing",
        },
      ],
    },
    {
      id: "g3c",
      type: "listingCards",
      title: "Open roles matching this project",
      cards: [
        {
          id: "l1",
          avatarName: "Amazon",
          title: "Senior UI/UX Designer",
          subtitle: "Amazon · Posted 5 days ago",
          tags: ["Part-time", "Senior level"],
          price: "$120",
          priceMeta: "/hr · San Francisco, CA",
          actionLabel: "Apply now",
          saved: false,
        },
        {
          id: "l2",
          avatarName: "Google",
          title: "Graphic Designer",
          subtitle: "Google · Posted 30 days ago",
          tags: ["Full-time", "Flexible schedule"],
          price: "$150–220k",
          priceMeta: "Mountain View, CA",
          actionLabel: "Apply now",
          saved: true,
        },
        {
          id: "l3",
          icon: "layers",
          title: "Graham Crackers",
          subtitle: "HQ Level 6 · Plot #965",
          tags: ["MartinGarrix", "Level 14"],
          price: "212,234.43",
          priceMeta: "coins",
          actionLabel: "Buy base",
        },
      ],
    },
    {
      id: "g3d",
      type: "statCards",
      title: "Today's vitals",
      cards: [
        {
          id: "s1",
          icon: "check",
          label: "Freud Score",
          value: "80",
          caption: "Healthy",
          tone: "success",
          visualization: { type: "ring", percent: 80 },
        },
        {
          id: "s2",
          icon: "chat",
          label: "Mood",
          value: "Sad",
          tone: "warning",
          visualization: { type: "bars", values: [2, 4, 3, 6, 8, 5, 3, 2] },
        },
        {
          id: "s3",
          icon: "calendar",
          label: "Health Journal",
          value: "31/365",
          tone: "accent",
          visualization: { type: "dots", total: 35, filled: 9 },
        },
      ],
    },
    {
      id: "g3e",
      type: "metricChartCards",
      title: "Portfolio",
      cards: [
        {
          id: "mc1",
          value: "$10,182.01",
          change: {
            amount: "+$1,234.11",
            percent: "+1.01%",
            caption: "All Time",
            direction: "up",
          },
          chartValues: [42, 48, 44, 52, 50, 58, 55, 62, 60, 68, 64, 72],
          timeframes: ["3H", "1D", "1W", "1M", "1Y", "5Y"],
          activeTimeframe: "3H",
        },
      ],
    },
    {
      id: "g3f",
      type: "filterSections",
      title: "Filter",
      sections: [
        {
          id: "fs1",
          label: "Market Cap",
          options: [
            { id: "small", label: "Small", selected: true },
            { id: "big", label: "Big" },
            { id: "large", label: "Large" },
          ],
        },
        {
          id: "fs2",
          label: "Performance",
          options: [
            { id: "gainers", label: "Gainers", selected: true },
            { id: "losers", label: "Losers" },
          ],
        },
        {
          id: "fs3",
          label: "P/E Ratio",
          options: [
            { id: "low", label: "Low", selected: true },
            { id: "medium", label: "Medium" },
            { id: "high", label: "High" },
          ],
        },
      ],
    },
    {
      id: "g3g",
      type: "activityCards",
      title: "Transaction history",
      cards: [
        {
          id: "a1",
          avatarName: "Apple",
          title: "Buy Apple Inc (AAPL)",
          status: { label: "Completed", tone: "success" },
          category: "Buy",
          amount: "$1,400",
          time: "3:15 PM",
        },
        {
          id: "a2",
          avatarName: "Microsoft",
          title: "Sell Microsoft Corp (MSFT)",
          status: { label: "Failed", tone: "danger" },
          category: "Sell",
          amount: "$820",
          time: "11:02 AM",
        },
        {
          id: "a3",
          icon: "layers",
          title: "Deposit to wallet",
          status: { label: "Pending", tone: "warning" },
          category: "Deposit",
          amount: "$500",
          time: "9:41 AM",
        },
      ],
    },
    {
      id: "g3h",
      type: "selectionTiles",
      title: "Which category do you prefer?",
      tiles: [
        { id: "t1", label: "Pop", selected: true, size: "tall" },
        { id: "t2", label: "Rock", size: "sm" },
        { id: "t3", label: "Epic", selected: true, size: "sm" },
        { id: "t4", label: "Lo-fi", size: "sm" },
        { id: "t5", label: "Symphonic", size: "wide" },
        { id: "t6", label: "Deep", selected: true, size: "sm" },
        { id: "t7", label: "Jazz", size: "sm" },
        { id: "t8", label: "Electronic", size: "wide" },
      ],
    },
    {
      id: "g3i",
      type: "timelineSteps",
      title: "Creation mode",
      steps: [
        { id: "st1", label: "Foundation", completed: true },
        { id: "st2", label: "Motive", completed: true },
        { id: "st3", label: "Timer", completed: true },
        { id: "st4", label: "Control", completed: true },
        { id: "st5", label: "Info", completed: true, showConnector: false },
      ],
    },
    {
      id: "g3j",
      type: "routeCards",
      title: "Trip route",
      cards: [
        {
          id: "r1",
          pickup: { label: "Pickup", address: "Mall Living World, Exit Gate" },
          dropoff: { label: "Drop off", address: "Pasar Buah, Meat Spot" },
        },
      ],
    },
    {
      id: "g3k",
      type: "profileSummaryCards",
      title: "Driver details",
      cards: [
        {
          id: "p1",
          avatarName: "Ashley Young",
          title: "Ashley Young",
          subtitle: "Driver",
          rating: "4.8",
          rows: [
            {
              icon: "smartphone",
              title: "Honda Brio",
              subtitle: "Standard Car",
              trailing: "XY23X5",
              trailingMeta: "License Plate No.",
            },
          ],
        },
      ],
    },
    {
      id: "g3l",
      type: "sessionCards",
      title: "Therapy scheduling",
      cards: [
        {
          id: "ss1",
          headline: "Next session in 5 minutes",
          avatarName: "Richard Hammer",
          title: "Richard Hammer",
          subtitle: "Attention deficit disorder",
          tags: ["Bad sleep", "Sociopathy", "Concentration issues"],
        },
      ],
    },
    {
      id: "g3m",
      type: "scheduleSlots",
      title: "Upcoming sessions for today",
      slots: [
        { id: "sl1", name: "Ellen Fisher", mode: "Online", timeRange: "10:00–11:30", tone: "success" },
        { id: "sl2", name: "Joe Stivenson", mode: "Online", timeRange: "15:00–16:00", tone: "warning" },
      ],
    },
    {
      id: "g3n",
      type: "insightCards",
      title: "Recommendations",
      cards: [
        {
          id: "i1",
          label: "Recommendation",
          title: "Revise meeting order",
          description: "Start later, rest longer, finish earlier",
        },
      ],
    },
    {
      id: "g3o",
      type: "timezoneCards",
      title: "Remote team clocks",
      cards: [
        {
          id: "tz1",
          rows: [
            { city: "Prague, CZ", time: "02:02", period: "PM", badge: "Local" },
            { city: "New York, US", time: "06:02", period: "PM", offset: "-7H" },
          ],
        },
      ],
    },
    {
      id: "g3p",
      type: "meetingCountdownCards",
      title: "Standup",
      cards: [
        {
          id: "m1",
          memberNames: ["Alex", "Jordan", "Sam", "Riley"],
          memberCount: "13 members",
          countdown: "Next Meeting in 00:19 min",
          actionLabel: "Start recording",
        },
      ],
    },
    {
      id: "g3q",
      type: "eventCards",
      title: "Today's classes",
      cards: [
        {
          id: "e1",
          title: "Grid Systems",
          startTime: "02:00",
          endTime: "03:30",
          timeLeft: { icon: "sparkles", label: "Time left 5h 39 min" },
        },
        {
          id: "e2",
          title: "Web Typography",
          startTime: "04:00",
          endTime: "05:30",
          timeLeft: { icon: "calendar", label: "Time left 7h 29 min" },
        },
      ],
    },
    {
      id: "g3r",
      type: "deviceCards",
      title: "Favorite actions",
      cards: [
        {
          id: "d1",
          title: "Front station",
          subtitle: "Garage",
          status: "70%",
          statusTone: "success",
          icon: "battery",
          iconTone: "success",
          progress: 70,
        },
        {
          id: "d2",
          title: "Shutter",
          subtitle: "Kitchen",
          icon: "minus",
          iconTone: "warning",
          progress: 30,
          progressSide: "right",
        },
        {
          id: "d3",
          title: "Light",
          subtitle: "Living Room",
          icon: "sun",
          iconTone: "warning",
          progress: 70,
        },
        {
          id: "d4",
          title: "Solar Panel",
          subtitle: "Roof",
          status: "8kw/h",
          statusTone: "accent",
          icon: "grid",
          iconTone: "accent",
          progress: 66,
        },
      ],
    },
    {
      id: "g3s",
      type: "expenseCards",
      title: "Expenses",
      cards: [
        { id: "x1", tone: "success", category: "Taxi", merchant: "Uber Inc.", amount: "-$35", avatarName: "Uber" },
        { id: "x2", tone: "warning", category: "Movie", merchant: "Netflix", amount: "-$15", avatarName: "Netflix" },
        { id: "x3", tone: "accent", category: "Design", merchant: "Dribbble Inc.", amount: "-$35", avatarName: "Dribbble" },
        { id: "x4", tone: "danger", category: "Food", merchant: "McDonald's", amount: "-$109", avatarName: "McDonald's" },
        { id: "x5", tone: "neutral", category: "Games", merchant: "Play Station", amount: "-$281.50", avatarName: "PlayStation" },
      ],
    },
    {
      id: "g3t",
      type: "courseCards",
      title: "Learning paths",
      cards: [
        { id: "cr1", variant: "pill", title: "Path", subtitle: "Unlock the Grid", tone: "neutral" },
        { id: "cr2", variant: "tile", title: "Design Odyssey", subtitle: "Brief 001", instructor: "by Maksym B.", progress: "1/3", tone: "warning" },
        {
          id: "cr3",
          variant: "hero",
          title: "UX Lab: Motion Edition",
          instructor: "Joseph Smith",
          progress: "2/3",
          actionLabel: "Join now",
          tone: "accent",
        },
      ],
    },
    {
      id: "g3u",
      type: "phoneHomeScreen",
      title: "Phone home screen",
      pageCount: 2,
      carrier: "No Service",
    },
    {
      id: "g3v",
      type: "assetShowcaseCards",
      title: "Featured assets",
      cards: [
        {
          id: "as1",
          title: "Elegant Pink Floral Wallpaper",
          description: "Soft abstract waves for desktop and mobile.",
          imageTone: "accent",
          stats: [
            { icon: "thumbs-up", label: "2.4k" },
            { icon: "message-square", label: "128" },
            { icon: "download", label: "890" },
          ],
          creatorName: "Miriam Martinez",
          creatorMeta: "12.4k followers",
          actionLabel: "Download",
        },
      ],
    },
    {
      id: "g3w",
      type: "cryptoMarketCards",
      title: "Markets",
      cards: [
        {
          id: "cm1",
          rows: [
            { symbol: "BTC", name: "Bitcoin", price: "$67,420", changePercent: "+2.4%", direction: "up", tone: "warning", chartValues: [40, 42, 38, 44, 48, 46, 52, 50] },
            { symbol: "ETH", name: "Ethereum", price: "$3,412", changePercent: "-0.8%", direction: "down", tone: "neutral", chartValues: [50, 48, 46, 44, 42, 40, 38, 36] },
          ],
        },
      ],
    },
    {
      id: "g3x",
      type: "vpnConnectionCards",
      title: "VPN",
      cards: [
        {
          id: "vpn1",
          active: true,
          statusLabel: "On",
          location: "France",
          ipAddress: "192.168.1.42",
          timeConnected: "2h 14m",
          download: { label: "Download", value: "842 Mbps", chartValues: [20, 28, 24, 32, 36, 30, 38, 42] },
          upload: { label: "Upload", value: "128 Mbps", chartValues: [12, 16, 14, 18, 20, 16, 22, 24] },
        },
      ],
    },
    {
      id: "g3y",
      type: "calendarScheduleCards",
      title: "Schedule",
      cards: [
        {
          id: "cal1",
          monthLabel: "April 2023",
          days: [
            { value: "", muted: true },
            { value: "", muted: true },
            { value: "", muted: true },
            { value: "", muted: true },
            { value: "", muted: true },
            { value: 1 },
            { value: 2 },
            { value: 19, selected: true },
            { value: 20 },
            { value: 21 },
          ],
          events: [
            { title: "Yoga Class", timeRange: "8:00–9:00 AM", tone: "accent" },
            { title: "Gym", timeRange: "6:00–7:00 PM", tone: "success" },
          ],
        },
      ],
    },
    {
      id: "g3z",
      type: "batteryStatusCards",
      cards: [{ id: "bat1", percent: "63%", powerMode: "Balanced", timeRemaining: "7h 36m", tone: "success" }],
    },
    {
      id: "g3aa",
      type: "musicPlayerCards",
      cards: [
        {
          id: "mp1",
          title: "Les Muses: Taylor",
          artist: "Taylor Swift",
          sourceLabel: "Spotify",
          progress: 42,
          elapsed: "1:24",
          duration: "3:18",
          playing: true,
        },
      ],
    },
    {
      id: "g3ac",
      type: "videoPlayerCards",
      cards: [
        {
          id: "vp1",
          elapsed: "1:43",
          duration: "1:43",
          progress: 100,
          ended: true,
          imageTone: "neutral",
        },
      ],
    },
    {
      id: "g3ab",
      type: "newsFeedCards",
      cards: [
        {
          id: "nf1",
          source: "CNN News",
          headline: "Biden says banking system is safe after SVB collapse",
          excerpt: "President Biden sought to reassure Americans that the banking system remains secure.",
          imageTone: "accent",
          stats: [{ icon: "thumbs-up", label: "1.2k" }, { icon: "message-square", label: "342" }],
        },
      ],
    },
    {
      id: "g3ac",
      type: "taskChecklistCards",
      cards: [
        {
          id: "tc1",
          tabs: [
            { id: "design", label: "Design" },
            { id: "uiux", label: "UI/UX" },
            { id: "website", label: "Website" },
          ],
          title: "Design Website",
          items: [
            { label: "Create wireframes", completed: true },
            { label: "Build component library", completed: true },
            { label: "Implement responsive layout", completed: false },
          ],
          progress: 70,
          memberNames: ["Alex", "Jordan", "Sam"],
          actionLabel: "Add Task",
        },
      ],
    },
    {
      id: "g3ad",
      type: "translationCards",
      cards: [
        {
          id: "tr1",
          panels: [
            { language: "English", flag: "🇺🇸", text: "The quick brown fox jumps over the lazy dog." },
            { language: "French", flag: "🇫🇷", text: "Le rapide renard brun saute par-dessus le chien paresseux." },
          ],
        },
      ],
    },
    {
      id: "g3ae",
      type: "colorPaletteCards",
      cards: [
        {
          id: "cp1",
          swatches: [
            { color: "#111827", label: "Black" },
            { color: "#1e3a8a", label: "Blue" },
            { color: "#14b8a6", label: "Teal" },
            { color: "#ec4899", label: "Pink" },
            { color: "#f97316", label: "Orange" },
          ],
        },
      ],
    },
    {
      id: "g3af",
      type: "designCards",
      title: "Live activities",
      cards: [
        {
          id: "dc1",
          variant: "flight",
          origin: "SFO",
          destination: "YEG",
          departureTime: "2:10 PM",
          arrivalTime: "6:42 PM",
          status: "Arrives in 47m",
          progress: 62,
        },
        {
          id: "dc2",
          variant: "order",
          status: "Picking up order",
          eta: "5:50",
          progress: 45,
          driverName: "Dave",
        },
        {
          id: "dc3",
          variant: "glucose",
          value: "7.2",
          unit: "mmol/L",
          trend: "down",
          chartValues: [42, 58, 72, 64, 80, 68, 92],
          labels: ["1PM", "2PM", "NOW"],
        },
        {
          id: "dc4",
          variant: "delivery",
          statusLabel: "Status",
          status: "Out for delivery",
          eta: "15–30 min",
        },
        {
          id: "dc5",
          variant: "espresso",
          timer: "16s",
          chartValues: [24, 48, 72, 56, 88, 64, 40, 72, 52],
        },
        {
          id: "dc6",
          variant: "iss",
          countdown: "in 15 min",
        },
        {
          id: "dc7",
          variant: "workout",
          elapsed: "24:15",
          distance: "1.8 MI",
          chartValues: [32, 48, 72, 56, 88, 64, 80, 52, 68],
        },
        {
          id: "dc8",
          variant: "race",
          sector: "Sector 2",
          progress: 38,
        },
        {
          id: "dc9",
          variant: "transit",
          stops: [
            { label: "Harajuku" },
            { label: "Shibuya", active: true },
            { label: "Ebisu" },
          ],
        },
        {
          id: "dc10",
          variant: "heartRate",
          value: "82",
          unit: "bpm",
          chartValues: [28, 52, 88, 44, 72, 36, 64, 48, 80],
        },
      ],
    },
    {
      id: "g3ag",
      type: "designCards",
      title: "Widget cards",
      cards: [
        {
          id: "w1",
          variant: "sleep",
          duration: "9h 40m",
          delta: "+219m",
          goalAt: 72,
        },
        {
          id: "w2",
          variant: "subwayNav",
          headline: "2 Min EXIT → Marcy Avenue",
          stationCount: "3 Stations",
          stopCount: 5,
          activeStop: 2,
        },
        {
          id: "w3",
          variant: "wishlist",
          kicker: "Wish List",
          title: "Death Stranding",
          price: "$13.29",
          discount: "-67%",
          progress: 34,
        },
        {
          id: "w4",
          variant: "weeklyRings",
          tags: [{ label: "Workout", tone: "neutral" }, { label: "Health", tone: "success" }],
          rings: [
            { label: "M", progress: 80 },
            { label: "T", progress: 65 },
            { label: "W", progress: 90 },
            { label: "T", progress: 55 },
            { label: "F", progress: 72, active: true },
            { label: "S", progress: 40 },
            { label: "S", progress: 30 },
          ],
        },
        {
          id: "w5",
          variant: "podcast",
          date: "Jun 2, 2023",
          title: "The Seagulls",
          show: "Radiolab",
          progress: 35,
          speed: "1x",
          duration: "1h 03m",
        },
        {
          id: "w6",
          variant: "weather",
          city: "New York",
          temperature: "66°",
          aqi: "38 AQI",
          wind: "7 Mph",
          chartValues: [42, 58, 72, 64, 48],
        },
        {
          id: "w7",
          variant: "network",
          stats: [
            { value: "161.35", direction: "up" },
            { value: "24 ms", direction: "down" },
            { value: "96.24", direction: "up" },
          ],
          downloadProgress: 62,
          uploadProgress: 38,
        },
        {
          id: "w8",
          variant: "sportsScore",
          homeTeam: "Knicks",
          awayTeam: "Wizards",
          homeScore: "86",
          awayScore: "91",
          league: "NBA",
        },
        {
          id: "w9",
          variant: "billing",
          kicker: "Due Payment",
          countdown: "5 Days Left",
          amount: "$109.43",
        },
        {
          id: "w10",
          variant: "activityGoals",
          goals: [
            { label: "0.60", progress: 60 },
            { label: "1.25", progress: 85 },
            { label: "SUN", progress: 100, completed: true },
            { label: "SAT", progress: 45 },
            { progress: 30 },
            { progress: 70 },
          ],
        },
        {
          id: "w11",
          variant: "airpods",
          featureValue: "13%",
          feature: "Noise Cancellation",
          leftBattery: 7,
          rightBattery: 19,
        },
        {
          id: "w12",
          variant: "laundry",
          program: "Intensive Wash",
          timer: "29m 13s",
          phase: "Rinse",
          phaseProgress: 55,
          phaseTimer: "4:13",
          temp: "45",
          spin: "1000",
        },
      ],
    },
    {
      id: "g3ah",
      type: "flowReportCards",
      title: "Analytics",
      cards: [
        {
          id: "fr1",
          title: "Flow report",
          icon: "folder",
          sources: [
            { label: "Licenses", value: "$5,000", tone: "purple" },
            { label: "Hardware", value: "$5,000", tone: "cyan" },
            { label: "Subscriptions", value: "$5,000", tone: "blue" },
          ],
          targets: [
            { label: "Adobe", value: "$5,000", tone: "purple" },
            { label: "Avast", value: "$5,000", tone: "cyan" },
          ],
          links: [
            { from: 0, to: 0, tone: "purple" },
            { from: 1, to: 0, tone: "cyan" },
            { from: 2, to: 1, tone: "purple" },
          ],
        },
      ],
    },
    {
      id: "g3ai",
      type: "savedMoneyCards",
      cards: [
        {
          id: "sm1",
          chartValues: [180, 210, 195, 90, 170, 220, 240],
          labels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
          timeframes: ["Week", "Month", "Year"],
          activeTimeframe: "Week",
          yMax: 300,
        },
      ],
    },
    {
      id: "g3aj",
      type: "fearGreedCards",
      cards: [
        {
          id: "fg1",
          score: 68,
          label: "Greed",
          leftPercent: 46,
          rightPercent: 54,
        },
      ],
    },
    {
      id: "g3ak",
      type: "targetChartCards",
      cards: [
        {
          id: "tc1",
          actualValues: [82, 82, 82, 82, 82, 82],
          targetEnd: 18,
          months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
          yLabels: ["5:00", "10:00", "15:00", "/km"],
        },
      ],
    },
    {
      id: "g3al",
      type: "quizScoreCards",
      title: "Learning metrics",
      cards: [
        {
          id: "qs1",
          value: "82%",
          change: "-10%",
          changeDirection: "down",
          highestValue: "92.50%",
          lowestValue: "64.25%",
          highestProgress: 92,
          lowestProgress: 64,
        },
      ],
    },
    {
      id: "g3am",
      type: "timeSpentCards",
      cards: [
        {
          id: "ts1",
          value: "12 Hours",
          change: "-12.00%",
          changeDirection: "down",
          subValue: "9.5H",
          chartValues: [40, 55, 48, 62, 70, 58, 45],
          activeIndex: 4,
        },
      ],
    },
    {
      id: "g3an",
      type: "weeklyStreakCards",
      cards: [
        {
          id: "ws1",
          value: "5 Days",
          longestValue: "15 days",
          days: [
            { label: "01", completed: true },
            { label: "02", completed: true },
            { label: "03", completed: true },
            { label: "04", completed: true },
            { label: "05", completed: true },
            { label: "06" },
            { label: "07" },
            { label: "08" },
            { label: "09" },
            { label: "10" },
          ],
        },
      ],
    },
    {
      id: "g3ao",
      type: "globalRankingCards",
      cards: [
        {
          id: "gr1",
          value: "#15 of 23K learners",
          entries: [
            { name: "Brooklyn Simmons" },
            { name: "Annette Black" },
            { name: "Guy Hawkins" },
          ],
        },
      ],
    },
    {
      id: "g3ap",
      type: "enrollmentChartCards",
      cards: [
        {
          id: "ec1",
          avgValue: "1,250,00",
          change: "+13.4%",
          changeDirection: "up",
          activeMonth: 6,
          tooltip: {
            title: "July 2024",
            enrollments: "Enrollments: 350",
            completion: "Completion: 85.20%",
          },
        },
      ],
    },
    {
      id: "g3aq",
      type: "activeProjectsCards",
      title: "Vuexy dashboard",
      cards: [
        {
          id: "ap1",
          items: [
            { name: "Laravel", category: "Ecommerce", icon: "code", progress: 85, tone: "purple" },
            { name: "Figma", category: "App UI Kit", icon: "layers", progress: 72, tone: "teal" },
            { name: "VueJS", category: "Calendar App", icon: "calendar", progress: 64, tone: "green" },
            { name: "React", category: "Dashboard", icon: "grid", progress: 58, tone: "orange" },
            { name: "Bootstrap", category: "Website", icon: "globe", progress: 45, tone: "accent" },
          ],
        },
      ],
    },
    {
      id: "g3ar",
      type: "miniStatChartCards",
      title: "KPI overview",
      cards: [
        {
          id: "ms1",
          title: "Order",
          subtitle: "Last week",
          value: "124k",
          change: "+12.6%",
          changeDirection: "up",
          chartType: "bar",
        },
        {
          id: "ms2",
          title: "Sales",
          subtitle: "Last year",
          value: "175k",
          change: "+18.2%",
          changeDirection: "up",
          chartType: "line",
        },
        {
          id: "ms3",
          title: "Profit",
          subtitle: "Last month",
          value: "624k",
          change: "+42.5%",
          changeDirection: "up",
          chartType: "line",
        },
        {
          id: "ms4",
          title: "Sessions",
          subtitle: "Last month",
          value: "38.5k",
          change: "-16.2%",
          changeDirection: "down",
          chartType: "bar",
        },
      ],
    },
    {
      id: "g3as",
      type: "statisticsProgressCards",
      cards: [
        {
          id: "sp1",
          rows: [
            { label: "Subscribers Gained", subLabel: "Monthly Report", change: "+92k", value: "92k", progress: 78 },
            { label: "Orders Received", subLabel: "Weekly Report", change: "+38k", value: "38k", progress: 52 },
          ],
        },
      ],
    },
    {
      id: "g3at",
      type: "salesOverviewCards",
      cards: [
        {
          id: "so1",
          total: "$42.5k",
          change: "+18.2%",
          left: { label: "Order", value: "62.2%", count: "6,440", icon: "hash" },
          right: { label: "Visits", value: "25.5%", count: "12,749", icon: "users" },
          leftRatio: 62,
        },
      ],
    },
    {
      id: "g3au",
      type: "webinarCtaCards",
      cards: [
        {
          id: "wc1",
          title: "Upcoming Webinar",
          description: "Join our live session on dashboard design patterns and data visualization.",
          date: "17 Nov 24",
          duration: "32 min",
        },
      ],
    },
    {
      id: "g3av3",
      type: "profileGridCards",
      title: "Recent profiles",
      cards: [
        {
          id: "pg1",
          columns: 3,
        },
      ],
    },
    {
      id: "g3av2",
      type: "spentThisMonthCards",
      title: "Monthly spending",
      cards: [
        {
          id: "stm1",
          amount: "€2,540.00",
          label: "Spent this Month",
          change: "5.8%",
          changeDirection: "up",
        },
        {
          id: "stm2",
          amount: "$1,820.00",
          label: "Spent this Month",
          change: "2.1%",
          changeDirection: "down",
          bars: [
            { label: "5", value: 28 },
            { label: "10", value: 34 },
            { label: "15", value: 22 },
            { label: "20", value: 40 },
            { label: "25", value: 18 },
            { label: "31", value: 26 },
          ],
        },
      ],
    },
    {
      id: "g3av",
      type: "expenseGaugeCards",
      cards: [
        {
          id: "eg1",
          value: "82.5k",
          label: "Expenses",
          percent: 78,
          caption: "78% of budget used this month",
        },
      ],
    },
    {
      id: "g3aw",
      type: "earningReportsCards",
      cards: [
        {
          id: "er1",
          stats: [
            { label: "Earnings", amount: "$545.69", change: "+12.5%", changeDirection: "up", icon: "dollar-sign" },
            { label: "Profit", amount: "$256.34", change: "+8.2%", changeDirection: "up", icon: "target" },
          ],
          activeIndex: 4,
        },
      ],
    },
    {
      id: "g3ax",
      type: "subscribersChartCards",
      cards: [
        {
          id: "sc1",
          value: "92.6k",
          subtitle: "Subscribers gained this month",
        },
      ],
    },
    {
      id: "g3ay",
      type: "glassWidgets",
      title: "Glass dashboard widgets",
      widgets: [
        { id: "gw1", variant: "wifi", network: "guest_wifi_5g", enabled: true },
        { id: "gw2", variant: "habits", label: "Daily Writing", remaining: "10m left", progress: 72 },
        { id: "gw3", variant: "gateInfo", gate: "B18", status: "Gate Open", countdown: "26 min" },
        { id: "gw4", variant: "audioRecording", elapsed: "01:12:25", recording: true },
        { id: "gw5", variant: "analogClock", hours: 10, minutes: 25 },
        { id: "gw6", variant: "cameraRecording", elapsed: "00:04:18", recording: true },
        {
          id: "gw7",
          variant: "timezoneWidget",
          theme: "light",
          location: "Shibuya, Tokyo",
          time: "10:25",
          dayProgress: 58,
          offsetLabel: "+4H",
          offsetTone: "success",
        },
        {
          id: "gw8",
          variant: "timezoneWidget",
          theme: "dark",
          location: "Shibuya, Tokyo",
          time: "10:25",
          dayProgress: 42,
          offsetLabel: "-4H",
          offsetTone: "warning",
        },
        { id: "gw9", variant: "rideShare", provider: "Uber", eta: "2 min", vehicle: "White sedan", model: "Mercedes-Benz" },
        { id: "gw10", variant: "charging", percent: 68, timeLeft: "37 min left" },
        {
          id: "gw11",
          variant: "flightArrival",
          size: "md",
          headline: "Arrival in 53min",
          origin: "London",
          originCode: "LHR",
          destination: "Istanbul",
          destinationCode: "IST",
          progress: 68,
        },
        {
          id: "gw12",
          variant: "navigation",
          size: "md",
          turnDistance: "300m",
          eta: "10:21",
          remaining: "64 km",
          progress: 58,
        },
        {
          id: "gw13",
          variant: "energyUsage",
          size: "md",
          percent: 57,
          durationLabel: "~ 5 hours",
          chartValues: [28, 44, 36, 52, 40],
        },
        {
          id: "gw14",
          variant: "musicWidget",
          size: "md",
          title: "Love On The Brain",
          artist: "Rihanna",
          source: "Spotify",
          progress: 42,
          playing: true,
        },
        {
          id: "gw15",
          variant: "scooterRide",
          size: "md",
          date: "Aug 12",
          distance: "3.2km",
          avgSpeed: "18.4km/h",
          calories: "186",
        },
        {
          id: "gw16",
          variant: "activityOverview",
          size: "lg",
          distance: "2.8 km",
          goal: "64 km",
          goalProgress: 44,
          duration: "42m",
          avgSpeed: "4.0km/h",
          calories: "312",
        },
        {
          id: "gw17",
          variant: "activityCalendar",
          size: "lg",
          month: "August",
          year: "2024",
          days: [
            { day: 1, tone: "low" },
            { day: 2, tone: "high" },
            { day: 3, tone: "high" },
            { day: 4, tone: "milestone" },
            { day: 5, tone: "high" },
            { day: 6, tone: "low" },
            { day: 7 },
            { day: 8, tone: "high" },
            { day: 9, tone: "high" },
            { day: 10, tone: "high" },
            { day: 11, tone: "low" },
            { day: 12, tone: "high" },
            { day: 13, tone: "milestone" },
            { day: 14, tone: "high" },
            { day: 15, tone: "high" },
            { day: 16 },
            { day: 17, tone: "low" },
            { day: 18, tone: "high" },
            { day: 19, tone: "high" },
            { day: 20, tone: "high" },
            { day: 21, tone: "high" },
            { day: 22, tone: "low" },
            { day: 23, tone: "high" },
            { day: 24, tone: "high" },
            { day: 25, tone: "milestone" },
            { day: 26, tone: "high" },
            { day: 27 },
            { day: 28, tone: "low" },
            { day: 29, tone: "high" },
            { day: 30, tone: "high" },
            { day: 31, tone: "high" },
          ],
        },
      ],
    },
    {
      id: "g3ay2",
      type: "creatorWidgets",
      title: "Creator & consultation cards",
      widgets: [
        {
          id: "cw1",
          variant: "consultantProfile",
          name: "Rick Wright",
          verified: true,
          available: true,
          priceTier: "$$$",
          durationValue: "25",
          durationLabel: "Minutes",
          followerCount: "+299K",
          rating: "4.5",
          bio: "A dedicated Productivity Manager with over a decade",
          memberNames: ["Alex", "Jordan", "Sam", "Riley"],
        },
        {
          id: "cw2",
          variant: "quoteArticle",
          showName: "Rick's Podcast",
          verified: true,
          subtitle: "How to improve communication in a relationship",
          dateValue: "30",
          dateLabel: "January",
          quote: "One of our proudest achievements was helping Michael",
        },
        {
          id: "cw3",
          variant: "streamEpisode",
          hostName: "John Doe",
          verified: true,
          donateLabel: "Donate",
          durationValue: "52",
          durationLabel: "minutes",
          rating: "5.0",
          title: "How to improve communication in a relationship",
          memberNames: "Alex",
          extraMembers: "+3",
        },
        {
          id: "cw4",
          variant: "videoCourse",
          showName: "Rick's Podcast",
          verified: true,
          available: true,
          priceTier: "$$$",
          episodeCount: "+6 Episodes",
          durationValue: "25",
          durationLabel: "Minutes",
          adFree: true,
          viewCount: "14k Views",
          rating: "5.0",
          memberNames: ["Alex", "Jordan", "Sam"],
          phoneAction: true,
        },
        {
          id: "cw5",
          variant: "liveCourse",
          hostName: "John Doe",
          verified: true,
          donateLabel: "Donate",
          sessionCount: "5 Sessions /",
          viewerCount: "(8)",
          live: true,
          title: "Title Of The Course",
          memberNames: ["Alex", "Jordan", "Sam"],
        },
        {
          id: "cw6",
          variant: "audioPlayer",
          title: "Title: Subject",
          subtitle: "Here's the info about the audio.",
          timeValue: "1:30",
          timeLabel: "hh / mm",
          chapterCount: "12 Capítulos",
          description: "A short overview of the audio content and what you'll learn in each chapter.",
        },
        {
          id: "cw7",
          variant: "workshopEvent",
          hostName: "Sarah Chen",
          verified: true,
          eventTitle: "Design Systems at Scale",
          countdownValue: "2d",
          countdownLabel: "Starts in",
          spotsLeft: "12 spots left",
          memberNames: ["Alex", "Jordan", "Sam", "Riley"],
        },
        {
          id: "cw8",
          variant: "masterclass",
          instructorName: "Elena Vasquez",
          verified: true,
          courseTitle: "Advanced Typography",
          lessonCount: "24 lessons",
          price: "$89",
          rating: "4.9",
          durationValue: "6",
          durationLabel: "Hours",
        },
        {
          id: "cw9",
          variant: "newsletterSignup",
          publisherName: "The Weekly Brief",
          verified: true,
          subscriberCount: "48K subscribers",
          issueValue: "#142",
          issueLabel: "Issue",
          headline: "Why async work is reshaping creative teams",
        },
        {
          id: "cw10",
          variant: "coachingSlot",
          coachName: "Jordan Hayes",
          verified: true,
          specialty: "Executive coaching",
          slotTime: "3:00",
          slotDate: "PM Today",
          timezone: "EST",
          rating: "4.8",
          price: "$120",
        },
      ],
    },
    {
      id: "g3az",
      type: "designCards",
      title: "Finance live activity",
      cards: [
        {
          id: "fa1",
          variant: "stockQuote",
          symbol: "TSLA",
          company: "Tesla Inc.",
          brandMark: "T",
          brandColor: "#e82127",
          updated: "updated 2m ago",
          price: "£ 8,01",
          change: "+£0.92",
          changePercent: "1.24%",
          changeDirection: "up",
        },
        {
          id: "fa2",
          variant: "stockActivity",
          symbol: "TSLA",
          company: "Tesla Inc.",
          brandMark: "T",
          brandColor: "#e82127",
          updated: "updated 2m ago",
          activeIndices: [4, 5],
        },
        { id: "fa3", variant: "amazonBuy", symbol: "AMZN", company: "Amazon Ltd." },
        { id: "fa4", variant: "amazonActions", symbol: "AMZN", company: "Amazon Ltd." },
        {
          id: "fa5",
          variant: "priceAlert",
          company: "Tesla, Inc.",
          alertLabel: "Price change",
          brandMark: "T",
          brandColor: "#e82127",
          progress: 73,
        },
        { id: "fa6", variant: "statusSpendings", amount: "£32.43", location: "London" },
        {
          id: "fa7",
          variant: "statusCrypto",
          symbol: "ETH",
          name: "Ethereum",
          change: "1.05%",
          changeDirection: "up",
          brandColor: "#627eea",
        },
        {
          id: "fa8",
          variant: "statusCrypto",
          symbol: "ETH",
          change: "1.05%",
          changeDirection: "up",
          brandColor: "#627eea",
          batteryPercent: 32,
        },
      ],
    },
    {
      id: "g4",
      type: "form",
      title: "Scheduled task details",
      fields: [
        { id: "f1", label: "Runs in", value: "Worktree" },
        { id: "f2", label: "Repeats", value: "Fridays at 4:00 PM" },
        { id: "f3", label: "Model", value: "GPT-5.5 Medium" },
      ],
    },
    {
      id: "g5",
      type: "code",
      language: "diff.ts",
      code: `-  socket.on("message", (raw) => handle(JSON.parse(raw)))\n+  socket.on("message", (raw) => handle(parseMessage(raw)))`,
    },
    {
      id: "g6",
      type: "terminal",
      lines: [
        "$ npm run typecheck --workspace=longformer-ui",
        "> tsc --noEmit",
        "✓ no errors",
      ],
    },
  ],
};
