import type { LifePlanningWorkspaceData } from "longformer-ui-tailwind";

export const lifePlanningWorkspaceData: LifePlanningWorkspaceData = {
  productName: "Life Planning",
  userName: "Alex Morgan",
  tagline: "AI-powered goals for every chapter of life",
  navItems: [
    { id: "dashboard", label: "Dashboard", icon: "grid", view: "dashboard", section: "overview" },
    { id: "goals", label: "All Goals", icon: "target", view: "goals", section: "overview" },
    { id: "health", label: "Health", icon: "heart", view: "health", section: "modules" },
    { id: "mind", label: "Mind", icon: "leaf", view: "mind", section: "modules" },
    { id: "finances", label: "Finances", icon: "dollar-sign", view: "finances", section: "modules" },
    { id: "housing", label: "Housing", icon: "home", view: "housing", section: "modules" },
    { id: "investments", label: "Investments", icon: "layers", view: "investments", section: "modules" },
    { id: "retirement", label: "Retirement", icon: "sun", view: "retirement", section: "modules" },
    { id: "ai-coach", label: "AI Coach", icon: "sparkles", view: "ai-coach", section: "tools" },
    { id: "settings", label: "Settings", icon: "settings", view: "settings", section: "tools" },
  ],
  overviewMetrics: [
    { id: "active-goals", label: "Active Goals", value: "14", icon: "target", tone: "accent" },
    { id: "on-track", label: "On Track", value: "78%", icon: "check", tone: "success", change: "+5% this month" },
    { id: "net-worth", label: "Net Worth", value: "$842K", icon: "dollar-sign", tone: "accent", change: "+$12K YTD" },
    { id: "ai-sessions", label: "AI Coach Sessions", value: "23", icon: "sparkles", tone: "neutral", change: "4 this week" },
  ],
  modules: [
    {
      id: "health",
      label: "Health",
      description: "Fitness, nutrition, sleep, and preventive care goals",
      icon: "heart",
      overallProgress: 72,
      activeGoals: 3,
      completedGoals: 2,
      metrics: [
        { id: "steps", label: "Avg Daily Steps", value: "8,420", change: "+12% vs last month" },
        { id: "sleep", label: "Sleep Score", value: "82", change: "7.2 hrs avg" },
        { id: "workouts", label: "Workouts / Week", value: "4.2", change: "Target: 5" },
      ],
      insights: [
        "Your sleep consistency improved 15% — keep the 10:30 PM wind-down routine.",
        "You're 340 steps/day away from your monthly step goal. A 20-min walk after lunch closes the gap.",
        "Annual physical is due in 6 weeks — I've added a reminder to your calendar.",
      ],
      goals: [
        {
          id: "health-1",
          title: "Run a half marathon",
          description: "Train for and complete the SF Half Marathon in October",
          moduleId: "health",
          progress: 58,
          targetDate: "Oct 2026",
          status: "on-track",
          milestones: [
            { id: "h1", title: "Complete 5K baseline", completed: true },
            { id: "h2", title: "Run 10K without stopping", completed: true },
            { id: "h3", title: "Complete 15K long run", completed: false, dueDate: "Aug 2026" },
            { id: "h4", title: "Race day", completed: false, dueDate: "Oct 2026" },
          ],
        },
        {
          id: "health-2",
          title: "Improve sleep quality",
          description: "Consistent 7.5+ hours with sleep score above 80",
          moduleId: "health",
          progress: 85,
          status: "on-track",
          milestones: [
            { id: "h5", title: "No screens after 10 PM", completed: true },
            { id: "h6", title: "30-day streak above 80 score", completed: false },
          ],
        },
        {
          id: "health-3",
          title: "Reduce body fat to 18%",
          description: "Strength training 3x/week plus nutrition tracking",
          moduleId: "health",
          progress: 45,
          targetDate: "Dec 2026",
          status: "at-risk",
          milestones: [
            { id: "h7", title: "Hit 20% body fat", completed: true },
            { id: "h8", title: "Hit 19% body fat", completed: false },
            { id: "h9", title: "Hit 18% body fat", completed: false },
          ],
        },
      ],
    },
    {
      id: "mind",
      label: "Mind",
      description: "Mental wellness, learning, creativity, and personal growth",
      icon: "leaf",
      overallProgress: 64,
      activeGoals: 2,
      completedGoals: 1,
      metrics: [
        { id: "meditation", label: "Meditation Streak", value: "21 days", change: "Personal best!" },
        { id: "reading", label: "Books Read (YTD)", value: "8", change: "Target: 12" },
        { id: "learning", label: "Learning Hours", value: "34 hrs", change: "+6 hrs this month" },
      ],
      insights: [
        "Your meditation streak is your longest yet — consistency is building resilience.",
        "You're on pace for 11 books this year. One more month of 2 books/month hits your goal.",
        "Consider scheduling a digital detox weekend — stress markers rose slightly last week.",
      ],
      goals: [
        {
          id: "mind-1",
          title: "Read 12 books this year",
          description: "Mix of fiction and non-fiction for breadth and depth",
          moduleId: "mind",
          progress: 67,
          targetDate: "Dec 2026",
          status: "on-track",
          milestones: [
            { id: "m1", title: "Read 6 books by mid-year", completed: true },
            { id: "m2", title: "Read 9 books by September", completed: false },
            { id: "m3", title: "Complete 12 books", completed: false },
          ],
        },
        {
          id: "mind-2",
          title: "Daily meditation practice",
          description: "10 minutes minimum, 6 days per week",
          moduleId: "mind",
          progress: 90,
          status: "on-track",
          milestones: [
            { id: "m4", title: "Establish morning routine", completed: true },
            { id: "m5", title: "30-day streak", completed: false },
            { id: "m6", title: "90-day streak", completed: false },
          ],
        },
      ],
    },
    {
      id: "finances",
      label: "Finances",
      description: "Budgeting, savings, debt management, and cash flow",
      icon: "dollar-sign",
      overallProgress: 81,
      activeGoals: 3,
      completedGoals: 1,
      metrics: [
        { id: "savings-rate", label: "Savings Rate", value: "28%", change: "Target: 25%" },
        { id: "emergency", label: "Emergency Fund", value: "8.2 months", change: "Fully funded" },
        { id: "debt", label: "Total Debt", value: "$14,200", change: "−$2,800 YTD" },
      ],
      insights: [
        "You're exceeding your savings target — consider redirecting the surplus to investments.",
        "Student loan payoff is 4 months ahead of schedule at current payment rate.",
        "Dining out spending is 22% over budget — I've suggested meal prep alternatives.",
      ],
      goals: [
        {
          id: "fin-1",
          title: "Pay off student loans",
          description: "Eliminate remaining $14,200 in student debt",
          moduleId: "finances",
          progress: 78,
          targetDate: "Mar 2027",
          status: "on-track",
          milestones: [
            { id: "f1", title: "Below $20K balance", completed: true },
            { id: "f2", title: "Below $10K balance", completed: false },
            { id: "f3", title: "Fully paid off", completed: false },
          ],
        },
        {
          id: "fin-2",
          title: "Build 12-month emergency fund",
          description: "Maintain liquid savings covering 12 months of expenses",
          moduleId: "finances",
          progress: 100,
          status: "completed",
          milestones: [
            { id: "f4", title: "6 months saved", completed: true },
            { id: "f5", title: "12 months saved", completed: true },
          ],
        },
        {
          id: "fin-3",
          title: "Save for home down payment",
          description: "Accumulate $120K for a 20% down payment",
          moduleId: "finances",
          progress: 52,
          targetDate: "Jun 2028",
          status: "on-track",
          milestones: [
            { id: "f6", title: "Reach $50K", completed: true },
            { id: "f7", title: "Reach $80K", completed: false },
            { id: "f8", title: "Reach $120K", completed: false },
          ],
        },
      ],
    },
    {
      id: "housing",
      label: "Housing",
      description: "Home purchase planning, affordability, and market research",
      icon: "home",
      overallProgress: 48,
      activeGoals: 2,
      completedGoals: 0,
      metrics: [
        { id: "saved", label: "Down Payment Saved", value: "$62,400", change: "52% of target" },
        { id: "affordability", label: "Max Affordable", value: "$620K", change: "At current rates" },
        { id: "market", label: "Target Markets", value: "3 cities", change: "Lakeside, Northgate, Bayview" },
      ],
      insights: [
        "Interest rates dropped 0.25% — your buying power increased by ~$18K.",
        "Lakeside median prices softened 3% this quarter. Good entry window forming.",
        "Pre-approval checklist is 60% complete. Next step: gather tax returns.",
      ],
      goals: [
        {
          id: "house-1",
          title: "Purchase first home",
          description: "Buy a 2-3 bedroom home in the East Bay",
          moduleId: "housing",
          progress: 48,
          targetDate: "Jun 2028",
          status: "on-track",
          milestones: [
            { id: "ho1", title: "Define must-haves list", completed: true },
            { id: "ho2", title: "Get pre-approved", completed: false },
            { id: "ho3", title: "Make first offer", completed: false },
            { id: "ho4", title: "Close on home", completed: false },
          ],
        },
        {
          id: "house-2",
          title: "Research neighborhoods",
          description: "Visit and score 3 target neighborhoods",
          moduleId: "housing",
          progress: 33,
          status: "on-track",
          milestones: [
            { id: "ho5", title: "Visit Lakeside", completed: true },
            { id: "ho6", title: "Visit Northgate", completed: false },
            { id: "ho7", title: "Visit Bayview", completed: false },
          ],
        },
      ],
    },
    {
      id: "investments",
      label: "Investments",
      description: "Portfolio growth, asset allocation, and wealth building",
      icon: "layers",
      overallProgress: 69,
      activeGoals: 2,
      completedGoals: 0,
      metrics: [
        { id: "portfolio", label: "Portfolio Value", value: "$385K", change: "+8.2% YTD" },
        { id: "allocation", label: "Stock / Bond Split", value: "80 / 20", change: "On target" },
        { id: "contributions", label: "Monthly Invested", value: "$2,400", change: "Auto-invest active" },
      ],
      insights: [
        "Portfolio is slightly overweight in tech (32% vs 25% target) — consider rebalancing.",
        "Your DCA strategy has outperformed lump-sum timing by 2.1% over 18 months.",
        "Tax-loss harvesting opportunity detected in international fund position.",
      ],
      goals: [
        {
          id: "inv-1",
          title: "Reach $500K portfolio",
          description: "Grow investment portfolio to half a million",
          moduleId: "investments",
          progress: 77,
          targetDate: "Dec 2027",
          status: "on-track",
          milestones: [
            { id: "i1", title: "Hit $400K", completed: false },
            { id: "i2", title: "Hit $450K", completed: false },
            { id: "i3", title: "Hit $500K", completed: false },
          ],
        },
        {
          id: "inv-2",
          title: "Max out retirement accounts",
          description: "Fully fund 401(k) and Roth IRA annually",
          moduleId: "investments",
          progress: 62,
          targetDate: "Dec 2026",
          status: "on-track",
          milestones: [
            { id: "i4", title: "Max Roth IRA ($7K)", completed: true },
            { id: "i5", title: "Max 401(k) ($23.5K)", completed: false },
          ],
        },
      ],
    },
    {
      id: "retirement",
      label: "Retirement",
      description: "Long-term retirement planning, projections, and lifestyle goals",
      icon: "sun",
      overallProgress: 55,
      activeGoals: 2,
      completedGoals: 0,
      metrics: [
        { id: "projected", label: "Projected at 65", value: "$2.1M", change: "82% of target" },
        { id: "monthly", label: "Retirement Income", value: "$6,800/mo", change: "Estimated" },
        { id: "years", label: "Years to Retirement", value: "28", change: "Target age: 60" },
      ],
      insights: [
        "Increasing 401(k) contribution by 1% closes the retirement gap in 3 years.",
        "Social Security estimate updated — expect ~$2,400/mo at full retirement age.",
        "Healthcare cost projection for retirement rose 4% — factor into planning.",
      ],
      goals: [
        {
          id: "ret-1",
          title: "Retire by 60 with $2.5M",
          description: "Financial independence with comfortable lifestyle",
          moduleId: "retirement",
          progress: 55,
          targetDate: "2048",
          status: "on-track",
          milestones: [
            { id: "r1", title: "Reach $500K by 40", completed: false },
            { id: "r2", title: "Reach $1M by 45", completed: false },
            { id: "r3", title: "Reach $2.5M by 60", completed: false },
          ],
        },
        {
          id: "ret-2",
          title: "Define retirement lifestyle",
          description: "Document desired location, activities, and budget",
          moduleId: "retirement",
          progress: 30,
          status: "not-started",
          milestones: [
            { id: "r4", title: "Research locations", completed: false },
            { id: "r5", title: "Create retirement budget", completed: false },
            { id: "r6", title: "Plan healthcare strategy", completed: false },
          ],
        },
      ],
    },
  ],
  aiCoach: {
    greeting: "I'm tracking 14 goals across 6 life areas. Here's what needs your attention this week.",
    weeklyFocus: "Focus on your half marathon long run and review the Lakeside housing market report I prepared.",
    messages: [
      {
        id: "msg-1",
        role: "assistant",
        content:
          "Good morning, Alex! Your health and finance modules are looking strong this month. I noticed your body fat goal is at risk — want me to adjust your meal plan?",
        timestamp: "Today, 8:00 AM",
        relatedModule: "health",
      },
      {
        id: "msg-2",
        role: "user",
        content: "Yes, and also give me an update on the housing market.",
        timestamp: "Today, 8:05 AM",
      },
      {
        id: "msg-3",
        role: "assistant",
        content:
          "I've updated your nutrition targets to prioritize protein and reduce evening carbs. For housing: Lakeside median prices dropped 3% this quarter, and your buying power increased ~$18K with the recent rate dip. I've added a neighborhood comparison to your Housing module.",
        timestamp: "Today, 8:05 AM",
        relatedModule: "housing",
      },
      {
        id: "msg-4",
        role: "assistant",
        content:
          "One more thing — your 401(k) is 62% funded for the year. If you increase contributions by $200/month, you'll max out by November.",
        timestamp: "Today, 8:06 AM",
        relatedModule: "investments",
      },
    ],
    recommendations: [
      {
        id: "rec-1",
        title: "Schedule 15K training run",
        description: "Your half marathon is 4 months out. Block a long run this weekend to stay on pace.",
        moduleId: "health",
        priority: "high",
        actionLabel: "View Health Goals",
      },
      {
        id: "rec-2",
        title: "Rebalance portfolio",
        description: "Tech allocation is 7% above target. Shift $8K to bond index to restore 80/20 split.",
        moduleId: "investments",
        priority: "medium",
        actionLabel: "View Investments",
      },
      {
        id: "rec-3",
        title: "Get mortgage pre-approval",
        description: "You're 52% toward your down payment. Starting pre-approval now gives you a realistic budget.",
        moduleId: "housing",
        priority: "medium",
        actionLabel: "View Housing",
      },
      {
        id: "rec-4",
        title: "Define retirement lifestyle",
        description: "This goal hasn't started yet. A 15-min exercise now unlocks better long-term projections.",
        moduleId: "retirement",
        priority: "low",
        actionLabel: "View Retirement",
      },
    ],
  },
  recentActivity: [
    {
      id: "act-1",
      title: "Completed 5K training run",
      moduleId: "health",
      type: "Workout",
      timestamp: "2 hours ago",
      status: "success",
    },
    {
      id: "act-2",
      title: "Emergency fund milestone reached",
      moduleId: "finances",
      type: "Savings",
      timestamp: "Yesterday",
      status: "success",
    },
    {
      id: "act-3",
      title: "Lakeside market report generated",
      moduleId: "housing",
      type: "Research",
      timestamp: "Yesterday",
      status: "info",
    },
    {
      id: "act-4",
      title: "Meditation streak: 21 days",
      moduleId: "mind",
      type: "Wellness",
      timestamp: "2 days ago",
      status: "success",
    },
    {
      id: "act-5",
      title: "Body fat goal flagged at-risk",
      moduleId: "health",
      type: "Alert",
      timestamp: "3 days ago",
      status: "warning",
    },
    {
      id: "act-6",
      title: "Roth IRA maxed for 2026",
      moduleId: "investments",
      type: "Contribution",
      timestamp: "1 week ago",
      status: "success",
    },
  ],
};
