import type { TicketsWorkspaceData } from "longformer-ui-tailwind";

export const ticketsWorkspaceData: TicketsWorkspaceData = {
  productName: "Pixel Lab",
  userRole: "Agent Admin",
  userName: "Alex Morgan",
  userEmail: "alex@example.com",
  navItems: [
    { id: "dashboard", label: "Dashboard", icon: "grid", view: "dashboard" },
    { id: "inbox", label: "Inbox", icon: "inbox", view: "inbox", badge: "3" },
    { id: "notification", label: "Notification", icon: "bell", view: "notification" },
    { id: "ticket", label: "Ticket", icon: "file", view: "ticket" },
    { id: "knowledge-base", label: "Knowledge Base", icon: "bookmark", view: "knowledge-base" },
    { id: "customer", label: "Customer", icon: "users", view: "customer" },
    { id: "forum", label: "Forum", icon: "message-square", view: "forum" },
    { id: "report", label: "Report", icon: "layers", view: "report" },
  ],
  conversationItems: [
    { id: "call", label: "Call", icon: "phone-call", meta: "+1 (555) 012-3456", badge: "1" },
    { id: "side-conversation", label: "Side Conversation", icon: "message-square" },
  ],
  pinnedTickets: [
    { id: "pin-192", label: "#TC-192", meta: "product…" },
    { id: "pin-191", label: "#TC-191", meta: "billing…" },
    { id: "pin-phone", label: "+1 (555) 012-3456" },
  ],
  automationCount: 12,
  metrics: [
    { id: "new", label: "New Ticket", value: 8, trend: 24, status: "new" },
    { id: "in-progress", label: "In Progress", value: 24, trend: 24, status: "in-progress" },
    { id: "awaiting", label: "Awaiting Customer", value: 16, trend: -5, status: "awaiting-customer" },
    { id: "closed", label: "Closed", value: 72, trend: 24, status: "closed" },
    { id: "draft", label: "Draft", value: 2, trend: 24, status: "draft" },
  ],
  tickets: [
    {
      id: "tc-192",
      displayId: "#TC-192",
      priority: "urgent",
      subject: "I need to get into my account",
      intent: "Account Access Failure",
      type: "incident",
      status: "new",
      clientName: "Santi Carloza",
      clientEmail: "santi.carloza@email.com",
      raisedAt: "Jul 1, 2026",
      raisedAtMs: Date.parse("2026-07-01T09:15:00"),
      pinned: true,
    },
    {
      id: "tc-191",
      displayId: "#TC-191",
      priority: "medium",
      subject: "Suspicious login attempt detected",
      intent: "Suspicious Activity",
      type: "problem",
      status: "in-progress",
      clientName: "Oliver Grant",
      clientEmail: "oliver.grant@email.com",
      raisedAt: "Jul 1, 2026",
      raisedAtMs: Date.parse("2026-07-01T08:42:00"),
      pinned: true,
    },
    {
      id: "tc-190",
      displayId: "#TC-190",
      priority: "urgent",
      subject: "My payment was declined",
      intent: "Billing Payment Declined",
      type: "incident",
      status: "new",
      clientName: "Emma Richardson",
      clientEmail: "emma.r@email.com",
      raisedAt: "Jun 30, 2026",
      raisedAtMs: Date.parse("2026-06-30T16:20:00"),
    },
    {
      id: "tc-189",
      displayId: "#TC-189",
      priority: "low",
      subject: "App keeps crashing on launch",
      intent: "App Crash",
      type: "incident",
      status: "awaiting-customer",
      clientName: "Jordan Hayes",
      clientEmail: "marcus.webb@email.com",
      raisedAt: "Jun 30, 2026",
      raisedAtMs: Date.parse("2026-06-30T14:05:00"),
    },
    {
      id: "tc-188",
      displayId: "#TC-188",
      priority: "medium",
      subject: "How do I export my data?",
      intent: "Data Export Request",
      type: "question",
      status: "in-progress",
      clientName: "Riley Chen",
      clientEmail: "dana.cho@email.com",
      raisedAt: "Jun 29, 2026",
      raisedAtMs: Date.parse("2026-06-29T11:30:00"),
    },
    {
      id: "tc-187",
      displayId: "#TC-187",
      priority: "low",
      subject: "Add dark mode to the mobile app",
      intent: "Feature Request",
      type: "suggestion",
      status: "closed",
      clientName: "Sam Patel",
      clientEmail: "priya.sharma@email.com",
      raisedAt: "Jun 28, 2026",
      raisedAtMs: Date.parse("2026-06-28T09:00:00"),
    },
    {
      id: "tc-186",
      displayId: "#TC-186",
      priority: "urgent",
      subject: "Cannot reset password — no email received",
      intent: "Account Access Failure",
      type: "incident",
      status: "new",
      clientName: "James Liu",
      clientEmail: "james.liu@email.com",
      raisedAt: "Jun 28, 2026",
      raisedAtMs: Date.parse("2026-06-28T07:45:00"),
    },
    {
      id: "tc-185",
      displayId: "#TC-185",
      priority: "medium",
      subject: "Invoice shows wrong billing period",
      intent: "Billing Dispute",
      type: "problem",
      status: "in-progress",
      clientName: "Sarah Mitchell",
      clientEmail: "sarah.m@email.com",
      raisedAt: "Jun 27, 2026",
      raisedAtMs: Date.parse("2026-06-27T15:10:00"),
    },
    {
      id: "tc-184",
      displayId: "#TC-184",
      priority: "low",
      subject: "What are your support hours?",
      intent: "General Inquiry",
      type: "question",
      status: "closed",
      clientName: "Alex Turner",
      clientEmail: "alex.turner@email.com",
      raisedAt: "Jun 27, 2026",
      raisedAtMs: Date.parse("2026-06-27T10:22:00"),
    },
    {
      id: "tc-183",
      displayId: "#TC-183",
      priority: "medium",
      subject: "Team chat integration not syncing",
      intent: "Integration Failure",
      type: "incident",
      status: "awaiting-customer",
      clientName: "Nina Patel",
      clientEmail: "nina.patel@email.com",
      raisedAt: "Jun 26, 2026",
      raisedAtMs: Date.parse("2026-06-26T13:55:00"),
    },
  ],
};
