/** Tailwind class map — converted from NavRail.module.css */
const styles: Record<string, string> = {
  brand: "flex items-center justify-center w-[32px] h-[32px] rounded-lf-md bg-[#fff] [flex-shrink:0] overflow-hidden p-[1px] transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)]",
  "brand svg": "block w-full h-full",
  brandHost: "flex items-center justify-between gap-lf-1 w-full min-w-0",
  brandRow: "flex items-center justify-center w-full mb-lf-4 [flex-shrink:0]",
  collapsed: "w-[56px] items-center",
  collapsed_brandHost: "relative w-[32px] h-[32px] justify-center hover:opacity-0 opacity-0 hover:opacity-100 hover:bg-lf-surface-2 hover:text-lf-text-primary opacity-100 bg-lf-surface-2 text-lf-text-primary",
  collapsed_footer: "items-center",
  collapsed_footerUtilities: "flex-col items-center",
  collapsed_itemActive: "before:before:[content:\"\"] before:before:absolute before:before:left-[-8px] before:before:top-[50%] before:before:[transform:translateY(-50%)] before:before:w-[3px] before:before:h-[16px] before:before:rounded-lf-pill before:before:bg-lf-accent",
  collapsed_itemButton: "w-[36px] h-[36px] justify-center",
  collapsed_items: "items-center",
  collapsed_itemSlot: "w-auto",
  collapsed_itemSlotDropBefore: "before:before:left-[2px] before:before:right-[2px]",
  collapsed_toggleButton: "absolute inset-0 m-0 opacity-0 focus-visible:opacity-100 focus-visible:bg-lf-surface-2 focus-visible:text-lf-text-primary",
  dragGhost: "fixed z-[10000] flex items-center gap-lf-2 pointer-events-none rounded-lf-md bg-lf-surface-2 border border-solid border-lf-border-subtle shadow-lf-md text-lf-text-primary [transform:translate(-50%,_-50%)]",
  dragGhostCollapsed: "w-[36px] h-[36px] justify-center p-0",
  dragGhostExpanded: "h-[34px] p-[0_var(--lf-space-3)] min-w-[120px]",
  dragGhostIcon: "flex [flex-shrink:0]",
  dragGhostLabel: "text-lf-md whitespace-nowrap",
  dragGhostUndocking: "opacity-[0.65] [transform:translate(-50%,_-50%)_scale(0.88)]",
  expanded: "w-full min-w-[56px] max-w-full items-stretch",
  expanded_footer: "items-stretch",
  expanded_itemButton: "w-full h-[34px] p-[0_var(--lf-space-2)] justify-start",
  expanded_itemRow: "hover:text-lf-text-primary w-full min-h-[34px] pr-[2px]",
  expanded_itemRow_itemButton: "flex-1 min-w-0 w-auto",
  expanded_itemRowActive_itemButton: "text-lf-text-primary",
  footer: "flex flex-col gap-lf-2 [flex-shrink:0] m-[var(--lf-space-2)_calc(-1_*_var(--lf-space-2))_calc(-1_*_var(--lf-space-3))] p-lf-2 border-t border-lf-divider",
  footerUtilities: "flex gap-lf-1",
  itemActive: "bg-lf-surface-2 text-lf-text-primary",
  itemButton: "relative flex items-center gap-lf-2 [flex-shrink:0] border-none bg-transparent rounded-lf-md text-lf-text-tertiary cursor-pointer whitespace-nowrap transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:text-lf-text-primary",
  itemIcon: "flex [flex-shrink:0]",
  itemLabel: "overflow-hidden text-ellipsis whitespace-nowrap text-lf-md",
  itemMenuButton: "inline-flex items-center justify-center w-[24px] h-[24px] [flex-shrink:0] mr-[2px] border-none rounded-lf-sm bg-transparent text-lf-text-tertiary cursor-pointer opacity-0 transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] focus-visible:opacity-100 opacity-100 hover:bg-lf-surface-3 hover:text-lf-text-primary",
  itemRow: "flex items-center gap-0 min-w-0 rounded-lf-md transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:bg-lf-surface-2 hover:opacity-100 opacity-100",
  itemRowActive: "bg-lf-surface-2",
  itemRowActive_itemMenuButton: "opacity-100",
  items: "relative flex flex-col gap-lf-1 flex-1 min-h-0 overflow-y-auto scrollbar-none [-ms-overflow-style:none]",
  itemSlot: "relative w-full",
  itemSlotDragging: "opacity-[0.35]",
  itemSlotDropBefore: "before:before:[content:\"\"] before:before:absolute before:before:top-[-2px] before:before:left-[6px] before:before:right-[6px] before:before:h-[2px] before:before:rounded-lf-pill before:before:bg-lf-accent before:before:z-[1]",
  itemSlotPending: "",
  itemSlotPending_itemButton: "bg-lf-surface-2 [transform:scale(0.96)]",
  itemSlotPending_itemRow: "bg-lf-surface-2 [transform:scale(0.96)]",
  itemSlotPending_itemRow_itemButton: "[transform:none]",
  itemSlotPinDropActive: "[touch-action:none]",
  itemSlotReorderable: "[touch-action:none]",
  itemSlotReorderActive: "[touch-action:none]",
  itemSlotUndocking: "opacity-[0.2]",
  overflowButton: "mt-lf-1",
  overflowButtonOpen: "bg-lf-surface-2 text-lf-text-primary",
  overflowCount: "ml-auto min-w-[18px] h-[18px] p-[0_5px] rounded-lf-pill bg-lf-surface-3 text-lf-text-tertiary text-lf-xs font-semibold leading-[18px] text-center",
  rail: "h-full flex flex-col p-[var(--lf-space-3)_var(--lf-space-2)] bg-lf-surface-sunken transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] overflow-hidden",
  railPinDragging: "[cursor:grabbing]",
  railReordering: "[cursor:grabbing]",
  railReordering_itemButton: "[cursor:grabbing]",
  railUndocking: "[cursor:grabbing]",
  railUndocking_undockHint: "opacity-100",
  toggleButton: "flex items-center justify-center w-[32px] h-[32px] ml-auto border-none bg-transparent rounded-lf-md text-lf-text-tertiary cursor-pointer [flex-shrink:0] transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:bg-lf-surface-2 hover:text-lf-text-primary",
  undockHint: "absolute inset-0 flex items-center justify-center rounded-lf-md bg-[color-mix(in_srgb,_var(--lf-danger)_12%,_transparent)] pointer-events-none opacity-0 transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] z-[1]",
};
export default styles;
