/** Tailwind class map — converted from BankDashboardView.module.css */
const styles: Record<string, string> = {
  accountBalance: "text-[0.875rem] font-semibold [font-variant-numeric:tabular-nums]",
  accountIcon: "inline-flex items-center justify-center w-[32px] h-[32px] rounded-lf-md text-[0.875rem]",
  accountList: "list-none m-0 p-0",
  accountMeta: "flex-1 min-w-0",
  accountName: "text-[0.875rem] font-medium",
  accountRow: "flex items-center gap-lf-3 p-[var(--lf-space-3)_0] border-b border-[var(--bc-border)] last:[border-bottom:none]",
  accountsCard: "p-lf-5 border border-solid border-[var(--bc-border)] rounded-lf-xl bg-[var(--bc-surface)]",
  accountSuffix: "text-[var(--bc-text-muted)] font-normal",
  balanceAmount: "text-[clamp(1.75rem,_3vw,_2.25rem)] font-semibold [letter-spacing:-0.03em] [font-variant-numeric:tabular-nums]",
  balanceCard: "p-lf-5 border border-solid border-[var(--bc-border)] rounded-lf-xl bg-[var(--bc-surface)]",
  balanceMeta: "flex items-center gap-lf-3 mt-lf-2 text-[0.8125rem] text-[var(--bc-text-muted)]",
  cardActions: "flex gap-lf-1",
  cardHeader: "flex items-center justify-between mb-lf-3",
  "cardHeader h2": "m-0 text-[0.9375rem] font-semibold",
  chartLabels: "flex justify-between mt-lf-2 text-[0.75rem] text-[var(--bc-text-muted)]",
  chartLine: "[stroke:var(--bc-accent)] [stroke-width:2] [stroke-linecap:round] [stroke-linejoin:round]",
  chartWrap: "mt-lf-4",
  content: "flex-1 min-h-0 overflow-auto p-[var(--lf-space-5)_var(--lf-space-6)]",
  dashboard: "flex flex-col h-full min-h-0 bg-[var(--bc-bg)] text-[var(--bc-text)] font-sans",
  grid: "grid grid-cols-[minmax(0,_1.4fr)_minmax(0,_1fr)] gap-lf-4 grid-cols-[1fr]",
  iconBtn: "inline-flex items-center justify-center w-[32px] h-[32px] border border-solid border-[var(--bc-border)] rounded-lf-md bg-[var(--bc-surface)] text-[var(--bc-text-muted)] cursor-pointer",
  kbd: "ml-auto p-[2px_6px] rounded-lf-sm bg-[var(--bc-bg)] text-[0.6875rem] font-sans",
  movementCard: "p-lf-5 border border-solid border-[var(--bc-border)] rounded-lf-xl bg-[var(--bc-surface)] col-[1_/_-1]",
  movementGrid: "grid grid-cols-[1fr_1fr] gap-lf-6 grid-cols-[1fr]",
  movementIn: "text-[var(--bc-success)]",
  movementLabel: "text-[0.8125rem] text-[var(--bc-text-muted)] mb-lf-1",
  movementList: "list-none m-0 p-0",
  movementRow: "flex justify-between gap-lf-3 p-[var(--lf-space-2)_0] text-[0.875rem]",
  "movementRow span": "last:[font-variant-numeric:tabular-nums] last:font-medium",
  movementSubhead: "text-[0.75rem] font-semibold uppercase [letter-spacing:0.04em] text-[var(--bc-text-muted)] mb-lf-2",
  movementTotal: "text-[1.5rem] font-semibold [font-variant-numeric:tabular-nums] mb-lf-4",
  moveMoneyBtn: "inline-flex items-center gap-lf-1 p-[var(--lf-space-2)_var(--lf-space-3)] border border-solid border-[var(--bc-accent)] rounded-lf-lg bg-transparent text-[var(--bc-accent)] text-[0.875rem] font-medium cursor-pointer",
  periodBtn: "inline-flex items-center gap-lf-1 p-[var(--lf-space-1)_var(--lf-space-2)] border border-solid border-[var(--bc-border)] rounded-lf-md bg-[var(--bc-surface)] text-[0.8125rem] text-[var(--bc-text-muted)] cursor-pointer",
  quickAction: "p-[var(--lf-space-2)_var(--lf-space-4)] border border-solid border-[var(--bc-border)] rounded-[999px] bg-[var(--bc-surface)] text-[0.875rem] font-medium text-[var(--bc-text)] cursor-pointer",
  quickActionPrimary: "border-[var(--bc-accent)] bg-[var(--bc-accent)] text-lf-text-on-accent",
  quickActions: "flex flex-wrap gap-lf-2 mb-lf-5",
  search: "flex items-center gap-lf-2 flex-1 max-w-[360px] p-[var(--lf-space-2)_var(--lf-space-3)] border border-solid border-[var(--bc-border)] rounded-lf-lg text-[0.875rem] text-[var(--bc-text-muted)]",
  tablePlaceholder: "mt-lf-4 p-lf-6 rounded-lf-md bg-[var(--bc-bg)] text-[0.875rem] text-[var(--bc-text-muted)] text-center",
  topActions: "flex items-center gap-lf-2",
  topBar: "flex items-center justify-between gap-lf-4 p-[var(--lf-space-3)_var(--lf-space-6)] border-b border-[var(--bc-border)] bg-[var(--bc-surface)]",
  trendDown: "text-[var(--bc-text-muted)]",
  trendUp: "text-[var(--bc-success)]",
  viewToggle: "flex gap-[2px] p-[2px] rounded-lf-md bg-[var(--bc-bg)]",
  "viewToggle button": "inline-flex items-center justify-center w-[28px] h-[28px] border-none rounded-lf-sm bg-transparent text-[var(--bc-text-muted)] cursor-pointer",
  viewToggleActive: "bg-[var(--bc-surface)] text-[var(--bc-text)] shadow-lf-sm",
};
export default styles;
