/** Tailwind class map — converted from CryptoWalletView.module.css */
const styles: Record<string, string> = {
  accountValueAmount: "text-[2rem] font-bold [letter-spacing:-0.03em] [font-variant-numeric:tabular-nums]",
  accountValueBlock: "flex flex-col gap-[4px]",
  accountValueLabel: "text-[0.8125rem] text-[var(--cw-text-muted)]",
  actionBtn: "inline-flex items-center justify-center gap-lf-2 p-[var(--lf-space-3)_var(--lf-space-4)] border-none rounded-[999px] bg-[var(--cw-pill)] text-[var(--cw-pill-text)] text-[0.9375rem] font-semibold cursor-pointer",
  actionRow: "grid grid-cols-[1fr_1fr] gap-lf-3 mb-lf-5",
  activitiesTitle: "m-[0_0_var(--lf-space-3)] text-[0.6875rem] font-semibold [letter-spacing:0.06em] uppercase text-[var(--cw-text-muted)]",
  activityAmount: "block text-[0.9375rem] font-semibold [font-variant-numeric:tabular-nums]",
  activityAmounts: "text-right",
  activityDate: "block text-[0.8125rem] text-[var(--cw-text-muted)]",
  activityList: "list-none m-0 p-0",
  activityRow: "flex items-center justify-between gap-lf-3 p-[var(--lf-space-3)_0] border-b border-[var(--cw-border)]",
  activityType: "block text-[0.9375rem] font-semibold",
  activityUsd: "block text-[0.8125rem] text-[var(--cw-text-muted)] [font-variant-numeric:tabular-nums]",
  addBtn: "inline-flex items-center justify-center w-[36px] h-[36px] mb-lf-3 border-none rounded-[999px] bg-[var(--cw-subtle-bg)] text-[var(--cw-text)] cursor-pointer",
  assetBalance: "text-[0.9375rem] font-semibold [font-variant-numeric:tabular-nums]",
  assetBalanceUsd: "text-[0.8125rem] text-[var(--cw-text-muted)] [font-variant-numeric:tabular-nums]",
  assetHoldings: "flex flex-col items-end gap-[2px]",
  assetIcon: "inline-flex items-center justify-center w-[40px] h-[40px] rounded-[999px] text-[1rem] font-bold text-[#fff] [flex-shrink:0]",
  assetList: "list-none m-0 p-0",
  assetMeta: "flex-1 min-w-0 flex flex-col gap-[2px]",
  assetName: "text-[1rem] font-semibold",
  assetPrice: "text-[0.8125rem] text-[var(--cw-text-muted)] [font-variant-numeric:tabular-nums]",
  assetRow: "flex items-center gap-lf-3 w-full p-[var(--lf-space-3)_0] border-none border-b border-[var(--cw-border)] bg-transparent text-left cursor-pointer text-[inherit]",
  backBtn: "inline-flex items-center justify-center w-[36px] h-[36px] border-none rounded-[999px] bg-[var(--cw-subtle-bg)] cursor-pointer text-[var(--cw-text)]",
  bottomNav: "absolute left-[50%] bottom-[var(--lf-space-5)] [transform:translateX(-50%)] flex items-center gap-lf-4 p-[var(--lf-space-2)_var(--lf-space-5)] rounded-[999px] bg-[var(--cw-surface)] shadow-[var(--cw-float-shadow)]",
  bottomNavBtn: "inline-flex items-center justify-center w-[40px] h-[40px] border-none rounded-[999px] bg-transparent text-[var(--cw-text-muted)] cursor-pointer",
  bottomNavBtnActive: "bg-[var(--cw-pill)] text-[var(--cw-pill-text)]",
  btcNavIcon: "text-[1rem] font-bold",
  detailActionBtn: "inline-flex items-center justify-center w-[44px] h-[44px] border-none rounded-[999px] bg-[var(--cw-bg)] text-[var(--cw-text)] cursor-pointer",
  detailActions: "absolute left-[50%] bottom-[var(--lf-space-5)] [transform:translateX(-50%)] flex items-center gap-lf-3 p-[var(--lf-space-2)_var(--lf-space-4)] rounded-[999px] bg-[var(--cw-surface)] shadow-[var(--cw-float-shadow)]",
  detailChart: "m-[var(--lf-space-2)_calc(var(--lf-space-2)_*_-1)_var(--lf-space-3)]",
  detailHeader: "grid grid-cols-[40px_1fr_40px] items-center mb-lf-4",
  detailIcon: "inline-flex items-center justify-center w-[36px] h-[36px] rounded-[999px] text-[0.875rem] font-bold text-[#fff] [justify-self:end]",
  detailTitle: "m-0 text-[1.125rem] font-semibold text-center",
  holdingAmount: "text-[1.25rem] font-bold [font-variant-numeric:tabular-nums]",
  holdingCard: "flex flex-col gap-[4px] p-lf-4 mb-lf-5 rounded-[20px] bg-[var(--cw-surface)] shadow-[var(--cw-card-shadow)]",
  holdingLabel: "text-[0.8125rem] text-[var(--cw-text-muted)]",
  holdingUsd: "text-[0.875rem] text-[var(--cw-text-muted)] [font-variant-numeric:tabular-nums]",
  periodPill: "p-[6px_10px] border-none rounded-[999px] bg-transparent text-[0.8125rem] font-medium text-[var(--cw-text-muted)] cursor-pointer",
  periodPillActive: "bg-[var(--cw-warning-bg)] text-[var(--cw-warning-text)]",
  periodRow: "flex flex-wrap gap-lf-1 mb-lf-4",
  phone: "flex justify-center p-[var(--lf-space-4)_var(--lf-space-5)_var(--lf-space-8)]",
  phoneScreen: "w-full max-w-[390px] min-h-[720px] p-[var(--lf-space-5)_var(--lf-space-4)_calc(var(--lf-space-8)_+_72px)] rounded-[32px] bg-[var(--cw-bg)] text-[var(--cw-text)] font-sans relative shadow-[0_0_0_1px_var(--cw-phone-ring),_var(--cw-phone-shadow)]",
  portfolioHeader: "mb-lf-5",
  portfolioTitle: "m-[0_0_var(--lf-space-4)] text-[2.5rem] font-bold [letter-spacing:-0.04em] leading-none",
  priceAmount: "text-[2rem] font-bold [letter-spacing:-0.03em] [font-variant-numeric:tabular-nums]",
  priceBlock: "flex flex-col gap-[6px] mb-lf-3",
  priceChange: "text-[0.875rem] font-medium text-[var(--cw-success)]",
};
export default styles;
