/** Tailwind class map — converted from FilePreviewPane.module.css */
const styles: Record<string, string> = {
  accent: "bg-lf-accent-muted text-lf-accent",
  codePreview: "m-0 p-lf-4 rounded-lf-lg bg-lf-surface-sunken text-lf-text-primary font-mono text-lf-sm leading-normal [overflow-x:auto] whitespace-pre-wrap",
  danger: "bg-lf-danger-muted text-lf-danger",
  empty: "h-full justify-center",
  fileName: "overflow-hidden text-ellipsis whitespace-nowrap text-lf-md font-semibold text-lf-text-primary",
  footer: "[flex-shrink:0] flex gap-lf-2 p-[var(--lf-space-3)_var(--lf-space-4)] border-t border-lf-divider",
  header: "[flex-shrink:0] flex items-center justify-between gap-lf-2 p-[var(--lf-space-3)_var(--lf-space-4)] border-b border-lf-divider",
  headerActions: "flex items-center gap-lf-1",
  headerTitle: "flex items-center gap-lf-2 min-w-0",
  icon: "flex items-center justify-center [flex-shrink:0] w-[28px] h-[28px] rounded-lf-md",
  metaList: "m-0 flex flex-col gap-lf-2",
  metaRow: "grid grid-cols-[88px_1fr] gap-lf-2 text-lf-sm",
  "metaRow dd": "m-0 text-lf-text-primary",
  "metaRow dt": "m-0 text-lf-text-tertiary",
  metaSection: "p-lf-4",
  neutral: "bg-lf-surface-3 text-lf-text-secondary",
  ownerValue: "flex items-center gap-lf-2",
  pane: "h-full flex flex-col min-h-0 bg-lf-surface-1",
  previewArea: "p-lf-4 border-b border-lf-divider",
  previewImage: "w-full max-h-[220px] object-contain rounded-lf-md bg-lf-surface-2",
  previewPlaceholder: "flex flex-col items-center justify-center gap-lf-2 min-h-[180px] rounded-lf-lg text-lf-text-secondary text-lf-sm",
  previewText: "m-0 text-lf-sm leading-[1.6] text-lf-text-secondary",
  scroll: "flex-1 min-h-0",
  sectionTitle: "m-[0_0_var(--lf-space-3)] text-lf-xs font-semibold uppercase [letter-spacing:0.04em] text-lf-text-tertiary",
  success: "bg-lf-success-muted text-lf-success",
  textSection: "p-lf-4 border-t border-lf-divider",
  warning: "bg-lf-warning-muted text-lf-warning",
};
export default styles;
