/** Tailwind class map — converted from app-icon-tile.module.css */
const styles: Record<string, string> = {
  dock: "w-[40px] h-[40px] rounded-[10px]",
  dockMac: "w-[48px] h-[48px] rounded-[12px]",
  hueAmber: "bg-[var(--lf-app-hue-amber-solid)]",
  hueBlue: "bg-[var(--lf-app-hue-blue-solid)]",
  hueCyan: "bg-[var(--lf-app-hue-cyan-solid)]",
  hueEmerald: "bg-[var(--lf-app-hue-emerald-solid)]",
  hueGold: "bg-[var(--lf-app-hue-gold-solid)]",
  hueGraphite: "bg-[var(--lf-app-hue-graphite-solid)]",
  hueGreen: "bg-[var(--lf-app-hue-green-solid)]",
  hueIndigo: "bg-[var(--lf-app-hue-indigo-solid)]",
  hueLime: "bg-[var(--lf-app-hue-lime-solid)]",
  hueOrange: "bg-[var(--lf-app-hue-orange-solid)]",
  huePurple: "bg-[var(--lf-app-hue-purple-solid)]",
  hueRose: "bg-[var(--lf-app-hue-rose-solid)]",
  hueSky: "bg-[var(--lf-app-hue-sky-solid)]",
  hueSlate: "bg-[var(--lf-app-hue-slate-solid)]",
  hueTeal: "bg-[var(--lf-app-hue-teal-solid)]",
  hueViolet: "bg-[var(--lf-app-hue-violet-solid)]",
  lg: "w-[52px] h-[52px] rounded-[12px]",
  md: "w-[44px] h-[44px] rounded-lf-lg",
  sm: "w-[32px] h-[32px] rounded-lf-md",
  taskbar: "w-[28px] h-[28px] rounded-[7px]",
  tile: "inline-flex items-center justify-center [flex-shrink:0] border border-solid border-[var(--lf-app-icon-solid-border)] text-lf-text-on-accent shadow-[var(--lf-app-icon-solid-shadow)] transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)]",
  tileGradient: "border-[var(--lf-app-icon-border)] shadow-[var(--lf-app-icon-shadow)]",
  tileGradient_hueAmber: "bg-[linear-gradient(155deg,_var(--lf-app-hue-amber-from),_var(--lf-app-hue-amber-to))]",
  tileGradient_hueBlue: "bg-[linear-gradient(155deg,_var(--lf-app-hue-blue-from),_var(--lf-app-hue-blue-to))]",
  tileGradient_hueCyan: "bg-[linear-gradient(155deg,_var(--lf-app-hue-cyan-from),_var(--lf-app-hue-cyan-to))]",
  tileGradient_hueEmerald: "bg-[linear-gradient(155deg,_var(--lf-app-hue-emerald-from),_var(--lf-app-hue-emerald-to))]",
  tileGradient_hueGold: "bg-[linear-gradient(155deg,_var(--lf-app-hue-gold-from),_var(--lf-app-hue-gold-to))]",
  tileGradient_hueGraphite: "bg-[linear-gradient(155deg,_var(--lf-app-hue-graphite-from),_var(--lf-app-hue-graphite-to))] text-lf-text-primary",
  tileGradient_hueGreen: "bg-[linear-gradient(155deg,_var(--lf-app-hue-green-from),_var(--lf-app-hue-green-to))]",
  tileGradient_hueIndigo: "bg-[linear-gradient(155deg,_var(--lf-app-hue-indigo-from),_var(--lf-app-hue-indigo-to))]",
  tileGradient_hueLime: "bg-[linear-gradient(155deg,_var(--lf-app-hue-lime-from),_var(--lf-app-hue-lime-to))]",
  tileGradient_hueOrange: "bg-[linear-gradient(155deg,_var(--lf-app-hue-orange-from),_var(--lf-app-hue-orange-to))]",
  tileGradient_huePurple: "bg-[linear-gradient(155deg,_var(--lf-app-hue-purple-from),_var(--lf-app-hue-purple-to))]",
  tileGradient_hueRose: "bg-[linear-gradient(155deg,_var(--lf-app-hue-rose-from),_var(--lf-app-hue-rose-to))]",
  tileGradient_hueSky: "bg-[linear-gradient(155deg,_var(--lf-app-hue-sky-from),_var(--lf-app-hue-sky-to))]",
  tileGradient_hueSlate: "bg-[linear-gradient(155deg,_var(--lf-app-hue-slate-from),_var(--lf-app-hue-slate-to))] text-lf-text-primary",
  tileGradient_hueTeal: "bg-[linear-gradient(155deg,_var(--lf-app-hue-teal-from),_var(--lf-app-hue-teal-to))]",
  tileGradient_hueViolet: "bg-[linear-gradient(155deg,_var(--lf-app-hue-violet-from),_var(--lf-app-hue-violet-to))]",
  tileLight: "text-[rgba(20,_20,_24,_0.92)]",
  xl: "w-[60px] h-[60px] rounded-[14px]",
  xs: "w-[24px] h-[24px] rounded-[6px]",
};
export default styles;
