/** Tailwind class map — converted from SettingsWorkspace.module.css */
const styles: Record<string, string> = {
  contentListItem: "relative text-lf-sm min-h-[52px] w-[calc(100%_+_var(--lf-space-4))] [margin-inline:calc(var(--lf-space-2)_*_-1)]",
  contentSection: "[scroll-margin-top:var(--lf-space-4)]",
  emptySection: "p-[var(--lf-space-6)_0] text-lf-text-secondary text-lf-md",
  fieldActions: "[flex-shrink:0] flex items-center gap-lf-2",
  fieldLabel: "[flex:0_0_160px] text-lf-md font-semibold text-lf-text-primary [flex-basis:120px]",
  fieldRow: "relative flex items-center gap-lf-4 min-h-[52px] p-[var(--lf-space-3)_0]",
  fieldValueWrap: "flex-1 min-w-0 flex items-center gap-lf-3 text-lf-text-secondary text-lf-md",
  linkAction: "text-[var(--settings-link)] hover:enabled:text-[var(--settings-link)] hover:enabled:bg-transparent hover:enabled:[text-decoration:underline]",
  main: "flex-1 min-w-0 min-h-0 flex flex-col",
  mainHeader: "[flex-shrink:0] flex items-center justify-between p-[var(--lf-space-5)_var(--lf-space-8)_var(--lf-space-4)] bg-[var(--settings-content-bg)] pl-lf-4 pr-lf-4",
  mainInner: "max-w-[740px] p-[var(--lf-space-2)_var(--lf-space-8)_var(--lf-space-8)] pl-lf-4 pr-lf-4",
  mainScroll: "flex-1 min-h-0",
  mainTitle: "text-lf-xl font-bold leading-[var(--lf-line-height-tight)]",
  navItems: "flex flex-col gap-lf-1",
  navListItem: "text-lf-sm rounded-lf-md",
  promoBadge: "bg-[linear-gradient(90deg,_#ff73fa_0%,_#a855f7_100%)] text-[#fff] text-[9px] font-[800] [letter-spacing:0.02em] h-auto p-[2px_6px]",
  searchInput: "mb-0",
  sectionDivider: "m-[var(--lf-space-7)_0]",
  sectionIntro: "m-[calc(var(--lf-space-4)_*_-1)_0_var(--lf-space-5)] text-lf-text-secondary text-lf-md leading-[var(--lf-line-height-normal)]",
  sectionIntroLead: "mt-0",
  sectionTitle: "m-[0_0_var(--lf-space-5)] text-lf-lg font-bold leading-[var(--lf-line-height-tight)]",
  sidebar: "h-full",
  sidebarResizable: "[flex-shrink:0] w-full max-h-[40%] border-b border-[var(--settings-divider)]",
  standingBody: "flex-1 min-w-0",
  standingCard: "flex items-start gap-lf-4",
  standingDescription: "m-0 text-lf-text-secondary text-lf-sm leading-[var(--lf-line-height-normal)]",
  "standingDescription a": "text-[var(--settings-link)] no-underline hover:[text-decoration:underline]",
  standingIcon: "[flex-shrink:0] flex items-center justify-center w-[40px] h-[40px] rounded-full bg-lf-success-muted text-lf-success",
  standingIconRestricted: "bg-lf-danger-muted text-lf-danger",
  standingIconWarning: "bg-lf-warning-muted text-lf-warning",
  standingTitle: "m-[0_0_4px] text-lf-base font-bold",
  subNav: "flex flex-col gap-lf-1 m-[var(--lf-space-1)_0_0] pl-lf-2",
  subNavItem: "pl-[calc(var(--lf-space-2)_+_15px_+_var(--lf-space-2))]",
  toggleBody: "flex-1 min-w-0",
  toggleDescription: "mt-[2px] text-lf-text-secondary text-lf-sm",
  toggleKnob: "absolute top-[3px] left-[3px] w-[18px] h-[18px] rounded-full bg-[#fff] transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)]",
  toggleLabel: "[flex:0_0_160px] text-lf-md font-semibold text-lf-text-primary [flex-basis:120px]",
  toggleRow: "relative flex items-center gap-lf-4 min-h-[52px] p-[var(--lf-space-3)_0]",
  toggleSwitch: "relative w-[40px] h-[24px] [flex-shrink:0] border-none rounded-lf-pill bg-lf-surface-3 cursor-pointer transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)]",
  toggleSwitchOn: "bg-lf-success",
  toggleSwitchOn_toggleKnob: "[transform:translateX(16px)]",
  workspace: "[--settings-content-bg:var(--lf-surface-1)] [--settings-link:#00a8fc] [--settings-divider:var(--lf-divider)] flex min-h-0 h-full bg-[var(--settings-content-bg)] text-lf-text-primary font-sans flex-col",
};
export default styles;
