import type { ComposerWorkspaceData } from "./types";

export const COMPOSER_SAMPLE_DATA: ComposerWorkspaceData = {
  productName: "Composer",
  user: {
    name: "tirufm",
    handle: "Tiru.fm",
    plan: "Pro Plan",
    upgradeLabel: "Upgrade to Premier",
  },
  navItems: [
    { id: "home", label: "Home", icon: "home" },
    { id: "explore", label: "Explore", icon: "globe" },
    { id: "create", label: "Create", icon: "sparkles" },
    { id: "studio", label: "Studio", icon: "layers" },
    { id: "library", label: "Library", icon: "list" },
    { id: "notifications", label: "Notifications", icon: "bell", badge: 2 },
  ],
  tracks: [
    {
      id: "yumi",
      title: "Yumi",
      version: "v3",
      description: "Gangster rap with Native American drums",
      duration: "1:05",
      durationSeconds: 65,
      artTone: "orange",
    },
    {
      id: "vismayo",
      title: "V. VISMAYO YOGABHŪMIKĀḤ",
      version: "v3",
      description: "Light russian pop song about escapism",
      duration: "3:43",
      durationSeconds: 223,
      artTone: "violet",
      liked: true,
    },
    {
      id: "neon-drift",
      title: "Neon Drift",
      version: "v4",
      description: "Synthwave instrumental with deep bass",
      duration: "2:18",
      durationSeconds: 138,
      artTone: "cyan",
    },
    {
      id: "midnight-garden",
      title: "Midnight Garden",
      version: "v3.5",
      description: "Dreamy lo-fi with vinyl crackle",
      duration: "3:36",
      durationSeconds: 216,
      artTone: "green",
    },
    {
      id: "pulse-wave",
      title: "Pulse Wave",
      version: "v4",
      description: "Pop-dance, 4/4 time, emo vocal",
      duration: "2:52",
      durationSeconds: 172,
      artTone: "pink",
    },
  ],
  styleSuggestions: ["minimalist beats", "deep vocal", "pop-dance", "4/4 time", "emo"],
  defaultPrompt: "Light russian pop song about escapism.",
  nowPlaying: {
    track: {
      id: "vismayo",
      title: "V. VISMAYO YOGABHŪMIKĀḤ",
      version: "v3",
      description: "Light russian pop song about escapism",
      duration: "3:43",
      durationSeconds: 223,
      artTone: "violet",
      liked: true,
    },
    progress: 19,
    elapsed: "0:45",
    creator: "Tiru.fm",
  },
};
