/** Tailwind class map — converted from SpecialPages.module.css */
const styles: Record<string, string> = {
  card: "w-full max-w-[360px]",
  cardBody: "flex flex-col gap-lf-3 p-[var(--lf-space-4)_var(--lf-space-5)]",
  cardFooter: "flex flex-col gap-lf-3 p-[var(--lf-space-4)_var(--lf-space-5)_var(--lf-space-5)] border-t border-lf-divider",
  cardHeader: "flex flex-col gap-lf-3 p-[var(--lf-space-5)_var(--lf-space-5)_var(--lf-space-3)] items-center text-center",
  centered: "w-full max-w-[360px] flex flex-col items-center gap-lf-4 text-center",
  errorIcon: "w-[48px] h-[48px] grid [place-items:center] rounded-[var(--lf-radius-full)] bg-lf-danger-muted text-lf-danger",
  featureItem: "flex items-center gap-lf-2 text-lf-sm text-lf-text-secondary",
  "featureItem svg": "[flex-shrink:0] text-lf-accent",
  featureList: "m-0 p-0 list-none flex flex-col gap-lf-2 text-left",
  footerNote: "m-0 text-lf-xs text-lf-text-tertiary text-center leading-normal",
  formField: "flex flex-col gap-lf-1 text-left",
  loader: "text-lf-accent [animation:special-page-spin_1s_linear_infinite]",
  logoMark: "block w-[56px] h-[56px] [flex-shrink:0]",
  page: "flex-1 min-h-0 flex flex-col items-center justify-center p-lf-6 bg-lf-surface-canvas text-lf-text-primary",
  planBadge: "[flex-shrink:0]",
  planCard: "grid grid-cols-[auto_1fr_auto] gap-lf-3 items-center w-full p-lf-4 rounded-lf-lg border border-solid border-lf-border-default bg-lf-surface-2 text-[inherit] cursor-pointer text-left transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:border-lf-border-strong",
  planCardCompact: "p-lf-3",
  planCardSelected: "border-lf-accent-border bg-lf-accent-muted shadow-[0_0_0_1px_var(--lf-accent-border)]",
  planContent: "flex flex-col gap-lf-1 min-w-0",
  planDescription: "text-lf-sm text-lf-text-secondary leading-[1.4]",
  planFeaturePanel: "w-full p-lf-4 rounded-lf-lg border border-solid border-lf-border-subtle bg-lf-surface-1",
  planFeatureTitle: "m-[0_0_var(--lf-space-3)] text-lf-xs font-semibold [letter-spacing:0.04em] uppercase text-lf-text-tertiary",
  planHeader: "flex items-center flex-wrap gap-lf-2",
  planList: "flex flex-col gap-lf-2 w-full",
  planListCompact: "gap-lf-1",
  planName: "text-lf-md font-semibold [letter-spacing:-0.01em]",
  planPrice: "flex items-baseline gap-[2px] [flex-shrink:0]",
  planPriceAmount: "text-lf-lg font-semibold [letter-spacing:-0.02em]",
  planPricePeriod: "text-lf-xs text-lf-text-tertiary",
  planRadio: "grid [place-items:center] w-[18px] h-[18px] rounded-[var(--lf-radius-full)] [border:2px_solid_var(--lf-border-strong)] text-transparent [flex-shrink:0] transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)]",
  planRadioSelected: "border-lf-accent bg-lf-accent text-[var(--lf-text-on-accent,_#fff)]",
  progressFill: "w-[42%] h-full rounded-[inherit] bg-lf-accent [animation:special-page-progress_1.6s_ease-in-out_infinite]",
  progressTrack: "w-full max-w-[200px] h-[3px] rounded-[var(--lf-radius-full)] bg-lf-surface-3 overflow-hidden",
  signInBackdrop: "absolute inset-0 [background-size:cover] [background-position:center] [background-repeat:no-repeat]",
  signInPage: "relative overflow-hidden before:after:[content:\"\"] before:after:absolute before:after:inset-0 before:after:bg-[color-mix(in_srgb,_var(--lf-surface-canvas)_72%,_transparent)] before:after:[backdrop-filter:blur(2px)]",
  stepLabel: "text-lf-xs text-lf-text-tertiary transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)]",
  stepLabelActive: "text-lf-text-primary font-medium",
  stepLabels: "grid grid-cols-[repeat(3,_minmax(0,_1fr))] gap-lf-1",
  stepSegment: "flex-1 h-[3px] rounded-[var(--lf-radius-full)] bg-lf-surface-3 transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)]",
  stepSegmentActive: "opacity-100",
  stepSegmentFilled: "bg-lf-accent opacity-[0.45]",
  stepSegments: "flex gap-lf-1 w-full",
  subtitle: "m-0 text-lf-sm text-lf-text-secondary leading-normal",
  themePicker: "flex flex-col gap-lf-2",
  themePickerLabel: "text-lf-sm font-medium text-lf-text-primary",
  themeSwatch: "w-[28px] h-[28px] rounded-[var(--lf-radius-full)] [border:2px_solid_transparent] cursor-pointer transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:[transform:scale(1.06)]",
  themeSwatches: "flex gap-lf-2",
  themeSwatchSelected: "shadow-[0_0_0_2px_var(--lf-surface-canvas),_0_0_0_4px_var(--lf-text-primary)]",
  title: "m-0 text-lf-lg font-semibold [letter-spacing:-0.02em]",
  wide: "max-w-[480px]",
  wideCard: "max-w-[440px]",
  wizardActions: "flex gap-lf-2 w-full",
  wizardCard: "max-w-[420px]",
  wizardEyebrow: "text-lf-xs font-medium [letter-spacing:0.04em] uppercase text-lf-accent",
  wizardHeading: "flex flex-col gap-lf-1 w-full",
  wizardPanel: "flex flex-col gap-lf-3 w-full p-lf-4 rounded-lf-lg border border-solid border-lf-border-subtle bg-lf-surface-1",
  wizardProgress: "flex flex-col gap-lf-2 w-full",
  wizardStack: "flex flex-col items-center gap-lf-4 w-full max-w-[420px]",
};
export default styles;
