/** Tailwind class map — converted from SocialWorkspace.module.css */
const styles: Record<string, string> = {
  birthdayRow: "flex items-start gap-lf-2 text-lf-text-secondary text-lf-sm leading-[1.45]",
  composer: "flex gap-lf-3 p-lf-4",
  composerActions: "flex items-center gap-lf-1 text-lf-accent",
  composerBlock: "border-bottom border-lf-divider",
  composerBlockFacebook: "mb-lf-3 border border-solid border-lf-border-subtle rounded-lf-lg bg-lf-surface-1 overflow-hidden",
  composerBlockFacebook_composerFooter: "[border-top:none] pt-0",
  composerBody: "flex-1 min-w-0",
  composerFacebook: "p-[var(--lf-space-3)_var(--lf-space-4)]",
  composerFooter: "flex items-center justify-between gap-lf-3 mt-lf-3 pt-lf-3 border-t border-lf-divider",
  composerInput: "border-none bg-transparent p-0 text-lf-lg",
  contactItem: "flex w-full gap-lf-3 p-[var(--lf-space-3)_var(--lf-space-4)] border-none bg-transparent text-left cursor-pointer hover:bg-lf-surface-2 items-center",
  contactsList: "list-none m-0 p-0",
  facebookBody: "flex-1 min-h-0 flex",
  facebookFeedScroll: "h-full p-lf-3",
  facebookLogo: "flex items-center justify-center w-[40px] h-[40px] rounded-lf-pill bg-[#1877f2] text-[#fff] text-[28px] font-bold leading-none",
  facebookMain: "flex-1 min-w-0 max-w-[680px]",
  facebookRight: "flex-1 min-w-[280px] max-w-[360px]",
  facebookRightScroll: "h-full p-lf-3",
  facebookSearch: "w-[240px]",
  facebookShell: "flex-1 min-w-0 flex flex-col min-h-0",
  facebookSidebar: "[flex-shrink:0] w-[280px] bg-[var(--social-sidebar-bg)] border-r border-lf-divider",
  facebookTopBar: "[flex-shrink:0] grid grid-cols-[1fr_auto_1fr] items-center gap-lf-4 p-[var(--lf-space-2)_var(--lf-space-4)] bg-lf-surface-1 border-b border-lf-divider",
  facebookTopLeft: "flex items-center gap-lf-2",
  facebookTopNav: "flex items-center gap-lf-1",
  facebookTopNavItem: "flex items-center justify-center w-[112px] h-[48px] border-none rounded-lf-md bg-transparent text-lf-text-secondary cursor-pointer hover:bg-lf-surface-2",
  facebookTopNavItemActive: "text-lf-accent shadow-[inset_0_-3px_0_var(--lf-accent)]",
  facebookTopRight: "flex items-center justify-end gap-lf-2",
  feed: "flex flex-col",
  feedTabs: "p-[0_var(--lf-space-4)] border-b border-lf-divider",
  "media-accent": "[--media-tone:var(--lf-accent-muted,_var(--lf-accent))]",
  "media-neutral": "[--media-tone:var(--lf-surface-3)]",
  "media-warning": "[--media-tone:var(--lf-warning-muted,_#f59e0b)]",
  mediaImage: "relative min-h-[220px] bg-[linear-gradient(135deg,_var(--media-tone),_var(--lf-surface-2))]",
  mediaImageLabel: "absolute left-[var(--lf-space-3)] bottom-[var(--lf-space-3)] p-[var(--lf-space-1)_var(--lf-space-2)] rounded-lf-sm bg-[rgba(0,_0,_0,_0.55)] text-[#fff] text-lf-sm static m-lf-4 bg-transparent text-lf-text-primary font-semibold",
  mediaLabel: "absolute left-[var(--lf-space-3)] bottom-[var(--lf-space-3)] p-[var(--lf-space-1)_var(--lf-space-2)] rounded-lf-sm bg-[rgba(0,_0,_0,_0.55)] text-[#fff] text-lf-sm",
  mediaPlay: "absolute inset-0 flex items-center justify-center m-auto w-[56px] h-[56px] border-none rounded-lf-pill bg-[rgba(0,_0,_0,_0.65)] text-[#fff] cursor-pointer",
  mediaVideo: "relative min-h-[220px] bg-[linear-gradient(135deg,_var(--media-tone),_var(--lf-surface-2))]",
  newsBody: "min-w-0",
  newsHeadline: "font-bold leading-[1.3] mb-[4px]",
  newsItem: "flex w-full gap-lf-3 p-[var(--lf-space-3)_var(--lf-space-4)] border-none bg-transparent text-left cursor-pointer hover:bg-lf-surface-2",
  newsList: "list-none m-0 p-0",
  newsMeta: "text-lf-text-secondary text-lf-xs",
  newsThumb: "[flex-shrink:0] w-[72px] h-[72px] rounded-lf-md bg-[linear-gradient(135deg,_var(--media-tone,_var(--lf-surface-3)),_var(--lf-surface-2))]",
  post: "flex gap-lf-3 p-lf-4 border-b border-lf-divider",
  postAuthor: "font-bold text-lf-text-primary",
  postBody: "flex-1 min-w-0",
  postContent: "mb-lf-3 leading-[1.45] whitespace-pre-wrap",
  postDot: "text-lf-text-secondary",
  postFacebook: "mb-lf-3 border border-solid border-lf-border-subtle rounded-lf-lg bg-lf-surface-1",
  postHandle: "text-lf-text-secondary text-lf-sm",
  postHeader: "flex items-start justify-between gap-lf-2 mb-lf-1",
  postIdentity: "flex flex-wrap items-center gap-[4px] min-w-0",
  postMedia: "mb-lf-3 rounded-lf-lg overflow-hidden border border-solid border-lf-border-subtle",
  postTime: "text-lf-text-secondary text-lf-sm",
  postVisibility: "text-lf-text-secondary",
  rail: "[flex-shrink:0] w-[68px] flex flex-col items-center p-[var(--lf-space-3)_var(--lf-space-2)] bg-[var(--social-rail-bg)] border-r border-lf-divider",
  railNetwork: "relative flex items-center justify-center w-[44px] h-[44px] border-none rounded-lf-lg bg-[var(--social-accent,_var(--lf-surface-3))] text-lf-text-on-accent text-lf-md font-[800] cursor-pointer transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:rounded-lf-md",
  railNetworkActive: "rounded-lf-md before:before:[content:\"\"] before:before:absolute before:before:left-[-10px] before:before:w-[3px] before:before:h-[20px] before:before:rounded-lf-pill before:before:bg-lf-accent",
  railNetworks: "flex flex-col items-center gap-lf-2 w-full",
  reactionButton: "inline-flex items-center gap-[6px] border-none bg-transparent text-[inherit] text-lf-sm p-[var(--lf-space-1)_var(--lf-space-2)] rounded-lf-pill cursor-pointer hover:text-lf-accent hover:bg-lf-surface-2",
  reactions: "flex items-center justify-between gap-lf-1 max-w-[420px] text-lf-text-secondary",
  reactionsFacebook: "max-w-[none] pt-lf-2 border-t border-lf-divider",
  shortcutAvatar: "flex items-center justify-center w-[28px] h-[28px] rounded-lf-sm text-[#fff] text-[10px] font-bold",
  sponsoredCopy: "p-[0_var(--lf-space-4)_var(--lf-space-4)] text-lf-text-secondary text-lf-sm",
  sponsoredThumb: "h-[160px] m-[0_var(--lf-space-4)_var(--lf-space-3)] rounded-lf-md bg-[linear-gradient(135deg,_var(--lf-surface-3),_var(--lf-surface-2))]",
  storiesRow: "flex gap-lf-2 p-[var(--lf-space-1)_0]",
  storiesScroll: "mb-lf-3",
  storyAvatarWrap: "absolute top-[var(--lf-space-2)] left-[var(--lf-space-2)] [border:3px_solid_var(--lf-accent)] rounded-lf-pill",
  storyCard: "relative [flex-shrink:0] w-[112px] h-[200px] border-none rounded-lf-lg overflow-hidden bg-lf-surface-2 cursor-pointer text-left",
  storyCardCreate: "",
  storyCardCreate_storyLabel: "bottom-[var(--lf-space-3)] text-center",
  storyCreateBg: "h-[70%] bg-lf-surface-3",
  storyCreatePlus: "absolute top-[58%] left-[50%] [transform:translate(-50%,_-50%)] flex items-center justify-center w-[36px] h-[36px] rounded-lf-pill bg-lf-accent text-lf-text-on-accent [border:3px_solid_var(--lf-surface-1)]",
  storyLabel: "absolute left-[var(--lf-space-2)] right-[var(--lf-space-2)] bottom-[var(--lf-space-2)] text-lf-xs font-semibold text-lf-text-primary whitespace-nowrap overflow-hidden text-ellipsis",
  storyThumb: "h-full bg-[linear-gradient(160deg,_var(--lf-surface-3),_var(--lf-surface-2))]",
  suggestionBio: "text-lf-text-secondary text-lf-sm",
  suggestionBody: "flex-1 min-w-0",
  suggestionHandle: "text-lf-text-secondary text-lf-sm",
  suggestionItem: "flex items-start gap-lf-3 p-[var(--lf-space-3)_var(--lf-space-4)]",
  suggestionName: "font-bold",
  suggestionsList: "list-none m-0 p-0",
  trendCategory: "text-lf-text-secondary text-lf-xs",
  trendItem: "flex w-full gap-lf-3 p-[var(--lf-space-3)_var(--lf-space-4)] border-none bg-transparent text-left cursor-pointer hover:bg-lf-surface-2",
  trendMeta: "text-lf-text-secondary text-lf-xs",
  trendsList: "list-none m-0 p-0",
  trendTopic: "font-bold m-[2px_0]",
  twitterFeedScroll: "h-full",
  twitterMain: "flex-1 min-w-0 max-w-[600px] border-r border-lf-divider",
  twitterNav: "[flex-shrink:0] w-[260px] bg-[var(--social-sidebar-bg)] border-r border-lf-divider",
  twitterNavItem: "text-lf-lg font-semibold",
  twitterPostButton: "m-[var(--lf-space-3)_var(--lf-space-4)] rounded-lf-pill",
  twitterRight: "flex-1 min-w-[280px] max-w-[380px]",
  twitterRightScroll: "h-full p-lf-3",
  verifiedBadge: "inline-flex items-center justify-center w-[16px] h-[16px] rounded-lf-pill bg-lf-accent text-lf-text-on-accent",
  widgetCard: "overflow-hidden",
  widgetCopy: "m-[0_0_var(--lf-space-3)] text-lf-text-secondary text-lf-sm leading-[1.45]",
  widgetHeader: "p-[var(--lf-space-3)_var(--lf-space-4)] text-lf-lg font-[800]",
  widgetHeaderInline: "p-[var(--lf-space-3)_var(--lf-space-4)] text-lf-lg font-[800] pb-lf-2",
  widgetSearch: "w-full",
  widgetStack: "flex flex-col gap-lf-3",
  widgetTitle: "text-lf-lg font-[800] mb-lf-2",
  workspace: "[--social-rail-bg:var(--lf-surface-sunken)] [--social-sidebar-bg:var(--lf-surface-1)] [--social-accent:var(--lf-accent)] h-full flex min-h-0 bg-lf-surface-canvas",
};
export default styles;
