/** Tailwind class map — converted from DeviceCard.module.css */
const styles: Record<string, string> = {
  accent: "",
  accentText: "text-lf-accent",
  body: "min-w-0 flex flex-col gap-lf-1",
  card: "relative overflow-hidden rounded-lf-xl border border-solid border-lf-border-subtle bg-lf-surface-2 min-h-[96px]",
  content: "relative flex items-center justify-between gap-lf-3 p-lf-4 h-full",
  dragging: "border-lf-border-default",
  "icon-accent": "bg-lf-accent-muted text-lf-accent",
  "icon-neutral": "bg-lf-surface-3 text-lf-text-primary",
  "icon-success": "bg-lf-success-muted text-lf-success",
  "icon-warning": "bg-lf-warning-muted text-lf-warning",
  iconTile: "flex items-center justify-center w-[40px] h-[40px] rounded-lf-pill [flex-shrink:0]",
  interactive: "[cursor:ew-resize] [touch-action:none]",
  meta: "flex items-center gap-lf-2 flex-wrap",
  neutral: "",
  neutralText: "text-lf-text-secondary",
  progress: "absolute top-0 bottom-0 left-0 bg-lf-surface-3 opacity-[0.85] pointer-events-none",
  progressRight: "left-auto right-0",
  status: "text-lf-sm font-semibold",
  status_accent: "text-lf-accent",
  status_neutral: "text-lf-text-secondary",
  status_success: "text-lf-success",
  status_warning: "text-lf-warning",
  subtitle: "text-lf-sm text-lf-text-tertiary",
  success: "",
  successText: "text-lf-success",
  title: "text-lf-md font-semibold text-lf-text-primary",
  warning: "",
  warningText: "text-lf-warning",
};
export default styles;
