/** Tailwind class map — converted from DashboardView.module.css */
const styles: Record<string, string> = {
  agentDescription: "text-lf-text-secondary",
  agentName: "font-semibold text-lf-text-primary",
  agentsSection: "flex flex-col gap-lf-3",
  breadcrumb: "inline-flex items-center gap-lf-1 p-0 mb-lf-4 border-none bg-transparent text-lf-sm text-lf-text-secondary cursor-pointer hover:text-lf-text-primary",
  columnsBtn: "ml-auto",
  dashboard: "p-lf-6 max-w-[1280px]",
  empty: "p-lf-8 text-center text-lf-text-tertiary",
  metricCard: "relative min-h-[96px]",
  metricHead: "flex items-start justify-between gap-lf-2 mb-lf-3",
  metricIcon: "inline-flex items-center justify-center w-[28px] h-[28px] rounded-lf-md [flex-shrink:0]",
  metricIconAccent: "bg-lf-accent-muted text-lf-accent",
  metricIconNeutral: "bg-lf-surface-sunken text-lf-text-secondary",
  metricIconSuccess: "bg-lf-success-muted text-lf-success",
  metricLabel: "text-lf-sm text-lf-text-secondary",
  metrics: "grid grid-cols-[repeat(4,_minmax(0,_1fr))] gap-lf-3 mb-lf-6 grid-cols-[repeat(2,_minmax(0,_1fr))] grid-cols-[1fr]",
  metricValue: "text-lf-xl font-bold [letter-spacing:-0.02em] text-lf-text-primary",
  metricValueSuccess: "text-lf-success",
  pageBtn: "min-w-[32px]",
  pageBtnActive: "bg-lf-accent-muted text-lf-accent",
  pagination: "flex items-center justify-end gap-lf-1 p-[var(--lf-space-3)_var(--lf-space-4)] border-t border-lf-divider",
  search: "flex-1 max-w-[320px] max-w-[none] w-full",
  sortBtn: "inline-flex items-center gap-lf-1 p-0 border-none bg-transparent [font:inherit] text-[inherit] cursor-pointer hover:text-lf-text-primary",
  table: "w-full [border-collapse:collapse] text-lf-sm",
  "table tbody tr": "last:[border-bottom:none] hover:bg-lf-surface-sunken",
  "table td": "p-[var(--lf-space-3)_var(--lf-space-4)] text-left border-b border-lf-divider",
  "table th": "p-[var(--lf-space-3)_var(--lf-space-4)] text-left border-b border-lf-divider text-lf-xs font-semibold text-lf-text-tertiary uppercase [letter-spacing:0.04em] bg-lf-surface-sunken",
  tableCard: "overflow-hidden",
  tableWrap: "[overflow-x:auto]",
  toolbar: "flex items-center gap-lf-3 flex-wrap",
};
export default styles;
