/** Tailwind class map — converted from ProjectsDashboardView.module.css */
const styles: Record<string, string> = {
  addBtn: "inline-flex items-center gap-lf-1 p-[var(--lf-space-2)_var(--lf-space-3)] border-none rounded-lf-lg bg-lf-text-primary text-lf-sm font-medium cursor-pointer text-lf-surface-canvas",
  body: "grid grid-cols-[280px_1fr] gap-lf-6 [align-items:start] grid-cols-[1fr]",
  branch: "inline-flex items-center gap-[4px]",
  breadcrumb: "inline-flex items-center gap-lf-1 p-0 border-none bg-transparent text-lf-sm text-lf-text-secondary cursor-pointer",
  commitMessage: "m-0 text-lf-xs text-lf-text-secondary overflow-hidden text-ellipsis whitespace-nowrap",
  dashboard: "p-lf-6 max-w-[1400px] p-lf-4",
  header: "mb-lf-4",
  headerLeft: "flex flex-col gap-lf-1",
  moreBtn: "inline-flex items-center justify-center w-[24px] h-[24px] border-none rounded-lf-sm bg-transparent cursor-pointer text-lf-text-tertiary",
  previewActions: "flex items-center gap-lf-2 mt-lf-1",
  "previewActions button": "p-0 border-none bg-transparent text-lf-xs font-medium cursor-pointer text-lf-accent",
  previewBody: "flex-1 min-w-0",
  previewBranch: "text-lf-xs font-semibold text-lf-text-primary",
  previewCommit: "text-lf-xs text-lf-text-tertiary overflow-hidden text-ellipsis whitespace-nowrap",
  previewItem: "flex gap-lf-2",
  previewList: "list-none m-0 p-0 flex flex-col gap-lf-4",
  previewTime: "ml-auto text-lf-xs text-lf-text-tertiary",
  projectActions: "flex items-center gap-lf-1",
  projectCard: "flex flex-col gap-lf-3",
  projectFooter: "flex items-center justify-between text-lf-xs text-lf-text-tertiary",
  projectIcon: "[flex-shrink:0] inline-flex items-center justify-center w-[36px] h-[36px] rounded-lf-lg text-lf-sm font-semibold",
  projectIdentity: "flex gap-lf-3 min-w-0",
  projectMeta: "flex items-center justify-between gap-lf-2",
  projectName: "text-lf-sm font-semibold text-lf-text-primary",
  projects: "grid grid-cols-[repeat(auto-fill,_minmax(280px,_1fr))] gap-lf-4",
  projectsList: "grid-cols-[1fr]",
  projectTop: "flex items-start justify-between gap-lf-2",
  projectUrl: "block text-lf-xs text-lf-accent no-underline overflow-hidden text-ellipsis whitespace-nowrap",
  repo: "inline-flex items-center gap-lf-1 text-lf-xs text-lf-text-tertiary overflow-hidden text-ellipsis whitespace-nowrap",
  searchBar: "flex-1 flex items-center gap-lf-2 p-[var(--lf-space-2)_var(--lf-space-3)] border border-solid border-lf-border-subtle rounded-lf-lg bg-lf-surface-sunken text-lf-sm text-lf-text-tertiary",
  statusBuilding: "text-lf-warning [animation:spin_1s_linear_infinite]",
  statusError: "text-lf-danger",
  statusReady: "text-lf-accent",
  statusStopped: "text-lf-text-tertiary",
  title: "m-0 text-lf-2xl font-semibold [letter-spacing:-0.02em]",
  toolbar: "flex items-center gap-lf-3 mb-lf-6 flex-col items-stretch",
  toolbarActions: "flex items-center gap-lf-2",
  upgradeBtn: "p-[2px_8px] border border-solid border-lf-border-subtle rounded-lf-md bg-transparent text-lf-xs font-medium cursor-pointer text-lf-text-primary",
  usageInfo: "flex-1 flex flex-col gap-[2px] min-w-0",
  usageItem: "flex items-center gap-lf-3",
  usageLabel: "text-lf-xs text-lf-text-secondary",
  usageList: "list-none m-0 p-0 flex flex-col gap-lf-3",
  usageRing: "[flex-shrink:0]",
  usageRingExceeded: "[stroke:var(--lf-warning)]",
  usageRingFill: "[fill:none] [stroke:var(--lf-accent)] [stroke-width:2.5] [stroke-linecap:round]",
  usageRingTrack: "[fill:none] [stroke:var(--lf-border-subtle)] [stroke-width:2.5]",
  usageValue: "text-lf-xs font-medium text-lf-text-primary",
  usageValueExceeded: "text-lf-warning",
  usageWarning: "flex items-center gap-lf-2 p-lf-2 rounded-lf-md bg-lf-warning-muted text-lf-xs font-medium text-lf-warning",
  viewBtn: "inline-flex items-center justify-center w-[32px] h-[32px] border-none bg-lf-surface-1 text-lf-text-tertiary cursor-pointer",
  viewBtnActive: "bg-lf-surface-sunken text-lf-text-primary",
  viewToggle: "flex border border-solid border-lf-border-subtle rounded-lf-md overflow-hidden",
  widget: "flex flex-col gap-lf-3",
  widgetEmpty: "m-0 text-lf-xs leading-normal text-lf-text-tertiary",
  widgetHeader: "flex items-center justify-between",
  widgets: "flex flex-col gap-lf-4 grid grid-cols-[repeat(auto-fit,_minmax(240px,_1fr))]",
  widgetTitle: "m-0 text-lf-sm font-semibold",
};
export default styles;
