/** Tailwind class map — converted from StorageWidgetsView.module.css */
const styles: Record<string, string> = {
  addBtn: "inline-flex items-center gap-lf-1 p-[var(--lf-space-2)_var(--lf-space-3)] border border-solid border-lf-border-subtle rounded-lf-lg bg-lf-surface-1 text-lf-sm font-medium cursor-pointer text-lf-text-primary [flex-shrink:0]",
  dbIcon: "text-[1.25rem] leading-none",
  dbIdentity: "flex items-center gap-lf-2 min-w-0",
  gauge: "relative flex items-center justify-center m-[var(--lf-space-2)_auto]",
  gaugeCenter: "absolute flex flex-col items-center gap-[2px]",
  gaugeFill: "[fill:none] [stroke-width:6] [stroke-linecap:round]",
  gaugeFill_accent: "[stroke:var(--lf-accent)]",
  gaugeFill_danger: "[stroke:var(--lf-danger)]",
  gaugeFill_warning: "[stroke:var(--lf-warning)]",
  gaugeLabel: "text-lf-xs text-lf-text-tertiary uppercase [letter-spacing:0.04em]",
  gaugePercent: "text-lf-lg font-semibold leading-none",
  gaugeTrack: "[fill:none] [stroke:var(--lf-border-subtle)] [stroke-width:6]",
  header: "flex items-start justify-between gap-lf-4 mb-lf-8 flex-col",
  mountPath: "flex items-center gap-lf-1 p-lf-2 rounded-lf-md bg-lf-surface-sunken text-lf-xs text-lf-text-tertiary",
  "mountPath code": "overflow-hidden text-ellipsis whitespace-nowrap font-mono",
  page: "p-lf-6 max-w-[1200px] p-lf-4",
  progressFill: "block h-full rounded-[inherit] bg-lf-accent",
  progressTrack: "h-[4px] rounded-[var(--lf-radius-full)] bg-lf-divider overflow-hidden",
  section: "mb-lf-8",
  sectionTitle: "m-[0_0_var(--lf-space-4)] text-lf-sm font-semibold text-lf-text-secondary uppercase [letter-spacing:0.04em]",
  serverDiskCard: "max-w-[640px]",
  statLabel: "block text-lf-xs text-lf-text-tertiary mb-[2px]",
  statValue: "text-lf-sm font-medium",
  storageWidget: "flex flex-col gap-lf-3",
  subtitle: "m-0 text-lf-sm text-lf-text-secondary max-w-[520px]",
  title: "m-[0_0_var(--lf-space-1)] text-lf-2xl font-semibold [letter-spacing:-0.02em]",
  widgetGrid: "grid grid-cols-[repeat(auto-fill,_minmax(260px,_1fr))] gap-lf-4",
  widgetName: "m-0 text-lf-sm font-semibold",
  widgetStats: "grid grid-cols-[1fr_1fr] gap-lf-3",
  widgetSub: "m-[2px_0_0] text-lf-xs text-lf-text-tertiary overflow-hidden text-ellipsis whitespace-nowrap",
  widgetTop: "flex items-start justify-between gap-lf-2",
};
export default styles;
