/** Tailwind class map — converted from FitnessWidget.module.css */
const styles: Record<string, string> = {
  actionBtn: "w-full p-[var(--lf-space-2)_var(--lf-space-3)] rounded-lf-pill bg-transparent text-[10px] font-bold [letter-spacing:0.1em] cursor-pointer",
  actionBtnGreen: "border border-solid border-[var(--fitness-accent-green,_#a4c639)] text-[var(--fitness-accent-green,_#a4c639)]",
  actionBtnPink: "border border-solid border-[var(--fitness-accent-pink,_#ffb6c1)] text-[rgba(255,_255,_255,_0.9)]",
  activityLabel: "text-[10px] font-semibold [letter-spacing:0.12em] uppercase text-[var(--fitness-accent-green,_#a4c639)]",
  activityUnit: "text-[11px] font-semibold [letter-spacing:0.08em] text-[rgba(255,_255,_255,_0.55)]",
  activityUnitCenter: "text-[11px] font-semibold [letter-spacing:0.08em] text-[rgba(255,_255,_255,_0.55)] text-center",
  activityValueRow: "flex items-baseline gap-lf-2",
  albumArt: "w-[56px] h-[56px] rounded-lf-md bg-[linear-gradient(145deg,_#2a2a2a,_#444)] [flex-shrink:0]",
  dotMatrix: "font-mono font-normal [letter-spacing:0.04em] leading-none",
  dotMatrixDark: "text-[#121212]",
  dotMatrixLg: "text-[28px]",
  dotMatrixLight: "text-[rgba(255,_255,_255,_0.95)]",
  dotMatrixMd: "text-[20px]",
  dotMatrixSm: "text-[14px]",
  dotMatrixXl: "text-[36px]",
  gymDot: "w-[10px] h-[10px] rounded-[999px] bg-[rgba(255,_255,_255,_0.12)] [justify-self:center]",
  gymDotDone: "bg-[var(--fitness-accent-green,_#a4c639)]",
  gymStreak: "gap-lf-2",
  gymStreakGrid: "grid grid-cols-[repeat(7,_1fr)] gap-[6px] flex-1 [align-content:center]",
  gymStreakHead: "flex items-center gap-lf-2",
  gymStreakIcon: "text-[var(--fitness-accent-pink,_#ffb6c1)]",
  gymStreakMeta: "text-[10px] text-[rgba(255,_255,_255,_0.45)]",
  gymStreakTitle: "text-lf-sm font-semibold",
  gymStreakWeekdays: "grid grid-cols-[repeat(7,_1fr)] gap-[4px] text-[9px] font-semibold text-[rgba(255,_255,_255,_0.35)] text-center",
  heartBadge: "flex items-center justify-center w-[28px] h-[28px] rounded-[999px] bg-[rgba(255,_182,_193,_0.18)] text-[var(--fitness-accent-pink,_#ffb6c1)]",
  heartRate: "gap-lf-3",
  heartRateAvgDot: "absolute right-0 top-[50%] [transform:translateY(-50%)] w-[6px] h-[6px] rounded-[999px] bg-[var(--fitness-accent-green,_#a4c639)]",
  heartRateAvgLine: "absolute left-0 right-0 h-[1px] bg-[var(--fitness-accent-green,_#a4c639)] pointer-events-none",
  heartRateBar: "flex-1 rounded-[2px_2px_0_0] bg-[var(--fitness-accent-pink,_#ffb6c1)] opacity-[0.85]",
  heartRateBars: "flex-1 flex items-end gap-[3px] min-h-[60px]",
  heartRateChart: "relative flex-1 min-w-0 flex flex-col",
  heartRateChartWrap: "flex gap-lf-2 flex-1 min-h-0",
  heartRateDate: "text-[10px] text-[rgba(255,_255,_255,_0.45)]",
  heartRateHead: "flex items-center gap-lf-2",
  heartRateStatLabel: "text-[9px] font-bold [letter-spacing:0.08em] text-[rgba(255,_255,_255,_0.45)]",
  heartRateStats: "flex gap-lf-4",
  heartRateStatUnit: "text-[9px] font-bold [letter-spacing:0.08em] text-[rgba(255,_255,_255,_0.45)]",
  heartRateTitle: "text-lf-sm font-semibold",
  heartRateXAxis: "flex justify-between mt-lf-1 text-[8px] text-[rgba(255,_255,_255,_0.35)]",
  heartRateYAxis: "flex flex-col justify-between text-[8px] text-[rgba(255,_255,_255,_0.35)] pb-[16px]",
  musicControlBtn: "flex items-center justify-center border-none bg-transparent text-[rgba(255,_255,_255,_0.75)] cursor-pointer",
  musicControls: "flex items-center justify-center gap-lf-4",
  musicPlayer: "gap-lf-3",
  nowPlaying: "flex gap-lf-3",
  nowPlayingArtist: "text-[10px] text-[rgba(255,_255,_255,_0.45)]",
  nowPlayingHeart: "mt-lf-1 text-[var(--fitness-accent-pink,_#ffb6c1)]",
  nowPlayingMeta: "min-w-0",
  nowPlayingTitle: "text-lf-sm font-bold",
  playRing: "relative flex items-center justify-center",
  playRingFill: "[fill:none] [stroke:var(--fitness-accent-green,_#a4c639)] [stroke-width:3] [stroke-linecap:round]",
  playRingIcon: "absolute flex text-[rgba(255,_255,_255,_0.9)]",
  playRingTrack: "[fill:none] [stroke:rgba(255,_255,_255,_0.12)] [stroke-width:3]",
  progressCell: "aspect-[1] rounded-[999px]",
  progressCellDone: "bg-[#121212]",
  progressCellOpen: "bg-[rgba(255,_255,_255,_0.92)]",
  progressColLabels: "grid gap-[6px] text-[8px] font-bold [letter-spacing:0.04em] text-center",
  progressGrid: "flex-1 grid gap-[6px]",
  progressGridWrap: "flex gap-lf-2 flex-1 min-h-0",
  progressRowLabels: "flex flex-col justify-around text-[8px] font-bold [letter-spacing:0.04em]",
  progressTitle: "text-lf-md font-bold",
  progressTracker: "gap-lf-2",
  runningAdjust: "inline-flex items-center justify-center w-[18px] h-[18px] rounded-[4px] bg-[var(--fitness-accent-pink,_#ffb6c1)] text-[#121212] text-[12px] font-bold",
  runningHead: "flex justify-between text-[10px] font-semibold [letter-spacing:0.06em] text-[rgba(255,_255,_255,_0.55)]",
  runningValue: "flex items-center justify-center gap-lf-2",
  stack: "justify-between gap-lf-2",
  stepsBlock: "flex flex-col gap-lf-1",
  stepsLabel: "text-[10px] font-bold [letter-spacing:0.1em] text-[rgba(0,_0,_0,_0.45)]",
  stepsStreak: "justify-between gap-lf-4",
  upNext: "mt-auto",
  upNextArt: "aspect-[1] rounded-lf-sm bg-[linear-gradient(145deg,_#333,_#555)]",
  upNextArtist: "text-[7px] text-[rgba(255,_255,_255,_0.4)] whitespace-nowrap overflow-hidden text-ellipsis",
  upNextGrid: "grid grid-cols-[repeat(4,_1fr)] gap-lf-2",
  upNextItem: "flex flex-col gap-[2px] min-w-0",
  upNextLabel: "text-[9px] font-bold [letter-spacing:0.08em] text-[rgba(255,_255,_255,_0.45)] mb-lf-2",
  upNextTitle: "text-[8px] font-bold whitespace-nowrap overflow-hidden text-ellipsis",
  weather: "gap-lf-3",
  weatherCloud: "absolute bottom-[2px] right-0 w-[22px] h-[12px] rounded-[999px] bg-[rgba(255,_255,_255,_0.55)]",
  weatherCloudSmall: "absolute bottom-[2px] right-0 w-[22px] h-[12px] rounded-[999px] bg-[rgba(255,_255,_255,_0.55)] w-[16px] h-[10px]",
  weatherCondition: "text-[10px] text-[rgba(255,_255,_255,_0.45)]",
  weatherCurrent: "flex gap-lf-3 items-start",
  weatherDay: "flex flex-col items-center gap-[4px] text-[9px]",
  weatherDay_weatherIcon: "w-[24px] h-[24px] [transform:scale(0.75)]",
  weatherDayHigh: "font-bold",
  weatherDayLabel: "font-bold [letter-spacing:0.04em] text-[rgba(255,_255,_255,_0.45)]",
  weatherDayLow: "text-[rgba(255,_255,_255,_0.35)]",
  weatherForecast: "grid grid-cols-[repeat(6,_1fr)] gap-lf-2 mt-auto",
  weatherHighLow: "text-[10px] text-[rgba(255,_255,_255,_0.45)] mt-[2px]",
  weatherIcon: "relative w-[36px] h-[36px] [flex-shrink:0]",
  weatherLocation: "text-lf-sm font-semibold mt-lf-1",
  weatherSun: "absolute top-[2px] left-[2px] w-[14px] h-[14px] rounded-[999px] bg-[rgba(255,_255,_255,_0.9)] shadow-[0_0_0_2px_rgba(255,_255,_255,_0.25)]",
  weightBarAbove: "bg-[var(--fitness-weight-alert,_#e53935)] min-h-[1px]",
  weightBarBelow: "bg-[#121212] min-h-[1px]",
  weightBarCol: "flex-1 min-w-0 max-w-[4px] flex flex-col justify-end min-h-[2px]",
  weightBars: "flex items-end gap-[3px] h-full min-h-[72px]",
  weightChange: "text-lf-sm font-semibold [letter-spacing:-0.02em]",
  weightChart: "relative flex-1 min-w-0 flex flex-col justify-end",
  weightChartWrap: "flex gap-lf-2 flex-1 min-h-0",
  weightHeader: "flex items-center justify-between",
  weightTab: "text-[11px] font-semibold [letter-spacing:0.06em] text-[rgba(0,_0,_0,_0.28)]",
  weightTabActive: "text-[#121212]",
  weightTabs: "flex gap-lf-3",
  weightThresholdLine: "absolute left-0 right-0 h-[0] [border-top:1px_dashed_var(--fitness-weight-alert,_#e53935)] pointer-events-none z-[1]",
  weightTracker: "gap-lf-4 font-mono",
  weightYAxis: "relative [flex-shrink:0] w-[20px] self-stretch text-[11px] font-semibold text-right",
  weightYBaseline: "absolute right-0 bottom-0 text-[#121212] leading-none",
  weightYThreshold: "absolute right-0 text-[var(--fitness-weight-alert,_#e53935)] [transform:translateY(50%)] leading-none",
  workoutPhoto: "relative p-0",
  workoutPhotoBg: "absolute inset-0 bg-[linear-gradient(160deg,_rgba(0,_0,_0,_0.15),_rgba(0,_0,_0,_0.45)),_linear-gradient(135deg,_#3d5a80_0%,_#6b8cae_40%,_#98c1d9_100%)] [background-size:cover] [background-position:center]",
  workoutPhotoBubble: "flex flex-col items-center justify-center w-[88px] h-[88px] rounded-[999px] bg-[rgba(255,_255,_255,_0.88)] text-[#121212] text-center",
  workoutPhotoLabel: "mt-[2px] text-[8px] font-bold [letter-spacing:0.08em] text-[rgba(0,_0,_0,_0.55)]",
  workoutPhotoOverlay: "relative z-[1] flex-1 flex items-center justify-center",
  workoutPhotoTime: "text-[18px] font-bold leading-[1.1]",
};
export default styles;
