/** Tailwind class map — converted from NotesGraphView.module.css */
const styles: Record<string, string> = {
  canvas: "relative w-full h-[480px] bg-[radial-gradient(circle_at_20%_30%,_color-mix(in_srgb,_var(--lf-accent)_6%,_transparent),_transparent_40%),_radial-gradient(circle_at_80%_70%,_color-mix(in_srgb,_#22c55e_6%,_transparent),_transparent_35%),_var(--lf-surface-sunken)]",
  canvasCompact: "h-full min-h-[320px] rounded-lf-lg",
  compactHeader: "flex items-center justify-between gap-lf-2 p-[var(--lf-space-2)_var(--lf-space-1)_0]",
  compactHint: "m-0 p-[0_var(--lf-space-1)_var(--lf-space-2)] text-[10px] text-lf-text-tertiary leading-[1.4]",
  compactTitle: "text-lf-xs font-semibold text-lf-text-secondary whitespace-nowrap overflow-hidden text-ellipsis",
  compactView: "flex flex-col h-full min-h-0 gap-lf-2",
  edgeArrow: "text-lf-text-tertiary",
  edgeLine: "[stroke:color-mix(in_srgb,_var(--lf-text-tertiary)_55%,_transparent)] [stroke-width:1] [stroke-linecap:round]",
  edgeLineActive: "[stroke:color-mix(in_srgb,_#22c55e_70%,_var(--lf-text-tertiary))] [stroke-width:1.5]",
  edgeList: "flex flex-col gap-lf-2",
  edgeRow: "flex items-start gap-lf-2 text-lf-xs text-lf-text-secondary leading-[1.4]",
  edges: "absolute inset-0 w-full h-full pointer-events-none",
  graphCard: "overflow-hidden min-h-[480px] border border-solid border-lf-border-subtle",
  header: "mb-lf-5",
  layout: "grid grid-cols-[minmax(0,_1fr)_320px] gap-lf-4 [align-items:start] grid-cols-[1fr]",
  node: "absolute [transform:translate(-50%,_-50%)] p-0 border-none rounded-full bg-[color-mix(in_srgb,_var(--lf-text-secondary)_70%,_transparent)] cursor-pointer transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:[transform:translate(-50%,_-50%)_scale(1.35)] hover:shadow-[0_0_0_4px_color-mix(in_srgb,_var(--lf-accent)_20%,_transparent)]",
  nodeActive: "bg-[#f8fafc] shadow-[0_0_14px_color-mix(in_srgb,_#f8fafc_60%,_transparent)] [transform:translate(-50%,_-50%)_scale(1.5)]",
  nodeDot: "w-[10px] h-[10px] rounded-full [flex-shrink:0] bg-lf-text-tertiary",
  nodeDotActive: "bg-[#f8fafc] shadow-[0_0_0_2px_color-mix(in_srgb,_var(--lf-accent)_40%,_transparent)]",
  nodeDotEvergreen: "bg-[#a78bfa]",
  nodeEvergreen: "bg-[color-mix(in_srgb,_#a78bfa_80%,_var(--lf-text-secondary))]",
  nodeInfo: "flex-1 min-w-0",
  nodeLinked: "bg-[#22c55e] shadow-[0_0_10px_color-mix(in_srgb,_#22c55e_45%,_transparent)]",
  nodeList: "flex flex-col gap-lf-2",
  nodeMeta: "text-[10px] text-lf-text-tertiary",
  nodeName: "text-lf-xs font-semibold",
  nodeRow: "flex items-center gap-lf-2 p-lf-2 rounded-lf-md bg-[var(--lf-surface-raised)] border border-solid border-lf-border-subtle cursor-pointer text-left w-full text-[inherit] [font:inherit] hover:border-[color-mix(in_srgb,_var(--lf-accent)_35%,_var(--lf-border-subtle))]",
  nodeRowActive: "border-[color-mix(in_srgb,_var(--lf-accent)_50%,_transparent)] bg-[color-mix(in_srgb,_var(--lf-accent)_8%,_var(--lf-surface-raised))]",
  sectionTitle: "m-0 text-lf-sm font-semibold",
  sidebar: "flex flex-col gap-lf-3",
  stat: "flex flex-col items-center p-lf-3 rounded-lf-lg bg-lf-surface-sunken border border-solid border-lf-border-subtle",
  statLabel: "text-[10px] text-lf-text-tertiary uppercase [letter-spacing:0.04em]",
  stats: "grid grid-cols-[repeat(3,_1fr)] gap-lf-2",
  statValue: "text-lf-lg font-bold",
  subtitle: "m-0 text-lf-sm text-lf-text-secondary max-w-[560px] leading-normal",
  title: "m-[0_0_var(--lf-space-1)] text-lf-2xl font-bold [letter-spacing:-0.02em]",
  view: "p-lf-6 max-w-[1280px]",
};
export default styles;
