/** Tailwind class map — converted from blocks.module.css */
const styles: Record<string, string> = {
  activityCardList: "flex flex-col gap-lf-2",
  block: "mb-lf-4",
  blockSubtitle: "text-lf-sm text-lf-text-secondary mb-lf-3 leading-[var(--lf-line-height-normal)]",
  blockTitle: "text-lf-sm font-semibold text-lf-text-tertiary uppercase [letter-spacing:0.03em] mb-lf-2",
  card: "flex flex-col gap-lf-2",
  cardDescription: "text-lf-sm text-lf-text-tertiary leading-[var(--lf-line-height-normal)]",
  cardGrid: "grid grid-cols-[repeat(auto-fill,_minmax(180px,_1fr))] gap-lf-3",
  cardHead: "flex items-start justify-between gap-lf-2",
  cardIcon: "flex items-center justify-center w-[28px] h-[28px] rounded-lf-sm bg-lf-surface-3 text-lf-accent [flex-shrink:0]",
  cardTitle: "text-lf-md font-semibold text-lf-text-primary",
  code: "m-0 p-lf-3 rounded-lf-md bg-lf-surface-sunken border border-solid border-lf-border-subtle [overflow-x:auto] font-mono text-lf-sm text-lf-text-secondary leading-[var(--lf-line-height-normal)]",
  codeLanguage: "inline-block mb-lf-2 text-lf-xs text-lf-text-tertiary font-mono",
  courseCardGrid: "grid grid-cols-[repeat(auto-fill,_minmax(220px,_1fr))] gap-lf-3",
  creatorWidgetGrid: "grid grid-cols-[repeat(auto-fill,_minmax(280px,_1fr))] gap-lf-4",
  dashboardCardGrid: "grid grid-cols-[repeat(auto-fill,_minmax(260px,_1fr))] gap-lf-3",
  dashboardWideGrid: "grid grid-cols-[minmax(0,_1fr)] gap-lf-3",
  designCardGrid: "grid grid-cols-[repeat(auto-fill,_minmax(280px,_1fr))] gap-lf-4",
  deviceCardGrid: "grid grid-cols-[repeat(auto-fill,_minmax(200px,_1fr))] gap-lf-3",
  eventCardGrid: "grid grid-cols-[repeat(auto-fill,_minmax(180px,_1fr))] gap-lf-3",
  expenseCardList: "flex flex-col gap-lf-2",
  filterSectionList: "flex flex-col gap-lf-2",
  form: "flex flex-col gap-[1px] rounded-lf-md overflow-hidden border border-solid border-lf-border-subtle",
  formLabel: "text-lf-md text-lf-text-tertiary",
  formRow: "flex items-center justify-between gap-lf-3 p-[var(--lf-space-2)_var(--lf-space-3)] bg-lf-surface-1 border-b border-lf-divider",
  formValue: "text-lf-md text-lf-text-primary font-medium text-right",
  glassWidgetGrid: "grid grid-cols-[repeat(auto-fill,_minmax(200px,_1fr))] gap-lf-4",
  insightCardGrid: "grid grid-cols-[repeat(auto-fill,_minmax(280px,_1fr))] gap-lf-3",
  listingCardGrid: "grid grid-cols-[repeat(auto-fill,_minmax(240px,_1fr))] gap-lf-3",
  mediaCardGrid: "grid grid-cols-[repeat(auto-fill,_minmax(200px,_1fr))] gap-lf-3",
  meetingCountdownGrid: "grid grid-cols-[repeat(auto-fill,_minmax(280px,_1fr))] gap-lf-3",
  metricChartCardGrid: "grid grid-cols-[repeat(auto-fill,_minmax(280px,_1fr))] gap-lf-3",
  phoneHomeScreenWrap: "flex justify-center p-[var(--lf-space-4)_0]",
  profileSummaryCardGrid: "grid grid-cols-[repeat(auto-fill,_minmax(280px,_1fr))] gap-lf-3",
  routeCardGrid: "grid grid-cols-[repeat(auto-fill,_minmax(280px,_1fr))] gap-lf-3",
  scheduleSlotsCard: "flex flex-col",
  scheduleSlotsGrid: "grid grid-cols-[repeat(auto-fit,_minmax(140px,_1fr))] gap-lf-4",
  selectionTileGrid: "grid grid-cols-[repeat(3,_minmax(0,_1fr))] gap-lf-2",
  sessionCardGrid: "grid grid-cols-[repeat(auto-fill,_minmax(280px,_1fr))] gap-lf-3",
  statCardGrid: "grid grid-cols-[repeat(auto-fill,_minmax(160px,_1fr))] gap-lf-3",
  terminal: "rounded-lf-md bg-lf-surface-sunken border border-solid border-lf-border-subtle overflow-hidden",
  terminalBody: "p-lf-3 font-mono text-lf-sm text-lf-success flex flex-col gap-[2px] max-h-[220px] overflow-y-auto",
  terminalDot: "w-[8px] h-[8px] rounded-lf-pill bg-lf-border-strong",
  terminalHeader: "flex items-center gap-[6px] p-[var(--lf-space-2)_var(--lf-space-3)] border-b border-lf-divider",
  textDefault: "text-lf-text-secondary text-lf-base leading-[var(--lf-line-height-normal)]",
  textHeading: "text-lf-text-primary text-lf-lg font-semibold",
  textMuted: "text-lf-text-tertiary text-lf-sm",
  timelineSteps: "flex flex-col gap-lf-2",
  timezoneCardGrid: "grid grid-cols-[repeat(auto-fill,_minmax(280px,_1fr))] gap-lf-3",
  videoPlayerGrid: "flex flex-wrap gap-lf-4 items-start",
};
export default styles;
