/** Tailwind class map — converted from AiCoachView.module.css */
const styles: Record<string, string> = {
  chatHeader: "p-[var(--lf-space-4)_var(--lf-space-6)] border-b border-lf-divider",
  chatPanel: "flex-1 min-w-0 flex flex-col border-r border-lf-divider [border-right:none] border-b border-lf-divider",
  chatSubtitle: "m-0 text-lf-sm text-lf-text-secondary",
  chatTitle: "flex items-center gap-lf-2 m-[0_0_var(--lf-space-1)] text-lf-lg font-bold",
  composer: "p-[var(--lf-space-4)_var(--lf-space-6)] border-t border-lf-divider",
  composerHint: "mt-lf-2 text-lf-xs text-lf-text-tertiary text-center",
  focusCard: "p-lf-4 rounded-lf-lg bg-[var(--lf-surface-raised)] border border-solid border-lf-border-subtle",
  focusText: "m-0 text-lf-sm leading-normal text-lf-text-primary",
  message: "flex gap-lf-3 max-w-[85%]",
  messageAvatar: "inline-flex items-center justify-center w-[32px] h-[32px] rounded-[var(--lf-radius-full)] [flex-shrink:0] bg-lf-accent-muted text-lf-accent",
  messageAvatarUser: "bg-lf-surface-sunken text-lf-text-secondary",
  messageBubble: "p-[var(--lf-space-3)_var(--lf-space-4)] rounded-lf-lg text-lf-sm leading-normal",
  messageBubbleAssistant: "bg-lf-surface-sunken border border-solid border-lf-border-subtle",
  messageBubbleUser: "bg-lf-accent text-[var(--lf-text-on-accent,_white)]",
  messageMeta: "mt-lf-1 text-lf-xs text-lf-text-tertiary",
  messageModuleTag: "inline-flex items-center gap-[4px] mt-lf-1 p-[2px_6px] rounded-lf-sm text-[10px] font-semibold uppercase bg-lf-accent-muted text-lf-accent",
  messages: "flex-1 min-h-0 overflow-y-auto p-[var(--lf-space-4)_var(--lf-space-6)] flex flex-col gap-lf-4",
  messageUser: "self-end flex-row-reverse",
  moduleChip: "inline-flex items-center gap-lf-1 p-[var(--lf-space-1)_var(--lf-space-2)] rounded-[var(--lf-radius-full)] text-lf-xs bg-[var(--lf-surface-raised)] border border-solid border-lf-border-subtle text-lf-text-secondary cursor-pointer hover:border-lf-border-strong hover:text-lf-text-primary",
  moduleQuickLinks: "flex flex-wrap gap-lf-2",
  priorityBadge: "text-[10px] font-semibold uppercase p-[2px_6px] rounded-lf-sm",
  priorityHigh: "bg-lf-danger-muted text-lf-danger",
  priorityLow: "bg-lf-surface-sunken text-lf-text-tertiary",
  priorityMedium: "bg-lf-warning-muted text-lf-warning",
  recommendation: "p-lf-3 rounded-lf-md bg-[var(--lf-surface-raised)] border border-solid border-lf-border-subtle mb-lf-2",
  recommendationHead: "flex items-center justify-between gap-lf-2 mb-lf-1",
  recommendationText: "m-[0_0_var(--lf-space-2)] text-lf-xs text-lf-text-secondary leading-[1.4]",
  recommendationTitle: "text-lf-sm font-semibold",
  sidePanel: "w-[340px] [flex-shrink:0] overflow-y-auto p-lf-4 bg-lf-surface-sunken w-full",
  sideSection: "mb-lf-5",
  sideSectionTitle: "m-[0_0_var(--lf-space-3)] text-lf-xs font-semibold uppercase [letter-spacing:0.04em] text-lf-text-tertiary",
  view: "flex h-full min-h-0 flex-col",
};
export default styles;
