/** Tailwind class map — converted from DashboardView.module.css */
const styles: Record<string, string> = {
  activityBody: "flex-1 min-w-0",
  activityIcon: "inline-flex items-center justify-center w-[28px] h-[28px] rounded-lf-md [flex-shrink:0]",
  activityIconInfo: "bg-lf-accent-muted text-lf-accent",
  activityIconSuccess: "bg-lf-success-muted text-lf-success",
  activityIconWarning: "bg-lf-warning-muted text-lf-warning",
  activityItem: "flex items-start gap-lf-3 p-lf-3 rounded-lf-md bg-lf-surface-sunken",
  activityList: "flex flex-col gap-lf-2",
  activityMeta: "text-lf-xs text-lf-text-tertiary",
  activityTitle: "text-lf-sm font-medium mb-[2px]",
  breadcrumb: "inline-flex items-center gap-lf-1 p-0 mb-lf-2 border-none bg-transparent text-lf-sm text-lf-text-secondary cursor-pointer hover:text-lf-text-primary",
  header: "mb-lf-6",
  metricCard: "relative min-h-[96px]",
  metricChange: "mt-lf-1 text-lf-xs text-lf-text-tertiary",
  metricChangePositive: "text-lf-success",
  metricHead: "flex items-start justify-between gap-lf-2 mb-lf-3",
  metricIcon: "inline-flex items-center justify-center w-[28px] h-[28px] rounded-lf-md [flex-shrink:0]",
  metricIconAccent: "bg-lf-accent-muted text-lf-accent",
  metricIconNeutral: "bg-lf-surface-sunken text-lf-text-secondary",
  metricIconSuccess: "bg-lf-success-muted text-lf-success",
  metricIconWarning: "bg-lf-warning-muted text-lf-warning",
  metricLabel: "text-lf-sm text-lf-text-secondary",
  metrics: "grid grid-cols-[repeat(4,_minmax(0,_1fr))] gap-lf-3 mb-lf-6 grid-cols-[repeat(2,_minmax(0,_1fr))] grid-cols-[1fr]",
  metricValue: "text-lf-xl font-bold [letter-spacing:-0.02em] text-lf-text-primary",
  metricValueSuccess: "text-lf-success",
  moduleCard: "cursor-pointer transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:border-lf-border-strong",
  moduleCardHead: "flex items-start justify-between gap-lf-2 mb-lf-3",
  moduleDescription: "text-lf-xs text-lf-text-tertiary leading-[1.4] [display:-webkit-box] line-clamp-[2] [-webkit-box-orient:vertical] overflow-hidden",
  moduleIcon: "inline-flex items-center justify-center w-[36px] h-[36px] rounded-lf-md [flex-shrink:0]",
  moduleIconFinances: "bg-lf-warning-muted text-lf-warning",
  moduleIconHealth: "bg-lf-success-muted text-lf-success",
  moduleIconHousing: "bg-[color-mix(in_srgb,_var(--lf-accent)_15%,_transparent)] text-lf-accent",
  moduleIconInvestments: "bg-[color-mix(in_srgb,_var(--lf-success)_12%,_transparent)] text-lf-success",
  moduleIconMind: "bg-lf-accent-muted text-lf-accent",
  moduleIconRetirement: "bg-lf-surface-sunken text-lf-text-secondary",
  moduleLabel: "text-lf-md font-semibold mb-[2px]",
  modulesGrid: "grid grid-cols-[repeat(3,_minmax(0,_1fr))] gap-lf-3 grid-cols-[repeat(2,_minmax(0,_1fr))] grid-cols-[1fr]",
  moduleStats: "flex gap-lf-3 mt-lf-3 pt-lf-3 border-t border-lf-divider text-lf-xs text-lf-text-tertiary",
  moduleStatValue: "font-semibold text-lf-text-primary",
  priorityHigh: "text-lf-danger",
  priorityLow: "text-lf-text-tertiary",
  priorityMedium: "text-lf-warning",
  progressRing: "relative w-[44px] h-[44px] [flex-shrink:0]",
  progressRingLabel: "absolute inset-0 flex items-center justify-center text-[10px] font-bold text-lf-text-primary",
  recommendation: "p-lf-3 rounded-lf-md border border-solid border-lf-border-subtle bg-[var(--lf-surface-raised)]",
  recommendationHead: "flex items-center gap-lf-2 mb-lf-1",
  recommendations: "flex flex-col gap-lf-2",
  recommendationText: "m-[0_0_var(--lf-space-2)] text-lf-xs text-lf-text-secondary leading-[1.4]",
  recommendationTitle: "text-lf-sm font-semibold",
  sectionTitle: "m-[0_0_var(--lf-space-3)] text-lf-md font-semibold",
  subtitle: "m-0 text-lf-sm text-lf-text-secondary max-w-[560px] leading-normal",
  title: "m-[0_0_var(--lf-space-1)] text-lf-2xl font-bold [letter-spacing:-0.02em]",
  twoCol: "grid grid-cols-[1fr_380px] gap-lf-6 [align-items:start] grid-cols-[1fr]",
  view: "p-lf-6 max-w-[1280px]",
};
export default styles;
