/** Tailwind class map — converted from ModuleView.module.css */
const styles: Record<string, string> = {
  description: "m-0 text-lf-sm text-lf-text-secondary leading-normal max-w-[480px]",
  goalCard: "p-lf-4",
  goalDescription: "text-lf-sm text-lf-text-secondary leading-[1.4]",
  goalHead: "flex items-start justify-between gap-lf-3 mb-lf-2",
  goalMeta: "flex items-center gap-lf-2 [flex-shrink:0]",
  goalProgress: "m-[var(--lf-space-3)_0]",
  goalsSection: "flex flex-col gap-lf-3",
  goalTitle: "text-lf-md font-semibold mb-[2px]",
  header: "flex items-start justify-between gap-lf-4 mb-lf-6 flex-col",
  headerMain: "flex-1 min-w-0",
  insights: "mb-lf-6 p-lf-4 rounded-lf-lg bg-lf-accent-muted border border-solid border-[color-mix(in_srgb,_var(--lf-accent)_20%,_transparent)]",
  insightsHead: "flex items-center gap-lf-2 mb-lf-3 text-lf-sm font-semibold text-lf-accent",
  insightsList: "m-0 pl-lf-5 text-lf-sm text-lf-text-secondary leading-[1.6]",
  metricCard: "min-h-[80px]",
  metricChange: "mt-[2px] text-lf-xs text-lf-success",
  metricLabel: "text-lf-xs text-lf-text-tertiary mb-lf-1",
  metrics: "grid grid-cols-[repeat(3,_minmax(0,_1fr))] gap-lf-3 mb-lf-6 grid-cols-[1fr]",
  metricValue: "text-lf-lg font-bold [letter-spacing:-0.02em]",
  milestone: "flex items-center gap-lf-2 text-lf-sm",
  milestoneCheck: "inline-flex items-center justify-center w-[18px] h-[18px] rounded-lf-sm [border:1.5px_solid_var(--lf-border-strong)] [flex-shrink:0]",
  milestoneCheckDone: "bg-lf-success border-lf-success text-[white]",
  milestoneDone: "text-lf-text-tertiary [text-decoration:line-through]",
  milestones: "flex flex-col gap-lf-2 pt-lf-3 border-t border-lf-divider",
  moduleIcon: "inline-flex items-center justify-center w-[48px] h-[48px] rounded-lf-lg mb-lf-3",
  moduleIconFinances: "bg-lf-warning-muted text-lf-warning",
  moduleIconHealth: "bg-lf-success-muted text-lf-success",
  moduleIconHousing: "bg-[color-mix(in_srgb,_var(--lf-accent)_15%,_transparent)] text-lf-accent",
  moduleIconInvestments: "bg-[color-mix(in_srgb,_var(--lf-success)_12%,_transparent)] text-lf-success",
  moduleIconMind: "bg-lf-accent-muted text-lf-accent",
  moduleIconRetirement: "bg-lf-surface-sunken text-lf-text-secondary",
  overallProgress: "flex flex-col items-center gap-lf-1 [flex-shrink:0]",
  progressBar: "h-[6px] rounded-[var(--lf-radius-full)] bg-lf-surface-sunken overflow-hidden",
  progressFill: "h-full rounded-[var(--lf-radius-full)] bg-lf-accent transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)]",
  progressFillSuccess: "bg-lf-success",
  progressFillWarning: "bg-lf-warning",
  progressLabel: "flex justify-between mt-lf-1 text-lf-xs text-lf-text-tertiary",
  progressRing: "relative w-[72px] h-[72px]",
  progressRingCaption: "text-lf-xs text-lf-text-tertiary",
  progressRingLabel: "absolute inset-0 flex items-center justify-center text-lf-md font-bold",
  title: "m-[0_0_var(--lf-space-1)] text-lf-2xl font-bold [letter-spacing:-0.02em]",
  view: "p-lf-6 max-w-[960px]",
};
export default styles;
