/** Tailwind class map — converted from CourseCard.module.css */
const styles: Record<string, string> = {
  hero: "rounded-lf-xl border border-solid border-lf-border-subtle flex flex-col gap-lf-3 p-lf-5 min-h-[180px]",
  heroAction: "self-start rounded-lf-pill",
  heroIcon: "flex items-center justify-center [flex-shrink:0] w-[36px] h-[36px] rounded-lf-pill bg-lf-surface-1",
  heroInstructor: "text-lf-xs text-lf-text-tertiary",
  heroTitle: "text-lf-lg font-bold text-lf-text-primary leading-[var(--lf-line-height-tight)]",
  heroTop: "flex items-center justify-between",
  pill: "rounded-lf-xl border border-solid border-lf-border-subtle flex items-center gap-lf-3 w-full p-[var(--lf-space-3)_var(--lf-space-4)] text-left cursor-pointer",
  "pill-accent": "bg-lf-accent-muted",
  "pill-neutral": "bg-lf-surface-sunken text-lf-text-on-accent",
  "pill-neutral_pillChevron": "text-lf-text-on-accent",
  "pill-neutral_pillSubtitle": "text-lf-text-on-accent",
  "pill-neutral_pillTitle": "text-lf-text-on-accent",
  "pill-warning": "bg-lf-warning-muted",
  pillBody: "flex-1 min-w-0 flex flex-col gap-[2px]",
  pillChevron: "flex items-center justify-center [flex-shrink:0] text-lf-text-tertiary",
  pillIcon: "flex items-center justify-center [flex-shrink:0] w-[36px] h-[36px] rounded-lf-pill bg-lf-surface-1",
  pillSubtitle: "text-lf-sm text-lf-text-secondary",
  pillTitle: "text-lf-md font-semibold text-lf-text-primary",
  progress: "inline-flex items-center justify-center min-w-[36px] h-[36px] p-[0_var(--lf-space-2)] rounded-lf-pill bg-lf-surface-1 text-lf-xs font-semibold text-lf-text-primary",
  tile: "rounded-lf-xl border border-solid border-lf-border-subtle flex flex-col gap-lf-2 p-lf-4 min-h-[160px] text-left cursor-pointer",
  tileIcon: "flex items-center justify-center [flex-shrink:0] w-[36px] h-[36px] rounded-lf-pill bg-lf-surface-1",
  tileInstructor: "text-lf-xs text-lf-text-tertiary",
  tileSubtitle: "text-lf-xs text-lf-text-tertiary",
  tileTitle: "text-lf-lg font-bold text-lf-text-primary leading-[var(--lf-line-height-tight)]",
  tileTop: "flex items-center justify-between",
  "tone-accent": "bg-lf-accent-muted",
  "tone-neutral": "bg-lf-surface-3",
  "tone-warning": "bg-lf-warning-muted",
};
export default styles;
