/** Tailwind class map — converted from PhoneHomeScreen.module.css */
const styles: Record<string, string> = {
  app: "relative max-w-[60px] max-h-[80px] m-[0_8px_7px]",
  appIcon: "m-auto border-none cursor-pointer [-webkit-tap-highlight-color:transparent] w-[60px] h-[60px] rounded-[14px] transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] active:[filter:brightness(0.82)]",
  appIconButton: "m-auto border-none cursor-pointer [-webkit-tap-highlight-color:transparent] p-0 bg-transparent active:[filter:brightness(0.82)]",
  appName: "text-center mt-[2px]",
  batteryMeter: "flex justify-end ml-auto w-[29px] h-[18px]",
  batteryMeterInner: "relative w-[25px] h-[12px] mr-[1px] rounded-[3px] shadow-[0_0_0_1px_rgba(255,_255,_255,_0.5)_inset] before:before:[content:\"\"] before:before:block before:after:[content:\"\"] before:after:block before:before:w-[19px] before:before:h-[8px] before:before:m-[2px] before:before:rounded-[1px_0_0_1px] before:before:bg-[#fff] before:after:absolute before:after:top-0 before:after:left-[100%] before:after:w-[2px] before:after:h-[4px] before:after:m-[4px_0_0_1px] before:after:rounded-[0_3px_3px_0] before:after:bg-[rgba(255,_255,_255,_0.5)]",
  bgBlur: "absolute top-0 left-0 z-[1] w-full h-[var(--phone-h)] invisible [backdrop-filter:blur(0)] [-webkit-backdrop-filter:blur(0)] transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)]",
  bgBlurVisible: "visible [backdrop-filter:blur(15px)] [-webkit-backdrop-filter:blur(15px)]",
  bottomBar: "absolute transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] top-[calc(100%_-_var(--bottom-bar-h))] left-0 z-[3] flex items-center justify-center w-full h-[var(--bottom-bar-h)] p-[0_6px] [transform-style:preserve-3d] bg-[rgba(255,_255,_255,_0.3)] [backdrop-filter:blur(15px)] [-webkit-backdrop-filter:blur(15px)]",
  bottomBar_app: "max-h-[60px] m-[11px_8px]",
  bottomBar_bgBlur: "top-[calc(-1_*_var(--phone-h)_+_var(--bottom-bar-h))]",
  bottomBar_folder: "max-h-[60px] m-[11px_8px]",
  bottomBar_folderAppsOpen_folderMiniApp: "m-[0_18px_27px]",
  bottomBar_folderMiniApp: "m-[0_8px_16px]",
  bottomBar_folderName: "hidden",
  carrier: "text-[11px]",
  clock: "text-center",
  dragGhost: "fixed z-[9999] pointer-events-none [transform:translate(-50%,_-50%)] [filter:drop-shadow(0_8px_20px_rgba(0,_0,_0,_0.45))]",
  dragGhostIcon: "w-[60px] h-[60px] rounded-[9px]",
  draggingSource: "opacity-[0.35]",
  dropTarget: "",
  dropTarget_appIcon: "[outline:2px_solid_rgba(255,_255,_255,_0.85)] [outline-offset:2px] [transform:scale(1.06)]",
  dropTarget_appIconButton: "[outline:2px_solid_rgba(255,_255,_255,_0.85)] [outline-offset:2px] [transform:scale(1.06)]",
  dropTarget_folderApps: "[outline:2px_solid_rgba(255,_255,_255,_0.85)] [outline-offset:2px] [transform:scale(1.06)]",
  fill: "w-full h-full m-0 rounded-none shadow-none [--phone-w:100%] [--phone-h:100%]",
  fill_page: "[flex:0_0_100%] w-full",
  folder: "relative max-w-[60px] max-h-[80px] m-[0_8px_7px]",
  folderApps: "m-auto border-none cursor-pointer [-webkit-tap-highlight-color:transparent] flex flex-wrap [align-content:flex-start] w-[304px] h-[304px] p-[44px_36px] rounded-[45px] bg-[rgba(255,_255,_255,_0.3)] [backdrop-filter:blur(15px)] [-webkit-backdrop-filter:blur(15px)] [transform:scale(calc(60_/_304))_translateZ(0)] [transform-origin:0_0] transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] active:[filter:brightness(0.7)]",
  folderAppsOpen: "p-[26px_8px] [outline:0] [backdrop-filter:blur(0)] [-webkit-backdrop-filter:blur(0)] [transform:scale(1,_1)_translate3d(var(--folder-x,_0),_var(--folder-y,_0),_1px)]",
  folderAppsOpen_folderMiniApp: "m-[0_18px_7px]",
  folderAppsOpen_folderMiniIcon: "rounded-[9px]",
  folderAppsOpen_folderMiniName: "[display:inherit]",
  folderMiniApp: "max-w-[60px] m-[0_8px_16px]",
  folderMiniButton: "flex flex-col items-center border-none p-0 bg-transparent text-[inherit] cursor-pointer",
  folderMiniIcon: "w-[60px] h-[60px] rounded-[18px]",
  folderMiniName: "hidden text-center",
  folderName: "text-center [transform:translateY(-244px)] transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)]",
  folderNameOpen: "w-[300px] text-[3em] opacity-100 [transform:translate3d(var(--folder-x,_0),_var(--folder-name-y,_0),_1px)] [animation:folderNameFadeIn_0.2s_0.2s_forwards]",
  hint: "absolute bottom-[calc(var(--bottom-bar-h)_+_2px)] left-0 z-[5] w-full text-[10px] text-center text-[rgba(255,_255,_255,_0.55)] pointer-events-none",
  page: "inline-flex flex-wrap [align-content:flex-start] [flex-shrink:0] w-[var(--phone-w)] h-full p-[calc(var(--status-h)_+_7px)_8px_7px]",
  pageDot: "inline-flex items-center justify-center w-[24px] h-[var(--pagination-h)] p-0 border-none bg-transparent cursor-pointer",
  "pageDot span": "inline-block w-[calc(var(--pagination-h)_/_3)] h-[calc(var(--pagination-h)_/_3)] rounded-full bg-[#fff] opacity-[0.3] transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)]",
  "pageDotActive span": "opacity-100",
  pages: "absolute transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] top-0 left-0 z-[2] flex w-full h-[calc(100%_-_var(--pagination-h)_-_var(--bottom-bar-h))] [transform:translateX(calc(var(--active-page,_0)_*_-100%))] [transform-style:preserve-3d] whitespace-nowrap [touch-action:pan-y]",
  pagination: "absolute flex top-[calc(100%_-_var(--bottom-bar-h)_-_var(--pagination-h))] justify-center w-full h-[var(--pagination-h)] z-[3]",
  screen: "[--phone-w:320px] [--phone-h:568px] [--status-h:20px] [--pagination-h:24px] [--bottom-bar-h:92px] [--folder-timing:cubic-bezier(0.2,_0.7,_0.3,_0.8)] relative w-[var(--phone-w)] h-[var(--phone-h)] m-[0_auto] overflow-hidden text-[#fff] font-sans text-[12px] font-[300] leading-[20px] [letter-spacing:0.5px] [transform-style:preserve-3d] bg-[#000] [background-image:var(_--phone-wallpaper,_linear-gradient(160deg,_#1a3a5c_0%,_#0d1f33_45%,_#2d1b4e_100%)_)] [background-position:center] [background-size:cover] rounded-[28px] shadow-[0_0_0_1px_rgba(255,_255,_255,_0.08),_0_24px_64px_rgba(0,_0,_0,_0.55)]",
  status: "absolute flex items-center top-0 left-0 z-[4] w-full h-[var(--status-h)] p-[0_4px]",
  widgetPage: "inline-flex flex-nowrap [align-content:stretch] pt-[calc(var(--status-h)_+_12px)]",
};
export default styles;
