/** Tailwind class map — converted from DesignSystemWorkspace.module.css */
const styles: Record<string, string> = {
  blockTypeList: "flex flex-wrap gap-lf-2",
  calculatorPreview: "flex justify-center p-lf-4 rounded-lf-lg bg-lf-surface-2 border border-solid border-lf-border-subtle",
  calculatorPreviewRow: "flex flex-wrap justify-center gap-lf-5 p-lf-4 rounded-lf-lg bg-lf-surface-2 border border-solid border-lf-border-subtle",
  componentColumn: "flex flex-col gap-lf-3 max-w-[420px]",
  componentRow: "flex flex-wrap items-center gap-lf-2",
  container: "flex-1 min-h-0 flex flex-col rounded-lf-lg overflow-hidden border border-solid border-lf-border-default bg-lf-surface-1 shadow-lf-md",
  content: "p-lf-5 flex flex-col gap-lf-6",
  eyebrow: "text-lf-xs font-semibold [letter-spacing:0.04em] uppercase text-lf-text-tertiary",
  familyDescription: "m-[0_0_var(--lf-space-3)] text-lf-sm text-lf-text-secondary",
  familyTabs: "mb-lf-3",
  galleryComponentCard: "w-full",
  galleryComponentRow: "flex flex-wrap items-center gap-lf-2",
  galleryCount: "text-lf-sm text-lf-text-tertiary",
  galleryFilters: "flex flex-wrap gap-lf-2",
  galleryToolbar: "flex flex-wrap items-center justify-between gap-lf-3 mb-lf-4",
  header: "[flex-shrink:0] p-[var(--lf-space-4)_var(--lf-space-5)] border-b border-lf-divider",
  headerLeft: "flex flex-col gap-lf-1",
  masonry: "[column-count:3] gap-x-lf-4 [column-count:2] [column-count:1]",
  masonryItem: "[break-inside:avoid] mb-lf-4 border border-solid border-lf-border-subtle rounded-lf-lg bg-lf-surface-canvas overflow-hidden",
  masonryItemBody: "p-lf-3 mb-0",
  masonryItemHeader: "flex flex-col gap-lf-2 p-[var(--lf-space-3)_var(--lf-space-4)] border-b border-lf-divider bg-lf-surface-2",
  masonryItemLabel: "text-lf-sm font-semibold text-lf-text-primary",
  masonryItemMeta: "flex flex-wrap items-center gap-lf-2",
  masonryItemType: "font-mono text-lf-xs text-lf-text-tertiary",
  ontologyCard: "p-lf-4 rounded-lf-md border border-solid border-lf-border-subtle bg-lf-surface-2",
  ontologyDescription: "m-[var(--lf-space-2)_0_0] text-lf-sm text-lf-text-secondary leading-[var(--lf-line-height-normal)]",
  ontologyGrid: "grid grid-cols-[repeat(auto-fill,_minmax(220px,_1fr))] gap-lf-3",
  ontologyLabel: "text-lf-md font-semibold text-lf-text-primary",
  ontologyMeta: "mt-lf-3 font-mono text-lf-xs text-lf-text-tertiary",
  patternCard: "max-w-[480px]",
  previewSurface: "p-lf-4 rounded-lf-md border border-solid border-lf-border-subtle bg-lf-surface-canvas",
  previewSurfaceWide: "p-lf-4 rounded-lf-md border border-solid border-lf-border-subtle bg-lf-surface-canvas max-w-[960px]",
  radiusPreview: "flex flex-wrap gap-lf-3 mt-lf-4",
  radiusTile: "w-[96px] h-[96px] flex flex-col items-center justify-center gap-lf-1 border border-solid border-lf-border-subtle bg-lf-surface-2 text-lf-xs text-lf-text-secondary",
  scroll: "flex-1 min-h-0",
  sectionDescription: "m-[var(--lf-space-1)_0_0] text-lf-sm text-lf-text-secondary",
  sectionHeader: "mb-lf-4",
  sectionTitle: "m-0 text-lf-lg font-semibold text-lf-text-primary",
  shadowGrid: "flex flex-wrap gap-lf-3 mt-lf-4",
  shadowTile: "w-[96px] h-[96px] flex flex-col items-center justify-center gap-lf-1 border border-solid border-lf-border-subtle bg-lf-surface-2 text-lf-xs text-lf-text-secondary",
  spacingBar: "h-[12px] rounded-lf-sm bg-lf-accent",
  spacingGrid: "flex flex-wrap gap-lf-4",
  spacingItem: "flex flex-col gap-lf-2 min-w-[80px]",
  subtitle: "m-0 text-lf-sm text-lf-text-secondary",
  swatchCard: "border border-solid border-lf-border-subtle rounded-lf-md overflow-hidden bg-lf-surface-2",
  swatchDescription: "text-lf-xs text-lf-text-tertiary",
  swatchGrid: "grid grid-cols-[repeat(auto-fill,_minmax(180px,_1fr))] gap-lf-3",
  swatchMeta: "p-lf-3 flex flex-col gap-[4px]",
  swatchName: "text-lf-sm font-semibold",
  swatchPreview: "h-[72px] border-b border-lf-divider",
  tabBar: "[flex-shrink:0] p-[0_var(--lf-space-5)] border-b border-lf-divider [overflow-x:auto] scrollbar-none",
  title: "m-0 text-lf-xl font-bold text-lf-text-primary",
  titleIcon: "flex text-lf-accent",
  titleRow: "flex items-center gap-lf-2",
  tokenMeta: "text-lf-xs text-lf-text-tertiary",
  tokenName: "text-lf-sm font-medium text-lf-text-primary",
  tokenRow: "grid grid-cols-[120px_1fr_auto] gap-lf-3 items-center p-[var(--lf-space-2)_var(--lf-space-3)] bg-lf-surface-2",
  tokenTable: "flex flex-col gap-[1px] border border-solid border-lf-border-subtle rounded-lf-md overflow-hidden",
  tokenVariable: "font-mono text-lf-xs text-lf-accent",
  typeSample: "p-lf-4 rounded-lf-md border border-solid border-lf-border-subtle bg-lf-surface-2",
  typeSampleMeta: "flex items-center justify-between gap-lf-3 mb-lf-2",
  typeSampleName: "font-semibold",
  typeSamples: "flex flex-col gap-lf-3",
  typeSampleText: "m-0 text-lf-text-primary",
  typeScale: "flex flex-col gap-lf-3",
  typeScaleRow: "p-lf-4 rounded-lf-md border border-solid border-lf-border-subtle bg-lf-surface-2 flex items-center justify-between gap-lf-3 mb-lf-2",
  typeScaleSample: "m-0 text-lf-text-primary",
  workspace: "h-full flex flex-col min-h-0 p-lf-3",
};
export default styles;
