/** Tailwind class map — converted from BankingWidget.module.css */
const styles: Record<string, string> = {
  cardBrand: "text-[10px] font-[800] [letter-spacing:0.14em] opacity-[0.45] mt-[4px]",
  cardDetailsGrid: "grid grid-cols-[1fr_1fr] gap-lf-3 mt-auto",
  cardFieldLabel: "text-[8px] font-bold [letter-spacing:0.08em] opacity-[0.45]",
  cardFieldValue: "text-[11px] font-semibold mt-[2px]",
  cardLimits: "flex flex-col gap-[6px] pt-lf-2 border-t border-lf-divider text-[10px]",
  "cardLimits strong": "font-bold opacity-100",
  cardMeta: "text-[10px] opacity-[0.55] mt-[2px]",
  cardNumber: "text-[clamp(1rem,_2vw,_1.25rem)] font-semibold [letter-spacing:0.12em] mt-lf-2",
  cardTitle: "text-[11px] font-medium opacity-[0.75]",
  cardTitleLight: "text-lf-sm font-semibold text-[rgba(255,_255,_255,_0.9)]",
  creditCard: "gap-lf-3",
  cryptoAbout: "m-0 text-[10px] leading-normal opacity-[0.65]",
  cryptoAboutLabel: "text-[9px] font-bold [letter-spacing:0.08em] opacity-[0.45] mb-[4px]",
  cryptoBody: "p-[0_var(--lf-space-4)_var(--lf-space-4)]",
  cryptoChange: "text-[10px] text-[#86efac] mb-lf-2",
  cryptoItem: "border-bottom border-lf-divider last:[border-bottom:none]",
  cryptoList: "gap-0 p-0",
  cryptoName: "flex-1",
  cryptoPrice: "text-lf-lg font-bold",
  cryptoRow: "flex items-center gap-lf-2 p-[var(--lf-space-3)_var(--lf-space-4)] text-lf-sm font-semibold",
  cryptoSymbol: "flex items-center justify-center w-[24px] h-[24px] rounded-[999px] bg-[rgba(255,_255,_255,_0.12)] text-[10px]",
  disclaimer: "mt-lf-2 text-[9px] leading-[1.4] opacity-[0.45]",
  dotBarCol: "flex-1 flex flex-col-reverse items-center gap-[3px] min-h-[100%] justify-start",
  dotBarColActive: "relative before:before:[content:\"\"] before:before:absolute before:before:[inset:0_-4px] before:before:bg-[rgba(0,_0,_0,_0.08)] before:before:rounded-[999px] before:before:z-[0]",
  dotBarDot: "w-[6px] h-[6px] rounded-[999px] bg-[#121212] relative z-[1]",
  dotBars: "flex items-end gap-[8px] w-full h-full",
  dotBarsWrap: "relative flex-1 min-h-[72px] flex items-end",
  dotBarTooltip: "absolute top-0 [transform:translateX(-50%)] p-[6px_10px] rounded-[10px] bg-[#121212] text-[#fff] text-[9px] whitespace-nowrap flex flex-col gap-[2px]",
  "dotBarTooltip strong": "text-[10px]",
  exchange: "gap-lf-2",
  exchangeBreakdown: "flex flex-col gap-[6px] text-[10px]",
  exchangeHead: "flex items-start justify-between gap-lf-2",
  exchangePair: "text-[10px] font-semibold opacity-[0.55]",
  exchangeRate: "m-[var(--lf-space-2)_0] p-[var(--lf-space-2)_0] [border-block:1px_solid_rgba(0,_0,_0,_0.08)] text-[11px] font-semibold text-center",
  exchangeTotal: "font-bold opacity-100 pt-[4px] border-t border-lf-divider",
  familyHead: "flex items-center justify-between",
  familySaving: "gap-lf-2",
  heroAmount: "text-[clamp(1.35rem,_2.5vw,_1.75rem)] font-bold [letter-spacing:-0.03em] leading-[1.1] mt-lf-1",
  heroAmountSm: "text-[clamp(1.5rem,_3vw,_2rem)] font-bold [letter-spacing:-0.03em] mt-lf-2",
  iconBtn: "flex items-center justify-center w-[28px] h-[28px] border-none rounded-[999px] bg-[rgba(0,_0,_0,_0.08)] cursor-pointer",
  legendDotGold: "w-[12px] h-[0] [border-top:2px_solid_rgba(255,_255,_255,_0.9)] [border-top-color:#ca8a04]",
  legendDotWhite: "w-[12px] h-[0] [border-top:2px_solid_rgba(255,_255,_255,_0.9)]",
  legendRow: "flex gap-lf-3 text-[9px] font-medium",
  "legendRow span": "flex items-center gap-[6px]",
  lineChart: "flex-1 min-h-0 flex flex-col justify-end",
  lineGold: "[fill:none] [stroke-width:2] [stroke-linecap:round] [stroke-linejoin:round] [stroke:#eab308]",
  lineGoldDark: "[stroke:#ca8a04]",
  lineLabels: "flex justify-between mt-[4px] text-[9px] font-semibold opacity-[0.55]",
  lineWhite: "[fill:none] [stroke-width:2] [stroke-linecap:round] [stroke-linejoin:round] [stroke:rgba(255,_255,_255,_0.95)]",
  lineWhiteDark: "[stroke:rgba(255,_255,_255,_0.9)]",
  monthlyRevenue: "gap-lf-2",
  planBtn: "mt-lf-3 w-full p-[var(--lf-space-2)_var(--lf-space-3)] border-none rounded-lf-pill bg-[#fff] text-[#121212] font-sans text-[11px] font-bold cursor-pointer",
  planCard: "p-lf-3 rounded-[16px] bg-[rgba(255,_255,_255,_0.04)]",
  planCardHighlight: "bg-[rgba(255,_255,_255,_0.08)]",
  planDescription: "m-0 text-[10px] leading-[1.45] opacity-[0.55]",
  planList: "flex flex-col gap-lf-3 flex-1",
  planName: "text-[11px] font-semibold opacity-[0.65]",
  planPrice: "text-lf-xl font-bold m-[4px_0]",
  "planPrice span": "text-[11px] font-medium opacity-[0.55]",
  pricingHead: "flex items-center justify-between",
  pricingPlans: "gap-lf-3",
  pricingTabActive: "text-[#fff] [text-decoration:underline] [text-underline-offset:4px]",
  pricingTabs: "flex gap-lf-3 text-[10px] font-semibold text-[rgba(255,_255,_255,_0.45)]",
  primaryBtn: "w-full mt-auto p-lf-3 border-none rounded-lf-pill bg-[#121212] text-[#fff] font-sans text-lf-sm font-semibold cursor-pointer",
  searchRow: "flex items-center justify-between pb-[6px] border-b border-lf-divider text-[11px] opacity-[0.45]",
  transactionAmount: "text-[11px] font-bold",
  transactionDate: "text-[9px] font-medium opacity-[0.45]",
  transactionGroupLabel: "text-[9px] font-bold [letter-spacing:0.08em] opacity-[0.45] mb-lf-2",
  transactionGroups: "flex-1 min-h-0 overflow-auto flex flex-col gap-lf-3",
  transactionIcon: "flex items-center justify-center w-[28px] h-[28px] rounded-[999px] bg-[rgba(0,_0,_0,_0.08)] text-[12px]",
  transactionMeta: "min-w-0 text-[11px] font-semibold",
  transactionRow: "grid grid-cols-[auto_1fr_auto] gap-lf-2 items-center p-[6px_0]",
  transactions: "gap-lf-3",
};
export default styles;
