/** Tailwind class map — converted from TaskTray.module.css */
const styles: Record<string, string> = {
  android: "flex-col gap-lf-1 bg-[var(--lf-desktop-android-tray-bg)] [-webkit-backdrop-filter:blur(20px)_saturate(1.2)] [backdrop-filter:blur(20px)_saturate(1.2)] border-t border-lf-divider",
  androidNav: "flex items-center justify-around w-full h-[40px] border-t border-lf-divider",
  androidNavButton: "inline-flex items-center justify-center w-[48px] h-[36px] border-none bg-transparent text-lf-text-secondary cursor-pointer",
  androidShelf: "flex items-center justify-center gap-lf-3 p-[var(--lf-space-2)_var(--lf-space-4)]",
  chromeos: "w-full p-[var(--lf-space-4)_var(--lf-space-3)] bg-[var(--lf-desktop-chromeos-tray-bg)] [-webkit-backdrop-filter:blur(20px)_saturate(1.2)] [backdrop-filter:blur(20px)_saturate(1.2)] border-t border-lf-divider",
  chromeShelf: "relative flex items-center gap-lf-1",
  createButton: "relative inline-flex items-center justify-center w-[40px] h-[40px] [border:1.5px_dashed_var(--lf-border-default)] rounded-[10px] bg-transparent text-lf-text-secondary cursor-pointer transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:[transform:translateY(-2px)] hover:border-lf-accent-border hover:text-lf-accent hover:bg-lf-surface-2",
  createButtonWindows: "w-[44px] h-[40px] [border:1px_dashed_var(--lf-desktop-create-btn-border)] rounded-lf-sm text-lf-text-secondary hover:[transform:none] hover:border-lf-accent-border hover:text-lf-accent hover:bg-[var(--lf-desktop-create-btn-hover-bg)]",
  dockDot: "absolute bottom-[-6px] left-[50%] w-[4px] h-[4px] rounded-full bg-lf-text-secondary [transform:translateX(-50%)]",
  dockReordering: "[cursor:grabbing]",
  dockReordering_taskButton: "hover:[transform:none] [cursor:grabbing]",
  dockReordering_trayIcon: "hover:[transform:none] [cursor:grabbing]",
  dockUndocking: "",
  dockUndocking_undockHint: "opacity-100",
  dragGhost: "fixed z-[10000] flex items-center justify-center pointer-events-none [transform:translate(-50%,_-50%)] [filter:drop-shadow(0_8px_20px_rgba(0,_0,_0,_0.42))]",
  dragGhostIcon: "[flex-shrink:0]",
  dragGhostUndocking: "opacity-[0.72] [transform:translate(-50%,_-50%)_scale(0.9)]",
  floating: "bg-transparent border-none",
  floating_android: "max-w-[720px] m-[0_auto] rounded-lf-lg bg-[var(--lf-desktop-floating-tray-bg)] [-webkit-backdrop-filter:blur(20px)_saturate(1.2)] [backdrop-filter:blur(20px)_saturate(1.2)] border border-solid border-[var(--lf-desktop-floating-tray-border)] shadow-lf-overlay rounded-[var(--lf-radius-lg)_var(--lf-radius-lg)_0_0]",
  floating_chromeos: "max-w-[720px] m-[0_auto] rounded-lf-lg bg-[var(--lf-desktop-floating-tray-bg)] [-webkit-backdrop-filter:blur(20px)_saturate(1.2)] [backdrop-filter:blur(20px)_saturate(1.2)] border border-solid border-[var(--lf-desktop-floating-tray-border)] shadow-lf-overlay",
  floating_ios_iosDock: "shadow-lf-overlay",
  floating_macos_macosDock: "shadow-lf-overlay",
  floating_windows: "max-w-[720px] m-[0_auto] rounded-lf-lg bg-[var(--lf-desktop-floating-tray-bg)] [-webkit-backdrop-filter:blur(20px)_saturate(1.2)] [backdrop-filter:blur(20px)_saturate(1.2)] border border-solid border-[var(--lf-desktop-floating-tray-border)] shadow-lf-overlay",
  homeIndicator: "w-[120px] h-[4px] p-0 border-none rounded-lf-pill bg-[var(--lf-desktop-home-indicator)] cursor-pointer",
  ios: "flex-col gap-lf-2 p-[var(--lf-space-2)_var(--lf-space-4)_var(--lf-space-1)] bg-transparent",
  iosDock: "flex items-center justify-center gap-lf-3 p-[var(--lf-space-2)_var(--lf-space-4)] rounded-lf-xl bg-[var(--lf-desktop-ios-dock-bg)] [-webkit-backdrop-filter:blur(24px)_saturate(1.2)] [backdrop-filter:blur(24px)_saturate(1.2)] border border-solid border-[var(--lf-desktop-ios-dock-border)]",
  itemSlot: "relative inline-flex [flex-shrink:0]",
  itemSlotDragging: "opacity-0 z-[2]",
  itemSlotPending: "",
  itemSlotPending_taskButton: "[transform:scale(0.92)]",
  itemSlotPending_trayIcon: "[transform:scale(0.92)]",
  itemSlotReorderable: "[touch-action:none]",
  itemSlotShifting: "transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)]",
  itemSlotUndocking: "opacity-0",
  macos: "relative z-[2] w-full p-[var(--lf-space-2)_var(--lf-space-4)_var(--lf-space-3)] bg-transparent",
  macosDock: "relative flex items-end gap-lf-2 p-[var(--lf-space-2)_var(--lf-space-3)] rounded-lf-xl bg-[var(--lf-desktop-dock-bg)] [-webkit-backdrop-filter:blur(20px)_saturate(1.2)] [backdrop-filter:blur(20px)_saturate(1.2)] border border-solid border-[var(--lf-desktop-dock-border)] shadow-lf-lg",
  macosIcon: "w-[44px] h-[44px] rounded-[12px]",
  phoneHomeButton: "inline-flex items-center justify-center w-[40px] h-[40px] border-none rounded-full bg-[color-mix(in_srgb,_var(--lf-text-primary)_10%,_transparent)] text-lf-text-secondary cursor-pointer transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:bg-[color-mix(in_srgb,_var(--lf-accent)_18%,_transparent)] hover:text-lf-accent",
  startButton: "inline-flex items-center justify-center [flex-shrink:0] w-[40px] h-[40px] border-none rounded-lf-sm bg-transparent text-lf-text-primary cursor-pointer transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:bg-[var(--lf-desktop-chrome-hover)] active:bg-[var(--lf-desktop-chrome-hover-strong)]",
  startMark: "w-[14px] h-[14px] rounded-[1px] bg-[linear-gradient(to_right,_#0078d4_0_50%,_#50a0e8_50%_100%)_top_/_100%_50%_no-repeat,_linear-gradient(to_right,_#0078d4_0_50%,_#50a0e8_50%_100%)_bottom_/_100%_50%_no-repeat]",
  systemTray: "flex items-center gap-[1px] [flex-shrink:0] p-[0_var(--lf-space-1)] text-lf-text-secondary",
  systemTrayButton: "inline-flex items-center justify-center w-[32px] h-[32px] border-none rounded-lf-sm bg-transparent text-[inherit] cursor-pointer transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:bg-[var(--lf-desktop-chrome-hover)]",
  systemTrayClock: "flex flex-col items-end justify-center min-w-[64px] h-[40px] ml-lf-1 p-[0_var(--lf-space-2)] border-none rounded-lf-sm bg-transparent text-lf-text-primary cursor-pointer leading-[1.1] transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:bg-[var(--lf-desktop-chrome-hover)]",
  systemTrayDate: "text-[10px] text-lf-text-secondary",
  systemTrayTime: "text-lf-xs [font-variant-numeric:tabular-nums]",
  taskButton: "relative inline-flex items-center justify-center [flex-shrink:0] w-[44px] h-[40px] border-none rounded-lf-sm bg-transparent text-lf-text-secondary cursor-pointer transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:bg-[var(--lf-desktop-chrome-hover)]",
  taskList: "flex items-center justify-center flex-1 min-w-0 overflow-hidden",
  taskListInner: "relative inline-flex items-center gap-[2px] max-w-full p-[0_var(--lf-space-1)]",
  toneAccent: "bg-lf-accent",
  toneDanger: "bg-lf-danger",
  toneNeutral: "bg-lf-surface-3 text-lf-text-primary",
  toneSuccess: "bg-lf-success",
  toneWarning: "bg-lf-warning",
  tray: "[flex-shrink:0] flex items-center justify-center select-none",
  trayDivider: "w-[1px] h-[24px] m-[0_var(--lf-space-1)] self-center bg-[var(--lf-desktop-tray-divider)] [flex-shrink:0]",
  trayDividerWindows: "h-[24px] m-[0_2px]",
  trayIcon: "relative inline-flex items-center justify-center p-0 border-none bg-transparent cursor-pointer transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:[transform:translateY(-2px)]",
  undockHint: "absolute inset-0 flex items-center justify-center rounded-[inherit] bg-[color-mix(in_srgb,_var(--lf-danger)_12%,_transparent)] pointer-events-none opacity-0 transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)]",
  watchNav: "flex justify-center gap-lf-3 pb-lf-1",
  windows: "justify-between gap-lf-1 h-[48px] p-[0_var(--lf-space-1)] bg-[var(--lf-desktop-taskbar-bg)] [-webkit-backdrop-filter:blur(20px)_saturate(1.2)] [backdrop-filter:blur(20px)_saturate(1.2)] border-t border-[var(--lf-desktop-taskbar-border)]",
  windowsIcon: "inline-flex items-center justify-center",
};
export default styles;
