/** Tailwind class map — converted from WindowFrame.module.css */
const styles: Record<string, string> = {
  active: "shadow-lf-overlay border-lf-border-strong",
  android: "rounded-[20px] border-none",
  android_chromeless: "rounded-none",
  android_contentLegacy: "p-lf-4",
  android_mobileTitleBar: "bg-lf-surface-2",
  chromeless: "",
  chromeless_content: "rounded-none",
  chromeos: "rounded-lf-md",
  closeLight: "bg-[#ff5f57]",
  content: "flex-1 min-h-0 min-w-0 overflow-hidden flex flex-col p-0 text-lf-text-secondary text-lf-md [container-type:inline-size] [container-name:lf-window]",
  contentLegacy: "overflow-auto p-lf-4",
  ios: "rounded-[20px] border-none",
  ios_chromeless: "rounded-none",
  ios_contentLegacy: "p-lf-4",
  ios_mobileTitleBar: "bg-[color-mix(in_srgb,_var(--lf-surface-1)_82%,_transparent)] [backdrop-filter:blur(16px)]",
  light: "w-[11px] h-[11px] border-none rounded-full p-0 cursor-pointer",
  macos: "rounded-[10px]",
  macos_titleBar: "justify-center relative",
  maxLight: "bg-[#28c840]",
  minLight: "bg-[#febc2e]",
  mobileClose: "absolute top-[8px] inline-flex items-center justify-center w-[28px] h-[28px] border-none rounded-full bg-[color-mix(in_srgb,_var(--lf-text-primary)_10%,_transparent)] text-lf-text-secondary cursor-pointer [flex-shrink:0] transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] right-[10px] hover:bg-[color-mix(in_srgb,_var(--lf-danger)_18%,_transparent)] hover:text-lf-danger",
  mobileHome: "absolute top-[8px] inline-flex items-center justify-center w-[28px] h-[28px] border-none rounded-full bg-[color-mix(in_srgb,_var(--lf-text-primary)_10%,_transparent)] text-lf-text-secondary cursor-pointer [flex-shrink:0] transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] left-[10px] hover:bg-[color-mix(in_srgb,_var(--lf-accent)_18%,_transparent)] hover:text-lf-accent",
  mobileTitleBar: "relative justify-between h-[44px] p-[0_var(--lf-space-3)] border-b border-lf-divider",
  mobileTitleCenter: "flex-1 min-w-0 flex items-center justify-center gap-lf-2 pr-lf-8 pl-lf-8 text-lf-text-primary text-lf-sm font-semibold",
  resizeE: "top-[8px] bottom-[8px] w-[6px] [cursor:ew-resize] right-0",
  resizeHandle: "absolute z-[2]",
  resizeN: "left-[8px] right-[8px] h-[6px] [cursor:ns-resize] top-0",
  resizeNE: "w-[10px] h-[10px] top-0 right-0 [cursor:nesw-resize]",
  resizeNW: "w-[10px] h-[10px] top-0 left-0 [cursor:nwse-resize]",
  resizeS: "left-[8px] right-[8px] h-[6px] [cursor:ns-resize] bottom-0",
  resizeSE: "w-[10px] h-[10px] bottom-0 right-0 [cursor:nwse-resize]",
  resizeSW: "w-[10px] h-[10px] bottom-0 left-0 [cursor:nesw-resize]",
  resizeW: "top-[8px] bottom-[8px] w-[6px] [cursor:ew-resize] left-0",
  titleBar: "[flex-shrink:0] flex items-center h-[32px] p-[0_var(--lf-space-2)] bg-lf-surface-2 border-b border-lf-divider",
  titleBarDraggable: "cursor-grab [touch-action:none] active:[cursor:grabbing]",
  titleCenter: "flex items-center gap-lf-2 min-w-0 text-lf-text-secondary text-lf-sm",
  titleText: "overflow-hidden text-ellipsis whitespace-nowrap",
  trafficLights: "absolute left-[var(--lf-space-2)] flex gap-[6px]",
  winClose: "hover:bg-lf-danger hover:text-lf-text-on-accent",
  winControl: "inline-flex items-center justify-center w-[40px] border-none bg-transparent text-lf-text-secondary cursor-pointer hover:bg-lf-surface-3",
  winControls: "ml-auto flex items-stretch h-full",
  window: "absolute flex flex-col min-w-0 min-h-0 rounded-lf-lg bg-lf-surface-1 border border-solid border-lf-border-default shadow-lf-lg overflow-hidden",
  windows: "rounded-lf-md",
  windows_titleBar: "pr-0",
  windows_titleCenter: "flex-1 pl-lf-2",
};
export default styles;
