/** Tailwind class map — converted from PassportPage.module.css */
const styles: Record<string, string> = {
  agentAvatar: "inline-flex items-center justify-center w-[40px] h-[40px] rounded-lf-md bg-lf-accent-muted text-lf-accent [flex-shrink:0]",
  agentDesc: "m-[2px_0_0] text-lf-xs text-lf-text-tertiary",
  agentInfo: "flex-1 min-w-0",
  agentName: "m-0 text-lf-md font-semibold",
  auditAction: "text-lf-xs font-semibold uppercase [letter-spacing:0.04em]",
  auditCreate: "text-[#6366f1]",
  auditGrant: "text-lf-accent",
  auditRead: "text-[#059669]",
  auditRevoke: "text-[#dc2626]",
  auditRow: "grid grid-cols-[0.9fr_1fr_1fr_0.8fr] gap-lf-3 items-center p-[var(--lf-space-3)_var(--lf-space-4)] border-b border-lf-divider text-lf-sm last:[border-bottom:none]",
  auditTableHead: "grid-cols-[0.8fr_1fr_1fr_0.8fr_1fr] grid-cols-[1fr]",
  auditTableRow: "grid-cols-[0.8fr_1fr_1fr_0.8fr_1fr] grid-cols-[1fr]",
  cardGrid: "grid grid-cols-[repeat(auto-fill,_minmax(260px,_1fr))] gap-lf-3",
  envCard: "flex flex-col gap-lf-2",
  envCardDesc: "m-0 text-lf-sm text-lf-text-secondary leading-[1.45]",
  envCardHead: "flex items-start justify-between gap-lf-2",
  envCardMeta: "flex flex-wrap gap-lf-2 text-lf-xs text-lf-text-tertiary",
  envCardTitle: "m-0 text-lf-md font-semibold",
  filterChip: "inline-flex items-center gap-lf-1 p-[var(--lf-space-1)_var(--lf-space-2)] border border-solid border-lf-border-subtle rounded-lf-md bg-lf-surface-1 text-lf-sm text-lf-text-secondary cursor-pointer",
  filterChipActive: "border-lf-accent bg-lf-accent-muted text-lf-accent",
  grantCard: "flex flex-col gap-lf-3",
  grantCount: "text-lf-xs text-lf-text-tertiary",
  grantHead: "flex items-center gap-lf-3",
  grantList: "flex flex-col gap-lf-2",
  grantRow: "flex items-center justify-between gap-lf-3 p-[var(--lf-space-2)_var(--lf-space-3)] border border-solid border-lf-border-subtle rounded-lf-md bg-lf-surface-sunken",
  grantRowLabel: "flex flex-col gap-[2px] min-w-0",
  grantRowMeta: "text-lf-xs text-lf-text-tertiary",
  grantRowName: "text-lf-sm font-medium",
  header: "flex items-start justify-between gap-lf-4",
  headerBody: "flex flex-col gap-lf-1",
  kindApiKey: "bg-[color-mix(in_srgb,_#10b981_14%,_transparent)] text-[#059669]",
  kindEnv: "bg-[color-mix(in_srgb,_#6366f1_14%,_transparent)] text-[#4f46e5]",
  kindPassword: "bg-[color-mix(in_srgb,_var(--lf-accent)_12%,_transparent)] text-lf-accent",
  kindPill: "inline-flex items-center p-[2px_8px] rounded-lf-sm text-lf-xs font-semibold bg-lf-surface-sunken text-lf-text-secondary",
  kindSecretKey: "bg-[color-mix(in_srgb,_#f59e0b_14%,_transparent)] text-[#d97706]",
  maskedValue: "font-mono text-lf-xs text-lf-text-secondary [letter-spacing:0.06em]",
  metricCard: "flex flex-col gap-lf-2",
  metricChange: "text-lf-xs text-lf-text-tertiary",
  metricHead: "flex items-center justify-between",
  metricIcon: "inline-flex items-center justify-center w-[28px] h-[28px] rounded-lf-md bg-lf-accent-muted text-lf-accent",
  metricLabel: "text-lf-xs text-lf-text-tertiary uppercase [letter-spacing:0.04em]",
  metrics: "grid grid-cols-[repeat(auto-fill,_minmax(160px,_1fr))] gap-lf-3",
  metricValue: "text-lf-xl font-bold",
  page: "flex flex-col gap-lf-4 p-lf-6 min-h-0",
  rowActions: "flex items-center gap-lf-1 justify-end",
  searchInput: "flex-1 min-w-[200px] max-w-[320px]",
  secretMeta: "text-lf-xs text-lf-text-tertiary",
  secretName: "flex flex-col gap-[2px] min-w-0",
  secretTitle: "font-semibold text-lf-text-primary",
  sectionHead: "flex items-center justify-between gap-lf-2",
  sectionTitle: "m-0 text-lf-md font-semibold",
  subtitle: "m-0 text-lf-sm text-lf-text-secondary leading-[var(--lf-line-height-normal)] max-w-[560px]",
  table: "flex flex-col border border-solid border-lf-border-subtle rounded-lf-lg overflow-hidden bg-lf-surface-1",
  tableHead: "grid grid-cols-[1.4fr_0.8fr_1fr_0.7fr_0.6fr] gap-lf-3 p-[var(--lf-space-2)_var(--lf-space-4)] border-b border-lf-divider text-lf-xs font-semibold text-lf-text-tertiary uppercase [letter-spacing:0.04em] grid-cols-[1fr] hidden",
  tableRow: "grid grid-cols-[1.4fr_0.8fr_1fr_0.7fr_0.6fr] gap-lf-3 items-center p-[var(--lf-space-3)_var(--lf-space-4)] border-b border-lf-divider text-lf-sm last:[border-bottom:none] hover:bg-lf-surface-sunken grid-cols-[1fr]",
  title: "m-0 text-lf-2xl font-semibold text-lf-text-primary",
  toggleKnob: "absolute top-[2px] left-[2px] w-[18px] h-[18px] rounded-full bg-[white] transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)]",
  toggleSwitch: "relative w-[40px] h-[22px] border-none rounded-[999px] bg-lf-divider cursor-pointer [flex-shrink:0] transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)]",
  toggleSwitchOn: "bg-lf-accent",
  toggleSwitchOn_toggleKnob: "[transform:translateX(18px)]",
  toolbar: "flex items-center gap-lf-2 flex-wrap",
  twoCol: "grid grid-cols-[repeat(auto-fit,_minmax(280px,_1fr))] gap-lf-4",
};
export default styles;
