/** Tailwind class map — converted from DashboardView.module.css */
const styles: Record<string, string> = {
  activityBody: "min-w-0",
  activityIcon: "inline-flex items-center justify-center w-[28px] h-[28px] rounded-lf-md [flex-shrink:0]",
  activityIconInfo: "bg-lf-accent-muted text-lf-accent",
  activityIconSuccess: "bg-[color-mix(in_srgb,_var(--lf-success)_16%,_transparent)] text-lf-success",
  activityIconWarning: "bg-[color-mix(in_srgb,_var(--lf-warning)_16%,_transparent)] text-lf-warning",
  activityItem: "flex items-start gap-lf-3 p-[var(--lf-space-2)_0]",
  activityList: "flex flex-col gap-lf-2 mb-lf-4",
  activityMeta: "text-lf-xs text-lf-text-tertiary mt-[2px]",
  activityTitle: "text-lf-sm font-medium",
  header: "mb-lf-6",
  identityLinks: "flex flex-wrap gap-lf-2",
  metricCard: "min-h-[96px]",
  metricChange: "mt-lf-1 text-lf-xs text-lf-text-tertiary",
  metricHead: "flex items-start justify-between gap-lf-2 mb-lf-3",
  metricIcon: "inline-flex items-center justify-center w-[28px] h-[28px] rounded-lf-md [flex-shrink:0]",
  metricIconAccent: "bg-lf-accent-muted text-lf-accent",
  metricIconNeutral: "bg-lf-surface-sunken text-lf-text-secondary",
  metricIconSuccess: "bg-[color-mix(in_srgb,_var(--lf-success)_16%,_transparent)] text-lf-success",
  metricIconWarning: "bg-[color-mix(in_srgb,_var(--lf-warning)_16%,_transparent)] text-lf-warning",
  metricLabel: "text-lf-sm text-lf-text-secondary",
  metrics: "grid grid-cols-[repeat(4,_minmax(0,_1fr))] gap-lf-3 mb-lf-4 grid-cols-[repeat(2,_minmax(0,_1fr))] grid-cols-[1fr]",
  metricValue: "text-lf-xl font-bold [letter-spacing:-0.02em]",
  metricValueSuccess: "text-lf-success",
  queryCard: "border border-solid border-lf-border-subtle",
  queryList: "flex flex-col gap-lf-2",
  queryMeta: "text-lf-xs text-lf-text-tertiary mb-lf-2",
  queryPreview: "m-0 text-lf-xs text-lf-text-secondary leading-[1.45] [display:-webkit-box] [-webkit-box-orient:vertical] line-clamp-[2] overflow-hidden",
  queryText: "text-lf-sm font-semibold mb-lf-1",
  sectionHead: "flex items-center justify-between gap-lf-2 mb-lf-3",
  sectionTitle: "m-0 text-lf-md font-semibold",
  statRow: "grid grid-cols-[repeat(3,_minmax(0,_1fr))] gap-lf-3 mb-lf-6 grid-cols-[1fr]",
  storeCard: "cursor-default",
  storeGrid: "grid grid-cols-[repeat(2,_minmax(0,_1fr))] gap-lf-3 grid-cols-[1fr]",
  storeHead: "flex items-center justify-between gap-lf-2 mb-lf-2",
  storeMeta: "text-lf-xs text-lf-text-secondary mb-lf-1",
  storeModel: "text-lf-xs text-lf-text-tertiary font-mono",
  storeName: "text-lf-sm font-semibold",
  subtitle: "m-0 text-lf-sm text-lf-text-secondary max-w-[640px] leading-normal",
  systemNote: "p-lf-3 rounded-lf-lg bg-lf-surface-sunken border border-solid border-lf-border-subtle mb-lf-4",
  systemNoteLabel: "flex items-center gap-lf-1 mb-lf-1 text-lf-xs font-semibold uppercase [letter-spacing:0.04em] text-lf-accent",
  systemNoteText: "m-0 text-lf-xs text-lf-text-secondary leading-[1.45]",
  title: "m-[0_0_var(--lf-space-1)] text-lf-2xl font-bold [letter-spacing:-0.02em]",
  twoCol: "grid grid-cols-[minmax(0,_1.4fr)_minmax(280px,_0.8fr)] gap-lf-6 grid-cols-[1fr]",
  view: "p-lf-6 max-w-[1280px]",
};
export default styles;
