/** Tailwind class map — converted from KnowledgeGraphView.module.css */
const styles: Record<string, string> = {
  canvas: "relative w-full h-[480px] bg-[radial-gradient(circle_at_20%_30%,_color-mix(in_srgb,_var(--lf-accent)_8%,_transparent),_transparent_40%),_radial-gradient(circle_at_80%_70%,_color-mix(in_srgb,_#a78bfa_8%,_transparent),_transparent_35%),_var(--lf-surface-sunken)]",
  edgeLabel: "text-lf-accent [font-style:italic]",
  edgeLine: "[stroke:color-mix(in_srgb,_var(--lf-accent)_35%,_var(--lf-border-subtle))] [stroke-linecap:round]",
  edgeList: "flex flex-col gap-lf-2",
  edgeRow: "flex items-start gap-lf-2 text-lf-xs text-lf-text-secondary leading-[1.4]",
  edges: "absolute inset-0 w-full h-full pointer-events-none",
  graphCard: "overflow-hidden min-h-[480px] border border-solid border-lf-border-subtle",
  header: "mb-lf-5",
  layout: "grid grid-cols-[minmax(0,_1fr)_320px] gap-lf-4 [align-items:start] grid-cols-[1fr]",
  node: "absolute [transform:translate(-50%,_-50%)] flex flex-col items-center gap-[2px] p-[var(--lf-space-2)_var(--lf-space-3)] rounded-lf-lg border border-solid border-lf-border-subtle bg-[var(--lf-surface-raised)] shadow-[0_4px_16px_color-mix(in_srgb,_var(--lf-shadow)_12%,_transparent)] min-w-[88px] text-center cursor-default transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:[transform:translate(-50%,_-50%)_scale(1.04)] hover:shadow-[0_8px_24px_color-mix(in_srgb,_var(--lf-shadow)_18%,_transparent)]",
  nodeConcept: "border-[color-mix(in_srgb,_var(--lf-accent)_40%,_transparent)]",
  nodeConcept_nodeDot: "bg-lf-accent",
  nodeDot: "w-[10px] h-[10px] rounded-full [flex-shrink:0] bg-lf-accent",
  nodeEntity: "border-[color-mix(in_srgb,_var(--lf-success)_40%,_transparent)]",
  nodeEntity_nodeDot: "bg-lf-success",
  nodeEvent: "border-[color-mix(in_srgb,_var(--lf-warning)_40%,_transparent)]",
  nodeEvent_nodeDot: "bg-lf-warning",
  nodeInfo: "flex-1 min-w-0",
  nodeLabel: "text-lf-xs font-semibold leading-[1.2]",
  nodeList: "flex flex-col gap-lf-2",
  nodeMeta: "text-[10px] text-lf-text-tertiary",
  nodeName: "text-lf-xs font-semibold",
  nodePolicy: "border-[color-mix(in_srgb,_#a78bfa_40%,_transparent)]",
  nodePolicy_nodeDot: "bg-[#a78bfa]",
  nodeRow: "flex items-center gap-lf-2 p-lf-2 rounded-lf-md bg-[var(--lf-surface-raised)] border border-solid border-lf-border-subtle",
  nodeType: "text-[10px] uppercase [letter-spacing:0.04em] text-lf-text-tertiary",
  nodeValue: "border-[color-mix(in_srgb,_#f472b6_40%,_transparent)]",
  nodeValue_nodeDot: "bg-[#f472b6]",
  sectionTitle: "m-0 text-lf-sm font-semibold",
  sidebar: "flex flex-col gap-lf-3",
  stat: "flex flex-col items-center p-lf-3 rounded-lf-lg bg-lf-surface-sunken border border-solid border-lf-border-subtle",
  statLabel: "text-[10px] text-lf-text-tertiary uppercase [letter-spacing:0.04em]",
  stats: "grid grid-cols-[repeat(3,_1fr)] gap-lf-2",
  statValue: "text-lf-lg font-bold",
  subtitle: "m-0 text-lf-sm text-lf-text-secondary max-w-[560px] leading-normal",
  title: "m-[0_0_var(--lf-space-1)] text-lf-2xl font-bold [letter-spacing:-0.02em]",
  view: "p-lf-6 max-w-[1280px]",
};
export default styles;
