/** Tailwind class map — converted from MemoryView.module.css */
const styles: Record<string, string> = {
  confidenceBar: "h-[4px] rounded-[var(--lf-radius-full)] bg-lf-surface-sunken overflow-hidden mb-lf-3",
  confidenceFill: "h-full rounded-[inherit] bg-[linear-gradient(90deg,_var(--lf-accent),_color-mix(in_srgb,_var(--lf-success)_70%,_var(--lf-accent)))]",
  filters: "flex flex-col gap-lf-3 mb-lf-5",
  grid: "grid grid-cols-[repeat(2,_minmax(0,_1fr))] gap-lf-3 grid-cols-[1fr]",
  header: "mb-lf-5",
  kindBtn: "p-[6px_12px] rounded-[var(--lf-radius-full)] border border-solid border-lf-border-subtle bg-[var(--lf-surface-raised)] text-lf-xs text-lf-text-secondary cursor-pointer hover:text-lf-text-primary hover:border-lf-border-strong",
  kindBtnActive: "bg-lf-accent-muted border-[color-mix(in_srgb,_var(--lf-accent)_30%,_transparent)] text-lf-accent font-semibold",
  kindEpisodic: "bg-[color-mix(in_srgb,_var(--lf-accent)_16%,_transparent)] text-lf-accent",
  kindFilters: "flex flex-wrap gap-lf-2",
  kindIcon: "inline-flex items-center justify-center w-[28px] h-[28px] rounded-lf-md [flex-shrink:0]",
  kindPill: "p-[2px_8px] rounded-[var(--lf-radius-full)] bg-lf-surface-sunken text-lf-text-secondary font-medium",
  kindProcedural: "bg-[color-mix(in_srgb,_#a78bfa_16%,_transparent)] text-[#a78bfa]",
  kindSemantic: "bg-[color-mix(in_srgb,_var(--lf-success)_16%,_transparent)] text-lf-success",
  kindWorking: "bg-[color-mix(in_srgb,_var(--lf-warning)_16%,_transparent)] text-lf-warning",
  memoryCard: "border border-solid border-lf-border-subtle",
  memoryHead: "flex items-start justify-between gap-lf-3 mb-lf-3",
  memoryMeta: "flex flex-wrap gap-lf-2 text-lf-xs text-lf-text-tertiary mb-lf-2",
  memorySource: "text-lf-xs text-lf-text-tertiary mt-[2px]",
  memorySummary: "m-[0_0_var(--lf-space-3)] text-lf-sm text-lf-text-secondary leading-[1.45]",
  memoryTitle: "text-lf-sm font-semibold",
  memoryTitleRow: "flex items-start gap-lf-2 min-w-0",
  search: "max-w-[420px]",
  subtitle: "m-0 text-lf-sm text-lf-text-secondary max-w-[560px] leading-normal",
  tag: "p-[2px_8px] rounded-lf-sm text-[11px] font-mono bg-lf-surface-sunken text-lf-text-secondary",
  tags: "flex flex-wrap gap-lf-1",
  title: "m-[0_0_var(--lf-space-1)] text-lf-2xl font-bold [letter-spacing:-0.02em]",
  view: "p-lf-6 max-w-[1200px]",
};
export default styles;
