/** Tailwind class map — converted from RagView.module.css */
const styles: Record<string, string> = {
  answerCard: "mb-lf-5 border border-solid border-[color-mix(in_srgb,_var(--lf-accent)_25%,_var(--lf-border-subtle))] bg-[color-mix(in_srgb,_var(--lf-accent)_4%,_var(--lf-surface-raised))]",
  answerLabel: "flex items-center gap-lf-2 mb-lf-3 text-lf-xs font-semibold uppercase [letter-spacing:0.04em] text-lf-accent",
  answerText: "m-0 text-lf-sm text-lf-text-primary leading-[1.55]",
  chunkCard: "border border-solid border-lf-border-subtle",
  chunkContent: "m-[0_0_var(--lf-space-3)] text-lf-sm text-lf-text-primary leading-normal",
  chunkHead: "flex items-center gap-lf-2 mb-lf-2",
  chunkList: "flex flex-col gap-lf-3",
  chunkMeta: "flex flex-wrap gap-lf-2 text-lf-xs text-lf-text-tertiary",
  chunkRank: "inline-flex items-center justify-center w-[24px] h-[24px] rounded-lf-md text-[11px] font-bold bg-lf-accent-muted text-lf-accent",
  chunkSource: "inline-flex items-center gap-[4px] flex-1 text-lf-xs text-lf-text-secondary font-mono",
  header: "mb-lf-5",
  historyItem: "block w-full p-[var(--lf-space-2)_var(--lf-space-3)] border border-solid border-lf-border-subtle rounded-lf-md bg-[var(--lf-surface-raised)] text-left cursor-pointer hover:border-lf-border-strong hover:bg-lf-surface-sunken",
  historyList: "flex flex-col gap-lf-1",
  historyMeta: "text-[10px] text-lf-text-tertiary",
  historyQuery: "text-lf-xs font-medium mb-[2px]",
  latency: "text-lf-xs text-lf-text-tertiary",
  layout: "grid grid-cols-[minmax(0,_1fr)_300px] gap-lf-5 [align-items:start] grid-cols-[1fr]",
  metaTag: "p-[2px_6px] rounded-lf-sm bg-lf-surface-sunken",
  pipeline: "flex flex-wrap items-center gap-lf-2",
  pipelineArrow: "text-lf-text-tertiary text-lf-xs",
  pipelineStep: "inline-flex items-center gap-[6px] p-[4px_10px] rounded-[var(--lf-radius-full)] text-lf-xs bg-lf-surface-sunken text-lf-text-secondary border border-solid border-lf-border-subtle",
  pipelineStepActive: "bg-lf-accent-muted text-lf-accent border-[color-mix(in_srgb,_var(--lf-accent)_30%,_transparent)] font-semibold",
  queryInput: "flex-1",
  queryLabel: "block mb-lf-2 text-lf-xs font-semibold uppercase [letter-spacing:0.04em] text-lf-text-secondary",
  queryPanel: "mb-lf-5 border border-solid border-lf-border-subtle",
  queryRow: "flex gap-lf-2 mb-lf-4 flex-col",
  sectionHead: "flex items-center justify-between gap-lf-2 mb-lf-3",
  sectionTitle: "m-[0_0_var(--lf-space-3)] text-lf-sm font-semibold",
  subtitle: "m-0 text-lf-sm text-lf-text-secondary max-w-[560px] leading-normal",
  title: "m-[0_0_var(--lf-space-1)] text-lf-2xl font-bold [letter-spacing:-0.02em]",
  view: "p-lf-6 max-w-[1200px]",
};
export default styles;
