/** Tailwind class map — converted from VectorDbView.module.css */
const styles: Record<string, string> = {
  collectionCard: "border border-solid border-lf-border-subtle",
  collectionFooter: "flex items-center justify-between text-lf-xs text-lf-text-tertiary",
  collectionHead: "flex items-start justify-between gap-lf-2 mb-lf-4",
  collectionModel: "text-lf-xs text-lf-text-tertiary font-mono mt-[2px]",
  collectionName: "text-lf-md font-semibold",
  collectionStat: "flex flex-col gap-[2px]",
  collectionStats: "grid grid-cols-[repeat(3,_1fr)] gap-lf-2 mb-lf-3",
  configCard: "border border-solid border-lf-border-subtle",
  configGrid: "grid grid-cols-[repeat(4,_minmax(0,_1fr))] gap-lf-3 grid-cols-[1fr]",
  configHead: "flex items-center gap-lf-2 mb-lf-4 text-lf-sm font-semibold",
  configItem: "flex flex-col gap-[4px] p-lf-3 rounded-lf-md bg-lf-surface-sunken",
  configLabel: "text-[10px] uppercase [letter-spacing:0.04em] text-lf-text-tertiary",
  configValue: "text-lf-sm font-semibold font-mono",
  grid: "grid grid-cols-[repeat(2,_minmax(0,_1fr))] gap-lf-3 mb-lf-5 grid-cols-[1fr]",
  header: "mb-lf-5",
  indexBar: "h-[6px] rounded-[var(--lf-radius-full)] bg-lf-surface-sunken overflow-hidden mb-lf-3",
  indexFill: "h-full rounded-[inherit] transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)]",
  indexFillDegraded: "bg-[linear-gradient(90deg,_var(--lf-danger),_color-mix(in_srgb,_var(--lf-danger)_70%,_var(--lf-warning)))]",
  indexFillHealthy: "bg-[linear-gradient(90deg,_var(--lf-success),_color-mix(in_srgb,_var(--lf-success)_70%,_var(--lf-accent)))]",
  indexFillSyncing: "bg-[linear-gradient(90deg,_var(--lf-warning),_color-mix(in_srgb,_var(--lf-warning)_70%,_var(--lf-accent)))]",
  statLabel: "text-[10px] uppercase [letter-spacing:0.04em] text-lf-text-tertiary",
  statRow: "grid grid-cols-[repeat(3,_minmax(0,_1fr))] gap-lf-3 mb-lf-5 grid-cols-[1fr]",
  statValue: "text-lf-sm font-semibold",
  subtitle: "m-0 text-lf-sm text-lf-text-secondary max-w-[560px] leading-normal",
  title: "m-[0_0_var(--lf-space-1)] text-lf-2xl font-bold [letter-spacing:-0.02em]",
  view: "p-lf-6 max-w-[1100px]",
};
export default styles;
