/** Tailwind class map — converted from NavSidebar.module.css */
const styles: Record<string, string> = {
  footer: "[flex-shrink:0] min-w-0 border-t border-lf-divider p-lf-2 bg-lf-surface-1",
  groupBlock: "flex flex-col gap-lf-1 min-w-0",
  groupedSection: "flex flex-col gap-lf-3 min-w-0",
  groupHeader: "flex items-center gap-lf-2 p-[0_var(--lf-space-2)] min-w-0 text-lf-text-primary text-lf-sm font-medium",
  groupHeaderIcon: "flex [flex-shrink:0] text-lf-text-tertiary",
  groupHeaderLabel: "min-w-0 overflow-hidden text-ellipsis whitespace-nowrap",
  groupItems: "flex flex-col gap-lf-1 min-w-0 pl-lf-2",
  groupShowMore: "self-start ml-lf-2 p-[var(--lf-space-1)_var(--lf-space-2)] border-none rounded-lf-sm bg-transparent text-lf-text-tertiary text-lf-sm cursor-pointer transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:bg-lf-surface-2 hover:text-lf-text-secondary",
  header: "[flex-shrink:0] min-w-0 p-[var(--lf-space-3)_var(--lf-space-3)_0] flex flex-col gap-lf-2 bg-lf-surface-1",
  headerSlot: "[flex-shrink:0] min-w-0 p-[var(--lf-space-3)_var(--lf-space-3)_var(--lf-space-2)] flex flex-col gap-lf-2 border-b border-lf-divider bg-lf-surface-1",
  navListItem: "text-lf-sm",
  quickLinks: "flex flex-col gap-lf-1 min-w-0",
  sectionFilterCheck: "flex [flex-shrink:0] text-lf-text-primary",
  sectionFilterItem: "flex items-center justify-between gap-lf-3 w-full",
  sectionFilterTrigger: "inline-flex items-center gap-lf-1 h-[20px] p-[0_var(--lf-space-1)] border-none rounded-lf-sm bg-transparent text-lf-text-tertiary text-lf-xs font-medium [letter-spacing:normal] [text-transform:none] cursor-pointer transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:bg-lf-surface-2 hover:text-lf-text-secondary",
  sectionHeader: "flex items-center justify-between gap-lf-2 p-[0_0_var(--lf-space-1)]",
  sectionHeaderButton: "inline-flex items-center justify-center w-[20px] h-[20px] border-none rounded-lf-sm bg-transparent text-lf-text-tertiary cursor-pointer transition-[background-color,border-color,color,box-shadow,opacity,transform] duration-[var(--lf-duration-fast)] ease-[var(--lf-ease)] hover:bg-lf-surface-2 hover:text-lf-text-primary",
  sectionHeaderTitle: "text-lf-xs font-semibold uppercase [letter-spacing:0.04em] text-lf-text-tertiary",
  sectionItems: "flex flex-col gap-lf-1 min-w-0",
  sections: "min-w-0 p-[var(--nav-sidebar-scroll-inset-top)_var(--lf-space-3)_var(--lf-space-2)] flex flex-col gap-lf-3",
  sectionsScroll: "flex-1 min-h-0 min-w-0",
  sidebar: "[--nav-sidebar-scroll-inset-top:0] h-full flex flex-col w-full min-w-0 max-w-full overflow-hidden bg-lf-surface-1 [--nav-sidebar-scroll-inset-top:var(--lf-space-2)]",
  userFooter: "flex items-center gap-lf-2 w-full p-lf-2 rounded-lf-md bg-transparent border-none cursor-pointer text-left hover:bg-lf-surface-2",
  userFooterActions: "flex items-center gap-lf-1 [flex-shrink:0]",
  userFooterBar: "flex items-center gap-lf-2 w-full p-lf-2",
  userFooterBody: "flex-1 min-w-0 flex flex-col",
  userFooterCompact: "justify-center w-auto p-lf-1",
  userFooterMeta: "text-lf-xs text-lf-text-tertiary overflow-hidden text-ellipsis whitespace-nowrap",
  userFooterName: "text-lf-md text-lf-text-primary font-medium overflow-hidden text-ellipsis whitespace-nowrap",
};
export default styles;
