/** Tailwind class map — converted from ExtensionPage.module.css */
const styles: Record<string, string> = {
  card: "flex flex-col gap-lf-2",
  cardDescription: "text-lf-sm text-lf-text-secondary leading-[var(--lf-line-height-normal)] flex-1",
  cardFooter: "flex items-center justify-between gap-lf-2 mt-lf-1",
  cardGrid: "grid grid-cols-[repeat(auto-fill,_minmax(240px,_1fr))] gap-lf-3",
  cardHead: "flex items-start justify-between gap-lf-2",
  cardIcon: "flex items-center justify-center w-[36px] h-[36px] rounded-lf-md bg-lf-surface-3 text-lf-accent [flex-shrink:0]",
  cardMeta: "text-lf-xs text-lf-text-tertiary",
  cardTitle: "text-lf-md font-semibold text-lf-text-primary",
  filterChip: "inline-flex items-center gap-lf-1 p-[var(--lf-space-1)_var(--lf-space-2)] border border-solid border-lf-border-subtle rounded-lf-md bg-lf-surface-1 text-lf-sm text-lf-text-secondary cursor-pointer",
  filterChipActive: "border-lf-accent bg-lf-accent-muted text-lf-accent",
  header: "flex items-start justify-between gap-lf-4",
  headerBody: "flex flex-col gap-lf-1",
  listCard: "flex flex-col gap-lf-3",
  page: "flex flex-col gap-lf-4 p-lf-6 min-h-0",
  promptBody: "m-0 text-lf-sm text-lf-text-secondary leading-[var(--lf-line-height-normal)] [display:-webkit-box] line-clamp-[2] [-webkit-box-orient:vertical] overflow-hidden",
  promptHead: "flex items-start justify-between gap-lf-3",
  promptMeta: "flex items-center gap-lf-3 text-lf-xs text-lf-text-tertiary",
  promptRow: "flex flex-col gap-lf-2 p-lf-3 border-b border-lf-divider last:[border-bottom:none]",
  promptTitle: "m-0 text-lf-md font-semibold text-lf-text-primary",
  rating: "inline-flex items-center gap-lf-1 text-lf-sm text-lf-text-secondary",
  searchInput: "flex-1 min-w-[200px] max-w-[320px]",
  stackRow: "flex flex-wrap gap-lf-1",
  starred: "text-lf-warning",
  stat: "text-lf-xs text-lf-text-tertiary",
  subtitle: "m-0 text-lf-sm text-lf-text-secondary leading-[var(--lf-line-height-normal)] max-w-[560px]",
  tag: "p-[2px_8px] rounded-lf-sm bg-lf-surface-sunken text-lf-xs text-lf-text-tertiary",
  tagRow: "flex flex-wrap gap-lf-1",
  title: "m-0 text-lf-2xl font-semibold text-lf-text-primary",
  toolbar: "flex items-center gap-lf-2 flex-wrap",
};
export default styles;
